loathers/autoscend

- RELEASE/scripts/sl_ascend/sl_ascend_header.ash
- RELEASE/scripts/sl_ascend/sl_combat.ash
- RELEASE/scripts/sl_ascend/sl_community_service.ash
- RELEASE/scripts/sl_ascend/sl_mr2017.ash
if we have meteor shower and a may saber, fight a bunny and end the fight with the saber to get 1 turn of meteorshowered for relevant community service quests
> Cs efficiency saber trick

- RELEASE/scripts/sl_ascend/sl_ascend_header.ash
- RELEASE/scripts/sl_ascend/sl_community_service.ash
- RELEASE/scripts/sl_ascend/sl_mr2019.ash
- RELEASE/scripts/sl_ascend/sl_util.ash
account for case when completing a quest when you have blood bond drops you to 0 hp and the script got confused.
Also generally improved hp/mp management before combats and added campaway as a free rest option.
> CS healing, mp, and survivability improvements

- RELEASE/scripts/autoscend/autoscend_migration.ash
> version bump to 1.1.0

- RELEASE/scripts/autoscend.ash
- RELEASE/scripts/autoscend/auto_combat.ash
- RELEASE/scripts/autoscend/autoscend_migration.ash
> Release 1.1.0

- RELEASE/scripts/autoscend/auto_post_adv.ash
Minor change, forgot to add Defiled Cranny to +ML zones
Hasn't
> Add defiled cranny to ml zones

- RELEASE/scripts/autoscend/auto_community_service.ash
- RELEASE/scripts/autoscend/auto_util.ash
Changed Gr8tness to Gr8ness due to Mafia change 19583
Hasn't
> Gr8tness to gr8ness

- RELEASE/scripts/autoscend.ash
Checks to see if Snow Berries are unrestricted before trying to use them in crafting
Issue reported on discord
Hasn't
> Snow berries fix

- RELEASE/scripts/autoscend/auto_restore.ash
Was still having issues where the restore algorithm was using multiple casts of tongue/nap/lasagna instead of 1 cocoon. Modified the algorithm to ignore comparing values for fields if their value is negative one. We can use this to mark fields that arent applicable to be ignored. For example hp_per_mp_use is important for realizing cocoon is better than tongue, but what is the hp_per_mp_used for campsite? hot tub? If 0, they will be removed, if total_hp_restored they will always win. So we set to -1, the algorithm ignores it this time and the "optimize to get the most hp per mp" pass only compares restore methods that are valid comparisons.
Did a few days of HCCS, saw instances where before it would have eliminated options inappropriately not happen:
```
> [INFO] - Target hp => 1062 - …
```
> Healing fixes 3 - use cocoon damnit

- RELEASE/scripts/autoscend.ash
Including Muculent Machete in the various Machete checks, pulls, and Equips.
#171 
Hasn't yet
> Muculent Machete BugFix

- RELEASE/scripts/autoscend.ash
EquipMachete accidentally in a comment block
> Machete bug fix

- RELEASE/scripts/autoscend/auto_combat.ash
- RELEASE/scripts/autoscend/auto_equipment.ash
KoL changed Red Hot to Red-Hot.
Issue reported in Discord
> KoL changed "Red Hot" to "Red-Hot" (Merge to Master)

- RELEASE/scripts/autoscend/auto_combat.ash
Adds custom combat to fighting Gurgle in Heavy Rains so that he doesn't kill you with your own spells
#188 
Hasn't
> Adding custom Combat rules for Gurgle

- RELEASE/scripts/autoscend.ash
- RELEASE/scripts/autoscend/auto_combat.ash
- RELEASE/scripts/autoscend/auto_equipment.ash
merge for all the things in master which are missing from beta.
> beta diverged from master

- RELEASE/scripts/autoscend.ash
- RELEASE/scripts/autoscend/auto_combat.ash
- RELEASE/scripts/autoscend/auto_cooking.ash
- RELEASE/scripts/autoscend/auto_equipment.ash
- RELEASE/scripts/autoscend/auto_mr2019.ash
- RELEASE/scripts/autoscend/auto_mr2020.ash
- RELEASE/scripts/autoscend/auto_pre_adv.ash
- RELEASE/scripts/autoscend/auto_restore.ash
- RELEASE/scripts/autoscend/auto_tower.ash
- RELEASE/scripts/autoscend/auto_util.ash
- RELEASE/scripts/autoscend/auto_zelda.ash
- RELEASE/scripts/autoscend/auto_zone.ash
- RELEASE/scripts/autoscend/autoscend_header.ash
Soolar and I have both completed a softcore Path of the Plumber run, *mostly* automated, with accounts that have most of the available IOTMs.
> Extremely extremely preliminary Plumber support

- RELEASE/data/autoscend_restoration.txt
Fixes #236
Hasn't been tested, am away from my desktop.
> Comfy Pillow does not restore MP

- RELEASE/scripts/autoscend.ash
- RELEASE/scripts/autoscend/auto_adventure.ash
- RELEASE/scripts/autoscend/auto_mr2020.ash
- RELEASE/scripts/autoscend/auto_pre_adv.ash
- RELEASE/scripts/autoscend/auto_tower.ash
- RELEASE/scripts/autoscend/auto_util.ash
- RELEASE/scripts/autoscend/autoscend_header.ash
* Tower test handling wasn't running the maximizer
* Use Triple Sized at bedtime ^_^
* Fix hilarious bug where preparing to yellow ray would screw up Lianas in Plumbercore
A few Plumber runs. Seems fine.
> Better tower tests, bedtime triple sized, plumber liana fix

- RELEASE/scripts/autoscend/auto_mr2020.ash
> Fix Power Glove buff glitch

- RELEASE/scripts/autoscend/autoscend_migration.ash
Update master version for release.
> version bump to 1.3.0

- RELEASE/scripts/autoscend.ash
- RELEASE/scripts/autoscend/auto_mr2016.ash
- RELEASE/scripts/autoscend/auto_util.ash
Improve handling of wand of nagamar acquisition.
Ran it in overdrunk to make sure there are no obvious errors.
But it needs more testing in run still.
> wand of nagamar acquisition fixes

- RELEASE/scripts/autoscend/auto_quest_level_10.ash
Another revert to reinstate a workaround...
> another thing still not fixed when it's supposed to be

- README.md
- RELEASE/scripts/autoscend.ash
Had some issues with plumber trying to do shore vacation without boots.
Autoscend kept on crashing when it tried to do the shore.
On my plumber run where it was not getting through the shore, it worked once i used this code.
> plumber trying to do a shore vacation without boots

- RELEASE/scripts/autoscend.ash
- RELEASE/scripts/autoscend/auto_quest_level_13.ash
Pull Etched Hourglass in softcore and uses it with other daily actions. Closes #303 .
Have run locally for a few days. Seems to work.
> Etched Hourglass support

- RELEASE/scripts/autoscend.ash
hahaha whoops, meant to put this in #329 
`validate`
> Fix log of zones-to-avoid when encountering Shen

- RELEASE/scripts/autoscend.ash
Fix plumber trying to collect a semirare without boots.
Issue #325 subissue 1
take off boots when at semirare, run with this code, it worked.
> Fix plumber trying to collect a semirare without boots.

- RELEASE/scripts/autoscend.ash
- RELEASE/scripts/autoscend/auto_aftercore.ash
- RELEASE/scripts/autoscend/auto_casual.ash
- RELEASE/scripts/autoscend/auto_elementalPlanes.ash
- RELEASE/scripts/autoscend/auto_optionals.ash
- RELEASE/scripts/autoscend/auto_quest_level_4.ash
- RELEASE/scripts/autoscend/autoscend_header.ash
*Added support for casual
*issue #218 subissue 2
*issue #218 subissue 4
Ash calls.
Also targetted portions of a casual run to make sure the components I added work as intended. fixing any errors i found.
> initial casual support

- RELEASE/scripts/autoscend/auto_quest_level_9.ash
boolean L9_twinPeak() refactoring and fixes:
*Only 1 NC has a variable value (that changes based on what we want to do). consolidate the other NC settings at the beginning, removing duplicates, and added comments explaining which is which
*Removed backwards handler for NCs.
*Backwards handler for welcome NC had a bug which is not an issue anymore since it was removed entirely. If you had enough item drop it was not a problem. If you did not it will just keep on wasting turns here.
*use providePlusNonCombat(25).
**Did not yet remove the hardcoded NC provider bjorned grimstone golem as that specific NC provider is not yet included in providePlusNonCombat. Adding it to providePlusNonCombat and replacing all instances of it (of which there seem to be quite a few) with providePlusNonCombat …
> boolean L9_twinPeak() refactoring and fixes

- RELEASE/scripts/autoscend/autoscend_header.ash
quick fix to header file as it's breaking the junkyard quest (and possibly a couple of things).
> header changes missed out in PR #375

- RELEASE/scripts/autoscend/autoscend_migration.ash
> update to 1.4. prior to pushing to master

- RELEASE/scripts/autoscend/auto_pre_adv.ash
- RELEASE/scripts/autoscend/quests/level_12.ash
Also fix the double check to actually fix these issues if they occur again somehow.
> ensure we only switch to a familiar when calculating meat drop.

- RELEASE/dependencies.txt
switch helix fossil dependency address to LASS fixed version
nothing to test
> switch helix fossil to LASS fixed version

- RELEASE/scripts/autoscend/quests/level_8.ash
What's worse than spaghetti code? Tagliatelle? Linguine? Fettuccine? Yeah lets go with Fettuccine. That's what I'm calling this from now on, Fettuccine code.
Hasn't. Validates.
> Don't farm ores if we have a mountain man trapped in the chateau painting

- LICENSE
- README.md
Change license and add button & hyperlink to Readme.
Fixes #451 
Doesn't need tested (isn't code).
> Change license to CC BY-NC-SA 4.0 and add info on readme.

- RELEASE/scripts/autoscend/autoscend_migration.ash
> change version to 1.4.1

- RELEASE/scripts/autoscend/autoscend_migration.ash
> and back to 1.5.0

- RELEASE/scripts/autoscend/auto_util.ash
> fix typo'd skill name. (#492)

- RELEASE/scripts/autoscend/auto_util.ash
> fix ProvidePlusNonCombat not inverting the return value from numeric_modifier() (#494)

- RELEASE/scripts/autoscend/iotms/mr2017.ash
Adding a check to mummify familiar for paths without familiar usage.
> updating mummifyFamiliar to be more path aware

- RELEASE/scripts/autoscend/auto_util.ash
Addresses the issue in https://github.com/Loathing-Associates-Scripting-Society/autoscend/issues/520
> Check that player has the Ur-Kel skill before shrugging off another song

- RELEASE/scripts/autoscend/auto_util.ash
> Merge #523 to beta

- RELEASE/scripts/autoscend/auto_util.ash
booty crab is not instakillable
validates. which is all it really needs.
> booty crab not instakillable

- RELEASE/scripts/autoscend/quests/level_8.ash
`boolean L8_getMineOres()` was a huge chain of `else if` which made it too fragile with multiple issues.
*fixed not getting ore if in hardcore and level > 11
*fixed normal ascension spending expensive resources on ore when if you reach that function when out of pulls for the day (just do other quests today and finish this tomorrow when you get new pulls).
*added comments
*improved heavy rains handling
*fixed infinite loop in normal if you have enough pulls remaining, try to pull ore, and fail for any reason (for example not having enough hangk meat to buy the ore)
HC standard seal clubber at level 14 was stuck with this being the only quest not completed and it would not do it. switched to this code and it fixed the issue.
> boolean L8_getMineOres() reworked

- RELEASE/scripts/autoscend/auto_restore.ash
auto_restore.ash adjusted whitespace for readability
I am spinning this off the whitespace changes into their own PR because they are making it too hard to see what is happening in #551 
validated. which is all it needs. it is just whitespace changes.
> auto_restore.ash adjusted whitespace for readability

- RELEASE/scripts/autoscend.ash
- RELEASE/scripts/autoscend/auto_adventure.ash
- RELEASE/scripts/autoscend/auto_choice_adv.ash
- RELEASE/scripts/autoscend/auto_equipment.ash
- RELEASE/scripts/autoscend/autoscend_header.ash
- RELEASE/scripts/autoscend/iotms/mr2016.ash
- RELEASE/scripts/autoscend/paths/pocket_familiars.ash
- RELEASE/scripts/autoscend/quests/level_10.ash
- RELEASE/scripts/autoscend/quests/level_11.ash
- RELEASE/scripts/autoscend/quests/level_12.ash
- RELEASE/scripts/autoscend/quests/level_13.ash
- RELEASE/scripts/autoscend/quests/optional.ash
* in_pokefam() created and used
validated. this is all it needs. also can't really test pokefam because it is very broken and we have yet to track down why
> in_pokefam() created and used

- RELEASE/scripts/autoscend/auto_choice_adv.ash
This will teach me to actually review things before I approve and merge  them in future not after.
> fix duplicate case label

- RELEASE/scripts/autoscend/auto_choice_adv.ash
And this one will teach me to verify and/or run files that have been modified (also we should add things like this and pre/post_adv to the verify task as they're not caught by just verifying autoscend.ash).
> remove extraneous semicolon

- RELEASE/scripts/autoscend.ash
Pushing this without waiting for review
> rename debugPrint to logRemainingFights to prevent clash with new ash function in mafia r20476

- RELEASE/scripts/autoscend.ash
https://kolmafia.us/showthread.php?25579
after ascending mafia thinks you are an astral spirit. which causes many issues for us. the fix is to re-login or restart mafia.
Can't test it until another account ascends, but it is just an abort.
> workaround for astral spirit bug

- RELEASE/scripts/autoscend/auto_util.ash
> don't use the force on monsters we don't want to use the force on.

- RELEASE/scripts/autoscend.ash
- RELEASE/scripts/autoscend/auto_util.ash
- RELEASE/scripts/autoscend/iotms/mr2017.ash
- RELEASE/scripts/autoscend/iotms/mr2019.ash
- RELEASE/scripts/autoscend/paths/picky.ash
Change all instances of "Torso Awaregness" to "Torso Awareness".
Also update min mafia version to similar change.
validates.
> drop the 'g'

- RELEASE/scripts/autoscend/auto_providers.ash
provideStats
* added rage of reindeer effect
* added BIG effect
* added The Moxious Madrigal effect
* added some documentation
validates.
> provideStats added some skills

- RELEASE/scripts/autoscend.ash
- RELEASE/scripts/autoscend/auto_bedtime.ash
- RELEASE/scripts/autoscend/auto_equipment.ash
- RELEASE/scripts/autoscend/auto_familiar.ash
- RELEASE/scripts/autoscend/auto_post_adv.ash
- RELEASE/scripts/autoscend/auto_util.ash
- RELEASE/scripts/autoscend/autoscend_header.ash
- RELEASE/scripts/autoscend/iotms/mr2018.ash
- RELEASE/scripts/autoscend/paths/g_lover.ash
- RELEASE/scripts/autoscend/quests/level_09.ash
- RELEASE/scripts/autoscend/quests/level_11.ash
- RELEASE/scripts/autoscend/quests/level_12.ash
- RELEASE/scripts/autoscend/quests/level_13.ash
boolean in_glover() created and used
use was a find and replace followed by going through each instance and cleaning it up if needed
day 1 and 3 of a 3 day run in glover
> boolean in_glover() created and used

- RELEASE/scripts/autoscend/quests/level_11.ash
verify that mcclusky file was successfully created and abort if creating it failed.
tested in normal glover
> McClusky file verify creation

- RELEASE/scripts/autoscend/autoscend_migration.ash
> update version to 1.8.0

- RELEASE/scripts/autoscend/paths/actually_ed_the_undying.ash
> Revert Ed Servant bug detection and workaround

- README.md
as title. No actual code changes.
> remove beta info from readme

- RELEASE/scripts/autoscend/auto_util.ash
Adding support for the scrapbook's banish.
Observed a scrapbook banish at gremlins.
> Support for Scrapbook Banish

- RELEASE/scripts/autoscend/quests/level_11.ash
* verify we can actually kill specters before adventuring there
tested it once when i was unable to defeat specters
> L11 hidden city verify we can actually kill specters before adventuring there

- BUILD/settings/any.dat
- RELEASE/data/autoscend_settings.txt
- RELEASE/scripts/autoscend.ash
- RELEASE/scripts/autoscend/auto_consume.ash
- RELEASE/scripts/autoscend/auto_familiar.ash
- RELEASE/scripts/autoscend/auto_settings.ash
- RELEASE/scripts/autoscend/autoscend_header.ash
- RELEASE/scripts/autoscend/iotms/mr2017.ash
- RELEASE/scripts/autoscend/paths/g_lover.ash
Reworking the mumming trunk handling - this is essentially identical #783 , just resolving conflicts.
6 days of AWOL, no issues so far.
> Mumming trunk rework conflicts resolved

- RELEASE/data/autoscend_monsters.txt
- RELEASE/data/autoscend_task_order.txt
someone forgot to hit compile the data when they made a change to our dat files
this PR updates the compiled data files
> data compiled fix

- BUILD/restoration/clan.dat
- BUILD/restoration/dwelling.dat
- BUILD/restoration/header.txt
- BUILD/restoration/item.dat
- BUILD/restoration/skill.dat
- RELEASE/data/autoscend_restoration.txt
- RELEASE/scripts/autoscend/auto_restore.ash
make restore datafile compileable
test function. see below
also ran it in QT path softcore
> make restore datafile compileable

- RELEASE/scripts/autoscend/quests/level_13.ash
I introduced a silly typo in my last PR, so I'm fixing that here.
I double checked that I spelled sorceress correctly this time.
> Icy-Hot for the Soreceress

- RELEASE/scripts/autoscend/auto_consume.ash
- RELEASE/scripts/autoscend/autoscend_header.ash
Reverts Loathing-Associates-Scripting-Society/autoscend#840
auto_limitConsume is a thing which exists. Plus all the other mistakes.
> Revert "allow chewing spleen for adventures from familiars"

- RELEASE/scripts/autoscend/auto_consume.ash
https://github.com/Loathing-Associates-Scripting-Society/autoscend/pull/848
> Update spleen branch auto_consume.ash

- RELEASE/scripts/autoscend/auto_consume.ash
https://github.com/Loathing-Associates-Scripting-Society/autoscend/pull/848
> spleen branch remove standard check

- RELEASE/scripts/autoscend/iotms/mr2018.ash
Period missing in the boombox message.
> boombox song change message is missing a period and a space

- README.md
- docs/ISSUE_TEMPLATE.md
- docs/PULL_REQUEST_TEMPLATE
Correct a typo, fix some minor grammar, remove references to beta branch.
Not needed to test.
> Minor word changes and remove beta branch references

- RELEASE/scripts/autoscend.ash
- RELEASE/scripts/autoscend/auto_consume.ash
- RELEASE/scripts/autoscend/auto_equipment.ash
- RELEASE/scripts/autoscend/auto_pre_adv.ash
- RELEASE/scripts/autoscend/auto_providers.ash
- RELEASE/scripts/autoscend/auto_util.ash
- RELEASE/scripts/autoscend/auto_zone.ash
- RELEASE/scripts/autoscend/autoscend_header.ash
- RELEASE/scripts/autoscend/combat/auto_combat_default_stage1.ash
- RELEASE/scripts/autoscend/combat/auto_combat_default_stage4.ash
- RELEASE/scripts/autoscend/combat/auto_combat_util.ash
- RELEASE/scripts/autoscend/iotms/mr2018.ash
- RELEASE/scripts/autoscend/iotms/mr2019.ash
- RELEASE/scripts/autoscend/iotms/mr2020.ash
- RELEASE/scripts/autoscend/paths/path_of_the_plumber.ash
- RELEASE/scripts/autoscend/quests/level_05.ash
- RELEASE/scripts/autoscend/quests/level_09.ash
- RELEASE/scripts/autoscend/quests/level_11.ash
- RELEASE/scripts/autoscend/quests/level_13.ash
- RELEASE/scripts/autoscend/quests/level_any.ash
- RELEASE/scripts/autoscend/quests/optional.ash
case sensitive find `zelda` and replace to `plumber`
validate
> zelda -> plumber find and replace

- .github/workflows/ci.yml
fix github automatic validation process
2021-09-26 jenkins underwent changes and our automatic validation process is broken
all fix code came from @Rinn who posted it on discord
code is only affecting github integration. the checkmark indicates it is working.
> github validation

- .github/workflows/ci.yml
fix github workflow failing to update java. thanks @Rinn 
github gui
> fix github workflow

- RELEASE/scripts/autoscend/paths/heavy_rains.ash
Fixes Heavy Rains Skill buying logic and improves script-readability in that area. 
Edited personal copy with this and tested. No longer got into infinite loop every time it got a HR Skill item
> Heavy rains

- RELEASE/scripts/autoscend/auto_choice_adv.ash
- RELEASE/scripts/autoscend/auto_consume.ash
- RELEASE/scripts/autoscend/auto_equipment.ash
- RELEASE/scripts/autoscend/auto_pre_adv.ash
- RELEASE/scripts/autoscend/auto_restore.ash
- RELEASE/scripts/autoscend/auto_util.ash
- RELEASE/scripts/autoscend/autoscend_header.ash
- RELEASE/scripts/autoscend/iotms/mr2015.ash
- RELEASE/scripts/autoscend/iotms/mr2016.ash
- RELEASE/scripts/autoscend/iotms/mr2018.ash
- RELEASE/scripts/autoscend/paths/avatar_of_boris.ash
- RELEASE/scripts/autoscend/quests/level_11.ash
Change in_boris to is_boris
Change in_boris to is_boris
Tested
> Consistency for Boris

- RELEASE/scripts/autoscend.ash
- RELEASE/scripts/autoscend/auto_post_adv.ash
- RELEASE/scripts/autoscend/autoscend_header.ash
- RELEASE/scripts/autoscend/iotms/mr2015.ash
- RELEASE/scripts/autoscend/paths/the_source.ash
- RELEASE/scripts/autoscend/quests/level_13.ash
Create boolean in_theSource() and update references across autoscend
Create boolean in_theSource() and update references across autoscend
Script checks out
> Clean up code for The Source

- RELEASE/scripts/autoscend.ash
- RELEASE/scripts/autoscend/auto_choice_adv.ash
- RELEASE/scripts/autoscend/auto_consume.ash
- RELEASE/scripts/autoscend/auto_pre_adv.ash
- RELEASE/scripts/autoscend/auto_util.ash
- RELEASE/scripts/autoscend/auto_zone.ash
- RELEASE/scripts/autoscend/autoscend_header.ash
- RELEASE/scripts/autoscend/combat/auto_combat_default_stage4.ash
- RELEASE/scripts/autoscend/iotms/mr2015.ash
- RELEASE/scripts/autoscend/iotms/mr2016.ash
- RELEASE/scripts/autoscend/paths/avatar_of_jarlsberg.ash
- RELEASE/scripts/autoscend/paths/bees_hate_you.ash
- RELEASE/scripts/autoscend/paths/live_ascend_repeat.ash
- RELEASE/scripts/autoscend/paths/picky.ash
- RELEASE/scripts/autoscend/paths/zombie_slayer.ash
- RELEASE/scripts/autoscend/quests/level_07.ash
- RELEASE/scripts/autoscend/quests/level_10.ash
- RELEASE/scripts/autoscend/quests/level_11.ash
- RELEASE/scripts/autoscend/quests/level_12.ash
- RELEASE/scripts/autoscend/quests/level_13.ash
More path renaming and code cleanup
Renames path code for consistency
It passes validation
> More code cleanup

- RELEASE/scripts/autoscend.ash
- RELEASE/scripts/autoscend/auto_acquire.ash
- RELEASE/scripts/autoscend/auto_choice_adv.ash
- RELEASE/scripts/autoscend/autoscend_header.ash
- RELEASE/scripts/autoscend/iotms/mr2014.ash
- RELEASE/scripts/autoscend/iotms/mr2018.ash
- RELEASE/scripts/autoscend/paths/kingdom_of_exploathing.ash
- RELEASE/scripts/autoscend/paths/license_to_adventure.ash
- RELEASE/scripts/autoscend/quests/level_03.ash
- RELEASE/scripts/autoscend/quests/level_07.ash
- RELEASE/scripts/autoscend/quests/level_09.ash
- RELEASE/scripts/autoscend/quests/level_10.ash
- RELEASE/scripts/autoscend/quests/level_12.ash
Refactors a number of choice adventures for various paths/quests.  Also includes two minor BHY changes to let path run
Fixes #939
Tested two KoE runs and one BHY runs
> Refactor some choiceAdventures

- RELEASE/scripts/autoscend/quests/level_12.ash
refactor boolean L12_clearBattlefield()
* fixes halting in bhy after junkyard is unlocked
* fixes not doing the 6th sidequest even if we wanted to. (extremely rare for us to actually want to)
* `WarPlan auto_bestWarPlan()` should respect the property "auto_skipNuns".
since it has been added here, special dispensation for that property in `boolean L12_clearBattlefield()` is no longer necessary
* cleaner code
@bustarhymes69 tested the first commit in bhy as hippy. with master branch he was stuck but with this fix it finished the quest for him.
rest is being tested still
> refactor boolean L12_clearBattlefield()

- RELEASE/scripts/autoscend.ash
- RELEASE/scripts/autoscend/auto_bedtime.ash
- RELEASE/scripts/autoscend/auto_familiar.ash
- RELEASE/scripts/autoscend/auto_pre_adv.ash
- RELEASE/scripts/autoscend/auto_util.ash
Exclude latte + Kramco check since Boris cannot equip latte.  Minor code cleanup for consistency
Boris runs and code validates
> Avatar of Boris Cleanup

- RELEASE/scripts/autoscend/auto_choice_adv.ash
- RELEASE/scripts/autoscend/autoscend_header.ash
- RELEASE/scripts/autoscend/iotms/mr2018.ash
- RELEASE/scripts/autoscend/paths/community_service.ash
- RELEASE/scripts/autoscend/quests/level_10.ash
- RELEASE/scripts/autoscend/quests/optional.ash
Moved things out of auto_choice_adv and into their own handlers.  Minor code cleanup and consistency
No issues, ran through an ascension and validates.
> Choice Refactoring

- RELEASE/scripts/autoscend/quests/level_11.ash
several people mentioned in discord how this bit of code confuses them. so I clarified the comments.
validates. only changes the message being printed and the comments
> clarified confusing message about stone wool

- RELEASE/scripts/autoscend.ash
- RELEASE/scripts/autoscend/auto_pre_adv.ash
- RELEASE/scripts/autoscend/auto_restore.ash
- RELEASE/scripts/autoscend/autoscend_header.ash
- RELEASE/scripts/autoscend/combat/auto_combat.ash
- RELEASE/scripts/autoscend/combat/auto_combat_default_stage3.ash
- RELEASE/scripts/autoscend/combat/auto_combat_default_stage5.ash
- RELEASE/scripts/autoscend/combat/auto_combat_header.ash
- RELEASE/scripts/autoscend/combat/auto_combat_zombie_slayer.ash
- RELEASE/scripts/autoscend/paths/zombie_slayer.ash
This implements enough of Zombie Slayer to get through a hardcore run, with all the recent auto-pull iotms + bear claws, all of the undead familiars, and 15 starting skill points.
What it does:
* Buys skills (Hunger -> Anger -> Master)
* Uses Infectious Bite and spams Plague Claws to kill anything that isn't physically resistant. 
* Restores HP
* Restore Horde with brains or meat, leaving enough brains to eat for the day
* Disables creating a WAND as it's not needed.
* If right bear arm is equipped, use Kodiak Moment for elemental damage if needed
* If both bear arms are equippied, use Bear Hug to get horde
* Otherwise if left bear arm is equipped, always use Bear-ly Legal for the delevel + free meat
What it currently doesn't do:
* Use any zombie buffs (+combat, +item, +ml, -combat)
* …
> minimal zombie slayer support

- BUILD/monsters/banish.dat
- BUILD/monsters/replace.dat
- BUILD/monsters/sniff.dat
- BUILD/task_order/default.dat
- RELEASE/data/autoscend_monsters.txt
- RELEASE/data/autoscend_task_order.txt
- RELEASE/scripts/autoscend.ash
- RELEASE/scripts/autoscend/auto_choice_adv.ash
- RELEASE/scripts/autoscend/auto_post_adv.ash
- RELEASE/scripts/autoscend/auto_zone.ash
- RELEASE/scripts/autoscend/autoscend_header.ash
- RELEASE/scripts/autoscend/combat/auto_combat_default_stage2.ash
- RELEASE/scripts/autoscend/paths/bugbear_invasion.ash
Enough Bugbear Invasion support to finish a run.
Could be improved by utilizing copies & backups for wanderers (may do this in a separate PR), and maybe changing routing (not gonna do this).
Fixes #90
Finished a softcore run.
> Bugbear invasion support

- RELEASE/scripts/autoscend/auto_buff.ash
* Burning Hands
* Hot Hands
* Shells of the Damned
ash calls
> add buffmaintain effects

- RELEASE/scripts/autoscend/auto_consume.ash
edit needed for division to report intended value instead of 0 or 1
tested in CLI
> consumptionProgress fix

- RELEASE/scripts/autoscend/auto_acquire.ash
Unpackage Carton of Astral Energy Drinks. Missed in #1010 
Validates and successfully unpackaged at start of day
> Unpackage carton of astral energy drinks

- README.md
Add Alium to contributors thanks to hard work post-nerf day
Not needed
> Add Alium to Contributors

- RELEASE/scripts/autoscend/auto_bedtime.ash
use spinning wheel at bedtime if that's what you have in the workshed
> use spinning wheel at bedtime

- RELEASE/scripts/autoscend/auto_util.ash
- RELEASE/scripts/autoscend/combat/auto_combat_default_stage4.ash
- RELEASE/scripts/autoscend/combat/auto_combat_quest.ash
flyer funksling with beehive to avoid the damage
update stunnable monsters
not, could not run test with funkslinging
> Flyer funksling beehive

- RELEASE/scripts/autoscend.ash
- RELEASE/scripts/autoscend/auto_buff.ash
- RELEASE/scripts/autoscend/autoscend_header.ash
- RELEASE/scripts/autoscend/iotms/mr2021.ash
Buys one of the 3 hats from the VIP lounge fireworks shop. Prioritizes -com > + com > ML
Also found bug in buffMaintain where it would attempt to buy items even if called speculatively.
Validate and ash commands in gcli. Haven't tested in run
> Buy a Fireworks Hat

- RELEASE/scripts/autoscend/iotms/mr2021.ash
KOE can't access Fireworks Shop
Fixes #1080 
Validates
> KOE Can't Access Fireworks Shop

- RELEASE/scripts/autoscend.ash
Void stones should be autosold. Extra meat is good
Validates
> Sell Void Stones

- RELEASE/scripts/autoscend/auto_bedtime.ash
- RELEASE/scripts/autoscend/auto_consume.ash
implement overdrinking green beers
fix bedtime thinking it's done when overdrunk without stooper
in run
>  St. Sneaky Pete's Day

- docs/PULL_REQUEST_TEMPLATE
Fixing typo in template
Not tested.
> Fix typo in PR template

- .github/workflows/ci.yml
Changes file pull (thx Alium and Rinn)
Fixes validation failures on Github
Validated via separate PR, including by itself now
> Github Workflow Fix

- RELEASE/scripts/autoscend/quests/level_12.ash
try to use spooky jelly as a last resort when running out of Filthworm Drone Stench, should not happen often.
if not guaranteed add bonus to retrospecs equivalent to a 50%item accessory in Filthworm zones
run but situation has not triggered again yet
> last resort Filthworm Drone Stench

- RELEASE/scripts/autoscend/iotms/eudora.ash
Adds Daily Candles and also re-orders numerically
Validates
> Add Daily Candles to Eudora

- RELEASE/scripts/autoscend/quests/level_12.ash
try to delay filthworms when waiting for Everything Looks Yellow to run out to be able to yellow ray, works best in paths where L12 is high in the task list
added monster argument to filthworms canYellowRay() check, with no monster argument it would have reported true for Use the Force, filthworms are immune
in run, works as expected
> delay filthworms for yellow ray

- RELEASE/scripts/autoscend/auto_consume.ash
adjust desirability of nightcaps by green beers drinkable
run
> Sneaky Pete's Day nightcap

- RELEASE/scripts/autoscend/auto_consume.ash
fix nothing found to consume for organ when best option was something from chez snootee or gnomish microbrewery
maybe sol-ves  #1001 or other nothing found to consume bugs
cli print
> fix consume from chez snootee or gnomish microbrewery

- RELEASE/scripts/autoscend/auto_buff.ash
- RELEASE/scripts/autoscend/auto_choice_adv.ash
- RELEASE/scripts/autoscend/auto_post_adv.ash
- RELEASE/scripts/autoscend/auto_providers.ash
- RELEASE/scripts/autoscend/autoscend_header.ash
- RELEASE/scripts/autoscend/iotms/mr2016.ash
- RELEASE/scripts/autoscend/iotms/mr2022.ash
- RELEASE/scripts/autoscend/quests/level_12.ash
Support for June Cleaver
(also snuck in a little update in mr2016.ash where I noticed we weren't checking to see if nuns was being skipped before getting an item to use at nuns)
This hasn't been tested yet - it's just choice adventure handling.
> June Cleaver

- RELEASE/scripts/autoscend/iotms/mr2022.ash
After testing, cleaning up some choices.
Casual run with june cleaver overriding the main hand weapon slot.
> June Cleaver cleanup

- RELEASE/scripts/autoscend.ash
update required mafia version to r26487
also removed an out of date comment.
Hasn't.
> bump since to the last Cleaver change

- BUILD/familiars/stat.dat
- RELEASE/data/autoscend_familiars.txt
- RELEASE/scripts/autoscend/iotms/mr2020.ash
> reenable commerce ghost

- RELEASE/scripts/autoscend.ash
- RELEASE/scripts/autoscend/autoscend_header.ash
- RELEASE/scripts/autoscend/iotms/mr2016.ash
add support for Ceci N'Est Pas Un Chapeau
can be useful for moxie class tower tests and probably for nobody else
run and cli
> Ceci N'Est Pas Un PR

- manifest.json
we can easily support git checkout
did a git checkout on my branch successfully
> Git checkout support

- README.md
- docs/CONTRIBUTING.md
- docs/PULL_REQUEST_TEMPLATE
Update references to Main
Updates references to Main
No need
> Update references to Main

- .github/workflows/ci.yml
- RELEASE/dependencies.txt
- RELEASE/scripts/autoscend.ash
> Update dependencies.txt to use git if available

- BUILD/monsters/banish.dat
- BUILD/monsters/replace.dat
- BUILD/monsters/sniff.dat
- RELEASE/data/autoscend_monsters.txt
- RELEASE/scripts/autoscend/auto_familiar.ash
- RELEASE/scripts/autoscend/auto_zone.ash
- RELEASE/scripts/autoscend/autoscend_header.ash
- RELEASE/scripts/autoscend/combat/auto_combat_default_stage2.ash
- RELEASE/scripts/autoscend/combat/auto_combat_ed.ash
- RELEASE/scripts/autoscend/combat/auto_combat_zombie_slayer.ash
- RELEASE/scripts/autoscend/iotms/mr2019.ash
- RELEASE/scripts/autoscend/iotms/mr2021.ash
- RELEASE/scripts/autoscend/quests/level_07.ash
https://kolmafia.us/threads/2023-s-nerf-s-improvements-day.28454/
and added evilness conditions to some monster data
> jan 2023 evilness change

- RELEASE/scripts/autoscend/iotms/mr2022.ash
> don't exclude paths that can't use familiars from equipping the stillsuit

- RELEASE/scripts/autoscend/iotms/mr2022.ash
Reverts Loathing-Associates-Scripting-Society/autoscend#1280
> Revert "don't exclude paths that can't use familiars from equipping the stillsuit"

- RELEASE/scripts/autoscend.ash
- RELEASE/scripts/autoscend/quests/level_11.ash
Adds Spectral Pickle Factory to tooManyAdventures override. Fixes-ish Hidden City healing issue for Jazz Agent in AoSOL.
Eyeball test.
> Spectral Pickle Factory and Jazz Agent Hidden City Issues

- RELEASE/scripts/autoscend/auto_equipment.ash
- RELEASE/scripts/autoscend/auto_pre_adv.ash
danger danger, high voltage
heavy rains run
> bonus thor's pliers in heavy rains for lightning regen

- RELEASE/scripts/autoscend/iotms/mr2021.ash
> Fix backing up in Noob Cave

- BUILD/familiars/regen.dat
- BUILD/familiars/stat.dat
- RELEASE/data/autoscend_familiars.txt
- RELEASE/scripts/autoscend.ash
- RELEASE/scripts/autoscend/paths/legacy_of_loathing.ash
buy eagle in lol, use it. no support for skills yet
yes
> lol eagles

- RELEASE/scripts/autoscend/paths/avatar_of_west_of_loathing.ash
fixes the Cow Punching description issue
self explanatory
hella tested
> super important PR

- RELEASE/scripts/autoscend.ash
- RELEASE/scripts/autoscend/auto_acquire.ash
- RELEASE/scripts/autoscend/auto_consume.ash
- RELEASE/scripts/autoscend/auto_equipment.ash
- RELEASE/scripts/autoscend/auto_familiar.ash
- RELEASE/scripts/autoscend/autoscend_header.ash
- RELEASE/scripts/autoscend/iotms/mr2022.ash
- RELEASE/scripts/autoscend/paths/small.ash
- RELEASE/scripts/autoscend/quests/level_11.ash
- RELEASE/scripts/autoscend/quests/level_13.ash
- RELEASE/scripts/autoscend/quests/optional.ash
Enables legendary book bat food for this path. 
Handles smaller organs
Pulls are a work in progress
Hippo did many runs, see discussion in this PR
> Basic Honey I Shrunk the Path Support

- README.md
- RELEASE/dependencies.txt
- RELEASE/scripts/autoscend.ash
- RELEASE/scripts/autoscend/combat/auto_combat_default_stage2.ash
- RELEASE/scripts/autoscend/combat/auto_combat_default_stage4.ash
- RELEASE/scripts/autoscend/paths/wildfire.ash
- docs/CONTRIBUTING.md
- docs/PULL_REQUEST_TEMPLATE
Please include a summary of the change. Pull requests should always be against the [main branch](https://github.com/Loathing-Associates-Scripting-Society/autoscend/tree/main).
Testing ASH scripts is tricky and generally involves you doing multiple runs with a change to see how it performs. If you did any particular tests, or have particular tests you would like to do but cant (e.g. need to test with an expensive item you dont have access to) please mention that here. Relevant Mafia session logs may also be helpful.
> Change references from LASS to Loathers

- RELEASE/scripts/autoscend.ash
- RELEASE/scripts/autoscend/auto_providers.ash
- RELEASE/scripts/autoscend/autoscend_header.ash
- RELEASE/scripts/autoscend/iotms/mr2023.ash
Use wardrobe and let maximizer decide what is worth actually using
https://kol.coldfront.net/thekolwiki/index.php/Wardrobe-o-matic
Validates. ~~Going to test in run as well so marking as draft for now~~ Tested in run and works as expected
> Wardrobe Support

- RELEASE/scripts/autoscend/iotms/mr2023.ash
Forgot to check we actually have wardrobe in #1412 
validates
> hotfix - Fix wardrobe

- RELEASE/scripts/autoscend/auto_util.ash
Fixes #1429
My `auto_hasSpringShoes()` method was different, but besides that my code has been tested in several runs. See my PR for spring shoes here: https://github.com/loathers/autoscend/pull/1426
Currently running autoscend with it.
> Fix spring shoes usage

- RELEASE/scripts/autoscend/auto_post_adv.ash
fixes #1399 
Got drunk, did drunken stupor NCs, ran `auto_post_adv.ash` in CLI and confirmed it aborted for every NC
> Abort when get drunken stupor NC

- RELEASE/scripts/autoscend/auto_bedtime.ash
- RELEASE/scripts/autoscend/iotms/mr2017.ash
Couple issues found in my first run of g lover
1. Use relatively new monster record wishable field for genie. Attempted and failed to summon a screambat. This will help all paths
2. Don't pull 11-leaf clovers in g-lover
3. Don't use pocket wishes in g-lover
In a g lover run
> Check Wishable Attribute and Small G Lover Fix

- RELEASE/scripts/autoscend/quests/level_07.ash
Reported (and rubber duck debugged) in Discord.
Hasn't.
> Fix issue with Actually Ed not doing the Alcove

- RELEASE/scripts/autoscend.ash
- RELEASE/scripts/autoscend/auto_acquire.ash
- RELEASE/scripts/autoscend/auto_familiar.ash
- RELEASE/scripts/autoscend/auto_powerlevel.ash
- RELEASE/scripts/autoscend/auto_pre_adv.ash
- RELEASE/scripts/autoscend/auto_util.ash
- RELEASE/scripts/autoscend/autoscend_header.ash
- RELEASE/scripts/autoscend/combat/auto_combat_default_stage1.ash
- RELEASE/scripts/autoscend/combat/auto_combat_default_stage3.ash
- RELEASE/scripts/autoscend/iotms/mr2023.ash
- RELEASE/scripts/autoscend/paths/avant_guard.ash
- RELEASE/scripts/autoscend/quests/level_11.ash
- RELEASE/scripts/autoscend/quests/level_12.ash
- RELEASE/scripts/autoscend/quests/level_any.ash
- RELEASE/scripts/autoscend/quests/optional.ash
Avant Guard support
5 SC AG and 2 HC AG.
> Avant Guard

- RELEASE/scripts/autoscend.ash
- RELEASE/scripts/autoscend/quests/level_04.ash
Adventures for the free bat items in the bat hole using bat wings
tested in an avant guard run, acquired all 4 items
> Get free bat zone items with bat wings

- RELEASE/scripts/autoscend/auto_equipment.ash
- RELEASE/scripts/autoscend/auto_util.ash
- RELEASE/scripts/autoscend/combat/auto_combat_util.ash
- RELEASE/scripts/autoscend/iotms/mr2023.ash
- RELEASE/scripts/autoscend/paths/wereprofessor.ash
Various wereprofessor improvements:
* buy and use Hunt
* don't try to use parka spikes when professor
* don't try to research in the hospital (as the surgeon gear means the blockers aren't used)
Some general improvements
* don't try to use the monolith if no campground
Ran Wereprof.
> feat: wereprof improvements

- RELEASE/scripts/autoscend/auto_acquire.ash
- RELEASE/scripts/autoscend/iotms/mr2023.ash
- RELEASE/scripts/autoscend/iotms/mr2024.ash
- RELEASE/scripts/autoscend/paths/legacy_of_loathing.ash
New PR to help do LoL runs
Updated PR to help run LoL runs.  I cut down a few unnecessary things from the prior PR and created this one to resolve conflicts
Several LoL runs from various parties
> Updated LoL Path Fixes

- RELEASE/scripts/autoscend/quests/level_13.ash
Please include a summary of the change. Pull requests should always be against the [main branch](https://github.com/loathers/autoscend/tree/main).
Testing ASH scripts is tricky and generally involves you doing multiple runs with a change to see how it performs. If you did any particular tests, or have particular tests you would like to do but cant (e.g. need to test with an expensive item you dont have access to) please mention that here. Relevant Mafia session logs may also be helpful.
> Keep yearbook camera in KOLHS (by equipping)

- docs/PULL_REQUEST_TEMPLATE
Path and IOTM support pages are chronically out of date. Perhaps this will help keep them updated.
Don't know how to until this is merged in.
> Reminder to update GitHub wiki pages

- .github/workflows/ci.yml
Avoid the warnings in actions.
> feat: use new cache, use new output format

- BUILD/familiars/drop.dat
- BUILD/monsters/copy.dat
- RELEASE/data/autoscend_familiars.txt
- RELEASE/data/autoscend_monsters.txt
- RELEASE/scripts/autoscend.ash
- RELEASE/scripts/autoscend/auto_consume.ash
- RELEASE/scripts/autoscend/auto_post_adv.ash
- RELEASE/scripts/autoscend/auto_pre_adv.ash
- RELEASE/scripts/autoscend/auto_sim.ash
- RELEASE/scripts/autoscend/auto_util.ash
- RELEASE/scripts/autoscend/autoscend_header.ash
- RELEASE/scripts/autoscend/combat/auto_combat_default_stage2.ash
- RELEASE/scripts/autoscend/combat/auto_combat_default_stage4.ash
- RELEASE/scripts/autoscend/combat/auto_combat_ed.ash
- RELEASE/scripts/autoscend/combat/auto_combat_util.ash
- RELEASE/scripts/autoscend/iotms/mr2012.ash
- RELEASE/scripts/autoscend/iotms/mr2015.ash
- RELEASE/scripts/autoscend/iotms/mr2017.ash
- RELEASE/scripts/autoscend/iotms/mr2021.ash
- RELEASE/scripts/autoscend/iotms/mr2022.ash
- RELEASE/scripts/autoscend/iotms/mr2023.ash
- RELEASE/scripts/autoscend/iotms/mr2025.ash
- RELEASE/scripts/autoscend/quests/level_08.ash
- RELEASE/scripts/autoscend/quests/level_11.ash
- RELEASE/scripts/autoscend/quests/level_any.ash
Poorly so far. Does not literally crash while running on a character with HugeLarge duffel and without. Avalanche used sometimes correctly. Minor issue with avalance sometimes being attempted and failing due to wrong output from Mafia `has_skill()`, this needs to be resolved before merge.
This is being put up so other people can test it and hopefully run without crashes in the level 8 quest before full merge.
Please help test.
> NSA nerf, Mt McLargeHuge duffel support for opening and avalanche.

- BUILD/restoration/item.dat
- RELEASE/data/autoscend_restoration.txt
- RELEASE/scripts/autoscend.ash
- RELEASE/scripts/autoscend/auto_acquire.ash
- RELEASE/scripts/autoscend/auto_choice_adv.ash
- RELEASE/scripts/autoscend/auto_restore.ash
- RELEASE/scripts/autoscend/autoscend_header.ash
- RELEASE/scripts/autoscend/combat/auto_combat_util.ash
- RELEASE/scripts/autoscend/iotms/mr2024.ash
- RELEASE/scripts/autoscend/quests/level_11.ash
- RELEASE/scripts/autoscend/quests/level_any.ash
Support Takerspace.
Three runs.
> feat: takerspace

- README.md
- RELEASE/scripts/autoscend.ash
Bad Moon isn't supported. Exit immediately.
validates.
> Camels back.

- RELEASE/scripts/autoscend/auto_zone.ash
- RELEASE/scripts/autoscend/autoscend_header.ash
- RELEASE/scripts/autoscend/paths/bugbear_invasion.ash
Various issues found while running Bugbear Invasion.
Still has an issue where it doesn't kill the final boss / free the king but that's easy enough to do manually. Still an issue where tracking Bugbear Battlesuits from the Airship makes them show up way too much in Engineering.
Bugbear runs. It's not perfect but does improve some things.
> feat: better bugbear invasion

- RELEASE/scripts/autoscend/iotms/mr2024.ash
Mmm-Brr Mouthwash does NOTHING (gives no stats) in Path of the Plumber
It Hasn't
> Tooth Decay for Mario

- RELEASE/scripts/autoscend/auto_buff.ash
- RELEASE/scripts/autoscend/auto_providers.ash
- RELEASE/scripts/autoscend/auto_util.ash
- RELEASE/scripts/autoscend/autoscend_header.ash
- RELEASE/scripts/autoscend/paths/zootomist.ash
Creates a provider for familiar experience.
Several Zootomist runs
> Familiar Experience Provider

- RELEASE/scripts/autoscend.ash
- RELEASE/scripts/autoscend/auto_choice_adv.ash
- RELEASE/scripts/autoscend/autoscend_header.ash
- RELEASE/scripts/autoscend/iotms/mr2025.ash
This will choose an appropriate monster if presented with the Peridot of Peril choice adventure
Half a standard
> Peridot of Peril Support

- RELEASE/scripts/autoscend/auto_post_adv.ash
Fixes trying to use antidote in zombie slayer
locally
> Galaktik sells anti-anti-antidote
