loathers/autoscend

RELEASE/scripts/sl_ascend/sl_ascend_header.ash, RELEASE/scripts/sl_ascend/sl_community_service.ash, RELEASE/scripts/sl_ascend/sl_mr2019.ash
Get beach head buffs for mus, myst, mox, hot and familiar weight CS quests. For some reason it often fails to get the beach head buff but I think this is a bug in mafia right now so calling it for now since the working ones prove the others will work one day. probably.
=> Cs beachcomb efficiency

BUILD/monsters/banish.dat, BUILD/monsters/yellowray.dat, RELEASE/data/autoscend_monsters.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_combat.ash, RELEASE/scripts/autoscend/auto_edTheUndying.ash, RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/auto_mr2019.ash, RELEASE/scripts/autoscend/auto_post_adv.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash
Long list of things I've been working on a testing for a while to make Actually Ed with no IotMs less bad.
There are a handful of bugfixes in here too which I didn't get around to extracting to submit individually (had been doing that in the past on sl_ascend). The main highlights are thus:
- Ed: no longer dies twice unnecessarily. This should mean your runs go faster and encounter fewer aborts. It can and will still die when it loses initiative 3 times in a row but since it now (mostly) gets 3 attempts at each combat for free, there's more chance of it killing the monster. Note: doesn't apply when flyering as we can abuse the UNDYING mechanic to flyer the same monster multiple times and by level 12 you're generally able to take a hit from full HP so it matters less.
- Ed: no longer …
=> Bunch of changes to make no IotM Ed less terrible.

RELEASE/scripts/autoscend.ash
as title. Single line change to hotfix something I didn't consider on the beta branch.
It hasn't yet. I realised I wouldn't see this as a problem in Ed since Ed doesn't fight the NS but any paths that do would fail to make the Wand before fighting the NS if they have no clovers when they reach level 13.
=> BugFix: Save a clover when powerlevelling at 12 if in a path that needs a Wand of Nagamar

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_edTheUndying.ash
- Add a check in L8_trapperGroar() to check if we've done the goat cheese and ores
- revert back to dumping the hippy pants in closet as the maximizer had issues.
- moved the level 5 quest earlier than then level 4 as we yellow ray a Harem Girl for the outfit
Found these during current test run of Ed. Hence hotfixing.
=> A couple of quick fixes

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_combat.ash
Fixes #94 
Fixes #107 
Relevant to #93 (delays the Nook)
Ran through two softcore KoE runs. Confirmed it:
* Delayed nook
* Used evil eyes when available
* Used exploding cigar against skeleton astronauts on day 1
* Opened and finished tower
=> Fix KoE keys, delay nook, use exploding cigar on astronauts

RELEASE/scripts/autoscend/auto_community_service.ash, RELEASE/scripts/autoscend/auto_mr2018.ash
On day 2 of community service, use fertilizer dropped on day 1 to get the +10 lb familiar equipment from tall grass. Wont do this if it already has one of the poke fam items or the astral pet sweater. Can add other fam equipment if needed.
Fixes #98 
I havent tested this yet since I already used my turns but I've written something like this before and lost it. Will remove WIP tag after tested.
=> WIP having CS path try to get +10 lb pokefam item using fertilizer

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_util.ash
Add prioritization for -combat to Hidden Park so that we relocate Janitors before we get the machete, and we can get the quest related items faster
Hasn't. :/
=> Optimize hidden park

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_koe.ash, RELEASE/scripts/autoscend/auto_mr2019.ash, RELEASE/scripts/autoscend/auto_post_adv.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash
* Adds utility functions for the Pill Keeper
* Adds utility functions for forcing the next adventure to be a noncombat (delegating to Pill Keeper/Clara's Bell/stench jelly as required)
* Use noncombat-forcing functionality in:
* Castle basement (1 use)
* Castle top floor (2 uses)
* Hidden Apartment Building (1 use - along with using the hidden tavern to drink 3x Cursed Punch, saving 9 turns)
Also a one-off fix to close #113 (aborting in KoE when out of quests).
Has gone through a KoE SC run. Looks good to me:
Note that there are some implications for nonstandard paths where spleen can be converted into turns and it might be a bad idea to save 3 turns for 3 spleen. I haven't thought about how to address those issues and would be pleased for rampant speculation to take place in the comments …
=> Pill Keeper and stench jelly usage

RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/auto_post_adv.ash
Keeps accessories required by outfits (War outfits and eXtreme) in our reserved slot acc3
Issues reported on Discord
Hasn't
=> Outfit acc normalization

RELEASE/scripts/autoscend/auto_restore.ash
new restoration logic will now buy restorers from NPC stores if appropriate.
Was previously checking `meat_reserve > my_meat()` which doesn't make much sense (only use the source when we have less than the amount of meat we want to keep on hand?).
Now checks for `meat_reserve < my_meat()`
Single character change.
Fixes #140 
Running HC Ed with this change right now. Also tested using `ash import <autoscend.ash> acquireMP(40, 1000);` in the cli.
=> fix to new restoration NPC store purchase logic

RELEASE/scripts/autoscend/auto_koe.ash
Uses `simMaximizerWith()` rather than `simMaximizer()` before the Invader. Also moved the addition of the maximizer string until we were sure we are ready to fight.
Fixes #144
Hasn't
=> Fixing maximizer issue with the Invader

README.md, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_combat.ash, RELEASE/scripts/autoscend/auto_cooking.ash, RELEASE/scripts/autoscend/auto_edTheUndying.ash, RELEASE/scripts/autoscend/auto_mr2015.ash, RELEASE/scripts/autoscend/auto_post_adv.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_restore.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash
More changes for Ed (hopefully the last for now, I really would like to work on a different path for a while e.g. KoE)
- Ed will use the new consumption code to fill stomach and liver when low on adventures (still uses Fortune Cookies/Lucky Lindy's for SR counters).
- Ed (and hopefully all other classes) do the Junkyard combats "optimally" now. Ed definitely wastes a lot fewer adventures trying to get Yossarians tools.
- Ed bugfix: When doing Sonofa beach, we no longer stop if we have no Talisman of Horus in inventory but actually have the buff it gives.
- Ed will buff using the telescope, Lyle and the cheap muscle & moxie buffs when attempting to fight modern zmobies so we don't just die repeatedly due to their massive initiative and Ed's pitiful HP.
- various other small quality of …
=> more changes for Ed

BUILD/familiars/stat.dat, RELEASE/scripts/autoscend/auto_edTheUndying.ash, RELEASE/scripts/autoscend/auto_util.ash
- add party mouse to stat familiars
- stop Ed from using pill keeper when it's not free
- Ed will buy whittled stuff when you have enough firewood
- add Paul's Passionate Pop Song to buffMaintain
Most of it hasn't. I'm running KoE not Ed at the moment.
=> some miscellaneous Ed and non-Ed changes

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_aftercore.ash, RELEASE/scripts/autoscend/auto_community_service.ash, RELEASE/scripts/autoscend/auto_edTheUndying.ash, RELEASE/scripts/autoscend/auto_mr2012.ash, RELEASE/scripts/autoscend/auto_mr2013.ash, RELEASE/scripts/autoscend/auto_mr2014.ash, RELEASE/scripts/autoscend/auto_mr2015.ash, RELEASE/scripts/autoscend/auto_mr2016.ash, RELEASE/scripts/autoscend/auto_mr2018.ash, RELEASE/scripts/autoscend/auto_theSource.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash
- update mafia version.
- rename some functions to be less ambiguous or vague
- move a bunch of stuff out of autoascend.ash and the doTasks() function to the appropriate auto_mr[year].ash file
- remove a duplicate Ed function
This is some of my current KoE changes. I'm attempting to break the changes down into smaller chunks so it's easier to review as it's going to be a massive onerous task otherwise. KoE runs are ongoing as are changes/improvements.
=>  move stuff out of autoscend.ash

RELEASE/scripts/autoscend/auto_combat.ash
Found doWeaksauce checks to be missing in some instances, causing us to waste a turn on invader bullets.
Reported on Discord.
Hasn't
=> Adding doWeaksauce check to two areas where it was missing.

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_util.ash
Changed OoP for unlocking Guild and Beach (meatcar), so that we can get the Antique Accordion faster.
Converted a lot of prices to reference npc_price() instead of a hardcoded price. Allowing for more accurate acquisition.
MP drain from casting expensive songs for 5 songs each, problems getting items from NPCs caused by incorrect or inaccurate item costs.
2/3 Softcore run
=> Optimize getting Antique Accordion, also make prices reflect real cost rather than hardcoded

RELEASE/scripts/autoscend.ash
Maximizer likes to force fam equips on us, which causes issues in Wall of Bones and Gremlins. This forces us to go into the fight with no Familiar equipment.
Fixes # (issue) #154 
Hasn't
=> Go into Wall Of Bones and Gremlins with no familiar equips

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_community_service.ash
Adds Mu as an alternative to Exotic Parrot
Issue reported on HC chat on KoL
Hasn't
=> Adding the use of Mu as an alternative to Exotic Parrot

RELEASE/scripts/autoscend.ash
Adding the possibility to get an Antique accordion BEFORE Toy Accordion.
Verifying npc_price does not return 0 (meaning we can get to the location)
macgregor reported issue on Discord
Hasn't yet.
=> Add price to early accordion check

RELEASE/scripts/autoscend/auto_zone.ash
Changes the Warnings printed when the script checks for zones to Debug. The script can get a bit spammy when searching for where to burn delay, and it is scaring people.
Nope.
=> Move the Unlock Warnings to Debug due to confusion in the community.

RELEASE/scripts/autoscend/auto_zone.ash
Script looping when we try to get logging hatchet. Added Camp Logging Camp to the possibilities in auto_zone
reported on discord
Hasn't
=> Add Camp Logging Camp to auto_zone to prevent looping

BUILD/monsters/sniff.dat, RELEASE/data/autoscend_familiars.txt, RELEASE/data/autoscend_monsters.txt, RELEASE/data/autoscend_properties.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_combat.ash, RELEASE/scripts/autoscend/auto_cooking.ash, RELEASE/scripts/autoscend/auto_deprecation.ash, RELEASE/scripts/autoscend/auto_edTheUndying.ash, RELEASE/scripts/autoscend/auto_koe.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/autoscend_header.ash
- add dirty old lihc to sniff targets with appropriate property check
- actually add Party Mouse to familiars (forgot to run the build script last time)
- remove auto_beta_test if it exists (another thing missed out in a previous PR)
- change all checks for 2CRS to use in_tcrs()
- in KoE don't bother fighting the Invader until we're at the hedge maze. Also use the mafia property to track if it's been killed.
- Fix an issue with 100% familiar runs where using the new consumption logic would remove familiars and not re-equip them so you'd adventure with no familiar.
- update minimum KoLMafia version since they fixed the issue with the Palindome quest in KoE
- rename doThemtharHills() to L12_ThemtharHills()
- KoE should not attempt to get Inhalers (since no nuns) nor Cyclops Eyedrops (since …
=> KoE (and general) changes...part 1

RELEASE/scripts/autoscend/auto_post_adv.ash
Using clever logic appropriated from auto_restore to determine if we CAN use familiars before trying to maintain the buffs that target familiars
#187 
Hasn't
=> Only maintain Familiar skills in paths with familiars.

RELEASE/scripts/autoscend/auto_util.ash
Mafia returns DRK as not a boss, but it is. Added it to the list and started a new entry for other randos like this.
#75 
Hasn't
=> Added Drunken Rat King to the no-instakill list

RELEASE/scripts/autoscend/auto_adventure.ash, RELEASE/scripts/autoscend/auto_edTheUndying.ash, RELEASE/scripts/autoscend/auto_post_adv.ash, RELEASE/scripts/autoscend/autoscend_header.ash
Fixes the failures in autoAdvBypass caused (probably) by changes in KoLMafia to adventure handling.
Generally our adventure handling needs some tech debt addressed but as Ed requires his own handling due to his special resurrection mechanic, I'm only fixing his issues for now (as testing non-Ed would require running another path).
Fixes #181 #153 
On a second Ed run at present. None of the issues listed in #181 have failed.
=> fix Ed adventure handling

RELEASE/scripts/autoscend/auto_edTheUndying.ash
Color specification in abort message causing script to fail.
reported on discord
---
=> BugFix: remove color specification from abort message

RELEASE/scripts/autoscend/auto_mr2019.ash
Had to resubmit as a different pull request because I bungled things up with regards to branch handling. As I was unfamiliar with git. Apparently I should use a different branch for every bug that I want to submit.
====
can't equip offhand items like kramko grinder in some paths, so don't try to fight sausage goblins in surprising fist and avatar of boris.
Fixes #200
How Has This Been Tested?
Tested in way of the surprising fist, not yet tested in avatar of boris.
In way of surprising fist I ran autoscend, and 3 times in a row it immediately failed on the first adventure as per #200
Once I made this change it proceeded to work.
@Malibu-Stacey
this includes the correction you suggested.
=> kramko can't be used in some paths

BUILD/monsters/yellowray.dat, RELEASE/data/autoscend_monsters.txt, RELEASE/data/autoscend_properties.txt, RELEASE/relay/autoscend_quests.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_adventure.ash, RELEASE/scripts/autoscend/auto_bondmember.ash, RELEASE/scripts/autoscend/auto_boris.ash, RELEASE/scripts/autoscend/auto_combat.ash, RELEASE/scripts/autoscend/auto_deprecation.ash, RELEASE/scripts/autoscend/auto_digimon.ash, RELEASE/scripts/autoscend/auto_edTheUndying.ash, RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/auto_glover.ash, RELEASE/scripts/autoscend/auto_groundhog.ash, RELEASE/scripts/autoscend/auto_heavyrains.ash, RELEASE/scripts/autoscend/auto_koe.ash, RELEASE/scripts/autoscend/auto_mr2015.ash, RELEASE/scripts/autoscend/auto_mr2016.ash, RELEASE/scripts/autoscend/auto_mr2018.ash, RELEASE/scripts/autoscend/auto_post_adv.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_sneakypete.ash, RELEASE/scripts/autoscend/auto_standard.ash, RELEASE/scripts/autoscend/auto_summerfun.ash, RELEASE/scripts/autoscend/auto_tcrs.ash, RELEASE/scripts/autoscend/auto_theSource.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/auto_zone.ash, RELEASE/scripts/autoscend/autoscend_header.ash
This is a large PR but for good reason. I split as much as I could out into #186 and #168 previously. There are a handful of things in here I could probably split into their own PR but it's not worth the effort and this is been going on long enough that I want to get it merged and move on to other things.
The main focus of this PR is to have our quest handling functions (yes **all** of them) conditioned on the appropriate mafia quest properties rather than our own properties and/or being the expected level. The impetus for this change was seeing Exploathing runs attempt to powerlevel which quite frankly is madness but I think this generally makes the whole script more resilient and future proof.
The pattern I've been following for checking if we should be in a quest handling function is …
=> KoE (and general) changes...part 2

RELEASE/scripts/autoscend/auto_cooking.ash
Fixes issue Kendaer reported on discord where the knapsack diet consumption code will try to "buy" speakeasy drinks and fail, because they aren't actually items to buy. It does so by disabling speakeasy drinks in that code completely, because they should probably not be automatically consumed just for their adventure content, they should be consumed for their effects if at all.
Only testing done was to make sure the script doesn't have any syntax errors or such via importing it and getting no errors. It's a simple change but difficult for me to test atm because I would need to do a non-standard run where I somehow didn't have better sources of booze for pure adventures than speakeasy drinks (which is far from the case since I have the source terminal, among other things). Kendaer should …
=> Don't attempt to buy speakeasy drinks

RELEASE/scripts/autoscend/auto_cooking.ash, RELEASE/scripts/autoscend/auto_util.ash
Fixes a minor issue I encountered during a Pastamancer run where I had wasted a ton of mp getting up to over 2000 turns of Shield of the Pastalord while my other buffs only had around 20 turns. The source of the issue was that `buffMaintain` was checking for the effect Flimsy Shield of the Pastalord to see if we had enough turns that we didn't need to cast it again. I also did the reverse for calling `buffMaintain` with regular Shield of the Pastalord just to be thorough, even though `buffMaintain` is never called on the non-flimsy version as the code stands (nor should it be for the sake of consistency).
Once again, this pull request seems to be including my already merged commit to prevent buying speakeasy drinks... Not sure how to solve that issue.
I have tested this as Pastamancer by …
=> Minor fix for an issue with shield of the pastalord

RELEASE/relay/autoscend_quests.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_island_war.ash, RELEASE/scripts/autoscend/auto_mclargehuge.ash
- use the evilometer and visit the cyrpt to make sure the status is correct for the level 7 quest properties
- force autoSatisfyWithCloset to false and backup the setting so it's restored when the script is aborted or finishes.
- remove warning for recoveryScript and just disable and backup regardless.
- fix infinite loop when deciding not to do Nuns
- fix quest status checks in level 8 quest so we don't pre-emptively attempt to get ninja climbing gear or eXtreme Cold-Weather Gear before we've even got the goat cheese and/or Ores.
Fixes #216 #215 
Running HC Ed at the moment.
=> Few small fixes from reports in discord and issue tracker

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_batpath.ash, RELEASE/scripts/autoscend/auto_cooking.ash, RELEASE/scripts/autoscend/auto_highlands.ash, RELEASE/scripts/autoscend/auto_macguffin.ash, RELEASE/scripts/autoscend/auto_mclargehuge.ash, RELEASE/scripts/autoscend/auto_mr2017.ash, RELEASE/scripts/autoscend/auto_mr2019.ash, RELEASE/scripts/autoscend/auto_tower.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash
Moves a bunch of repeated manual calls for various buffs in to general functions to provide a given stat, so we only have to add future effects that provide that stat in one place, instead of everywhere we use that stat.
Also I'm not sure why that "Don't attempt to buy speakeasy drinks" commit is there, considering it's already been merged in to autoscend in a separate pull request... any help with getting that excluded from this pull request so we don't have a weird dupe commit would be appreciated.
I've done five hardcore standard runs with these changes and they seem to work as expected.
=> Add provider functions for initiative, resistances, and stats

BUILD/settings/any.dat, RELEASE/data/autoscend_settings.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_adventure.ash, RELEASE/scripts/autoscend/auto_edTheUndying.ash
The main issue here is fixing how we handle powerlevelling in the Neverend due to a report on Discord but I had a few other small fixes for annoyances/aborts I've noticed during Ed test runs or people raised on Discord pending, so I've bundled them all together.
- Remove a bunch of unnecessary IotM availability toggles from the relay page (mafia preferences support almost all of these)
- Fix powerlevelling in the Neverend to actually count as powerlevelling and not completely skip a bunch of important stuff we use to handle doing quests instead of powerlevelling when there are quests to do.
- Fix an abort that could happen if you powerlevelled in the Haunted Gallery from 12 -> 13
- Ed should no longer care about having enough MP to cast Shelter of Shed when doing the Tavern
- Add backing …
=> Another bunch of small fixes.

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_aftercore.ash, RELEASE/scripts/autoscend/auto_cooking.ash, RELEASE/scripts/autoscend/auto_mr2015.ash, RELEASE/scripts/autoscend/auto_mr2016.ash, RELEASE/scripts/autoscend/auto_mr2019.ash, RELEASE/scripts/autoscend/auto_tower.ash, RELEASE/scripts/autoscend/autoscend_header.ash
* Don't try to use Snojo, DMT, or shoe gum in Exploathing
* Adjust Milk of Magnesium handling, since it now gives 5 advs once/day.
* Consume Milk of Magnesium before eating magical sausages.
* When at the tower and missing the star key, alert the player that
perhaps they should set auto_getStarKey. This mostly comes up in
barely-supported paths where start-of-run logic doesn't set
auto_getStarKey.
Milk of Magnesium changes partially address #214 
1 HC Exploathing run, followed by 1 HC Big! run. I own the IOTMs under test.
=> Post-rotation Exploathing fixes, new Milk of Magnesium handling

RELEASE/scripts/autoscend/auto_cooking.ash, RELEASE/scripts/autoscend/auto_util.ash
Add debug printing to provider functions to help figure out any potential issues in them in the future.
Also fix an issue with speculative `buffMaintain` where it would think you could provide buffs you were incapable of providing.
Since this is primarily a logging change, I've tested by running the functions with debug logging enabled and observing the output.
As for the `buffMaintain` fix, I tested it by checking the output of `buffMaintain($effect[Hide of Sobek], 0, 1, 1, true);` before and after the change (while not Ed, of course). Before it was `true`, after it was `false`. Not extensive, but I'm not in run at the moment.
=> Providers debug printing

RELEASE/scripts/autoscend/auto_cooking.ash, RELEASE/scripts/autoscend/auto_util.ash
Someone in Discord reported Ed trying to use mayoflex: https://pastebin.com/0ZNCTt2Q . It appears that Mafia's `get_campground()` implementation doesn't know that Ed doesn't have campground access? This adds a guard in `auto_get_campground` to early-return if we're in Actually Ed, which should also flush out any other related bugs in Ed that nobody has reported yet.
I have checked that `verify autoscend` works locally. I have not tested the actual functionality.
=> Campground items are not available in Actually Ed

RELEASE/scripts/autoscend/auto_post_adv.ash
[Crash reported in Discord](https://cdn.discordapp.com/attachments/538086828234899458/672654502574161951/unknown.png)
`verify auto_post_adv` and nothing else.
=> Fix crash in postadventure with zero MP regen

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_cooking.ash, RELEASE/scripts/autoscend/auto_mr2020.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash
Will seek out a bird or visit your favorite bird when possible to provide initiative, resistances, or stats.
Also adds auto_mr2020.ash, with some bird calendar functions, since those are needed to be able to use the bird calendar in the first place.
I played around with the provider functions and observed them behaving as I would expect with my current bird buffs, so it's not super duper thoroughly tested but I think it's probably tested enough.
=> Add support for bird calendar buffs in provider functions

RELEASE/scripts/autoscend/auto_clan.ash, RELEASE/scripts/autoscend/auto_island_war.ash, RELEASE/scripts/autoscend/auto_mr2020.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash
Partially addresses #232 
I ran this code for a day and belatedly realized it wasn't using the Powerful Glove to get. After fixing two embarrassing typos, the best test I could do was:
```
> ash import <autoscend> providePlusNonCombat(25)
WARNING: Unreachable code (auto_cooking.ash, line 1120)
[INFO] - I think we're good to go to apply The Sonata of Sneakiness
[DEBUG] - Adding "-200combat 25max" to current maximizer statement
[DEBUG] - Removing "-equip fancy boots" from current maximizer statement
[DEBUG] - Adding "+equip fancy boots" to current maximizer statement
Maximizing...
240 combinations checked, best score 19,218.31
You acquire an effect: Invisible Avatar (10)
Preference _powerfulGloveBatteryPowerUsed changed from 0 to 5
CHEAT CODE: Invisible Avatar was successfully cast. …
```
=> Use Powerful Glove for -combat

RELEASE/scripts/autoscend/auto_giant_trash.ash, RELEASE/scripts/autoscend/auto_mr2018.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash
* Reset maximizer when doubling-up adventures in Castle.
Fixes bug that could happen when preadventure equips three
accessories, finds the noncombat that requires the amulet, and then
complains that there's no space to equip the amulet.
* Don't get Muddled in Plumber, since we mostly kill with moxie and it
might make our muscle too high. Hopefully this will make scaling
fights on Day 2+ a little less lethal? :)
* Equip Pill Keeper in Plumber when flyering. Although we still don't
always win initiative, so the effect might be limited.
* Fix bug where in some cases, we would not have an un-allocated
accessory slot for the Fancy Boots in Path of the Plumber.
Ran fine during Day 2 of a softcore plumber run.
=> Misc. Plumber fixes

RELEASE/scripts/autoscend/auto_zone.ash
Compensating for `get_monsters()` not providing path-specific monsters. Veracity is considering changing this (https://kolmafia.us/showthread.php?24497-Spring-2020-Challenge-Path-Path-of-the-Plumber&p=155739&viewfull=1#post155739), but it's easy to handle this in autoscend, since currently it King Boo is the only place it's relevant (that I know of).
```
> ash get_monsters($location[summoning chamber])
Returned: aggregate monster [1]
0 => Lord Spookyraven
```
=> Equip Fire Flower for King Boo fight

RELEASE/scripts/autoscend.ash
Mafia checkpointing changes led to really bad bugs involving the war, Mafia fixed it, this bumps the version so nobody uses the bad version of mafia.
I used the web editor so it hasn't been
=> Bump Mafia version to r19810 to fix equipment checkpointing

RELEASE/scripts/autoscend/auto_zone.ash
Autoscend was attempting to burn delay in the The Boss Bat's Lair after the quest is completed because zone_available was incorrectly returning true.
The Boss Bat's Lair is only available if questL04Bat is step3
Fixes issue reported in discord.
I started a new run and verified delay burning never occurred in The Boss Bat's Lair after that quest was completed.
=> Fix Boss Bat's Lair zone_available check

RELEASE/scripts/autoscend/auto_mr2019.ash
it is actually possible to have a casing but not have the kramko grinder. for example if your grinder is in the display case.
was getting an error about being unable to grind sausage after every turn in a plumber run. After I made this change it stopped giving said error.
also I copy pasted that if function to test for if you have kramko from another part of the mr_2019 file
=> Grindsausage

BUILD/monsters/replace.dat, RELEASE/data/autoscend_monsters.txt, RELEASE/relay/relay_autoscend.ash, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_combat.ash, RELEASE/scripts/autoscend/auto_island_war.ash, RELEASE/scripts/autoscend/auto_mr2017.ash, RELEASE/scripts/autoscend/auto_mr2020.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash
Move monster replacement logic to use a data file
Move macrometeorite logic to common functions, add support for CHEAT CODE: Replace Enemy
Track monster replacement in auto_replaces instead of auto_otherstuff
Plumber: Don't fight scaling monsters without scaling damage unless a one hit ko is possible as I was losing a lot of fights
Allow replacing into lobserfrogmen when auto_hippyInstead before 64 frat defeated (auto_hippyInstead has some additional issues I may look at in another PR)
Fix ambiguous skills not being used in combat correctly
TODO for a different PR: The community service monster replacements are in the data file, but currently unused
Plumber Day 1:
* Successfully used CHEAT CODE: Replace Enemy on Banshee Librarian after acquiring a killing jar
* Successfully used CHEAT …
=> Support CHEAT CODE: Replace Enemy, 

BUILD/monsters/replace.dat, RELEASE/data/autoscend_monsters.txt
We use ';' as a delimiter in data files, so "LavaCo&trade; Lamp Factory"
was splitting into "LavaCo&trade" and " Lamp Factory", crashing the
condition-parsing engine:
"LavaCo™" does not properly convert to a location!
To fix this, I replaced "LavaCo&trade; Lamp Factory" with "LavaCo Lamp
Factory", removing the stray ';'. Mafia will correctly coerce the
no-trademark string to the correct location via
`to_location("LavaCo Lamp Factory")`
so behavior is unchanged.
I modified local data files to
```
replace    24    Lava Golem    loc:LavaCo&trade; Lamp Factory
```
so I could test outside of Community Service (outside of CS it would short-circuit the check, which is why we didn't find this before). I ran
```
ash import <autoscend> auto_wantToReplace($monster[lava golem], …
```
=> Remove parse-breaking ';' in monsters.dat

RELEASE/scripts/autoscend/auto_combat.ash, RELEASE/scripts/autoscend/auto_island_war.ash, RELEASE/scripts/autoscend/auto_restore.ash, RELEASE/scripts/autoscend/auto_zelda.ash, RELEASE/scripts/autoscend/autoscend_header.ash
The main part of this pull request is switching to calculating how many times to cast blood bond and blood bubble each ahead of time when using them, instead of casting them one by one, since that could result in an absurd number of server hits for no good reason.
I also fixed an issue where the script would attempt to start the war before unlocking the island if you were high enough level already (such as when eating a pie man was not meant to eat pizza in path of the plumber).
Finally, I got rid of `zelda_ppCurr` because it is no longer necessary.
I've done several plumber runs with these changes, but only one non-plumber run, which is what is needed to test the blood skill stuff. Absolutely no issues popped up as a result of the blood skill change though, so I'm fairly confident in it.
=> Bloodandstuff

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash
* Use triple-sized to provide stats
* Add some logging that should clarify what banish/replace/yellow ray sources we're expecting to use.
Fixes #232 (We now have all functionality described in this issue other than using the +stats when we. Might not be a bad idea to use if the "I'm having difficulty in combat" logging triggers.)
Haven't done much testing: just `verify autoscend`. Treat with suspicion.
=> Use Triple-Sized at tower test

RELEASE/scripts/autoscend/auto_combat.ash, RELEASE/scripts/autoscend/auto_highlands.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_tower.ash, RELEASE/scripts/autoscend/auto_zelda.ash
Preliminary Logging Camp optimization for Plumber runs.
Also has two minor changes thrown in, one of which fixes #256
Correctly equipped frosty button and fire flower at the Logging Camp in a high-starting-coin high-IOTM Plumber run. Correctly used fire abilities.
```
[INFO] - If we encounter Blech House when we are not expecting it we will stop.
[INFO] - Currently setup for Muscle/Weapon Damage, option 1: Kick it down
[INFO] - Equipping frosty button to slot acc1
Preference _auto_maximize_equip_acc1 changed from to frosty button
Preference auto_combatHandler changed from (banishercheck)(sk7333) to
[INFO] - Starting preadventure script...
[DEBUG] - Adventuring at The Smut Orc Logging Camp
[INFO] - Equipping [10462]fire flower to slot weapon
Preference _auto_maximize_equip_weapon changed …
```
=> [plumber] Attempt to use cold damage at Logging Camp

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_awol.ash, RELEASE/scripts/autoscend/auto_batpath.ash, RELEASE/scripts/autoscend/auto_bondmember.ash, RELEASE/scripts/autoscend/auto_boris.ash, RELEASE/scripts/autoscend/auto_digimon.ash, RELEASE/scripts/autoscend/auto_fallout.ash, RELEASE/scripts/autoscend/auto_glover.ash, RELEASE/scripts/autoscend/auto_groundhog.ash, RELEASE/scripts/autoscend/auto_heavyrains.ash, RELEASE/scripts/autoscend/auto_jellonewbie.ash, RELEASE/scripts/autoscend/auto_koe.ash, RELEASE/scripts/autoscend/auto_majora.ash, RELEASE/scripts/autoscend/auto_picky.ash, RELEASE/scripts/autoscend/auto_sneakypete.ash, RELEASE/scripts/autoscend/auto_standard.ash, RELEASE/scripts/autoscend/auto_summerfun.ash, RELEASE/scripts/autoscend/auto_tcrs.ash, RELEASE/scripts/autoscend/auto_theSource.ash, RELEASE/scripts/autoscend/auto_tower.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/auto_zelda.ash, RELEASE/scripts/autoscend/autoscend_header.ash
auto_getStarKey is set to false in initializeSettings().
Then every path will re-set it to the appropriate value for that path... which is true for every path other than ed.
This meant that pathless and standard ending up not acquiring the star key, even though they need it.
There is also already a check to change it to false if its not actually needed in auto_tower.ash, so it should default to true.
Also fixed up the function to get the star key a bit. It had some minor additional issues.
Currently doing a pathless hardcore turtle tamer with it. It set auto_getStarKey correctly to true on initialization.
The corrections to the function for getting the star key itself will be tested tomorrow. don't merge until they are tested.
=> Tidy up acquisition of star key

RELEASE/scripts/autoscend.ash
there were some combinations of path and sign that would cause the meatcar crafting logic to explode. redid the logic to both fix it and avoid future errors.
For example Vampyre + The Opossum sign did not work and caused autoscend to abort repeatedly
Vampyre non knoll sign run was erroring out about being unable to reach guild which it wanted to use to unlock degrassi knoll (vampyres don't get guild access)
With this code it instead adventured in cobb knob until it reached level 2, which then allowed it to unlock degrassi knoll, then it adventured there for components. acquired enough of them and then crafted the meatcar
=> meatcar logic

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_heavyrains.ash, RELEASE/scripts/autoscend/auto_island_war.ash, RELEASE/scripts/autoscend/auto_tower.ash
Lots of issues with the island war when fighting for the hippies.
worse offenders are:
1. it pulls frat outfit
2. if you manually pulled hippy outfit, it wears it then adventures in hippy camp to start the war for 52 turns before realizing something is wrong.
Fixes #167
probably fixes a few other open issues too
all testing thus far was in mafia r19898, which predates the NC handling change by mafia.
main account = has tons of IOTMs and all skills permed.
side account = has very few permed skills and zero IOTMs
So far I have tested:
main account, softcore plumber on hippies side, I manually fought all the way until the arena and got the hippy band fliers before deciding to start writing this update.
It successfully flyered for the hippies and then fought until the man. Did not actually …
=> Fixes for the myriad of auto_hippyInstead = true issues.

RELEASE/scripts/autoscend.ash
On April Fools, KoL replaces random words with "salad". This screws up quest handling, so we need to be extra paranoid.
https://kol.coldfront.net/thekolwiki/index.php/April_Fools%27_Day
`verify autoscend`, so it compiles at least
=> Always be paranoid on April Fools'

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_island_war.ash, RELEASE/scripts/autoscend/autoscend_header.ash
I made a mistake when rebasing the previous war branch (the one that got merged upstream already) and lost a few commits in the process.
This pull is for the missing stuff:
1. orchard fix. function to accept the quest is pointless for frat and harms the hippies
2. junkyard fix. added code to the quest handler function to start the quest if needed for both hippies and fratboys. note that current lass/beta includes a removal of a hacky unreliable code to start it for only frat, so at the moment lass/beta does not start it for either side. instead aborting and asking the player to manually acquire the magnet then rerun.
3. quest override function removed, the sole remaining thing in it is addressing a long solved mafia issue
all of it has already been thoroughly tested before being lost. so …
=> War3 missing stuff from previous commit

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_cooking.ash, RELEASE/scripts/autoscend/auto_macguffin.ash, RELEASE/scripts/autoscend/auto_mr2018.ash, RELEASE/scripts/autoscend/auto_zelda.ash, RELEASE/scripts/autoscend/autoscend_header.ash
People really like manually eating Diabolic Pizza Cube pies in Plumber, because it gives them boatloads of muscle stats and helps them hit high levels very quickly. Unfortunately, autoscend really likes using moxie and mysticality mode in Plumber, and our weak little moxie- and mysticality-based attacks, even if they *technically* scale with our stats, are unable to scratch monsters that are scaling with our BRUTE STRENGTH because we are boasting absolutely insane stat ratios like 50 moxie/50 mysticality/700 muscle.
This fixes a few issues with how we decide whether we feel comfortable fighting scaling monsters in Plumber.
* First, we calculate the expected HP of the scaling fight, and do not consider, say, scaling Moxie attacks when our Moxie is much lower than our Muscle.
* Second, we …
=> [plumber] Be smarter about when to fight scaling monsters

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_combat.ash, RELEASE/scripts/autoscend/auto_macguffin.ash
there are multiple different bugs (and more are occasionally introduced) that can cause autoscend to fail to equip the unstable fulminate before trying to adventure in the haunted boiler room. When that happens, it would waste over 50 adventures there before aborting with the message of having spent too many turns there.
Now there is a last second check to immediately abort if it tries to adventure in that zone without the unstable fulminate, preventing that loss of adventures.
Also the warning for not being able to acquire cold damage for smut orcs is clearer now and only shows up for the 6 core classes (since avatar paths have their own handling).
hardcore Kingdom of Exploathing run.
=> some fixes

RELEASE/scripts/autoscend/auto_choice_adv.ash, RELEASE/scripts/autoscend/auto_mr2017.ash, RELEASE/scripts/autoscend/auto_mr2018.ash, RELEASE/scripts/autoscend/auto_quest_level_11.ash, RELEASE/scripts/autoscend/auto_quest_level_13.ash
- fixes for God Lobster post-combat choice abort and Tunnel of L.O.V.E handling (doesn't use choiceAdventureScript since it's not necessary. Technically neither should the God Lobster).
- also fix a missing function rename from PR #284 
Tested the LOV handling on my regular account with some copy & paste shenanigans.
God Lobster change is 100% untested.
=> More choiceAdventureScript fixes.

RELEASE/scripts/autoscend/auto_quest_level_12.ash
fix to getting frat boy ensemble and filthy hippy disguise before the war quest started for hardcore players without any summoning ability.
Sent a copy of it to someone on discord who was having the issue and it solved it.
=> fix infinite loop for hardcore at pre-war outfit with no summons

RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_quest_level_11.ash
Redoing the unstable fulminate fix. I handled incorrectly earlier, it seemed fine because it was catching an instance where maximize was failing. But I didn't notice that the way I handled it would "catch" all attempts to adventure there, as it triggers before the maximizer.
This should be done correctly this time. I managed to adventure with it and complete the wine bomb. Additionally I think the new implementation is more robust and will solve other instances where it fails to equip the unstable fulminate.
vampyre softcore run, used the unstable fulminate with it to make the wine bomb.
=> redoing the unstable fulminate fix

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_quest_level_4.ash, RELEASE/scripts/autoscend/auto_restore.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/auto_zelda.ash
I spun off the common issues into their own pull request / branch. left previous branch to deal with the 2adv stuff.
This branch does:
issue 1: trying to use providePlusNonCombat() in plumber with less than 15 coins would produce an error with a stack trace (and probably skipping the rest of the buff function) due to trying to buy blooper ink without enough coins to do so. (requires 15).
Additionally there was a todo there to make the check 400 coins because blooper ink is very wasteful early on the run before you have bought more important things like a scaling damage source.
I added a check for number of coins and set it to 400
issue 2: don't assume success when using sonar-in-a-biscuit
issue 3: don't print overly specific advice instructing the player to do stuff we do automatically …
=> Plumber and a few other fixes

BUILD/settings/any.dat, RELEASE/data/autoscend_settings.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_cooking.ash, RELEASE/scripts/autoscend/auto_edTheUndying.ash, RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/auto_king.ash, RELEASE/scripts/autoscend/auto_quest_level_10.ash, RELEASE/scripts/autoscend/auto_quest_level_11.ash, RELEASE/scripts/autoscend/auto_quest_level_4.ash, RELEASE/scripts/autoscend/auto_quest_level_9.ash
This is mostly fixing/removing workarounds we had for mafia issues that have been fixed recently.
See https://kolmafia.us/showthread.php?24767-Quest-tracking-preferences-change-request(s)
Also fixes an issue with Ed aborting after dying a 3rd time in the same combat (my fault not mafia's) and equipBaseline basically doing nothing (again my fault, I removed the non-maximizer code).
I also changed the check for using milk of magnesium to check we have one before we try to blindly use it as the periodic error it threw annoyed me.
Done some HC Ed. Just finished day 1 of a new run which tested the choiceAdventureScript handling successfully.
=> Fixing/removing workarounds we had for (now fixed) mafia issues.

RELEASE/scripts/autoscend/auto_quest_level_9.ash
Looks like there might be issues with these. Lets revert for now while they're tested.
=> Undo new property changes to level 9 quest

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_combat.ash, RELEASE/scripts/autoscend/auto_koe.ash, RELEASE/scripts/autoscend/auto_quest_level_12.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash
Farm sidequest handling for L12 war quest.
Plumber softcore as hippy, when I applied this patch to this run the war already started, but all i did in it was spend 1 turn in the orchard. had a chaos butterfly in inventory already and it correctly performed the sidequest
plumber softcore as fratboy
Vampyre softcore as fratboy, 0 skill 0 iotm. did find a bug. fixed below.
=> War farm sidequest

BUILD/settings/any.dat, RELEASE/data/autoscend_settings.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/autoscend_header.ash
Change the handling of how many adventures to keep at the end of the day.
The old method was to loop doTasks() until 1 adventure is left. Then do rollover prep, which included fighting free fights and last minute copiers. This was bad because:
1. crafting
on my side account I don't have IOTMs to provide me with food, and as such need to resort to cooking lo mein, scrumdiddlyumptious noodles, and hi mein. As well as cocktailcrafting the upgraded drinks (like neuromancer). All of those require 2 adventures to craft.
https://kol.coldfront.net/thekolwiki/index.php/Dry_noodle_guide
https://kol.coldfront.net/thekolwiki/index.php/Advanced_Cocktailcrafting#Upgraded_Recipe_Guide
2. free fights
free fights are only free if you win. If you wait until 1 adv is left to free fight then you can lock …
=> end of day adv to keep handling

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_adventure.ash, RELEASE/scripts/autoscend/auto_community_service.ash, RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/auto_heavyrains.ash, RELEASE/scripts/autoscend/auto_mr2014.ash, RELEASE/scripts/autoscend/auto_mr2015.ash, RELEASE/scripts/autoscend/auto_mr2017.ash, RELEASE/scripts/autoscend/auto_mr2018.ash, RELEASE/scripts/autoscend/auto_quest_level_12.ash, RELEASE/scripts/autoscend/auto_quest_level_13.ash, RELEASE/scripts/autoscend/auto_quest_level_8.ash, RELEASE/scripts/autoscend/auto_quest_level_9.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash
rename is100FamiliarRun to forbidFamChange
applies to both is100FamiliarRun() and is100FamiliarRun(familiar thisOne)
Why it is needed:
*There are some bugs related to people thinking "is100FamiliarRun" actually answers the question "is this a 100% familiar run" instead of what it actually does which determine if you are allowed to change familiar.
*I want to make some pokefam specific improvements to those functions (in a future PR).
*A function that actually answers the question "is this a 100% familiar run" instead of what the current function does is actually needed.
To address those issues we either need to create a new function called "isReally100FamiliarRun" and hope people stop making this reasonable mistake. Or rename the existing function and then reuse its name for the new …
=> rename is100FamiliarRun to forbidFamChange

RELEASE/scripts/autoscend.ash
Fix for auto free combats aborting when you have 1 adv left but no free combats.
`validate autoscend.ash`
=> fix for freecombats aborting when it shouldn't

RELEASE/scripts/autoscend/auto_quest_level_12.ash
Hippy and fratboy were inverted when checking the plan result field.
As a result they were both checking whether the plan was to do arena instead of dooks.
tested it in a fratboy plumber run where it initially wanted to do dooks before i corrected it.
=> that was backwards

README.md, RELEASE/scripts/autoscend/auto_adventure.ash, RELEASE/scripts/autoscend/auto_combat.ash, RELEASE/scripts/autoscend/auto_deprecation.ash, RELEASE/scripts/autoscend/auto_edTheUndying.ash, RELEASE/scripts/autoscend/auto_post_adv.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_restore.ash
Major issue fixed is Ed's combat tracking wasn't being reset. This leads to failing to do the nuns as we don't use Curse of Fortune in any combat at Themthar Hills after the first. It also breaks using his other skills like banish/YR more than once per day (yeah this was an oversight by me when I did the choiceAdventureScript changes).
Minor fixes are
- Restoring HP out of combat works for Ed. You'll see why I fixed this in the next PR I put up but it means we should no longer abort when you get Zerg Rush in Sonofa Beach or some other non-combat which puts you on 0 HP.
- should also no longer abort if losing initiative in places we handle with `autoAdvBypass` (such as the Tavern cellar)
- Don't use Blessing of Serqet in the Hippy Camp at all, this just ends up wasting adventures due to …
=> Ed fixes/tidying

RELEASE/scripts/autoscend/auto_quest_level_12.ash, RELEASE/scripts/autoscend/autoscend_header.ash
Replaces old war planning code with an easier-to-use and easier-to-read WarPlan record. Also cleans up some recent code and comments.
Hasn't really, unfortunately I just finished the war so it'll be a while until I can test this.
=> Refactor war planning code to use new WarPlan record

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_adventure.ash, RELEASE/scripts/autoscend/auto_community_service.ash, RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/auto_heavyrains.ash, RELEASE/scripts/autoscend/auto_mr2014.ash, RELEASE/scripts/autoscend/auto_mr2015.ash, RELEASE/scripts/autoscend/auto_mr2017.ash, RELEASE/scripts/autoscend/auto_mr2018.ash, RELEASE/scripts/autoscend/auto_quest_level_12.ash, RELEASE/scripts/autoscend/auto_quest_level_13.ash, RELEASE/scripts/autoscend/auto_quest_level_8.ash, RELEASE/scripts/autoscend/auto_quest_level_9.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash
replaced forbidFamChange() with canChangeFamiliar()
replaced forbidFamChange(familiar target) with canChangeToFamiliar(familiar target)
This is not a rename, but an inversion of the logic from asking a negative to asking a positive. 
Adjusted the functions to have inverted logic.
Adjusted all instances in which it is used to invert the logic. (by adding or removing ! as appropriate)
Validated autoscend.ash
=> familiar functions changes

RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_quest_level_11.ash, RELEASE/scripts/autoscend/auto_zelda.ash, RELEASE/scripts/autoscend/autoscend_header.ash
Ed fighting disables the standard pre-adventure handling, so calls to autoEquip() never happen and the pre-adventure code that would normally force-equip Plumber tools never gets called. This adds a utility function for equipping Plumber tools, calls it before fighting Ed, calls `equipMaximized()` before fighting Ed, and refactors the existing pre-adventure Plumber code to use this utility function.
This also fixes a long-standing bug where we wouldn't equip lots of stuff we intended to equip before fighting Ed.
Relevant to #325 
An automated run ran into the above Ed crash. I made the listed changes and re-ran autoscend. It equipped the fancy boots and defeated Ed. So I have tested this for about two minutes total, but it seems promising.
=> [plumber] Always equip plumber combat tool before Ed fight

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_quest_level_4.ash
* Haunted Bedroom was skipping the pre-adventure handler and so adventuring without equipping a plumber tool.
* In Plumber runs, we were infinite-looping at the Bat Hole, trying to adventure in the Lair after defeating the Boss Bat-equivalent. This was because Mafia wasn't updating the quest tracking property when we beat the substitute boss in Plumber. I fixed this by visit_url-ing the Bat Hole after adventuring in the Boss Bat's zone. This is definitely an upstream Mafia bug, though. Ah well.
Both were tested via observing the crash locally, re-running to confirm that the bug persisted through restarts, adding the change, and confirming that the bug disappeared. This should avoid a false positive, where the bug wasn't actually fixed by my code but I assumed it was because hey, it …
=> [plumber] Fix failures at Haunted Bedroom and Bat Hole

RELEASE/scripts/autoscend/auto_quest_level_11.ash
Workaround for Mafia bug
https://kolmafia.us/showthread.php?24888-mafia-not-tracking-desert-progress-in-plumber&p=157035#post157035
wastes lots of adv in there without this fix.
validates.
calling it from ash to confirm it visit the correct spot
when I manually visited that page earlier it correct my desert exploration from 43 to 100
it will be days before i can fully test it in the wild. but i think this needs merging now.
=> plumber desert tracking is broken in latest mafia.

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_quest_level_10.ash, RELEASE/scripts/autoscend/auto_quest_level_11.ash, RELEASE/scripts/autoscend/auto_quest_level_4.ash, RELEASE/scripts/autoscend/auto_quest_level_8.ash, RELEASE/scripts/autoscend/auto_quest_level_9.ash, RELEASE/scripts/autoscend/autoscend_header.ash
Since each Shen snake requires 4-6 adventures in a zone after Shen asks
us to go there, this could save at least 10 adventures per ascension.
There are two obvious reasons this hasn't been done previously:
1. Low-IOTM or low-skill accounts might need those early zones to level
up to unlock later quests. If we skip those early zones, they'll run
out of tasks to complete.
2. Accounts without solid combat suites might need those early zones to
level up to not die in higher-level zones. If we skip those early
zones, they'll be weaker and die more.
This commit handles the running-out-of-tasks issue by, after running out
of tasks to do, allowing ourselves to adventure in zones with potential
snakes awaiting. This is implemented similarly to the powerlevelling
code, using the property …
=> Procrastinate adventuring in zones that Shen snakes might appear in

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_community_service.ash, RELEASE/scripts/autoscend/auto_heavyrains.ash, RELEASE/scripts/autoscend/auto_king.ash, RELEASE/scripts/autoscend/auto_koe.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash
*add boolean acquireOrPull(item it) and use it in heavy rains and koe for getting meteorb
*add buff maintain capability of Benetton's Medley of Diversity
*use Benetton's Medley of Diversity and frigidalmation against heavy rains boss
*instead of casting iron palms as part of ablativeBuffs function and a few other places, just make casting it universal if it is available. (it is an intrinsic that costs nothing to cast)
some ash calls. could probably use more testing.
it ran on a bunch of accounts doing different paths without causing any errors, but not during a heavy rains run
=> Heavy rains

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_boris.ash, RELEASE/scripts/autoscend/auto_mr2015.ash, RELEASE/scripts/autoscend/auto_mr2016.ash, RELEASE/scripts/autoscend/auto_mr2018.ash, RELEASE/scripts/autoscend/auto_mr2019.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_quest_level_11.ash, RELEASE/scripts/autoscend/auto_sneakypete.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash
Tweaked skill purchase order to be more helpful for low skill players. (high skill gets them all anyways).
Custom ML management for boris. Including when to use overconfidence.
Also added in_boris() and used it.
Ash calls.
1 new account doing HC pete
1 new account doing HC boris
ran it on other paths too to see that nothing unexpected happened.
=> Avatar of Pete and Boris changes

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_mr2015.ash, RELEASE/scripts/autoscend/auto_mr2018.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash
Free combats on rollover multiple bugs fixed and multiple improvements.
Fixed aborting mid rollover prep due to having free fights remaining.
Fixed NEP fighting an 11th dude and using an adventure when trying to free combat
Fixed NEP using non powerleveling function when you want to powerlevel.
Added debuging output to free fights related functions and auto call it when it fails
fixed OCRS spending adventures in NEP
fixed hardcoding ms. puck man as snojo familiar
removed code for writing desk tricks that kol now blocks
don't assume success in snojo and machine elf tunnels
don't silently block subsequent free fights if one mysteriously fails
Mostly through direct ash calls. But also running it on my main account that has free combats.
=> free combats improvements

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_quest_level_11.ash, RELEASE/scripts/autoscend/auto_quest_level_5.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash
1. pathAllowsFamiliar() created. this allows us to replace auto_have_familiar($familiar[mosquito]) checks. And do it better since the former gives misleading results in pokefam. This will be useful for correcting PR#177
2. mob of zepplin protestors block on waiting for shen to be done made into a soft block rather than a hard block. If there is nothing else left to do then it will be done suboptimally. Partially fixes #319 
3. Don't flip flop on MCD setting so much. alter its desired target figure then finally set it once in pre adventure just before we go adventuring somewhere.
included an option to change it immediately but looking at the various places it is called I don't see any where we would want to.
4. backup and then enable mafia setting for not auto aborting automation when …
=> MCD, zeppelin protestors, and a few misc things

RELEASE/scripts/autoscend.ash
If you run out of other things to do. Do not delay logging camp for shen.
Was previously checking this after the powerlevel to level 13 function instead of before.
In hardcore ed, i was delaying it and boss bat. I made the change then ran it and it stopped delaying logging camp.
=> shen softblock check should be before powerleveling

BUILD/settings/any.dat, RELEASE/data/autoscend_settings.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_batpath.ash, RELEASE/scripts/autoscend/auto_bondmember.ash, RELEASE/scripts/autoscend/auto_choice_adv.ash, RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/auto_mr2013.ash, RELEASE/scripts/autoscend/auto_post_adv.ash, RELEASE/scripts/autoscend/auto_quest_level_12.ash, RELEASE/scripts/autoscend/auto_quest_level_5.ash, RELEASE/scripts/autoscend/auto_quest_level_8.ash, RELEASE/scripts/autoscend/autoscend_header.ash
Adds support to acquire Mining Gear outfit from Itznotyerzitz Mine and then mine for ore if we have no better options for acquiring ores.
Changes are currently guarded by the property `auto_mineForOres` which needs to be set to true for this to actually do anything (property can be set from relay preferences) so this can be more widely tested by users opting in.
Functionality can be tested in aftercore using the following line on the CLI
`ash import <autoscend.ash> auto_testMining($item[insert ore type]);`
Fixes #8 
A bunch of HC Ed runs, ran a lot of aftercore testing too. Current Ed run did the following:
That was 10 adventures to get all 3 ores. From the mineLayout1 property you can see the path it took
After hitting the loadstone it first went to the left which hit the asbestos ore …
=> Trapper quest ore mining

RELEASE/scripts/autoscend/auto_mr2019.ash, RELEASE/scripts/autoscend/auto_util.ash
don't burn delay using Kramco in Oasis if we don't have Ultrahydrated
don't burn delay to Gnasir if we haven't used the free 10 turns of Ultrahydrated from first combat.
Formula has  been tested on my main account.
=> update sausage goblin probability with spoilered formula.

RELEASE/scripts/autoscend/auto_mr2019.ash, RELEASE/scripts/autoscend/auto_zone.ash
Superlikelies beat all wanderers now, not just goblins
Fixes trying to burn delay in The Oasis and getting Ultrahydrated instead and wasting a turn
trivial change, check effect
=> Don't burn delay in The Oasis unless ultrahydrated

BUILD/monsters/sniff.dat, RELEASE/data/autoscend_monsters.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_choice_adv.ash, RELEASE/scripts/autoscend/auto_cooking.ash, RELEASE/scripts/autoscend/auto_edTheUndying.ash, RELEASE/scripts/autoscend/auto_post_adv.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_quest_level_12.ash, RELEASE/scripts/autoscend/auto_quest_level_6.ash
- Add Possibility Giant to Sniffed monsters
- Move checking we're not breaking a 100% familiar run to auto_pre_adv (I should have put it there in the first place).
- Set autorecovery options to the same values that mafia uses to disable. This fixes the abort that can happen if you end up on 0 HP after an adventure.
- make sure Ed fills his spleen first before trying to eat or drink (we have failover code to farm Ka if needed which doesn't trigger otherwise)
- Add code to set `auto_shenSkipLastLevel` in Ed if we run out of quests that we can get Ka from and don't have the 3rd Elemental Resistance Upgrade (as that is when we consider Ed "done" with Ka farming for upgrades).
- Equip war outfits before turning in war loot to the coinmasters to avoid mafia repeatedly unequipping and requipping …
=> Handful of small changes/fixes

RELEASE/scripts/autoscend/auto_quest_level_9.ash
Make oil peak's wait for better conditions be a soft-block instead of a hard one. that gets unblocked if you start powerleveling.
On an account which had nothing to do except oil peak or power level, and was power leveling, it started doing oil with the change until it leveled up halfway through doing oil. At which point it stopped to go do other quests
also played with it for several days on all my accounts with no issue.
=> oil peak bypass wait for better conditions if powerleveling.

RELEASE/scripts/autoscend.ash
Arbor day holiday requries you to spend 100 adv in $location[The Arrrboretum]
Which triggered the "spent over 52 adv in a zone and this is bad" aborting for autoscend. requiring the usage of newbie override to proceed.
This adds an exclusion for $location[The Arrrboretum]
set newbie override to false and then copy pasted it to my mafia and ran one adventure before aborting. it stopped complaining that i spent too many turns there.
=> Arbor Day don't abort for 52+ adventures spent in $location[The Arrrboretum]

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/auto_mr2018.ash, RELEASE/scripts/autoscend/autoscend_header.ash
equipment maximizer bugs squashed:
*resetMaximize() special handling of jtote items fixed.
**Above required adding `boolean isjanuaryToteAvailable();` to header file
*addToMaximize won't add duplicates anymore
*removeFromMaximize also protect against `comma space comma` or ending in `comma space` or starting in `space comma`. should probably do a loop on those but I think it is good enough as is.
*when initializing settings (before doTasks() is reached). Have  `resetMaximize();` be done before doing `equipBaseline();`
Fixes #348
Ash calls. Also had an instance where I was stuck on trying to run it due to an outdated state call during the early equipBaseline() that was able to go through once I used this.
Also played with it for a day
=> equipment maximizer bugs squashed.

RELEASE/scripts/autoscend/auto_equipment.ash
exclude the text scramblers [staph of homophones] and [sword behind inappropriate prepositions] from default maximizer string if you happen to have them on hand.
Likely because you pulled them for their rollover bonus
It validated
=> exclude text scramblers from maximizer by default

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_mr2018.ash, RELEASE/scripts/autoscend/auto_post_adv.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash
january tote fixed:
*verify crafting actually succeeded before returning true.
*fix a block that only allowed crafting one item per day.
*fixed special handling for letter to melvin the gnome
*fixed leftover charge saving logic to actually protect leftover charges
*since this is an acquire function, return true if you already had the item even if no crafting occurs.
*instead of preemptively switching to garbage shirt during doTasks in preparation for love tunnel during doBedtime when love on adventures. Actually call on the garbage shirt crafting during doBedtime right before adventuring in the tunnel of love.
*instead of calling to acquire wad of used tape every loop early in doTasks, call on it in pre adventure right before equipping maximizer gear, only if nothing called on …
=> january tote fix folding items, and verify success before returning true. also maximizer fixes

RELEASE/scripts/autoscend.ash
fixed steel organ quest:
*make sure to equip items before trying to turn them in to mourn
*don't continue adventuring in laugh floor hoping to get observational glasses to dropped if the glasses are currently equipped already (such as if they are the best gear you have)
My test account got stuck doing the laugh floor, even after getting the glasses, because it was wearing the glasses, because maximizer decided they were the best item to wear.
With this fix it went on to do the rest of the quest properly.
=> fixed steel organ quest

BUILD/settings/any.dat, RELEASE/data/autoscend_settings.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_quest_level_13.ash, RELEASE/scripts/autoscend/auto_theSource.ash, RELEASE/scripts/autoscend/auto_zone.ash, RELEASE/scripts/autoscend/autoscend_header.ash
L13_powerLevel() reworked:
*Power leveling code was split between L13_powerLevel() and LX_attemptPowerLevel() in a messy fashion. Consolidated it into LX_attemptPowerLevel()
*moved The Source path specific powerleveling code to boolean LX_attemptPowerLevelTheSource()
*releasing the softblock on quests awaiting optimal conditions was done far too late in L13_powerLevel(). moved it to be done right before L13_powerLevel() is called, and inserted a mcall to getDigitalKey and getStarKey between those two.
*removed L13_powerLevel() entirely as the only thing it still does is serve as a wrapper for LX_attemptPowerLevel(). replaced it with calling on LX_attemptPowerLevel() if under level 13.
*boolean LX_unlockThinknerdWarehouse(boolean spend_resources) added and used in melvin quest and in …
=> L13_powerLevel() reworked

RELEASE/scripts/autoscend/auto_boris.ash, RELEASE/scripts/autoscend/auto_cooking.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/autoscend_header.ash
boolean borisDemandSandwich(boolean immediately) and void void borisWastedMP() created and used
1. boolean borisDemandSandwich(boolean immediately) automatically uses the skill demand sandwich to summon 3 sandwiches a day of the best type between adventures. Or if the eating code was engaged then summoning whatever sandwiches you can get just before eating.
This significantly helps turngen for anyone who doesn't have so many IOTMs they can generate 30 stomach worth of IOTM foods.
TODO: auto unlock a bakery so you could bake some pies.
2. void borisWastedMP() will check if you are about to waste MP regen and if so waste the excess MP regen on laugh it off. It gets called during pre_adv
Played with it for 4 days. So far it works.
=> Boris demand sandwich and ongoing MP to HP conversion

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_adventure.ash, RELEASE/scripts/autoscend/auto_aftercore.ash, RELEASE/scripts/autoscend/auto_mr2018.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_quest_level_12.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash
free combat fixes:
*additional debug logging messages related to free combats, also improved comments and better worded error messages.
*boolean disregardInstantKarma() created and used.
*more places now specifically state if they want to powerlevel when calling LX_freeCombats rather than letting it be determined automatically
*do your free combats as part of doTasks() loop when only 1 non-reserved adv remains. Before it was left exclusively for doBedtime().
** resolves aborting during bedtime free combats if used override to reserve 1 adv
** resolves aborting during bedtime free combats if some bug (like god lobster one below) prevented you from doing one of the free fights.
** resolves automatic adventure reserving ending the day with 2 adv and 0 free fights left instead of 1 adv and 0 …
=> free combat fixes. do free combats in doTasks() when 1 unreserved adv remains + god lobster fixes

RELEASE/scripts/autoscend.ash
currently every loop we:
1. reset maximizer string
2. call equipBaseline very early in doTasks, which maximizes with our current freshly reset maximizer string. replacing parts of our outfit. In plumber this means removing boots every single adventure
3. determine where we want to go and modify our maximizer string to match
4. run pre_adventure where we call on equipMaximize, which is identical to equipBaseline and performs a maximize with our current maximizer gear.
This is probably a legacy from when equipbaseline actually did stuff (addressing certain bugs) but a the moment all it does is a wrapper for equipMaximize.
Doing 2 maximizing between each adventure is a waste of server hits and an unnecessary slowdown. simply removing number 2 gives a much better streamlined path of
1. reset …
=> reduce unnecessary equipment flipping.

RELEASE/scripts/autoscend/auto_cooking.ash
correcting a mistake I made on previous boris related PR.
Boris should wait until less than 10 adventures remain (which is the prerequisite for knapsack to consume until full) before disregarding level for demand sandwich.
Used it in boris run and observed results.
=> boris wait until <10 adv left before disregard level for demand sandwich

RELEASE/scripts/autoscend/auto_combat.ash, RELEASE/scripts/autoscend/autoscend_header.ash
mafia's run_combat() gives us the monster name as a $monster
don't force convert it into a string and then immediately convert said string into a $monster
this introduces bugs where it fails to recognize various monsters and thinks we are fighting $monster[none]
currently testing it, so far it is working.
=> mafia's run_combat gives us the monster name as a $monster

RELEASE/scripts/autoscend/auto_combat.ash
*enemyCanBlocksSkills() created and used (for intimidating shout only at the moment. will be used in more places later)
*boris intimidating bellow logic refactored. Do use it when low on skills. don't require lots of spare MP. don't use it against bosses that interrupt skill use. don't use it if enemy cannot harm us.
*removed obsolete workaround for detecting $monster[your shadow] in plumber path.
still testing
=> boris use intimidating shout logic changes

RELEASE/scripts/autoscend/quests/level_12.ash
*fixes #365 prevent maximizer from unintentionally equipping frat warrior fatigues to fight the filthworms prematurely as that causes infinite loop
*don't assume success when adventuring, assuming causes infinite loops
*only try to raise item drop if we can't guarentee stealing (supports Ed and XO skeleton. TODO zombie master and cat burglar)
*removed outded hardcoding of equipping some specific equip that gave +item drop. this outdated code didn't even work anymore (it equipped them then removed them). removed this code instead of fixing it because because we want to maximize and not hardcode equipping specific items.
*item drop code buffing will now use maximize. also use ed item drop servant on the very rare scenario of not having lash.
*don't hardcode switching to item familiar AFTER …
=> boolean L12_filthworms() refactored

RELEASE/scripts/autoscend/quests/level_8.ash
- add some handling for a loadstone replacing the ore we are looking for and subsequently exhausting all cells that as twinkling and adjacent to the ores we have found.
- add an abort if we don't find a single cell we want to mine.
ran a validate autoscend & tested in aftercore so it all still works but testing this specific issue relies on RNG (and the code is still in public beta test guarded behind a property).
=> itznotyerzitz mine handling fixes

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_choice_adv.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/auto_zone.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/paths/actually_ed_the_undying.ash, RELEASE/scripts/autoscend/paths/the_source.ash, RELEASE/scripts/autoscend/quests/level_11.ash, RELEASE/scripts/autoscend/quests/level_2.ash, RELEASE/scripts/autoscend/quests/level_7.ash, RELEASE/scripts/autoscend/quests/level_9.ash
Description
- move choice handling for Spooky Forest, Spookyraven first and second floors, and Hidden City zones to choiceAdventureScript
- refactor quest handling functions for unlocking Hidden Temple, L2 quest, unlocking Spookyraven first and second floor and some of the Hidden City (lots more to do).
- handful of other minor fixes/tweaks.
This started off as an attempt to fix our handling of the Haunted Bedroom encounters and the Hidden City zone unlocking and kind of grew arms and legs.
I was hoping to get to work on the hidden city unlocking quest handling (so we can handle not having Stone Wool) and more of the macguffin quest but I need to put this up now as it's growing large, I have a mining fix to look into and the new path needs to be worked on.
Ran 3 HC Eds so far.
=> Moving stuff to the choiceAdventureScript

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_choice_adv.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/paths/low_key_summer.ash, RELEASE/scripts/autoscend/quests/level_13.ash, RELEASE/scripts/autoscend/quests/level_any.ash
Supports adventuring for low key summer keys. Some keys are acquired early if they would help with quests, otherwise they are all acquired at the end of the run when all other quests are completed.
Currently does not support the following
* Epic weapon quest to unlock fun house
* Pirate quest to unlock F'cl'e or Belowdecks
* Unlock door
* Lock Picking skill
If the script has nothing left to do it will abort and tell you the remaining zones you need to do manually (for now).
Two low key summer runs.
=> Basic low key summer support

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_choice_adv.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/quests/level_any.ash
Support casting Lock Picking before acquiring any loot tokens.
Ran LX_lockPicking() to test, seemed to work.
=> Support Lock Picking

RELEASE/scripts/autoscend.ash
reinstate ccs setting to fix broken adventuring. mafia is dumb.
=> fix broken adventuring

BUILD/settings/any.dat, RELEASE/data/autoscend_settings.txt, RELEASE/scripts/autoscend/auto_cooking.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/quests/level_any.ash
Improve consumption code:
* Only consume a single item at once
* Don't prevent pulled consumables on if they are in storage already
* Stop drinking at 10 inebriety if billiards room isn't completed, unless there is no fullness remaining
* Add auto_consumeMinAdvPerFill to prevent eating garbage
* fill isn't checked in auto_knapsackAutoConsume, this function is now not called.
Ran auto_autoConsumeOne with simulate, ran manually to test consumption
=> Auto consume improvements

RELEASE/scripts/autoscend/auto_choice_adv.ash, RELEASE/scripts/autoscend/auto_post_adv.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash
Detect any aborts or errors in choice adventure, pre adventure and post adventure script and set auto_interrupt so main autoscend script will stop.
This will fix an issue I'm having with autoscend looping if stuck in a choice adventure (commonly happens to me with the saber)
Verified all scripts, ran day two of a standard ascension.
=> Catch errors in external scripts

RELEASE/scripts/autoscend/quests/level_11.ash
fix faulty while loop in L11_hiddenCity()
It was doing
```
while (not thrice cursed)
if (various checks for if you can drink cursed punch)
drink cursed punch
```
which should have been
```
while (not thrice cursed && various checks for if you can drink cursed punch)
drink cursed punch
```
If you couldn't drink cursed punch it meant you get stuck in this infinite loop
I was getting stuck in an infinite loop every time i ran autoscend on one of my accounts. until i tracked it down to this and once I applied the code it stopped getting stuck in said loop and continued to adventure
=> fix faulty while loop in L11_hiddenCity()

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_choice_adv.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/quests/level_11.ash
refactoring LX_unlockHauntedLibrary()
*use auto_is_valid to check chalky hands. for example in g-lover it is not valid.
*chalky hands logic was faulty. it was only used when equipping a cue while calculations were assuming we always use it (as we should because it boosts training speed)
*boris cannot equip pool cues. do not add it to maximizer.
*don't add ALL cues available to maximizer, only add the best cue
*do not skip all calculations / equipment logic / inebrity rules when you have not yet encountered "That's your cue" (NC that drops a basic pool cue). It no longer blocks other NCs in that zone.
*reworked the cue equipping logic.
*adjusted drunkness rules to account for the current way consumption code works. (it drinks to full. so only wait for drinking in paths whose max is under …
=> refactoring LX_unlockHauntedLibrary()

BUILD/monsters/replace.dat, RELEASE/data/autoscend_monsters.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_cooking.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/quests/level_11.ash
- Don't replace beefy bodyguard bats for paths with an alternate boss bat
- Allow eating spaghetti breakfast only as the first thing
- Check auto_is_valid before pulling anything, to prevent pulling harmful \ unusable items
- Pull deck of lewd playing cards for protesters
- Fix not consuming anything if script is started below adventure threshold
- Fix heavy rains familiar handling equipping to wrong familiar
- Fix considering switching to familiars when dropped spleen item is unusable
Fixes #65
Fixes #85
Fixes #346 
Validates
Manually ran auto_autoConsumeOne to consume spaghetti breakfas
=> Various fixes

RELEASE/scripts/autoscend/auto_cooking.ash
I was accidentally only checking inebreity == 0 in consume one, and wasn't otherwise considering remaining space.
Ensured the 0 remaining case worked, but I'm not in a run so I can't test this right now. Should work though, the knapsack call was copied from the old consumption function.
=> Critical: Consume fix

RELEASE/scripts/autoscend/quests/level_13.ash
- don't pull white pixels in low key summer unless we only need the digital key to open the door.
Ran `validate autoscend` with no errors. Need to wait until rollover to properly test but the logic should be correct as far as I can see.
=> LKS: Fix for pulling white pixels too early

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_adventure.ash, RELEASE/scripts/autoscend/auto_casual.ash, RELEASE/scripts/autoscend/auto_combat.ash, RELEASE/scripts/autoscend/auto_cooking.ash, RELEASE/scripts/autoscend/auto_king.ash, RELEASE/scripts/autoscend/auto_post_adv.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/clan.ash, RELEASE/scripts/autoscend/iotms/mr2015.ash, RELEASE/scripts/autoscend/iotms/mr2016.ash, RELEASE/scripts/autoscend/iotms/mr2017.ash, RELEASE/scripts/autoscend/paths/community_service.ash, RELEASE/scripts/autoscend/paths/heavy_rains.ash, RELEASE/scripts/autoscend/quests/level_13.ash
*inAftercore() created and used
**replaced the various permutations of checking property kingLiberated
**fixed function boolean inPostRonin(). It needed to verify we are !inAftercore()
ash calls
=> inAftercore() created and used

RELEASE/scripts/autoscend/auto_equipment.ash
in default maximizer string include `plumber` when in_zelda()
Fixes #325 subissue 1
part of a softcore plumber run.
=> have plumber in default string in plumber

RELEASE/scripts/autoscend/quests/level_12.ash
fratboy filthworm. fix for when maximizer lands on frat war outfit. there were two typos in the function that handled that.
validates
=> fratboy filthworm fix when your best outfit is frat outfit

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/quests/level_9.ash
*track internally quest progress. (for now. talking to mafia devs about adding mafia tracking)
**checking for items it drops is unreliable. frobozz house can be lost. giant pinky ring can be sold or pulled from previous ascension.
**fix not doing leaflet in casual.
tested in a low key run. it worked
=> boolean L9_leafletQuest() refactoring

RELEASE/scripts/autoscend.ash
*account for user set delay being less than 0
*replace casual check with in_casual() at start of doTasks()
2 days of ed run
which should be sufficient considering the contents
=> account for user set delay being less than 0

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_choice_adv.ash, RELEASE/scripts/autoscend/auto_combat.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/paths/low_key_summer.ash, RELEASE/scripts/autoscend/quests/level_11.ash, RELEASE/scripts/autoscend/quests/level_12.ash, RELEASE/scripts/autoscend/quests/level_any.ash, RELEASE/scripts/autoscend/quests/optional.ash
- add Pirates Quest handling to unlock all zones. Also move functions from auto_util.ash which relate to pirates quest.
- add first stage of Nemesis quest handling to unlock "Fun" House.
- get Junk Junk for island access in Low Key Summer since we need to farm the scrap metal key in the zone anyway. add choice handling for the zone.
- start 3rd part of Lady Spookyraven's quest to open access to the Haunted Nursery for the music box key and add choice handling for the zone.
- add starting the Meatsmith quest to open the Skeleton Store for the actual skeleton key and add choice handling for the Skeleton Store.
- some fixes & tweaks to acquiring useful keys (few bugs with conditions but mostly ensuring we do the quest in the appropriate zone first if required.
- use tower_door() function to …
=> Low Key Summer changes

RELEASE/scripts/autoscend/auto_cooking.ash
speakeasy drinks are not mall tradeable.
fixes a crash when it tries to mallbuy them
played a day in out of standard path with VIP key
=> speakeasy drinks are not mall tradeable.

RELEASE/scripts/autoscend/quests/optional.ash
- Make sure the starter weapon is not equipped when trying to get the Legendary Epic Weapon so we don't fail the swap.
Hasn't yet. Will need to wait until next run which will likely be 2 or 3 days time since LKS is so damn slow.
=> Unquiet Garves NC fix

RELEASE/scripts/autoscend/auto_combat.ash
Disguise Delimit combat handling for:
*welding mask. It reflects spell damage but also lets the monster suffer said damage too... from some spells. Wiki was wrong about this, saying the monster still takes damage from all spells.
Saucegeyser (our preferred attack method) does not deal damage to the monster with welding mask while saucestorm does.
I changed it to prefer to just use attack with weapon on the monster unless the monster the has over 80% physical resistance in which case it prefers to use saucestorm if we we have enough HP to tank it.
Fixes #406
*tiki mask. triples monster HP and hard caps damage at 10 per source. we were tossing saucegeysers at it dealing 10 dmg per round at very high MP cost. Now checks prismatic weapon damage. if weapon deals more than 20 damage to tiki …
=> Disguise Delimit welding & tiki mask combat handling

RELEASE/scripts/autoscend/quests/optional.ash
When doing legendary epic weapon:
1. need to first unlock guild.
2. if quest not started, start it instead of returning false. it is just a single url visit to start it.
validated
=> for nemesis quest. unlock guild and accept legendary epic weapon quest

RELEASE/relay/relay_autoscend.ash, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_combat.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2017.ash, RELEASE/scripts/autoscend/iotms/mr2018.ash, RELEASE/scripts/autoscend/iotms/mr2019.ash, RELEASE/scripts/autoscend/iotms/mr2020.ash, RELEASE/scripts/autoscend/quests/level_11.ash
- Check for success when using pill keeper pills
- Track pill keeper usage in auto_chewed
- Track Powerful Glove usage in auto_powerfulglove
- Track beach comb Beach Head in auto_otherstuff
- Track eating magical sausage
- Track Cat Burglar heists in auto_otherstuff
- Track Mumming Trunk in auto_otherstuff
- Simplify handleTracker & generateTrackingData functions
- Minor fix: Defer forcing a non-combat in gallery or bathroom if delay hasn't been burned (fixes possibly wasting a forced non-combat on out in the garden for example)
Ran day 1 of hardcore standard:
=> Track additional interesting data for relay

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/quests/level_11.ash, RELEASE/scripts/autoscend/quests/level_3.ash, RELEASE/scripts/autoscend/quests/level_5.ash, RELEASE/scripts/autoscend/quests/level_8.ash, RELEASE/scripts/autoscend/quests/level_9.ash, RELEASE/scripts/autoscend/quests/optional.ash
- heal if we're at less than 75% hp in pre-adv as otherwise we die a lot unnecessarily at low levels by entering combat on tiny amounts of hp
- add shen delay check to LX_acquireLegendaryEpicWeapon() since it adventures in The Unquiet Garves
- remove powerlevelAdjustment, move functionality in to LX_attemptPowerLevel along with the soft block unlock.
- create isAboutToPowerlevel() and replace calls to checking the auto_powerlevelLastLevel property with it.
Ran some LKS runs with these changes. No issues thus far. The healing before adventuring is helping with not dying for dumb reasons (like starting combats on 1 or 2 hp) so adventures are being saved.
=> Some random fixes

RELEASE/scripts/autoscend/iotms/mr2019.ash
My guess is that the Force Saber choiceAdventureScript issue is a race condition in mafia as the property being set is always missing from the logs we get of failures so lets try slowing it down & seeing if it makes a difference. At worst, it adds 15 seconds extra each day for anyone who has the saber and does nothing.
Fixes #313 (potentially, well works around it rather than fixes it)
It hasn't. I don't have the saber on my testing account. But I'm quite confident those 3 lines aren't going to cause catastrophic failure.
=> Testing a hypothesis that mafia encounters a race condition.

BUILD/familiars/drop.dat, BUILD/familiars/item.dat, BUILD/familiars/regen.dat, RELEASE/data/autoscend_familiars.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_adventure.ash, RELEASE/scripts/autoscend/auto_familiar.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2018.ash, RELEASE/scripts/autoscend/paths/heavy_rains.ash
*handling for intentionally trying to set familiar to $familiar[none]
**fixes wall of bones tower killing without electric bone knife failing to set familiar to none when it was trying to.
**fixes fantasy realm error in pokefam when trying to set familiar to none
*removed familiar consideration of astral energy drinks. it no longer exists
*handleFamiliar now consistently returns false if it cannot set a familiar as a target. before it was inconsistent
*hr_handleFamiliar deleted. it was only wearing life preserver on familiar, but doing it in the wrong place such that you only wore it if you used the same familiar 2 turns in a row. relevant logic was added to preAdvUpdateFamiliar instead
*instead of autoscend calling `handleFamiliar("item"); basicFamiliarOverrides();` it will now just call …
=> familiars revamped

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_choice_adv.ash, RELEASE/scripts/autoscend/iotms/mr2019.ash
As the race condition hypothesis test returned a negative result, lets try just not using the choiceAdventureScript as it is the thing that appears to be failing us here.
Lets rely on mafia to handle the post-combat choice if we set the choiceAdventure property appropriately as I can verify this works without issue in aftercore as my end of day script does something almost identical without any issues.
Fixes #313 (potentially, well works around it rather than fixes it).
Again, it hasn't. I don't have the saber on my testing account.
=> Race condition hypothesis proven false

RELEASE/scripts/autoscend/auto_adventure.ash, RELEASE/scripts/autoscend/auto_familiar.ash, RELEASE/scripts/autoscend/iotms/mr2018.ash, RELEASE/scripts/autoscend/quests/level_13.ash
Just set disableFamiliarChanging to true and use the mafia function to switch to no familiar.
Hasn't yet. Waiting for a 100% run to complete before I jump in to testing the familiar_handling branch.
=> remove use of "REALLY_NONE".

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_choice_adv.ash, RELEASE/scripts/autoscend/auto_combat.ash, RELEASE/scripts/autoscend/auto_deprecation.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/auto_zone.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2014.ash, RELEASE/scripts/autoscend/iotms/mr2019.ash, RELEASE/scripts/autoscend/paths/actually_ed_the_undying.ash, RELEASE/scripts/autoscend/paths/avatar_of_boris.ash, RELEASE/scripts/autoscend/paths/avatar_of_sneaky_pete.ash, RELEASE/scripts/autoscend/paths/dark_gyffte.ash, RELEASE/scripts/autoscend/paths/disguises_delimit.ash, RELEASE/scripts/autoscend/paths/g_lover.ash, RELEASE/scripts/autoscend/paths/kingdom_of_exploathing.ash, RELEASE/scripts/autoscend/paths/license_to_adventure.ash, RELEASE/scripts/autoscend/paths/live_ascend_repeat.ash, RELEASE/scripts/autoscend/paths/nuclear_autumn.ash, RELEASE/scripts/autoscend/paths/pocket_familiars.ash, RELEASE/scripts/autoscend/quests/level_11.ash, RELEASE/scripts/autoscend/quests/level_any.ash
desert unlocking, get compass, and a few other things
*desert unlocking made into its own function instead of piggy backing over bitchin meatcar function.
*boolean isDesertAvailable() created and used
*boolean inKnollSign() created and used
*boolean inCanadiaSign() created and used
*boolean inGnomeSign() created and used
*boolean allowSoftblockShen() created and used
*general refactoring of old code in regards to dowsing rod & compass in the desert.
*moved ornate dowsing rod NC handling to auto_choice_adv.ash
*moved doVacation NC handling to auto_choice_adv.ash
*verify you have enough meat and adventures left before vacationing in doVacation()
*if we are doing the desert right now, ignore the requirement to be at least day 2 to do the dowsing rod
*pull a grimstone mask to make a dowsing …
=> desert unlocking, get compass, and a few other things

RELEASE/scripts/autoscend/auto_combat.ash
abortCombat(string msg) created an used
using abort() in combat does not work. instead we need the combat filter function to return the string "abort"
replaced
`abort(msg);`
with
`return combatAbort(msg)`
which will use the above mentioned new function to first print the message and then return the string "abort" up the chain until it reaches run_combat() function itself.
i used a test script to verify this is the correct way to abort run_combat(filter).
but i have not tested it in autoscend yet. it might be that after run_combat aborts autoscend will not abort and instead recognize we are in combat and call it again.
tested in autoscend during a disguise delimit run where it successfully aborted instead of falling back on CCS
=> abortCombat(string msg) created an used

RELEASE/scripts/autoscend/auto_combat.ash
Fixes the unreachable code warning mafia gives.
The code in question was actually unreachable for a while. my recent fix to aborting in combat made mafia able to recognize it is unreachable and report it to us.
Part of the code was redundant and was removed (using love stenchbug, it was already being done just a little above it. also attacking with weapon if we couldn't find anything else to do. or returning attackMinor. several redundant lines of both of those).
I also moved the abort if turns>25 check to the start of the function instead of the end.
part of a disguise delimit HC run in r20161 with #432 integrated too.
=> Unreachable code warning

BUILD/familiars/combat.dat, BUILD/familiars/drop.dat, BUILD/familiars/item.dat, BUILD/familiars/noncombat.dat, RELEASE/data/autoscend_familiars.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_familiar.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/quests/level_10.ash, RELEASE/scripts/autoscend/quests/level_11.ash, RELEASE/scripts/autoscend/quests/level_12.ash, RELEASE/scripts/autoscend/quests/level_13.ash, RELEASE/scripts/autoscend/quests/level_7.ash, RELEASE/scripts/autoscend/quests/level_8.ash, RELEASE/scripts/autoscend/quests/level_9.ash, RELEASE/scripts/autoscend/quests/optional.ash
- Use +item familiars in zones when they're needed rather than just blindly using +item familiars.
- Add +stats familiars to the fallback choices when nothing else applies because levelling is somewhat useful in-run I've heard.
- add +meat familiars to the fallback choices for zones where the monsters have high meat drop.
- remove almost all other calls to `handleFamiliar()`. Some are left as they're specific familiar overrides or specific to the task (e.g. wishing for a moutain man calls `handleFamiliar("item");` then `handleFamiliar("Cat Burglar");`)
- remove the use of Stooper and Jumpsuited Hound Dog for +/-combat. They unnecessarily soak up familiar experience and farming drops/stats will be more beneficial across the whole run when +item/+meat/+init is not required.
- only farm the …
=> add choosing of familiars by zone and add using stat familiars

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_combat.ash
- update gremlins code to use new monster names
- bump mafia version.
Gremlins worked. Waiting for the run to complete so I can see if the NS works too then we're good to go. This was tested on KoLMafia r20181.
+++ Shadow still not being recognised correctly in r20181 +++
Fixes: #433 
Fixes #313
=> update gremlins code to use new monster names

RELEASE/scripts/autoscend/auto_choice_adv.ash, RELEASE/scripts/autoscend/quests/optional.ash
fixes trying to do pirate quest with Frat Boy Ensemble outfit in inventory.
*when handling choice adventure 188 do not assume that we are able to do choice 3 if 1 and 2 are unavailable.
*use autoOutfit instead of outfit for wearing the pirate quest outfits. Otherwise maximizer will just unequip them before we adventure.
used test script and ashq calls to call the functions in question it in aftercore.
=> piratequest fix Frat Boy Ensemble outfit

RELEASE/scripts/autoscend/quests/level_13.ash
we should to visit the contest booth to find out what the contests are
if we do not have a telescope
otherwise it wastes too many turns by not properly optimizing.
`ash remove_property("nsChallenge1")`
`ash remove_property("nsChallenge2")`
then run the test code, it correctly identified that one of the above 2 is unknown and visited the contest booth first to make mafia update.
However, since it had already started the elemental challenge at the time it could not update it anymore that run. so I reset that one manually
according to prefref nsChallenge2 has the same default value as nsChallenge1 so I see no reason this won't work for it too
=> we should to visit the contest booth to find out what the contests are

RELEASE/scripts/autoscend/auto_combat.ash
disguise delimit identify [your shadow] mask
this prevents aborting for unidentified mask
validates
=> disguise delimit identify [your shadow] mask

RELEASE/scripts/autoscend/quests/level_any.ash
fix infinite loop when trying to do vacation without enough adventures
Fixes issue reported in discord
validates
=> fix infinite loop when trying to do vacation without enough adventures

RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/iotms/mr2014.ash, RELEASE/scripts/autoscend/iotms/mr2019.ash, RELEASE/scripts/autoscend/quests/level_11.ash
*auto_is_valid will identify grimstone mask as invalid if you are playing as any non-core class.
as vampyre shows a generic message that says only core classes are allowed to use. (unlike the tested older paths who showed path specific messages explaining why they cannot use it).
**This does need spading to see if an exception exists.
*UV compass and ornate dowsing rod check for auto_can_equip instead of checking is_unrestricted. This allows them to also catch paths in which you are forbidden to equip offhand items by the path rules (boris and way of surprising fist). And will be more robust going forward.
The first issue cropped up because I added the ability to pull a grimstone mask for the dowsing rod, as it saves 9+ adv in desert from 1 pull. Avatar paths could never get a grimstone …
=> grimstone mask fix. also UV compass and ornate dowsing rod should test auto_can_equip

RELEASE/scripts/autoscend/quests/optional.ash
fix error introduced by #438 by partially reverting it
validates
is a reverting of code to an older known to work code.
=> fix error introduced by #438

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/quests/level_13.ash
*disguises delimit don't waste all adventures if the naughty sorceress 3rd form is wearing one of the masks that prevent her from advancing the quest to step 12. making bear verb orgy impossible in that specific ascension
**Since we have not fully spaded which masks do this. this is handled by looking at the quest state. If mafia thinks we are at quest state 12 it means mafia thinks we unlocked bear verb orgy by losing to NS 3rd form. At that point we refresh quests, that causes mafia to recognize we are on step 11 not 12 according to the quest log. which indicates that in this particular disguises delimit ascension the NS 3rd form is wearing a mask that is preventing bear verb orgy. at which point we abort and tell the user to fix it manually by getting a wand (in such a run the only way …
=> disguises delimit bear verb orgy handling

RELEASE/scripts/autoscend/paths/g_lover.ash
don't do this unless in G Lover. Also this is probably bad regardless but let's just let G Lover be bad and every other path can ignore these terrible choices.
Hasn't. No IotMs on test account & it's done for today regardless. However I suspect this is fine.
=> Don't spam specific familiars with mumming trunk choices in every path

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_combat.ash
removed abortCombat as mafia r20210 can now handle abort() command in combat filter function
see https://kolmafia.us/showthread.php?25122
this commit effectively reverts #434 now that mafia is handling it correctly.
tested by making a temporary modification to immediately abort
=> removed abortCombat as mafia r20210 handles it via abort()

RELEASE/scripts/autoscend/auto_post_adv.ash, RELEASE/scripts/autoscend/iotms/mr2019.ash
- only use campfire smoke if we don't get the buff
- add Prevent Scurvy and Sobriety to MP burning summons.
Works fine on my test account in LKS but I don't have the relevant IotM or skill on that account so it's really just passing a validate.
=> Couple of issues/requests from the discord channel

RELEASE/scripts/autoscend/auto_restore.ash
Stops the `Could not find a known, usable skill of yours uniquely matching "# null"` messages happening repeatedly as we no longer blindly try to `use_skill` on skills we may not either have or have access to in the current path.
Fixes #382 
Running an LKS run on a character with none of the Booke skills. Looks fixed as the spam is gone (and I tested it while debugging by printing the skill it was trying to use in that loop and the number of times).
=> only try casting blood skills if you actually have some

BUILD/familiars/regen.dat, RELEASE/data/autoscend_familiars.txt
So it turns out when I wrote "At worst the player will have something like a Ghuol Whelp or Starfish." I was wrong. Some players don't bother getting the very basic familiars, some of which are practically free. Actually some of them _do_ get the familiars, **they just don't bother putting them in their terrariums** :angry: 
also remove duplicate XO Skeleton entry from regen familiars (didn't matter anyway but consistency).
It hasn't. I'd have to create a new account entirely to test this which I'm not going to. Lets assume anyone who doesn't put the Mosquito in their terrarium is not worth our time.
=> add Mosquito as the absolute default failover for regen familiars

RELEASE/data/autoscend_restoration.txt, RELEASE/scripts/autoscend/auto_restore.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash
- add meat_per_use values for restoration skills so they are better compared against NPC purchased items
- fix Disco Nap being considered too low when you have Adventurer of Leisure
- fix value for Lasagna Bandages being lower than the out of combat average
- add a function to check if the Myst class guild store is available so we can know if magical mystery juice is available as an MP restore.
Fixes #405 
Ran day 1 as Normal Sauceror in LKS. It only used skills to restore HP (as it should). Note I tested it mostly without the special handling for Sauceror first so I could make sure all classes will benefit. The Sauceror handling is due to Soul Food and Curse of the Weaksauce giving ridiculous amounts of MP.
=> Resoration changes to address wasting meat on NPC items when skills are available and MP is in abundance

RELEASE/scripts/autoscend/quests/level_10.ash
try to fix infinite loop when trying to plant the bean
Fixes #459
validates
I can't reproduce the bug so I am asking the person who reported it to test it.... I do have the idea of manually "producing" the bug via property manipulation such as CLI `set questL10Garbage = started` when it is in step1
I will also test to make sure this does not break anything else by doing some runs with it.
=> Bean issue #459

RELEASE/scripts/autoscend/quests/level_9.ash
As title.
Hasn't yet. My test account is done for the day but conveniently it's level 11 in a normal LKS run with none of the peaks started so I'll give it a test after rollover by manually clovering to get 3 or more A-boo Clues after getting down to 90% hauntedness.
=> Don't waste clovers if we have enough A-boo Clues to complete the peak

BUILD/familiars/regen.dat, BUILD/familiars/stat.dat, RELEASE/data/autoscend_familiars.txt
move the non-IotM stat familiars below the IotM ones and put the Miniature Sword & Martini Guy below other item dropping Volleyballs as the drinks he gives are literally crappy.
Also add the Piranha Plant, Antique Nutcracker and Smiling Rat to the stat familiars.
Runs fine. I don't have the familiar on my account so it ends up at the Party Mouse when switching to a stat familiar.
=> add the melodramedary to stat and regen familiars

RELEASE/scripts/autoscend/auto_util.ash
workaround for cosmetics wraith not being recognized as a boss. thus crashing autoscend when we waste an instakill on it such as stomp boots.
mafia bug: https://kolmafia.us/showthread.php?25190
validates
=> cosmetics wraith not recognized as boss workaround

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/quests/level_any.ash
get clovers on dependence day from green rocket 
Fixes #347 
I verified the function was called back when it was unusable due to mafia issue.
after mafia issue was resolved I was already overdrunk, so I tested it via a test function that called `https://kolmafia.us/showthread.php?25200`
=> get clovers on dependence day from green rocket

RELEASE/scripts/autoscend/auto_restore.ash
This PR continues to address #405. I was still seeing some of the behavior described in that issue, and I think this PR fixes it. The optimization objective of `hp_per_meat_spent` was using `total_meat_used`, not `meat_per_use`. This integrates Malibu Stacey's `meat_per_use` implementation into `total_meat_used` for skills.
Casual run. More testing is incoming.
=> Ensure skill restores and item restores are being compared correctly.

RELEASE/scripts/autoscend/quests/level_any.ash
only equip ring of boring doors when current progress is at 4 or 9. since it is only used on 5th and 10th visit
been using that if line in my aftercore script for a while now and it reliably equips the ring of boring doors only at the correct interval
also played with it for a day in autoscend and it works here too. only equipping the ring of boring doors when needed
=> only equip ring of boring doors when its needed (5th and 10th turn)

RELEASE/scripts/autoscend/auto_util.ash
As title. Noticed every second adventure in the Orc Chasm it had 10 ML when it should have 0. The print_footer() in #453 really helps spot stuff like this.
Running Normal LKS. Seems good now.
=> fix MCD flip flopping when not set to max (e.g. Orc Chasm).

RELEASE/scripts/autoscend/quests/level_11.ash
Check was using `item_amount()` rather than `possessEquipment()` so it would calculate less than it should if you happened to be wearing some of them.
I really wish mafia would just make `item_amount()` work like `possessEquipment()` and create `inventory_amount()` that does what `item_amount()` does presently.
My LKS run was past this point when I noticed it had run 14 adventures in the zone when it should be only 6 with all 3 lynyrd items and the musk effect as it should be burning clovers. Validates fine.
=> fix lynyrd protestors amount calculating less than it should 

RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash
rewrite providePlusCombat and providePlusNonCombat so they use the same pattern as the other providers
Fixes #400 
Running Normal LKS with these changes on #453 and have removed the early call to `equipMaximizedGear()`. Looks all good.
=> rewrite providePlusCombat and providePlusNonCombat

RELEASE/scripts/autoscend/auto_cooking.ash
- tweak the desirability for pulled consumables a little lower
I noticed the consumption code favours Advanced Cocktail Crafting booze over better stuff it could pull. Tracked it down to the desirability modifier causing it to value better consumables far lower than it probably should.
- also exclude the unidentified drink as the adventure gain range is wild (6-20 from size 3!)
Like WTF is this thing even? Mafia lists it as 4.33 adv/liver which is mathematically correct but that range is horrific! Not counting the Ode bonus, I've seen it give 9 or less adventures on more than one occasion (and one that gave 15).
Been running these a while. Pulled them out of #453 as I'm still addressing LKS things on that so it may be a while before it's ready to merge and stuff like this shouldn't need …
=> couple of tweaks to consumption

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash
*issue #400 running half the -combat zone adventures without -combat gear equipped
*limit the amount of maximizer combinations check to 100k, which will only be reached in casual and postronin. but will make a significant difference in those.
ran it for a few days now on multiple accounts. no issues thus far
checked the log for neck of the woods for one of them and it is including `-200combat 25max` every turn instead of flip flopping on the equipment
=> issue #400 flipflop on -combat gear resulting in half adv in zone not wearing gear

BUILD/monsters/sniff.dat, RELEASE/data/autoscend_monsters.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_choice_adv.ash, RELEASE/scripts/autoscend/auto_combat.ash, RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/auto_familiar.ash, RELEASE/scripts/autoscend/auto_post_adv.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_restore.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/auto_zone.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/paths/low_key_summer.ash, RELEASE/scripts/autoscend/quests/level_10.ash, RELEASE/scripts/autoscend/quests/level_11.ash, RELEASE/scripts/autoscend/quests/level_12.ash, RELEASE/scripts/autoscend/quests/level_13.ash, RELEASE/scripts/autoscend/quests/level_2.ash, RELEASE/scripts/autoscend/quests/level_5.ash, RELEASE/scripts/autoscend/quests/level_6.ash, RELEASE/scripts/autoscend/quests/level_7.ash, RELEASE/scripts/autoscend/quests/level_8.ash, RELEASE/scripts/autoscend/quests/level_9.ash, RELEASE/scripts/autoscend/quests/level_any.ash, RELEASE/scripts/autoscend/quests/optional.ash
- change calls to `auto_have_familiar($familiar[Mosquito])` to `pathAllowsFamiliar()` as the former returns false in 100% familiar runs and was being used to check if familiars are allowed in the current run (which screwed 100% runs out of some buffs and other things for no reason)
- reinstate calling `equipMaximizedGear()` at the start of each loop iteration until the issues with flip-flopping equipment is addressed.
- add NC handling for the Overgrown Lot
- add drop tracking for junksprites similar to unstable fulminate ingredient drop tracking
- add printing a "footer" at the end of our pre-adventure handling since a lot can change between the header being printed and actually adventuring and this is when we actually care about what certain values are.
- fix combat modifiers and item …
=> Better routing for LKS and some other related fixes

RELEASE/scripts/autoscend/auto_pre_adv.ash
In Dark Gyffte we end up aborting if we try to burn mana on Librams/whatever else.
Tested in multiple Dark Gyffte runs,
=> Fix trying to burn mana on Pre-adventure in Dark Gryffte

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/quests/level_8.ash
Issue reported in Discord
> Getting this following every turn: `> [WARNING] - Could not uneffect for ninja snowmen, delaying`
I intentionally didn't make changes to L8_trapperNinjaLair() or L8_trapperGroar() when working on #453 as #443 is in progress but I should have. This addresses that oversight.
It does not address dying instantly to ninja snowman assassins however (and is not intended to, it is intended to allow the previous behaviour of doing the snowman route in hardcore when you can get +combat to work again).
Also added updating minimum mafia version to fix
>nukasevToday at 08:29
>autoscend updated automatically when I launched mafia, now I get an error when running autoscend: Bad familiar value: "Melodramedary" (level_11.ash, line 25)
and
>LaLaWingsToday at 17:59
>Huh, did a …
=> mafia version and ninjas combat rate

RELEASE/scripts/autoscend/auto_util.ash
Single line change. Had wrong buff name. Reported in Discord.
Hasn't yet but I'm confident this fixes the issue.
=> fix typo'd skill name.

RELEASE/scripts/autoscend/auto_util.ash
Fixes attempting to get crazy amounts of non-combat. 
Also only try to get Invisible Avatar if we have the Powerful Glove (otherwise there will be lots of spam of "Effect (Invisible Avatar) is not known to us. Beep.")
Tested it in aftercore with lots of use of `ash import <autoscend.ash> providePlusNonCombat(25, true/false, true);` with `auto_logLevel = debug` to make sure it's working properly now.
=> fix ProvidePlusNonCombat not inverting the return value from numeric_modifier()

RELEASE/scripts/autoscend/auto_choice_adv.ash, RELEASE/scripts/autoscend/auto_combat.ash, RELEASE/scripts/autoscend/auto_cooking.ash, RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2019.ash, RELEASE/scripts/autoscend/paths/actually_ed_the_undying.ash, RELEASE/scripts/autoscend/quests/level_11.ash, RELEASE/scripts/autoscend/quests/level_7.ash, RELEASE/scripts/autoscend/quests/level_any.ash
- don't use Curse of Fortune on brigands unless we're sure we'll kill it that round (we lose the bonus meat drop if we resurrect)
- removed other pointless casts of Curse of Fortune, tidy up a few things and add some comments/log messages.
- re-add Ed eating fortune cookies for the first SR window as it's almost certain he'll be farming Ka. May revisit later.
- add ownership check to horsery so there's no property changing console spam for people who don't have it.
- don't force auto_delayHauntedKitchen as Ed as it then 'sticks' for users from that point on.
- clean up some Ed functions.
- add more of a buffer to check for whether we'll survive a hit from the modern zmobie as Ed since expected_damage() isn't reliable (TODO: replace with some BatBrain/zlib calls)
- move Ed's underworld …
=> Misc Ed fixes

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_combat.ash, RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/auto_familiar.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/auto_zone.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2017.ash, RELEASE/scripts/autoscend/iotms/mr2018.ash, RELEASE/scripts/autoscend/paths/bees_hate_you.ash, RELEASE/scripts/autoscend/quests/level_10.ash, RELEASE/scripts/autoscend/quests/level_11.ash, RELEASE/scripts/autoscend/quests/level_12.ash, RELEASE/scripts/autoscend/quests/level_13.ash, RELEASE/scripts/autoscend/quests/level_4.ash, RELEASE/scripts/autoscend/quests/level_9.ash
Don't try to use forbidden items and familiars in paths like BHY. 
Use auto_is_valid() instead of is_unrestricted() in several older iotms because auto_is_valid already checks for bees (and other special path) restrictions
Don't try to complete impossible quest sections and don't skip any mandatory quests in BHY.
Make sure to have an antique hand mirror instead of a wand for the final battle. (obtaining the antique hand mirror is left as an exercise for the user).
Fixes #91
Completed a bees hate you softcore run as sauceror with most skills permed and IOTMs since 2015. These changes fix aborts, infinite loops, and quests that never start in bees hate you that were trivial to reproduce. I have no idea how optimal these are, just trying to get the path to be better supported. Session log …
=> Bees Hate You fixes

RELEASE/scripts/autoscend/paths/actually_ed_the_undying.ash, RELEASE/scripts/autoscend/quests/level_11.ash, RELEASE/scripts/autoscend/quests/level_12.ash
- Add handling to get a seal tooth for the Gremlins (issue reported in Discord)
- Don't force NC's in the Haunted Ballroom.
- Try to get the Seal Tooth in Ed earlier if we have a bunch of meat.
Fixes #506
Ran HC Ed and Normal LKS with this.
=> Couple of small bug fixes.

BUILD/monsters/banish.dat, RELEASE/data/autoscend_monsters.txt, RELEASE/scripts/autoscend/auto_choice_adv.ash
- Fight the Remains of a Jilted Mistress for the Antique Hand Mirror (needed for NS replacement)
- Don't banish the Animated Rustic Nightstand in BHY so we can do the above.
Untested personally but @mattgiltaji say's he'll be starting a new BHY run & can test it.
=> BHY Antique Hand Mirror changes

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_zone.ash, RELEASE/scripts/autoscend/iotms/mr2020.ash
- Add fighting the free Piranha plant(s) and getting the mushroom filets if you have the Mushroom Garden installed.
- Add getting the Guzzlr cocktail set if you have the Guzzlr and have unlocked the Platinum quest (requires 5 Gold quests completed which also requires 5 Bronze quests completed).
Ran this over a handful of Normal LKS runs. Looks fine.
=> Mushroom Garden and Guzzlr handling

RELEASE/scripts/autoscend/quests/level_11.ash
for L11 stone wool check, only abort for lack of stone wool if we have nothing else to do.
since at the moment we just use semirare to get stone wool. and we might encounter said semirare later on if we go do something else.
use isAboutToPowerlevel() to determine if we have other things to do or not.
tested it in an HC ed run
=> L11 stone wool check

RELEASE/scripts/autoscend/auto_familiar.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_zone.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2017.ash, RELEASE/scripts/autoscend/paths/low_key_summer.ash, RELEASE/scripts/autoscend/quests/level_11.ash
- fix issue with delay burning in Hidden City zones we've already finished (reported in Discord)
- also don't try to adjust equipment for YR/Banish/Replace when delay burning (same issue as above)
- add more debug logging to familiar selection (might help trace issues if people switch it on)
- don't default Horsery to dark horse when an empty string is passed, treat as failure.
- don't speak to Shen until day 2 at the earliest as day 2 snakes are better for routing than day 1
- don't try to adventure in the palindome if you don't have the talisman o' namsilat
- make sure LKS key zones can accept wanderers if we try to burn delay in them.
- handful of tweaks to LKS routing.
Other than the delay burning stuff I've been running this in LKS and Ed for a while.
=> Some misc bug fixes

RELEASE/scripts/autoscend/quests/level_any.ash
otherwise it gets the green rocket on turn 1 and makes you too poor to unlock the island which extends the run by at least 1 day.
validates and runs on an ed run
but I can't really test the code itself until next dependence day when it starts breaking runs
=> depedence day rocket. as ed wait until island unlock

BUILD/familiars/drop.dat, BUILD/familiars/item.dat, BUILD/familiars/regen.dat, BUILD/familiars/stat.dat, BUILD/monsters/banish.dat, BUILD/monsters/sniff.dat, RELEASE/data/autoscend_familiars.txt, RELEASE/data/autoscend_monsters.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/auto_zone.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2018.ash, RELEASE/scripts/autoscend/iotms/mr2019.ash, RELEASE/scripts/autoscend/iotms/mr2020.ash, RELEASE/scripts/autoscend/quests/level_11.ash, RELEASE/scripts/autoscend/quests/level_12.ash, RELEASE/scripts/autoscend/quests/optional.ash
- Lots of tweaks to familiars. Mostly removing the Fairyballs from a whole lot of places they don't need to be as they dominate familiar selection otherwise. Tweaked regen familiars so the Fairywhelps are higher and grouped together (above XO Skeleton). Removed a bunch of drop farming from the stat familiars (they don't need to be in both drop and stat).
- add "new" monsters in the Cyrpt to the banish list ("new" because the were added on the 1st of January 2020 which was a full 8 months ago).
- Add Red Butler, Skinflute and Camel Toe to sniff monsters and a duplicate of pygmy witch accountant since it's optimal to sniff when we have thrice-cursed already.
- More Left-Hand Man support. Use it to grab Latte ingredients if burning delay. Also unequip whatever it is equipped with when we …
=> Some random fixes and tweaks

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_choice_adv.ash, RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/auto_familiar.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/paths/bees_hate_you.ash, RELEASE/scripts/autoscend/quests/level_11.ash, RELEASE/scripts/autoscend/quests/level_12.ash, RELEASE/scripts/autoscend/quests/level_13.ash, RELEASE/scripts/autoscend/quests/level_4.ash, RELEASE/scripts/autoscend/quests/level_7.ash, RELEASE/scripts/autoscend/quests/level_9.ash
Second pass of BHY fixes as I test the first set. So far:
Fixed knob goblin outfit to not cause an abort
Fixed preference override to actually override
Fixes #91
HC run of BHY as sauceror with most skills permed and many IOTMs
[sytras_20200728.txt](https://github.com/Loathing-Associates-Scripting-Society/autoscend/files/4986762/sytras_20200728.txt)
=> More BHY Fixes

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_deprecation.ash, RELEASE/scripts/autoscend/auto_familiar.ash, RELEASE/scripts/autoscend/auto_post_adv.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2015.ash, RELEASE/scripts/autoscend/paths/actually_ed_the_undying.ash, RELEASE/scripts/autoscend/paths/avatar_of_boris.ash, RELEASE/scripts/autoscend/paths/avatar_of_sneaky_pete.ash, RELEASE/scripts/autoscend/paths/dark_gyffte.ash, RELEASE/scripts/autoscend/paths/gelatinous_noob.ash, RELEASE/scripts/autoscend/paths/nuclear_autumn.ash, RELEASE/scripts/autoscend/paths/path_of_the_plumber.ash, RELEASE/scripts/autoscend/paths/pocket_familiars.ash, RELEASE/scripts/autoscend/quests/level_any.ash
*removed jello initialization as it was only used to set auto_cubeItems to false, which is incorrect. we actually want the cube item drops in that path so we can do the daily dungeon. currently behavior resulted in getting stuck at the door with nothing left to do and not fat loot tokens for keys
*boolean wantCubeling() created and used. It determines if we want to use the gelatinous cubeling familiar for its drops.
**remove setting auto_cubeItems
**remove setting auto_useCubeling
**fix casual and postronin getting stuck on cubeling forever. it prioritizes the cubeling to get the drop, but the check for the drops was checking item amount == 1, instead of >0. in casual it failed because you had more than 1.
**fix avatar paths not pulling cubeling drops in softcore or postronin.
fixes #105 …
=> cubeling fixes

RELEASE/scripts/autoscend/auto_pre_adv.ash
we're only burning delay if we're adventuring in the zone solveDelayZone() returns.
Fixes #527 
It hasn't been tested massively as I'd need to jump into a non-LKS run and the account I could test this in is day 2 of LKS. Validates and runs fine though.
=> Bugfix for delay burning issue with sausage goblins

RELEASE/scripts/autoscend/auto_combat.ash
*remove a redundant abort when yellow ray fails that happens after the yr block function.
**it already gives a warning if it fails inside the yr function block. and sometimes you just do not have a yr
*ed combat yellow ray checked should not check canYellowRay(monster). that function is actually a pre-combat prep for yellow ray not a check if you can yellowray, it just produces errors during combat as it tries to acquire items which cannot be done during combat. modified to match the non ed combat function.
*take an old update for asdon martin yr (daily missile launcher) handling and apply it to ed combat handler as well
several HC ed on different accounts
day 3 of 3 of SC ed
=> yellow ray

RELEASE/scripts/autoscend/auto_familiar.ash, RELEASE/scripts/autoscend/paths/gelatinous_noob.ash
*blacklist your last set of lockpicks from being absorbed as gnoob
*boolean wantCubeling() check if cubeling already dropped items this ascension.
ash calls and validates
=> gnoob blacklist and cubeling handling

RELEASE/scripts/autoscend/auto_restore.ash
fix infinite loop if you possess a hand in glove and try to acquireHP()
owning a hand in glove breaks maxHP tracking when equipping, unequipping, or smithness score changes.
We need to check possession rather than equipped because unequipping it also breaks it. unequipping specifically can get autoscend stuck in an infinite loop of trying to restore hp when already at max HP.
mafia devs say it is a kol bug so they won't add automatic refreshes
https://kolmafia.us/showthread.php?25214
so we need to work around this issue. The workaround is CLI command refresh status at the start of acquireHP function if we possess a hand in glove.
half of a day 1 of casual accordion thief which had gotten stuck in the infinite loop 3 times already before I applied this fix.
also added debug message on when …
=> fix infinite loop if you possess a hand in glove and try to acquireHP()

RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash
I was reviewing IotM use in an LKS run and noticed it was still using Powerful Glove charges for Invisible Avatar occasionally (and ending up on 27% combat rate) even when it had the key sausage, smooth movements, sonata of sneakiness and horsery available which is sufficient to hit the 25% soft cap. 
- fix use of horsery in providers
- also tweak speculative values when we have Musk of the Moose/Smooth Movements since they are removed by each other.
Ran LKS day 3 with these changes (and G-Lover but 0 IotMs).
=> Couple of tweaks to combat rate providers

RELEASE/scripts/autoscend/quests/level_11.ash
do not skip unlocking 2nd floor of spookyraven manor just because you have ghost of a necklace.
this seems to be some sort of error correction that assumes that if we have a ghost of a necklace it means we must have finished this quest already. However we already use mafia tracking on this quest to check the state of it. And you can have ghost of a necklace either as a manual pull in softcore or as a result of being in casual.
So this method of error correction only introduces errors instead of fixing them.
got stuck in casual run with autoscend thinking there is nothing left to do. applied this fix and it did the haunted library
=> casual fix not unlocking spookyraven 2nd floor

RELEASE/scripts/autoscend/iotms/mr2014.ash
While running as a HC snake oiler, ran into an infinite loop that cluttered logs with complaints about not being able to reach the prince's balcony. Turned out that the script was trying to use a grimstone mask to get a Fancy oil painting, but grimstone mask is not usable outside of regular classes. The auto_is_valid() function already handles this use case correctly, so added some calls to auto_is_valid() before trying to get the fancy oil painting.
Issue was extremely reproducible, left me with a GB session log full of 18 million lines of the same warning. After purging that from the logs and implementing this fix, issue doesn't reoccur, even with grimstone mask in inventory. Though it was fixed for west of loathing, the fix should work for all paths that don't allow a grimstone mask.
=> Don't try to make a fancy oil painting if grimstone mask is unusable

RELEASE/scripts/autoscend/auto_combat.ash
*gulp latte is usable 4 times a day. we only allowed it to be used 1/day
*gulp latte should not be used unless your current MP is less than half your maxMP. because it restores 50% of your MP.
standard softcore disco bandit
=> Latte fixes

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/paths/grey_goo.ash
Grey goo is certainly a path in the online video game Kingdom of Loathing.
```Adventuring in Grey Goo is not currently supported, or necessary. Have fun!
Please     come back in 2 days.
Stack trace:
at LA_grey_goo_tasks     (grey_goo.ash:33)
at doTasks (autoscend.ash:3334)
at     auto_begin (autoscend.ash:3656)
at safe_preference_reset_wrapper     (autoscend.ash:3691)
at safe_preference_reset_wrapper     (autoscend.ash:3698)
at safe_preference_reset_wrapper     (autoscend.ash:3698)
at safe_preference_reset_wrapper     (autoscend.ash:3698)
at main (autoscend.ash:3726)```
=> Initial Grey Goo support :)

RELEASE/scripts/autoscend/auto_familiar.ash
- you can't switch to a familiar if it's in the crown of thrones or buddy bjorn.
Issue reported (and debugged) in Discord.
It hasn't. I don't have either of those on my test account to test it so we're going to have to rely on users who do have them to let us know if this is terrible.
=> Crown of Thrones/Buddy Bjorn familiar handling bugfix

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2019.ash, RELEASE/scripts/autoscend/quests/level_10.ash, RELEASE/scripts/autoscend/quests/level_11.ash
- add handling for changing the tracked phylum of the snapper.
- force swapping to the Red-Nosed Snapper in zones where we can farm human musk (Airship, some L11 quest zones, NEP when not powerlevelling).
- add human musk to banishers.
- add micronova to yellow rays.
- add some failover handling if the Snapper ends up as the best +item familiar to get some of the useful drops and/or increase odds of fighting the monster we want.
Fixes #212 
Used this in my last couple of LKS runs.
=> Red-Nosed Snapper handling.

RELEASE/scripts/autoscend/auto_combat.ash
removed automatic debugging of whether or not an old workaround for detecting your shadow is still needed for gnoob.
I already confirmed it was an obsolete workaround for plumber and gnoob. Currently west of loathing testing remaining
validates. which is all it needs considering what is changed
=> remove auto debug for gnoob on shadow workaround.

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_consume.ash, RELEASE/scripts/autoscend/auto_equipment.ash
when we are at 19/19 drunkness we auto equip stooper to make it 19/20 and then tell the user to overdrink and run autoscend again.
so i overdrink with stooper. then run it again... it then switches stooper to none, because we always switch stooper to none if it is current familiar to avoid stooper stupor. then after doing so it recognizes we are overdrunk so it stops main loop and goes to do bedtime.
in bedtime it will add switch for the 3 IOTM familiars that help bedtime beyond a normal familiar
but. a person without any of those iotm familiars who has solid shifting time weirdness would get +5 adv from rollover on any familiar... any familiar other than none that is. which is what it is set to. and as such would not use it
got an account overdrunk with stooper as current familiar and …
=> fix rare case of not using [solid shifting time weirdness]

RELEASE/scripts/autoscend.ash
the softblock release on quests that await optimal conditions is done after the return false if over level 12. this means that if you are level 13+ autoscend will never release the softblock. all those quests will continue waiting... thus it reaches the last line and quits saying it has nothing to do
I just flipped the order in which those two ifs were being done.
was stuck as level 14 sealclubber HC standard with several quests waiting for optimal conditions and not being done, it was saying there is nothing left to do.
With this change it now works
=> fix quest softblock not releasing when level 13+

RELEASE/scripts/autoscend/combat/auto_combat.ash
logic for it was missing a ! for canSurvive and the figure was too low.
also it can only be used once per round
used it on HC beanslinger. it started using beanscreen appropriately.
although I think there might be an unrelated issue of failing to find a banisher causing it to fail to use a stunner. but that would be for a followup PR
=> fixed beanscreen for awol

RELEASE/scripts/autoscend/iotms/mr2020.ash
I was caught in an infinite loop of attempting to cast triple size at bed time. Mafia thought I had used 90% of the battery, when I had actually used 100%.
I reran autoscend after making this change, saw the log message I added, and did not encounter the same infinite loop again.
=> Catch if we fail to cast a powerful glove skill and update battery if needed.

RELEASE/scripts/autoscend/combat/auto_combat_quest.ash
*do not commit suicide against tool gremlin using seal tooth
*avatar of west of loathing use beanscreen to get 3 extra turns of survival against tool gremlin
Fought gremlins with it as a beanslinger
=> gremlins. no suicide and use beanscreen

RELEASE/scripts/autoscend/auto_deprecation.ash
cleanup auto_deprecation.ash
there is no reason to do an if check to see if a property exists before calling on remove_property(). the latter does that check and it just does nothing (no error) if the setting does not exist
ash calls
=> cleanup auto_deprecation.ash

RELEASE/scripts/autoscend/auto_util.ash
*bitchin meatcar meatreserve should be my_turncount() > 50 not <. fixup for PR #551
todo
=> bitchin meatcar meatreserve should be my_turncount() > 50 not <. fixup for PR #551

RELEASE/scripts/autoscend/quests/level_09.ash
*if we decide to not do aboo peak then we should not equipBaseline() but resetState() instead before returning false
the former actually changes our outfit which can cause us to lose HP from switching the outfit back and forth and waste a lot of meat. the latter does not do that and instead resets our maximizer as well as a few other things to as if we just started a new loop.
ran it on my account that was just at the right spot for this to be an issue. and it solved the problem
=> if we decide to not do aboo peak then we should not equipBaseline() but resetState() instead

BUILD/settings/any.dat, RELEASE/data/autoscend_familiars.txt, RELEASE/data/autoscend_settings.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_deprecation.ash, RELEASE/scripts/autoscend/auto_king.ash, RELEASE/scripts/autoscend/paths/community_service.ash
*replace king liberated script's many many individual pulls with a single "pull all" command
*fixes the king liberated script crashing with a failure to find the function `pullPVPJunk()`
*allow kingliberated to do stuff regardless of snapshot state or setting. actual calling of snapshot scripts already had its own check for its own setting.
*do breakfast as part of kingliberated. remove the individual visit url calls that were obsoleted by it
*property auto_kingLiberation used to determine if we switch from the user defined king liberated script to autoscend's king liberated script. old behavior was to always switch to our script but then have it do nothing if set to false
*removed auto_pullPVPJunk setting
*start sea quest so we can grab sea jelly as part of breakfast. move displaying to …
=> auto_king.ash refactored

RELEASE/scripts/autoscend.ash
it is already handled in our familiar code. in fact the very first line option in "drop" dat file is the same as what I removed.
validates. all it really needs
=> remove hardcoded fist turkey familiar from doTasks()

RELEASE/scripts/autoscend/combat/auto_combat_quest.ash
account for ed being undying when avoiding death by gremlin.
#556 prevents us from committing suicide against gremlins via poking them with a seal tooth when they are projected to kill us within 1.5 rounds (a little over 1 round to account for inaccuracies in canSurvive())
However as ed the undying this is not an issue since he can resurrect for free twice per fight. will now account for this. will only above if not ed OR if ed is out of free resurrections
validates. issue is not that easy to replicate
=> account for ed being undying when avoiding death by gremlin

RELEASE/scripts/autoscend/quests/level_04.ash
*[Guano Junction] do not suicide with clover, with any class.
*[Guano Junction] do not assume success when adventuring there
validates
=> Guano Junction do not suicide with clover & do not assume success

RELEASE/scripts/autoscend/auto_adventure.ash
KoLmafia sometimes returns false even though we successfully adventured (see https://kolmafia.us/showthread.php?25370-adv1-returns-false-for-quot-choiceless-quot-choice-adventures)
This causes issues as the script then carries on in the doTasks() loop from that point without resetting things like the maximizer statement.
I've been running this for quite a while according to my logs. At least a few Normal LKS runs and 6 Normal Standard runs (1 of each class). I've been meaning to report it on the mafia forum for a while but was prompted by @taltamir running into this issue in Ed runs while building extremity to ascend the peak.
=> workaround for mafia bug in adv1

RELEASE/scripts/autoscend/paths/actually_ed_the_undying.ash, RELEASE/scripts/autoscend/quests/level_03.ash, RELEASE/scripts/autoscend/quests/level_05.ash, RELEASE/scripts/autoscend/quests/level_07.ash, RELEASE/scripts/autoscend/quests/level_08.ash, RELEASE/scripts/autoscend/quests/level_10.ash, RELEASE/scripts/autoscend/quests/level_11.ash, RELEASE/scripts/autoscend/quests/level_12.ash, RELEASE/scripts/autoscend/quests/level_13.ash
Makes some quest code a little easier to read by searching for all expressions matching the regex `(\S+) < (\S+) \|\| \1 > \2` and replacing them with `\1 != \2`.
proof by inspection
=> Replace expressions like 'a > b || a < b' with 'a != b

RELEASE/scripts/autoscend/quests/level_03.ash
Current tavern quest code runs the maximizer n times after n turns in the tavern. No need for this; our maximizer command doesn't change as you move through the tavern layout. This PR just pulls the code out of the loop.
I've tested this on one casual ascension and it worked well.
=> Fix tavern loop.

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/combat/auto_combat.ash, RELEASE/scripts/autoscend/iotms/mr2017.ash, RELEASE/scripts/autoscend/paths/g_lover.ash, RELEASE/scripts/autoscend/quests/level_06.ash, RELEASE/scripts/autoscend/quests/level_09.ash, RELEASE/scripts/autoscend/quests/level_11.ash, RELEASE/scripts/autoscend/quests/level_12.ash
Fixes for G-Lover so it runs without interruption. I have paid very little attention to speed issues (one exception being delaying adventuring in The Dark Heart of the Woods until we start the Dakota Fanning quest as it's trivial enough and not G-Lover specific).
My current run spent 82 adventures trying to unlock the Hidden City (can't use Stone Wool) and will waste a lot of adventures trying to get non-combats as without manual pulls it can't get any -combat.
It also breaks in combat as it runs out of MP if it casts Gallapagosian Mating Call since it keeps a relatively small amount of MP on hand (my test runs have been as Sauceror but since you can't cast Weaksauce (or Saucestorm) you get no extra MP). Otherwise combat seems fine spamming Saucegeyser. I probably should've been running …
=> G-Lover fixes

RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2020.ash
Support opening cargo shorts pockets. Currently unused. I leave this as an exercise for someone who is actively ascending.
Doesn't support all pockets, I just added (most of) the interesting ones from the spreadsheet.
Manually tested:
```
> ash import autoscend; auto_cargoShortsOpenPocket($item[alabaster knight])
Inspecting Cargo Cultist Shorts
picking pocket 275
You acquire an item: alabaster knight
Returned: true
> ash import autoscend; auto_cargoShortsOpenPocket($item[alabaster knight])
```
=> Initial support for cargo shorts

RELEASE/scripts/autoscend/quests/level_09.ash
Changes Level 9 A-Boo peak handling to switch to Trick-or-Treating Tot via HandleFamiliar rather than only through maximizer, to avoid weird buffing/flip-flopping.
Was unable to test, due to lacking a tot, have handed off to player to this end.
- [NA] I have commented my code, particularly in hard-to-understand areas.
=> Use tot properly in a-boo peak

RELEASE/scripts/autoscend/quests/level_10.ash
*finish giant trash quest questL10Garbage before doing L10_holeInTheSkyUnlock()
In a run where it broke, tried the fixed version and it solved the problem
=> *finish giant trash quest questL10Garbage before doing L10_holeInTheSkyUnlock()

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_familiar.ash, RELEASE/scripts/autoscend/auto_post_adv.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/paths/pocket_familiars.ash, RELEASE/scripts/autoscend/quests/level_12.ash, RELEASE/scripts/autoscend/quests/level_13.ash
familiars passive damage and bad familiars
*no need to log every single time we look to see if a familiar is valid and find it is not because we are in a 100% familiar run. It just adds pages long list of all the familiars which are not valid because we are in 100% run
*boolean isAttackFamiliar(familiar fam) created. lets us know if familiar deals damage to enemy.
*void gremlinsFamiliar() created and used. will prepare our familiar for the gremlins fight.
*pokefam removed redundant initialize for auto_getBoningKnife
*refactored the wall of bones fight.
**improving familiar handling. use gremlins familiar chart (delevel and no attacks) when possible instead of always none
**only buffing for towerkill if we actually try to towerkill
**always want boning knife in 100familiar run with attack …
=> familiars passive damage and bad familiars

RELEASE/scripts/autoscend/auto_zone.ash
*add tunnel of love to generic_t zone_available(location loc) so it will correctly identify its availability.
tested via ash calls.
=> tunnel of love zone availability

RELEASE/scripts/autoscend/iotms/mr2019.ash
sausage grinding was set to always reserve 5k meat, which situationally could make it grind below the meat reserve and trigger doing doc galaktik quest. wasting adventures.
Fixes #576
validates.
=> sausage grinding use meatReserve()

BUILD/settings/any.dat, RELEASE/data/autoscend_settings.txt, RELEASE/scripts/autoscend/quests/optional.ash
* accordion thief, pastamancer, and sauceror considergalaktik fixes. do not do it with S and P, while AT should not do it after level 10.
* auto_considerGalaktik setting added. Set to true to allow autoscend to automatically enable galaktik quest for this ascension when it deems it necessary
partially fixes #587 
validates
=> Galaktik consideration fixes and auto_considerGalaktik optin setting

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_familiar.ash
remove outdated workaround for Adventurous Spelunker familiar. fixed upstream mafia r20417
I do not own that IOTM, but it is simple enough to not need testing beyond verifying
=> remove outdated workaround. fixed upstream mafia r20417

.github/workflows/ci.yml, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2020.ash
Update cargo shorts function to use builtin mafia functions, now that support is completed.
Fixes # N/A
```
> ash import autoscend; auto_cargoShortsOpenPocket("Yeg's Motel toothbrush")
Inspecting Cargo Cultist Shorts
picking pocket 284
You acquire an item: Yeg's Motel toothbrush
Returned: true
> ash import autoscend; auto_cargoShortsOpenPocket("Yeg's Motel toothbrush")
```
=> Cargo shorts redux

RELEASE/scripts/autoscend/auto_equipment.ash
there was a sign error on default maximizer string for non mys classes. it said we want flat dmg bonus, want elemental dmg bonus, and do NOT want % dmg bonuses. this is erroneous and was fixed
```
> ash import autoscend.ash; defaultMaximizeStatement();
Returned: 5item,meat,0.5initiative,0.1da 1000max,dr,0.5all res,1.5mainstat,mox,-fumble,0.4hp,0.2mp 1000max,3mp regen,1.5weapon damage,0.75weapon damage percent,1.5elemental damage,2familiar weight,5familiar exp,10exp,5Muscle experience percent
```
=> non myst classes want dmg%

RELEASE/scripts/autoscend/auto_choice_adv.ash, RELEASE/scripts/autoscend/quests/level_10.ash, RELEASE/scripts/autoscend/quests/level_11.ash
* In Live Ascend Repeat can get in inf loop at an NC that can be skipped for no adv cost. as this NC will always reoccur (only to be skipped again) unless we spend an adv somewhere else.
** Fixed for NC163 = https://kol.coldfront.net/thekolwiki/index.php/Melvil_Dewey_Would_Be_Ashamed
** fixed for NC178 = https://kol.coldfront.net/thekolwiki/index.php/Hammering_the_Armory
encountered and successfully passed those infinite loop triggering NCs
=> Live. Ascend. Repeat. fix inf loop in NC163 and 178

RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/paths/pocket_familiars.ash
* string pokefam_defaultMaximizeStatement() created and used
** instead of putting all the code to generate our default maximizer string inside a giant `if !pokefam` moved pokefam to its own function and cleaned up the main function to match
I suggest using "hide whitespace changes" when viewing file changes here
tested changes to default maximizer as seal clubber in class act to make sure I did not break it. pokefam testing is not really viable since pokefam autoscend support is very broken right now.
=> default maximizer pokefam cleanup

.github/workflows/ci.yml
github pull request automatic verification was missing a few files. Added the following files to verification:
* auto_pre_adv.ash
* auto_post_adv.ash
* auto_choice_adv.ash
looked at the checks tab above after each change and checked that it works
intentionally broke post_adv and made sure it caught it, then dropped the breaking commit
=> verify companion scripts

RELEASE/scripts/autoscend/auto_choice_adv.ash, RELEASE/scripts/autoscend/combat/auto_combat.ash
* sealclubber should consider northern explosion against physically immune enemies. We require sauce storm but sauce storm is not available in all paths. for example in class act we lose access to sauce storm so falling back to northern explosion is necessary
* The Dark Neck of the Woods cartography NC. instead of 1k meat prefer to skip a NC and finish this quest quicker
I was dying to ancient protector specter because I was just trying to hit it with regular weapon. Then with this patch it used northern explosion and killed it in one hit
=> sealclubber should consider northern explosion

RELEASE/scripts/autoscend/combat/auto_combat.ash, RELEASE/scripts/autoscend/quests/level_13.ash
* When facing [your shadow] without enough healing items, grab red pixel potions. also use them in combat against it.
* improve funkslinging code against your shadow to better mix and match items as needed
* fix rain-doh indigo cup against Your Shadow. its code was never actually used against shadow. added code to use it when it is worthwhile to do so
Seal clubber run. I had only 2 poultices, immediately crafted 2 red pixel potions, then farmed enough pixels for a 3rd one, crafted it, and fought the shadow
standard sauceror run. tested the new ambidexterous funkslinging code
=> your shadow: red pixel potion support & improve funksling & fix rain-doh indigo cup

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2016.ash
timespinner refactoring:
* int timeSpinnerRemaining() created
* int timeSpinnerRemaining(boolean verify) created
** used it in the various time spinner functions. since all the functions wanted to verify the
** informs us how many minutes remain on timespinner and also if it is available and unrestricted. since it will return 0 if unavailable or restricted
** switch restricted check from mafia is_unrestricted() to autoscends auto_is_valid. this ensures future path compatibility and also fixes some potential g-lover infininte loops
* timeSpinnerConsume
** no need for using temp variable to discard the output of visit_url. running a script is equivalent to ashq not ash.
** it assumed we always fail for some reason. always returning false.
* timeSpinnerCombat removed some error catching that …
=> timespinner refactoring

RELEASE/scripts/autoscend.ash
#611 was missing an import in autoscend.ash for the bedtime file
ran autoscend.ash and saw it actually run bedtime
=> fixup bedtime

RELEASE/scripts/autoscend/auto_familiar.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/combat/auto_combat.ash, RELEASE/scripts/autoscend/paths/heavy_rains.ash, RELEASE/scripts/autoscend/quests/level_08.ash
* cleared up some redundant notifications from pre_adv.
** redundant in that we were saying the same thing multiple times in a row
* pre_adv should not abort if it detects that heavy rains familiar has no gear equipped.
** this is already handled in preAdvUpdateFamiliar(place)
** the abort was done before the familiar handling, which meant it could not be fixed
* do not try to equip miniature life preserver on left-hand man
* heavy rains cleanup some obsolete code in rainManSummon
* heavy rains fix [wink at] not working properly
* cleanup combat code for [wink at].
* added combat support for [Fire a badly romantic arrow]
* hardcore heavy rains stop abort on failing to copy using raindoh blackbox when you do not have one. that IOTM is only accessible in softcore. And in heavy rains runs we …
=> heavy rains familiar equip fix & copying

RELEASE/scripts/autoscend/auto_zone.ash, RELEASE/scripts/autoscend/autoscend_header.ash
* location[int] zone_list() removed
** instead of keeping a giant yet incomplete list of locations that exist. use $locations[] which has mafia provide a list of all known locations
* generic_t zone_available(location loc) changed to boolean zone_available(location loc)
ash calls
=> Zone cleanup

RELEASE/scripts/autoscend/auto_zone.ash, RELEASE/scripts/autoscend/autoscend_header.ash
* provides all the locations in which this monster can be found. note that they are not filtered by accessibility
```
> ash import autoscend.ash; monster_to_location($monster[bar])
Returned: aggregate boolean [location]
The Spooky Forest => true
> ash import autoscend.ash; monster_to_location($monster[A.M.C. gremlin])
Returned: aggregate boolean [location]
Near an Abandoned Refrigerator => true
Next to that Barrel with Something Burning in it => true
Out by that Rusted-Out Car => true
Over Where the Old Tires Are => true
Post-War Junkyard => true
```
=> boolean[location] monster_to_location(monster target) created

RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/quests/level_13.ash
Auto failed to towerkill the wall of skin during one of my runs and was leaving many sources of damage on the table. I've updated it to include a couple extra, but I haven't found the original bug as to why it failed the first time. I expect that failure is due to the deeper problem where the towerkilling code doesn't distinguish between passive sources of damage and stinging sources.
Tested on a casual run.
=> Add Cosplay Saber to Wall of Skin.

RELEASE/scripts/autoscend/auto_restore.ash
* fix infinite loops in restore code
* more reasonable acquireMP() target.
** If someone wanted to get 100% MP they would use acquireMP(100.0).
** acquireMP() should be "get a reasonable amount of MP". so that is what it does now. It gets 300 MP or 95% of your maxMP, whichever is lower.
** Worth nothing that `acquoreMP()` without specifying a specific amount was only used once in all of autoscend... by me, incorrectly thinking it means "automatically get a reasonable amount of MP" instead of "get 100% of MP". which was fixed at #612 
I was at a position where I was regularly getting an infinite loop in restore every time I ran autoscend due to sausage slurping changing outfit. this fixed it by preventing a command to restore higher than maxmp
tested the code to prevent the inf loop when a …
=> fix infinite loops in restore

BUILD/familiars/item.dat, RELEASE/data/autoscend_familiars.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_post_adv.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/combat/auto_combat.ash, RELEASE/scripts/autoscend/iotms/mr2019.ash, RELEASE/scripts/autoscend/quests/level_06.ash, RELEASE/scripts/autoscend/quests/level_09.ash, RELEASE/scripts/autoscend/quests/optional.ash
* slightly reworked familiar buffing check
* misc spelling fixes
* void houseUpgrade() created and used
** fixes #19
* do not assume that any sauceror with 5 soulsauce can use soul bubble. verify it via the `canUse` function. which checks for limiting factors. For example, the fact that you are in a g-lover run and cannot use soul bubble because it has no g in the name will be caught by canUse.
* fix inf loop at L6_friarsGetParts() when delaying [The Dark Heart of the Woods] for the purpose of doing dakota fanning
ash calls.
did a few combats in g-lover to test the soul bubble fix
L6 inf loop tested by encountering it in pathless softcore
=> misc minor fixes

RELEASE/scripts/autoscend/auto_consume.ash
daily specials in Chez Snootee and the Gnomish Microbrewery were being checked for path validity. This is not required as they're never blocked from being consumed by path restrictions (e.g. in Standard you can eat or drink stuff that is out of Standard, in G-Lover you can eat or drink stuff that lacks G's).
Reported in Discord.
Ran a few HC Standard runs with Canadia moon signs with this but nothing worth consuming has come up yet in Chez Snootee so it hasn't broken anything but verifying it works as expected requires either a G-Lover run or waiting for something good to appear which could take forever.
=> Don't check if chez snootee/microbrewery stuff is valid

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_choice_adv.ash, RELEASE/scripts/autoscend/auto_consume.ash, RELEASE/scripts/autoscend/auto_familiar.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/auto_zone.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/paths/kolhs.ash, RELEASE/scripts/autoscend/quests/level_09.ash, RELEASE/scripts/autoscend/quests/optional.ash
* kolhs initial support
* special diet support
** try to rush to level 9 early via free combats for the better combat drink drops
* handling for choice adv 700 [Delirium in the Cafeterium]. KOLHS 22nd adventure every day
* basic adventuring in school
* yearbook camera sidequest
* boolean kolhs_mandatorySchool() created and used
** fixed trying to get logging hatchet on turn 1 of the run and getting stuck in infinite loop
* hats are forbidden in high school
* fix canDrink not identifying stepmom's booze and fountain 'soda'
* changes to generic_t zone_delay(location loc) for the purpose of recognizing the kolhs zones as delay zones
* fix steel margarita drinking for kolhs
* do not abort for too many adventures spent in school
* small cleanup of convoluted code for adventureFailureHandler(). …
=> KOLHS support

BUILD/settings_extra/post.dat, RELEASE/data/autoscend_settings_extra.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_post_adv.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2012.ash, RELEASE/scripts/autoscend/iotms/mr2016.ash, RELEASE/scripts/autoscend/paths/actually_ed_the_undying.ash, RELEASE/scripts/autoscend/paths/casual.ash, RELEASE/scripts/autoscend/paths/heavy_rains.ash, RELEASE/scripts/autoscend/paths/license_to_adventure.ash, RELEASE/scripts/autoscend/paths/the_source.ash, RELEASE/scripts/autoscend/quests/level_08.ash
* L8 quest heavily refactored.
* added lots of commends for documentation
* auto_ninjasnowmanassassin should be a boolean. it is used for heavy rains path to track if we are done summoning snowman assassins.
* auto_L8_ninjaAssassinFail used to track inability to fight snowmen assassins.
** if beaten up by a ninja snowman assassin set it
** we need to make this predictive as well in future PR
* auto_L8_extremeInstead used to track not wanting to adventure in the ninja lair
** need a 2nd variable because we might be able to fight them using copiers. We might be unable to encounter them in the lair due to +combat being too low
* boolean L8_trapperSlope() created. it is used to specifically handle the 2nd stage of the L8 quest which is climbing the slope.
** calls special handling for …
=> L8 refactored

.github/workflows/ci.yml, .gitignore, RELEASE/scripts/autoscend.ash
This pull requests automatically fetches the correct version of the kolmafia artifact from Jenkins. It grabs the necessary SVN revision from `RELEASE/scripts/autoscend.ash`, then uses the Jenkins API to find the build number corresponding to the SVN revision.
This ensures that:
* the version autoscend needs always exists on the kolmafia build server
* continuous integration and the script itself are never mismatched
Save the script as script.sh in the git root, and ensure that you have jq installed (which github does on its ubuntu runners)
Then run `bash script.sh` and watch as `.github/kolmafia.jar` is downloaded.
```bash
set -o pipefail
export MAFIA_VERSION=$(head -n1 RELEASE/scripts/autoscend.ash | grep -o '[0-9]\+')
if [[ -z "$MAFIA_VERSION" ]]; then
echo "Couldn't determine required …
```
=> ci: automatically fetch correct mafia artifact

RELEASE/scripts/autoscend/combat/auto_combat.ash
These stagger and devel, and cost 0 mp, so there's no reason to not use these in combat when we can. Kolmafia r20494 supports robo-handcuffs.
I ran this for about 50 adventures at the peak. Example fight:
```
[478] Twin Peak
Encounter: the Big Wheelin' Twins
Round 0: jonchang wins initiative!
[INFO] - auto_combatHandler: 0
Round 1: jonchang tries to steal an item!
Round 2: jonchang casts DETECT WEAKNESS!
Round 3: Big Wheelin' Twins drops 12 attack power.
Round 3: Big Wheelin' Twins drops 11 defense.
Round 3: jonchang casts DEPLOY ROBO-HANDCUFFS!
Round 4: Big Wheelin' Twins drops 20 attack power.
Round 4: jonchang attacks!
Round 5: Big Wheelin' Twins takes 87 damage.
Round 5: jonchang attacks!
Round 6: Big Wheelin' Twins takes 90 damage.
Round 6: jonchang wins the fight!
You gain 58 Meat …
```
=> ccs: use retrospecs and retrocape delevels

RELEASE/scripts/autoscend/auto_util.ash
Adds checks to utils to properly use retrocape yellow rays. This needs mafia r20494.
Ran it while waiting for yellow ray debuff to wear off, then checked that mafia equipped the retrocape and set it to the proper configuration. Then watched as it disintegrated an enemy.
```
[INFO] - Starting preadventure script...
[INFO] - Trying to provide 25 negative combat rate, with equipment
Maximizer: 5item,meat,0.5initiative,0.1da 1000max,dr,0.5all res,1.5mainstat,mox,-fumble,0.4hp,0.2mp 1000max,3mp regen,1.5weapon damage,-0.75weapon damage percent,1.5elemental damage,2familiar weight,10exp,5Moxie experience percent,-200combat 25max,effective
Maximizing...
32 combinations checked, best score 2,800.95
[INFO] - I think we're good to go to apply The Sonata of Sneakiness
[INFO] - Adjusting to have YR …
```
=> util: support retrocape yellow ray

BUILD/familiars/drop.dat, BUILD/familiars/item.dat, BUILD/monsters/sniff.dat, BUILD/monsters/yellowray.dat, RELEASE/data/autoscend_familiars.txt, RELEASE/data/autoscend_monsters.txt, RELEASE/scripts/autoscend/auto_choice_adv.ash, RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_providers.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/auto_zone.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/combat/auto_combat.ash, RELEASE/scripts/autoscend/iotms/mr2015.ash, RELEASE/scripts/autoscend/iotms/mr2016.ash, RELEASE/scripts/autoscend/iotms/mr2020.ash, RELEASE/scripts/autoscend/quests/level_05.ash, RELEASE/scripts/autoscend/quests/level_07.ash, RELEASE/scripts/autoscend/quests/level_08.ash, RELEASE/scripts/autoscend/quests/level_09.ash, RELEASE/scripts/autoscend/quests/level_10.ash, RELEASE/scripts/autoscend/quests/level_11.ash, RELEASE/scripts/autoscend/quests/level_12.ash, RELEASE/scripts/autoscend/quests/level_13.ash
- Add using map the monsters and camel spit
- add using Cargo pocket for Filthworms to skip the first 2 chambers
- Add using the Slay the Undead skill in the Cyrpt
- add using SGEEA's to remove On the Trail if we're going somewhere we want to olfact a monster
- change provideInit to only switch familiar if we haven't hit the target from equips (saves switching familiars unnecessarily in some situations)
- use vampire cape Wolf skill for extra meat drop against brigands
- bunch of random bug fixes
Fixes #470 #606 #631 #633 #634 
Ran a couple of HC Standard so far. Last one was broken by mafia changes so I want to run one more before I'm happy this is good.
=> Mapping the Monsters, Camel Spitting, a Cargo Pocket Use, Undead Slaying and more!

RELEASE/scripts/autoscend/auto_post_adv.ash, RELEASE/scripts/autoscend/quests/level_10.ash
- only bjorn the El Vibrato Megadrone if you have one
- handle needing the HitS unlocked for Shen for all classes & paths not just Ed.
It runs fine but testing these issues requires either a specific account setup (Bjorn, Grim Brother, no El Vibrato Megadrone) or some manual intervention (have a Star Key without unlocking the HitS, I guess I could play a normal run and pull the chart and enough star key lime pies to make it?)
=> couple of issues reported in discord

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2020.ash, RELEASE/scripts/autoscend/quests/level_07.ash
r20555 and later of mafia made the maximizer fold the retrocape which broke our handling of it for Yellow Rays and Slay the Undead. This fixes it so when we want a specific configuration, we exclude it from the maximizer and manually equip it after configuring it.
Ran day 1 of HC Standard. It's using the YR and cast Slay the Undead in every single Cyrpt combat again now.
=> stop retrocape being reconfigured by maximizer when we want a specific config

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_equipment.ash
Adds autoscend support for the newly added maximizer bonus keyword. This way we can suggest certain items to the maximizer without forcing them.
Specific recommendations atm are:
- Powerful Glove (massive bonus if pixels still needed)
- Mafia thumb ring (moderate bonus for extra adventures, also now pulled if available)
- Mr. Screege's spectacles (small bonus, might as well get extra meat drops)
- Eight Days a Week Pill Keeper (small bonus if blood bubble isn't active, to dodge first hit in combat)
Ran across several ascensions while I just had the mafia changes locally but they hadn't been officially merged yet. Observed gear occasionally, mafia thumb ring was used often but not when we really needed something else. Also no longer forced powerful glove when we needed elemental resistance …
=> Support maximizer bonus keyword

BUILD/settings/any.dat, RELEASE/data/autoscend_settings.txt, RELEASE/scripts/autoscend/quests/optional.ash
This is a very simple change to add a preference to skip guild unlock, for folks who are advanced and just don't need to unlock it for skills or whatever.
Tested in a casual today. Will test again tomorrow before this is merged.
=> Add preference for skipping guild unlock.

RELEASE/scripts/autoscend.ash
* fix aborting for lack of flyering targets when there are still quests remaining.
** I just moved the call on the function L12_lastDitchFlyer() to be called a few functions later. specifically after removing the shen softblock due to lack of things to do, and also after grabbing the digital and star key
Ran into this situation, this branch fixed it
=> fix aborting for lack of flyering targets

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2019.ash, RELEASE/scripts/autoscend/quests/level_02.ash, RELEASE/scripts/autoscend/quests/level_05.ash, RELEASE/scripts/autoscend/quests/level_10.ash, RELEASE/scripts/autoscend/quests/level_11.ash, RELEASE/scripts/autoscend/quests/optional.ash
I've been adding more and more delay zones to `zone_delay()` so we now attempt to burn delay in all the places it helps. However some of those places can be optimised to wait until we have burned the delay before doing whatever we want to do there. This does that.
I've been running this stuff for literally months. Like since before LKS stopped being the current challenge path. I have more on top of this to use non-free Voter ghosts but that requires a lot more effort to be useful (like our war handling not being terrible so you can actually make twice-haunted screwdrivers from all the ghostly ectoplasm you end up with).
=> add delaying for delay burning

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/quests/level_05.ash
L5 quest cleanup and fixes:
* fixed trying to adventure inside cob knob before unlocking it. specifically the function for killing the king and for finding the harem outfit should only be run on step1 and not on step0
* added info about quest progress status and tightened when different functions are allowed to run (to make sure they are only run when they quest is at the correct step)
* switched default pathing in autoscend.ash from calling each individual components of L5 quest to instead calling a function that does the entire quest (function already existed but was unused)
I was running into errors when trying to kill the goblin king before unlocking it and then I switched to this branch and it finished the quest correctly.
=> L5 quest cleanup and fixes:

RELEASE/scripts/autoscend/auto_equipment.ash
Reported in Discord. Sausage Goblins override the Map the Monsters non-combat which can then cause the charge to be used in the wrong zone (which then causes an abort if it's a zone we don't handle mapping monsters in).
Hasn't yet but it's a one line change. Not exactly easy to set up the conditions to test it though either.
=> exclude kramco if mapping monsters

RELEASE/scripts/autoscend/combat/auto_combat_ed.ash, RELEASE/scripts/autoscend/paths/actually_ed_the_undying.ash, RELEASE/scripts/autoscend/quests/level_11.ash
- fix off by one error in shenItemsReturned()
- Ed should use all available banishes not just Curse of Vacation and use the glove to replace.
- Start Shen Copperhead quest as soon as it is available as Ed.
Ran an Ed run. All works now.
=> Some Ed fixes

BUILD/familiars/item.dat, BUILD/familiars/meat.dat, BUILD/familiars/stat.dat, RELEASE/data/autoscend_familiars.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/auto_post_adv.ash, RELEASE/scripts/autoscend/auto_restore.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2020.ash, RELEASE/scripts/autoscend/quests/level_09.ash, RELEASE/scripts/autoscend/quests/level_12.ash
- add the 3 Crimbo Ghosts to familiars
- add handling to buy the Commerce ghost item from the mall so we get the stats in the next combat we win with it (25 * current level substats is better than a Volleyball will give).
- update min mafia version to fix issues with Crimbo Cafe consumables that were renamed causing consumption to break.
- exclude miniature crystal ball from being equipped as it overrides astral pet sweater and other useful familiar equips (e.g. dromedary drinking helmet)
- add Crimbo 2020 skill book consumables to MP burning summons list
- make adjustForSniffingIfPossible actually make sure we have enough MP to cast Olfaction if we're about to go somewhere we want to use Olfaction
- don't use Map the Monsters in Twin Peak until we've passed the intro adventure
- update …
=> Box o' ghosts support and a handful of other bugfixes

RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/iotms/mr2019.ash
Just removing the backup and restore of logPreferenceChange around all the calls to maximize.
I added these to cut down on the session log spam but the restore is failing and making it way more difficult to diagnose anything.
=> remove maximize anti-spam measures

BUILD/settings/any.dat, RELEASE/data/autoscend_familiars.txt, RELEASE/data/autoscend_settings.txt
auto_skipUnlockGuild setting had space instead of tab which resulted in a broken config line in the GUI for that specific setting
copied altered files to autoscend and then rerun the GUI, confirming that this fixed the issue
=> fix error in datafile for config page

RELEASE/scripts/autoscend/auto_consume.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/iotms/mr2020.ash, RELEASE/scripts/autoscend/paths/actually_ed_the_undying.ash, RELEASE/scripts/autoscend/quests/level_08.ash
Fixes for issues raised by users in Discord (or adding logging to help debug an issue).
- Add some logging to why Ed wants to go shopping.
- Ed can eat and drink at level 11 even with spleen still to fill.
- Exclude the Haunted Gallery Knight from Saber YR (breaks for some reason, might be mafia not handling choice -> fight -> choice but I CBA debugging it and TBH it's a waste of a Saber use since if you have the saber, you don't need the serpentine sword for the ML once you lose Ed's Staff at level 11).
- Fix for Commerce Ghost items with commas breaking `buy from mall` cli command.
I've only manually tested the stripping of commas on the CLI by setting the commerceGhostItem property to "Notes from the Elfpocalypse, Chapter IV" and calling the auto_buyCrimboCommerceMallItem() function as …
=> Some Ed fixes/debugging info and a fix for Commerce Ghost item buying

RELEASE/scripts/autoscend/iotms/mr2020.ash
bug fix for a bad check in and merge earlier.
=> move a bracket so the item we're buying for the crimbo ghost is correctly converted to item id

BUILD/monsters/sniff.dat, RELEASE/data/autoscend_monsters.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_providers.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2021.ash, RELEASE/scripts/autoscend/quests/level_09.ash
- add Feeling Lonely to providePlusNonCombat
- add Feeling Peaceful to provideResistances
- add Feeling Excited to provideStats
- add Feel Hatred to Banishers
- add Feel Envy to Yellow Rays
Also 3 minor bug fixes.
- fix for BHY to not waste turns in Oil Peak (reported in Discord).
- fix for wasting SGEEAs in the Hidden City every turn.
- when burning delay, give the Spooky Forest priority when delay is equal with the current lowest delay zone since we want it unlocked for the SR.
Ran Normal Standard Pastamancer and Sauceror runs with these changes. Uses all the skills when expected.
=> Add support for some of the Emotion Chip skills

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/paths/actually_ed_the_undying.ash, RELEASE/scripts/autoscend/paths/community_service.ash, RELEASE/scripts/autoscend/quests/level_01.ash
refactored toot oriole quest
* toot quest will now recover if for some reason failed to initialize on day 1
* will be done in all paths (for some paths we just assumed it would be done via a 3rd party)
* more error checking and reporting
* has its own function now. also moved tootGetMeat() to level_01.ash
* make use of quest tracking correction option (via refresh quests) added in r20655
tested in ed, greygoo, and standard
using both ash calls and running autoscend
=> refactored toot oriole quest

RELEASE/scripts/autoscend/paths/actually_ed_the_undying.ash, RELEASE/scripts/autoscend/quests/level_11.ash
- check if we've finished the L11 quest as Ed when we return any part of his staff
- add doing manor first and second floors to Ed's routing so hopefully it opens the billiards room before losing Ed's Staff at level 11.
Validates. can't really test it fixes the issue(s) reported in Discord without running it on a blinged out account.
=> more Actually Ed fixes due to feedback from Beldur

.github/workflows/ci.yml, RELEASE/scripts/autoscend.ash
a few months ago jenkins had to be rebuilt. this resulted in some changes to it which broke our ci automatic verification before merging a commit is allowed. this PR fixes it
since I am fixing github checks before merger is allowed, then testing is done via github
look at the `Checks` tab above
=> ci fixes for jenkins changes

RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/paths/kingdom_of_exploathing.ash
* prevent infinite loop in softcore exploathing. when trying to get ornate dowsing rod via grimstone mask. as the zone is not reachable
* fix yellow ray. preparing for yellow ray in softcore exploathing would give constant errors as it would repeatedly try to buy viral video for 20 bacon (from infinite bacon machine) every loop and fail because bacon store does not work in exploathing
grimstone mask test:
reached infinite loop spot. used
`set auto_grimstoneOrnateDowsingRod = false`
and it stopped giving me that infinite loop
bacon test: just ran the code and it stopped failing to buy viral video every loop.
=> prevent infinite loop in softcore exploathing

RELEASE/scripts/autoscend/quests/level_11.ash
Fixed some issues with paths where off-hand equipment are banned. (boris, way of surprising fist, pokefam)
* L11 scavenger haunt fix (alternate fulminate).
** do not assume success after adventuring in a zone. Fixes an infinite loop which was caused by the next bug.
** fix mafia failing to adv in 3rd floor zones. mafia thinks I must first talk to lady spookyraven and start quest questM17Babies before we can autoadventure there.
* machete logic fix for L11 quest in offhand restricted paths
** our machete code was trying to account for off-hand restricted paths, but was accounting for them incorrectly.
3rd floor unlocking code tested on HC boris account with 0 iotms and 0 perms
machete code tested on account with all the skills and lots of perms. I was stuck at the start where autoscend …
=> Offhand restricted path fixes

RELEASE/scripts/autoscend/paths/kingdom_of_exploathing.ash
fix infinite loop in exploathing for people with grimstone golem
addresses one of the subissues in #664
I do not own a grimstone golem so I can not test it. I tested the very similar fix for ornate dowsing rod (which, unlike this issue, can affect people without a grimstone golem).
it is just a one line setting change though so it should be fine.
=> fix infinite loop in exploathing for people with grimstone golem

RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash
* forceEquipSword check auto_can_equip() instead of can_equip()
* boolean isArmoryAndLeggeryStoreAvailable() created
* fix auto_forceEquipSword() for paths where you cannot just buy a sword in armory and leggery
tried it in koe where it was erroring. fixed by this code
=> retrocape fix for paths where armory and leggery is unavailable

BUILD/settings_extra/post.dat, RELEASE/data/autoscend_settings_extra.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_zone.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/paths/community_service.ash, RELEASE/scripts/autoscend/paths/the_source.ash, RELEASE/scripts/autoscend/quests/optional.ash
optional quests:
* comments for galaktik quest
* boolean finishArmorySideQuest() was spunoff from boolean LX_armorySideQuest()
* make sure we have check for the meatsmith before finishing that quest
* add extra post setting auto_doMeatsmith indicating we should do the meatsmith quest this ascension. false by default
* boolean LX_meatsmithSubQuest(). will start and finish quest. if auto_doMeatsmith is true will also do the quest
* galaktik unavailable in koe
* startGalaktikSubQuest() url cleanup
* do not assume success when using $item[Map to a Hidden Booze Cache]
* finishArmorySideQuest() do not assume success
* startGalaktikSubQuest() do not assume success
* boolean startMeatsmithSubQuest() fixes
** fix infinite loop in koe
** cleaned up url
** do not assume success (avoids infinite …
=> optional quests fixes

RELEASE/scripts/autoscend/iotms/mr2016.ash
LX_ghostBusting() refactor:
* remove redundant checks for whether you possess the proton pack
* use auto_can_equip instead of can_equip
* (goal == none) moved from wrapping around the entire function to instead just be an initial check on its own at the front. lots of whitespace changed to account for this change
* remove vestigial choiceAdventure1061 setting. already handled in auto_choice_adv.ash
* removed vestigial turning in of finished armorySubQuest. it has its own separate handling
* remove vestigial turning in of doc galaktik quest. it has its own function and handling elsewhere
* remove unnecessary temp string for visit_url
* remove vestigial choiceAdventure1060 handling
* cleanup protonic accelerator pack equipping
* reorganize goal and quest progress specific abandonment to …
=> LX_ghostBusting() refactor

RELEASE/scripts/autoscend/auto_pre_adv.ash
* [The Tunnel of L.O.V.E.] is actually allowed while overdrunk. so do not abort during pre_adv when trying to do so.
* pre_adv report to user the target location when aborting due to being overdrunk to help debug
dropped standard while overdrunk. originally it aborted doBedtime(). with this code it did not abort and instead started the tunnel of love and killed the first enemy inside.
although mafia did lose track of where it was halfway into the tunnel. requiring manual finishing of the tunnel. still an improvement compared to aborting before starting. and should be able to finish it if mafia fixes the issue with tracking location while overdrunk.
=> [The Tunnel of L.O.V.E.] is actually allowed while overdrunk

RELEASE/scripts/autoscend/paths/actually_ed_the_undying.ash, RELEASE/scripts/autoscend/quests/level_any.ash
* ed catch island unlock failure. which is a critical issue with pathing ed that can easily turn a 3 day run into a 10 day run if not resolved in a timely manner.
this should not really happen. I have only seen it happen when it failed to initialize due to some mafia issue. or because the user tried to play a few turns before running autoscend.
tested it on a broken run. this caught the issue and alerted me to get more meat. which allowed the run to recover
=> ed catch island unlock failure.

RELEASE/scripts/autoscend/quests/level_any.ash
* fix infinite loop in bees hate you when trying to use gnollish toolbox to make bitchin' meatcar
* it is impossible to make a meatcar in bees hate you path if your sign is not a knollsign. with the infinite loop fixed above this will in turn just waste adventures achieving nothing. now it will instead use the alternative unlock method
I was stuck at said infinite loop. until I used this code
=> fix infinite loop in bees hate you

RELEASE/scripts/autoscend/auto_choice_adv.ash
choice adventure 878 One Ornate Nightstand (The Haunted Bedroom). if your meat is too low or if your primestat is not myst, then you should prefer to take 500 meat instead of myst XP
tested in aftercore by using a modified autoscend.ash set to autoAdv in haunted bedroom instead of quitting.
=> choice adventure 878

BUILD/settings/any.dat, RELEASE/data/autoscend_settings.txt, RELEASE/scripts/autoscend/auto_bedtime.ash, RELEASE/scripts/autoscend/auto_consume.ash, RELEASE/scripts/autoscend/autoscend_header.ash
add the ability to automatically consume nightcap. It will not drink nightcap if you have free fights remaining (in case you disabled automatic free fights fighting).
if you do not want autoscend to drink nightcap you can disable it via the GUI. the setting is called
auto_skipNightcap
and if set to true will prevent nightcap drinking
ash calls
4 standard HC runs with disco bandit. and 1 with accordion thief
HC boris run
HC ed
SC exploathing (to test switching to stooper and back)
=> automatic nightcap drinking

RELEASE/scripts/autoscend/iotms/mr2016.ash
kill ghosts if protonic pack is unavailable. which requires either:
1. a hypothetical future path that blocks back slot
2. using almost-dead walkie talkie to get a ghost without owning the IOTM.
walkie talkie is a very cheap item to get in the mall. as they are common drops from the proton pack and not that popular.
however almost-dead walkie talkie is not tracked by mafia correctly. when used the tracking does not update.
as such you need to perform a `refresh quests` command after using the walkie talkie.
autoscend automatically performs a single `refresh all` when it starts. so if a user used a walkie talkie and then ran autoscend then it will work
BIG run with all perms and most IOTMs. successfully busted ghosts
can't really test walkie talkie yet until mafia fixes its tracking of …
=> kill ghosts if proton pack unavailable

RELEASE/scripts/autoscend/auto_consume.ash
as it currently causes an abort for trying to call loadConsumables() in dark gyffte
validation
=> disable auto nightcap for vampyres

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/paths/bees_hate_you.ash
* boolean bhy_is_item_valid(item it) created and used. equipment is valid even if it has a B in the name, you just take backlash damage. there are also some items which are explicit exceptions.
* autosellCrap() refactoring:
** do not autosell stuff at all in casual unless you have less than 20k meat
** use wallets 10 at a time instead of one per loop
** more aggressive selling of meatstack and dense meatstack. no need to keep some in reserve as you can just make them at no meat loss from your meat. however will still only sell 10 per loop just in case the user is doing something weird with them
** autosell spare elegant nightsticks. keep 2 and sell the rest
** fix trying and failing to use forbidden wallets in bees hate you. (they have B in the name. only matters in postronin or if …
=> bees hate you item validation & autosellCrap() refactoring

RELEASE/scripts/autoscend/auto_choice_adv.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/paths/kingdom_of_exploathing.ash, RELEASE/scripts/autoscend/quests/level_12.ash
kingdom of exploathing battlefield fixes
* fix failing to process the noncombat where you murder enemies with food. moved it to new method
* fixed potential infinite loop on quest turnin for casual (in case you drop or break ronin)
* fixed failing to buy space chowder. thus leaving you stuck at the choice advance with nothing to throw. wasting the choice adventure and significantly slowing you down.
* fixed not fighting the final boss of the frat-hippy war
* special handling for turning in the quest and verifying it worked.
* refactored code heavily. creating functions:
** int koe_rmi_count();
** item koe_L12FoodSelect();
** void koe_RationingOutDestruction();
** boolean L12_koe_clearBattlefield();
** boolean L12_koe_finalizeWar();
Fixes #683
note: there is heavy whitespace changes here. …
=> exploathing battlefield fixes

RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/paths/kingdom_of_exploathing.ash, RELEASE/scripts/autoscend/quests/level_13.ash
includes PR#697 which should be merged and then rebased before this is merged
fix wand of nagamar in kingdom of exploathing path:
* boolean koe_acquire_rmi(int target)
* boolean L13_koe_towerNSNagamar() spunoff from L13_towerNSNagamar() and had its code refactored
* fix repeatedly dying to sorceress due to not having wand in koe. an intermittent problem.
* prefer to to pull WA and ND in softcore koe rather than spending 30k meat (or equivalent rmi) on wand of nagamar
* convert meat to rare meat isotopes for the purpose of buying wand of nagamar if needed
tested in a SC exploathing run with all perms and most IOTMs
=> exploathing wand fix

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_familiar.ash, RELEASE/scripts/autoscend/autoscend_header.ash
* pet coral familiar does nothing. added it to doNotBuffFamiliar100Run()
* clarified some comments
* will now automatically hatch common familiars as they drop for you. including quest items that can be hatched into familiars
** boolean hatchFamiliar(familiar adult)
** void hatchList(). hatches a list of common familiars
ash calls
=> familiar hatching

RELEASE/scripts/autoscend.ash
This is a tiny fix to check the auto_skipNuns property before getting the inhaler, hopefully preventing a semi-rare from being wasted if set to true.
I've never really used github, so I figured I'd try to submit a pull request for something very minor to get a handle on things. Any advice at all is appreciated.
This hasn't been tested yet, but the plan is to give it a go on my next ascension.
=> Semi-rare Handling - Inhaler

RELEASE/scripts/autoscend/auto_consume.ash, RELEASE/scripts/autoscend/auto_familiar.ash, RELEASE/scripts/autoscend/iotms/mr2021.ash
* fix for glover crashing when it tries to hatch mosquito larvae. note that because the hatchling is a quest item, it disappears after the failed use. unlike normal hatchlings which do not. as such this is not a persistent issue. it aborts once during the run and then you can run autoscend again and have it complete the run. still it is better to fix it
* glover fix for emotion chip combat skills
* fix mosquito larva hatching prematurely. only try to hatch this after the quest is finished. first copy is given to concil which returns it to you if you need to hatch it
* workaround for mafia bug of using create() function in g-lovers path to create clip art tome items 
https://kolmafia.us/threads/g-lovers-clip-art-create-function-failure.26007/
day 1 & 2 of glover softcore run
=> glover fixes. crashing due to mosquito larvae & emotion chip & more

RELEASE/scripts/autoscend/iotms/mr2020.ash
* fix infinite loop during auto_burnPowerfulGloveCharges() if the skill Triple Size was invalid
* auto_burnPowerfulGloveCharges() fix doing 20 cycles of equip glove, use skill, unequip glove. instead it will now equip it once and then cast all 20 without further equipping/unequipping
infinite loop was tested in glover where Triple Size is invalid by using ash to import autoscend and call doBedtime()
=> powerful glove bedtime fixes

RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/paths/avatar_of_boris.ash
* fix boris sometimes going unarmed
* void borisTrustyCheck() created and used
* fix maximizer string for non myst classes. we want +weapon damage percent not -weapon damage percent for a non myst class.
** while more robust, this is not a 100% reliable fix for the possibility of maximizer deciding we should be unarmed. but it will fix it most of the time.
* fix boolean simMaximizeWith(string add)
sometimes changing auto_maximize_current during simulation. for example if the "add" value already existed it will end up being removed during the add, simulate, remove cycle.
ash calls
played in boris run. it fixed him going unarmed
played in glover with all perms and lots of iotms.
=> default maximizer weapon fixes

RELEASE/scripts/autoscend/iotms/mr2017.ash
fix infinite loop in kgbWasteClicks() when we are unable to find any valid buff to spend our clicks on
this usually happens if we used an external script to use the kgb.
this PR solves the infinite loop by detecting it and breaking the while function. It does not add special handling to spend your remaining clicks in such a scenario. That should be done in a future PR
end of day. was constantly getting the inf loop. tries with the fixed code and it did not.
=> KGB fix infinite loop in bedtime if we can not find any buffs

RELEASE/scripts/autoscend/auto_consume.ash
fix auto_skipNightcap setting not working
tested in standard hc accordion thief.
=> fix auto_skipNightcap setting

RELEASE/scripts/autoscend/quests/level_11.ash
The script waits until at least 8 drunk before attempting to play pool. This is bad if your liver is less than that. This update makes it happy to play pool as long as you're at max liver, even at less than 8.
Please include a summary of the change. Pull requests should generally be against the [beta branch](https://github.com/Loathing-Associates-Scripting-Society/autoscend/tree/beta) which will eventually be merged into master once beta changes are sufficiently vetted.
Run through 2 Ed ascension with the new version, and Spookyraven properly unlocks on day1, rather than waiting until the end …
=> don't insist on inebriety > 8 for pool if our liver is full at less than that

RELEASE/scripts/autoscend/quests/level_09.ash
Call LX_loggingHatchet() in L9_chasmBuild()
Frankly, it hasn't yet.
=> get the logging hatchet before starting to build the bridge

RELEASE/scripts/autoscend.ash
Green rockets are no longer sold on Dependence Day, so there's no point in checking to see if it is Dependence Day or trying to acquire a green rocket if it is. I'm not sure on how content that has been phased out of the game is handled from the perspective of autoscend, so I didn't mess with the dependenceDayClover() function in level_any.ash.
I ran autoscend after incorporating this change and didn't run into any issues.
=> Stopping calling dependenceDayClover()

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/combat/auto_combat_ed.ash, RELEASE/scripts/autoscend/paths/actually_ed_the_undying.ash, RELEASE/scripts/autoscend/quests/level_any.ash
General:
- remove the dependence day clovers function and calls
- set maximizerMRUSize to 0 to remove all the maximizer spam 🎉
Actually Ed:
- add using Slay the Dead for Ed same as non-Ed combat handling (this really needs refactored but 🤷)
- when UNDYING in combat, send BALLS macro with repeat rather than CCS commands repeatedly to reduce server hits
- add an abort once the Macguffin is found in the he Secret Council Warehouse so Ed works same as all other paths which have a class choice.
- increase the meat amount for buying a Seal Tooth, it was too low and could lead to not having enough meat to make the dingy dinghy if the Hippy Camp is needed for Ka farming
- first attempt at a workaround for the KoL servant bug (if mafia gets a workaround for this we can remove it)
Ran one HC Ed …
=> some ed stuff and removing dependence day clovers

RELEASE/scripts/autoscend/iotms/mr2017.ash
Adds a "Can Change to familiar" check to mumming trunk logic. CanChangeToFamiliar already checks if we have a familiar, so having both would be redundant.
Not Tested
=> Alter Mumming Trunk logic regarding CanChangetoFamiliar

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_consume.ash, RELEASE/scripts/autoscend/auto_familiar.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2019.ash, RELEASE/scripts/autoscend/iotms/mr2021.ash, RELEASE/scripts/autoscend/paths/quantum_terrarium.ash
- attempt to handle not overdrinking with Stooper in Quantum Terrarium path
- enable backup camera reverser if not enabled
- some as yet unused functions for backup camera and QT path support and some tidying up of earlier merges.
Ran 2 Normal QT's, one with IotMs & one without. Fortuitously the one with IotMs got the Stooper as it was on full organs & running out of adventures. It stopped on 2 advs with 14/15 liver available so I can say it's been tested now.
=> Some QT path handling stuff

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/paths/quantum_terrarium.ash
Adding a function to check if a familiar is available to be swapped to in QT and for designating a swap after checking if the familiar is available.
Both functions were tested in mafia. Due to path limitations, I was only able to test forcing a few swaps.
Also added a settings initialization for QT, which currently just sets auto_skipNuns to true since there's currently no handling to swap to a leprechaun type familiar at Nuns - this prevents getting inhaler for no reason and prevents potentially starting nuns and losing a leprechaun midway through.
=> Adding Familiar Swapping functionality for QT

RELEASE/scripts/autoscend/quests/level_any.ash
Presently, if we have the scrip available, we will attempt to make a dinghy even if we already have island access. This change makes us only make a dinghy if mafia thinks we have no island access.
Has been run with skeletal skiff already pulled, did not attempt to make a dinghy
- [NA] I have commented my code, particularly in hard-to-understand areas.
=> Only attempt to make dinghy if we have no other access

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/combat/auto_combat.ash
As title.
Also ix the things @Phillammon said he was going to fix for DB and AT (untested)
Ran Normal QT as Sauceror on my no IotMs account from start to finish while testing the task_order branch. It ran out of MP a lot  less than it used to since it generates more MP than it ever uses in combat now which means it dies a lot less since it has MP to adequately buff itself.
DB and AT changes are untested as yet but they're fixing what looks like an oversight or copy/paste issues. They may also die less in combat now too.
=> remove the minimum mp check from using Weaksauce as Sauceror as it's MP postive almost all the time

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_choice_adv.ash
I'm adding some barebones handling for the mini-adventurer to prevent the need for manual intervention in QT, also removing the warning generated by having a poolSharkCount that falls outside the expected range, this warning serves no purpose.
Plain and simple, this hasn't been tested. The nature of QT means my opportunities to test familiar-related stuff is limited. Please, please, look carefully over my choice adventure logic, it's the first choice adventure I've written and it is untested.
=> Mini-Adventurer handling and poolSharkCount warning removal

RELEASE/scripts/autoscend/auto_consume.ash
fixes mafia halting our nightcap drinking to popup a confirmation for the user to click through
4 accounts doing greygoo.
=> fix popup when trying to overdrink nightcap

RELEASE/scripts/autoscend/paths/actually_ed_the_undying.ash
Autoscend has been stopping at level 13 recently. Reported by multiple users in the autoscend discord channel. From investigating on my multi, I believe this may be due either Ed council text not stacking, or where the character has not got to level 13 by the time they have completed the last on-lvl-13 quest. This fixes those issues by moving a call to visit the council within the structure of  ` L13_ed_towerHandler()` to before it checks the Internal Quest Status
Not yet tested but my no-iotm multi has just started a new Edscension today so can be tested via them in a few days if needed.
=> Fix Attempt of Ed pausing at Lvl 13

RELEASE/scripts/autoscend/quests/level_07.ash
Adding workaround to fixing evil eye tracking
Please include a summary of the change. Pull requests should generally be against the [beta branch](https://github.com/Loathing-Associates-Scripting-Society/autoscend/tree/beta) which will eventually be merged into master once beta changes are sufficiently vetted.
This was reported on the discord as having happened multiple times
It hasn't and I'm not in position to do a run.
=> Adding workaround to current mafia evil eye bug

RELEASE/scripts/autoscend/auto_pre_adv.ash
* auto_pre_adv.ash should perform an auto_interruptCheck() check to properly abort before spending the adventure. this also fixes some adventuring without maximizing gear properly
in quantum terrarium run with mini hipster while trying to do the steel organ quest tested the fixed pre_adv interrupt and it now works correctly and does a proper shutdown before spending the adv when pre_adv fails
=> fix auto_pre_adv.ash interrupt

RELEASE/scripts/autoscend/iotms/mr2020.ash, RELEASE/scripts/autoscend/quests/level_09.ash
- fix Cargo Shorts monster handling
- use Cargo Shorts for a Smut Orc Pervert when we start building a bridge.
Ran 2 Normal QT Sauceror runs back to back. Seems fine.
```
Inspecting Cargo Cultist Shorts
picking pocket 666
Preference _cargoPocketEmptied changed from false to true
Preference cargoPocketsEmptied changed from  to 666
Preference lastAdventure changed from Camp Logging Camp to None
Preference nextAdventure changed from Noob Cave to None
[99] Cargo Cultist Shorts
Preference lastEncounter changed from Axes of Evil to smut orc pervert
Encounter: smut orc pervert
Preference _lastCombatStarted changed from 20210601000609 to 20210601000628
Round 0: Player Two wins initiative!
<snip>
Round 5: Player Two wins the fight!
After Battle: You gain 50 Mana Points
After Battle: You pause for …
```
=> fix Cargo Shorts monster handling and fight a Smut Orc Pervert

RELEASE/scripts/autoscend/auto_bedtime.ash, RELEASE/scripts/autoscend/auto_consume.ash, RELEASE/scripts/autoscend/autoscend_header.ash
* boolean stillReachable() created = stills_available() insufficient. it returns 0 if your class can not unlock still and 10 if your class can unlock it but did not.
* boolean distill(item target) created = use Nash Crosby's Still to create target
* item still_targetToOrigin(item target) created = Nash Crosby's Still can convert Origin item into Target item. This function takes a target and tells us what origin it needs.
* void bedtime_still() created = during bedtime use up all remaining uses of Nash Crosby's Still. warn if fail to do so
tested during bedtime with my main account. it crafted 4 drinks for me
=> Nash Crosby's Still

RELEASE/scripts/autoscend/quests/level_11.ash
The hidden bowling alley map the master check would map the monster and then check to see if we had any bowling balls in inventory.  This caused an issue where we would map, adventure in the bowling alley and get Life is Like a Cherry of Bowls, and then adventure elsewhere and throw an error in cartographyChoiceHandler.
I re-ran autoscend with the fix, however I will need to ascend again to potentially test this fix.  It is a pretty minor code change.  Here's a session log showing the original bug.
[bob_sanders_20210603 copy.txt](https://github.com/Loathing-Associates-Scripting-Society/autoscend/files/6595010/bob_sanders_20210603.copy.txt)
=> L11 Hidden Bowling Alley Map the Monsters Issue with Bowling Balls

RELEASE/scripts/autoscend/auto_consume.ash
Presently, if we do not have skipNightcap set to true, we drink a nightcap automatically. This behaviour has been changed to prevent nightcapping if limitConsume is set as well.
Local casual testing
=> Prevent nightcap consumption if limitConsume is set,

RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2019.ash, RELEASE/scripts/autoscend/paths/quantum_terrarium.ash, RELEASE/scripts/autoscend/quests/level_13.ash
A couple little additions to level_13.ash: 
- Added Shorter-Order Cook and Mu to the list of Wall of Skin familiars.
- Added checks to see if the current QT familiar was a Wall of Skin familiar.
- Added handling for bird skills before Wall of Meat.
Additionally, made sure to try to finish the Untinkerer quest before swapping from a knoll sign.
I haven't tested these changes yet, but they're pretty simple, self-explanatory changes. I will update the PR description after I have an opportunity to test the changes.
=> Level_13.ash adjustments

BUILD/familiars/boss.dat, RELEASE/data/autoscend_familiars.txt, RELEASE/scripts/autoscend/auto_choice_adv.ash, RELEASE/scripts/autoscend/auto_familiar.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2012.ash
- Added Shorty to the list of boss-applicable familiars.
- Added handling for the Reagnimated Gnome.
As of yet, untested. Pretty much harmless if it doesn't work though.
=> Reagnimated Gnome handling, and Shorter-Order Cook boss familiar tag

RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/auto_util.ash
I figured out what the problem was with the previous attempt at implementing this. If the user had `logPreferenceChange` set to false when they started the script, we back that up and set it to true.
Subsequently, if we call `backupSetting()` again on the same property to set it to false, it doesn't resave it because it's already been saved. So when we then call `restoreSetting()` to restore it to true, it's actually restoring it to false from the original user's setting. So it gets stuck as false from that point onwards (as we only force it to true when starting the script).
Hence handling it "manually" in these changes.
Started day 3 of QT Normal on my IotM-less test account. Seems fine. You do get a bunch of stuff like this
```
[INFO] - Turn(462): Starting with 161 left and 16 pulls …
```
=> silence the maximizerMRUList and auto_maximize_current pref setting

RELEASE/scripts/autoscend/auto_consume.ash
dark gyfte fix nightcap recommendation error when it tries to load the consumable list
validates. copy pasted from the drink function (which has been tested) into the print function
=> dark gyfte fix nightcap recommendation error

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/quests/level_12.ash
Just adding a check before using gardens to make sure we're not trying to use them when standard restrictions would prevent us from being able to do so.
Tested via CLI in QT.
=> checking that gardens aren't blocked by standard restrictions

RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2019.ash
fix [Red-Nosed Snapper] aborting quantum terrairum
by fixing auto_snapperPreAdventure(location loc) to not cause pre_adv to abort if it can not find a desired target
validates
=> fix [Red-Nosed Snapper] aborting quantum terrairum

RELEASE/scripts/autoscend/iotms/mr2021.ash
feelsNostalgicMonster has been renamed lastCopyableMonster in Mafia. Updated reference to it
also fixed `auto_backupUsesLeft` to be correct in You Robot.
=> Update reference to lastCopyableMonster

RELEASE/scripts/autoscend/combat/auto_combat.ash
Update to auto_combat.ash logic regarding when to use Gulp Latte. Corrected logic regarding Dark Gyffte, and added in logic regarding Zombie Slayer (futureproofing should said path ever get further support)
Has not yet been tested.
=> Vampyre's Can't use MP, so don't use Gulp Latte

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2021.ash
This adds support to obtain a particular battery, untinkering from larger batteries if necessary and possible, and mimics the code that mafia uses to pick batteries during breakfast to pick batteries each day.
The battery combining is a nightmare to look at, I apologize in advance.
Tested the individual battery crafting functions pretty extensively in the CLI, tested the battery picking function across two days of autoscending QT.
=> Battery Picking and Crafting

README.md, RELEASE/scripts/autoscend/auto_choice_adv.ash, RELEASE/scripts/autoscend/quests/level_10.ash, RELEASE/scripts/autoscend/quests/level_13.ash
We've had report in Discord of choiceadventure preference for EBK noncom not being set when backfarming during the tower. This PR ensures the appropriate preference is set at that point to prevent any issues like this occuring.
Also added in an attempt to pull healing items when at the shadow if we have any pulls left as per #757 
It hasn't.
=> ensure noncom choice is set prior to backfarming a EBK

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/auto_util.ash
- Revert changes from #763 
- Use new logPreferenceChangeFilter function to silence maximizerMRUist, testitudinalTeachings and auto_maximize_current properties
- unequip and shrug stuff that messes with text in game so we don't break mafia tracking.
Haven't yet. It's halloween so my accounts are busy right now. Will test after rollover.
=> Use new logPreferenceChangeFilter function to silence maximizerMRUist, testitudinalTeachings and auto_maximize_current properties

RELEASE/scripts/autoscend.ash
Got the Crimbo P.R.E.S.S.I.E in a QT run. It gave the buff. Next iteration of doTasks script aborted because of no SGEEA to uneffect  Can Haz Cyborger.
Removed and could continue.
=> Can Haz Cyborger isn't freely shruggable

RELEASE/scripts/autoscend/auto_equipment.ash
As per the title.
Ran a bit of autoscend in a path with familiars, saw the bonus added to the maximizer line. Not yet tested in Vampyre or a path without familiars.
=> Give scrapbook a moderate maximizer bonus to encourage scrap generation, when you can generate scrap.

BUILD/settings/any.dat, RELEASE/data/autoscend_settings.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_familiar.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/paths/casual.ash
acquire familiars then hatch them.
familiars acquired in all paths:
* [Lil\' Barrel Mimic]
* [Blood-Faced Volleyball]
familiars acquired in casual and postronin: 
* [Ragamuffin Imp]. only if user opt in.
* [Leprechaun]. may spend a few adventures/stomach space/ten-leaf clovers
* [Gelatinous Cubeling]
* [Levitating Potato]
* [Howling Balloon Monkey]
* [hovering sombrero]
* [barrrnacle]
* [Cocoabo]
* [Oily Woim]
* [Stooper]
* [Cute Meteor]
New functions:
* boolean checkTerrarium()
* void getTerrarium()
* void acquireFamiliars() a function that acquires hatchling of easy to get or cheap familiars and then hatches them.
* void acquireFamiliarsCasual(). get and hatch familiars in casual
* void acquireFamiliarRagamuffinImp()
** auto_hatchRagamuffinImp setting added
* boolean …
=> familiar acquisition

RELEASE/scripts/autoscend/combat/auto_combat_header.ash
Copy comment structure from Autoscend_header with regards to indicating from what files each function has come from.
Only making changes to comments, so should be fine
=> Changing comment structure in auto_combat_header to improve readability

RELEASE/data/autoscend_properties.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_settings.ash, RELEASE/scripts/autoscend/autoscend_header.ash
* fix auto_100familiar setting upgrade being done incorrectly
* sorted settings to appropriate function
* cleanup code
* will now remove the deleted auto_debug setting
* remove upgrading the format of pre/post adv, between battle, and kingliberated settings. we always update those settings when autoscend starts
* void defaultConfig(string prop, string val)
* void auto_settingsFix()
ash calls and checks
=> rename auto_deprecation.ash to auto_settings.ash. cleanup code. improve default config of new settings

RELEASE/scripts/autoscend/auto_consume.ash, RELEASE/scripts/autoscend/autoscend_header.ash
Added a silent flag to autoDrink for night capping.
I ran autoscend in aftercore and confirmed that ode to booze was cast and that the "are you sure..." confirmation box did not appear.
=> Added a silent flag to autoDrink for night capping.

RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/paths/dark_gyffte.ash
Added in functions for checking if we have an Ensorceled Monster & getting the phylum of the Ensorcelled monster. Also amended the current "do we want to cast ensorcel" function to not waste additional casts on goblins if we currently have an ensorcel
tested the internal code for the `bat_ensorcelledMonster` via ash commands in CLI
=> We can now track Ensorcelled Monsters

RELEASE/scripts/autoscend/auto_consume.ash
void auto_drinkNightcap() could have caused an error in quantum terrarium by trying to return your familiar to the pre_stooper familiar. this only happened if crafting your nightcap drink just happened to push you over the line and cause QT to randomly change your familiar
too hard to reproduce and it is a one line fix.
=> prevent bedtime error in QT from familiar change attempt during nightcap

RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/quests/level_12.ash
Adds a couple of effects - candy hearts, a love song, and most notably the car battery from the potted power plant IOTM. These are current used for nuns, nowhere else.
Ran one ascension with my only equipped character, seemed to work.
=> Add car battery and candy to nuns

RELEASE/scripts/autoscend/quests/level_13.ash
We would buff to kill the wall of skin before checking to see if we had a beehive. This could cause unnecessary issues when trying to kill the wall of bones and unnecessarily sank resources. Now the check for a beehive precedes all checks for wall of skin damage sources.
```
> [INFO] - About to start a combat indirectly at Tower Level 1... (1) accesses required.
Preference lastAdventure changed from The Hedge Maze to Tower Level 1
[540] Tower Level 1
Preference lastEncounter changed from Mazel Tov! to wall of skin
Encounter: wall of skin
Preference _lastCombatStarted changed from 20210618051346 to 20210618051415
Round 0: beldur wins initiative!
> [INFO] - autoAdvBypass has encountered a combat! (param: 'auto_combatHandler')
> [INFO] - auto_combatHandler: 0
Preference auto_combatHP changed …
```
=> check for beehive before buffing to kill

RELEASE/scripts/autoscend/paths/actually_ed_the_undying.ash
Reported in discord.
edAcquireHP should return true if we don't need to heal not false.
Hasn't TBH but the one place the return value from `edAcquireHP` is used is in `acquireHP` which is what's returning false and causing the Hidden City not to be completed as Ed.
=> fix issue with Ed failing to do the Hidden City

RELEASE/scripts/autoscend/auto_util.ash
reserve meat for zeppelin ticket (after no priceless diamond obtained) and palindome
has been run, but under few expenses and while plenty of meat was still available
=> reserve meat for zeppelin ticket and palindome

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_adventure.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/paths/pocket_familiars.ash, RELEASE/scripts/autoscend/quests/level_04.ash
Replace all digimon references with pokefam.  This is my first time with scripting or GitHub so apologies if I am screwing something up along the way.  Thanks to Beldur for holding my hand on how to do this, MS for always encouraging me, and all the LASS folks who put up with dumb questions from me.
I replaced all of the digimon code references within a few of the various files to now use pokefam.  I also replaced the outdated non-helpful commentary about other video games.  I also removed Space Jellyfish references as they are out of standard anyway.
I am running autoscend in pocket familiars and it is working fine for these changes (please ignore that there are other, more complicated handling of choice adventures that need to be fixed.  Also mafia or KOL needs to push the familiars …
=> Remove references to Digimon

RELEASE/dependencies.txt
Formerly LASS, now back to Ezandora
Changed dependencies to reference Ezandora Helix Fossil script
Deleted autoscend on a multi and re-installed.
- [ X ] My code follows the style guidelines of this project.
- [ X ] I have performed a self-review of my own code.
- [ X ] I have commented my code, particularly in hard-to-understand areas.
- [ X ] I have based by pull request against the [master branch](https://github.com/Loathing-Associates-Scripting-Society/autoscend/tree/master) or have a good reason not to.
=> Updated Helix Dependency back to Ezandora

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_choice_adv.ash
* fix autoscend wasting adventures powerleveling mainstat when we were in fact short of mox or mys for the frat hippy war outfit and not short on mainstat.
* if we do not have iotm powerleveling locations. then do not abort for spending too many adventures in haunted gallery/haunted bedroom as those two are used for powerleveling when there are no iotm locations.
* use the ghost key in haunted bedroom for primestat if it gives at least 50 XP more than non ghost key choice
* grab [engorged sausages and you] if it actually shows up (rare item. currently 1.3 million in mall). will stop grabbing them if mall price ever drops below 1000 meat (min price is 150 for this item)
* One Simple Nightstand will now grab meat if you are short on meat. previously it always took muscle XP. short of meat …
=> powerlevel fixes & ghost keys & rare book engorged sausages and you

BUILD/monsters/sniff.dat
wait until Green Ops Soldier can appear before preparing to sniff it:
added one property in sniff data
to avoid wasting uneffect when starting battlefield
=> Update Green Ops Soldier sniff.dat

RELEASE/scripts/autoscend/auto_consume.ash, RELEASE/scripts/autoscend/auto_util.ash
* boolean canPull(item it) will now respect autoBuyPriceLimit setting instead of assuming it is set to the default value of 20k
* loadConsumables will now actually check `canPull(it)` before adding an item to the pullable table.
* loadConsumables fixed incorrect custom pullable check for key_lime_pies. it was incorrectly its independent function instead of a sub function of pullable. thus was missing some of the necessary checks and verifications
* loadConsumables will now use autoBuyPriceLimit instead of assuming it is 20k.
** removed the override for key lime pies where they were set at 40k. that override just resulted in failure to do anything as they were above the autoBuyPriceLimit and as such not purchased
was stuck at trying yet failing to mallbuy jerlsberg's key lime pie at 35k …
=> canPull respect custom autoBuyPriceLimit && fix consume code issues with key lime pies

RELEASE/data/autoscend_restoration.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_restore.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2019.ash, RELEASE/scripts/autoscend/paths/casual.ash, RELEASE/scripts/autoscend/quests/level_04.ash
- Detect casual ascensions properly (workaround until mafia adds a function)
- fix auto_forceNextNoncombat to work when the user doesn't have a pillkeeper.
- change restore code to not give skills an MP cost if Sauceror or in Casual/Post-Ronin (fixes using items on hand instead of casting restore skills)
- untangle the spaghetti of using Sonar-In-A-Biscuits in L4 quest.
Waiting for rollover to run another Casual.
=> Casual fixes

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/paths/pocket_familiars.ash
Improves team building and weasels around the non-standard issues with the pocket familiars.  Things are still broken but are now slightly less broken.  Also removes an out-of-standard call to Witchess as it is not needed.
Removes some of the hard codes in the "team building" aspect of the script.  This lets Ezandora's script handle team building based upon your ideal "strongest team" and still offers a spot to level other familiars.  With the existing pocket familiars not currently parsed as "standard" this somehow lets you use them.  It currently only runs at the beginning of the day so next step is putting it in pre_adv.  Baby steps for a guy with no coding experience.
I have been running this on a multi in HC pokefam.  This part works
=> Help Fix Team Building in Pokefam

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_choice_adv.ash, RELEASE/scripts/autoscend/auto_settings.ash, RELEASE/scripts/autoscend/iotms/mr2015.ash, RELEASE/scripts/autoscend/paths/community_service.ash
* fix NC 1115 missing a `break;` resulting in it spilling over to god lobster NC 1310
* NC 1119 moved to auto_choice_adv.ash and fixed to always grab abstractions (previously it sometimes grabbed abstractions and sometimes failed and aborted)
* fixed resolveSixthDMT() function not actually working properly.
validation. for the most part this deletions. also I do not have a machine elf to properly test it with.
=> NC 1119 fixed and migrated to auto_choice_adv.ash & NC 1115 fixed missing break

RELEASE/scripts/autoscend/quests/level_11.ash
don't pull Antique Machete when we have Muculent Machete
loaded the script
=> don't pull Antique Machete when we have Muculent Machete

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_util.ash
Consider yellow rocket from the clan VIP lounge as a yellow ray source, and prioritize it as it is unlimited and has the lowest cooldown.
Fixes # N/A
```
> ash import autoscend; canYellowRay($monster[beanbat])
Putting on Travoltan trousers...
Equipment changed.
Purchasing yellow rocket (1 @ 213)...
You spent 225 Meat
You acquire an item: yellow rocket
Unexpected error, debug log printed.
Purchases complete.
Putting on purpleheart "pants"...
Equipment changed.
Returned: true
> ash import autoscend; yellowRayCombatString($monster[beanbat], false, false)
Returned: item yellow rocket
```
=> Yellow rocket support

RELEASE/scripts/autoscend/auto_post_adv.ash
* cleanup soul food code
* do not try to conserve 25 soulsauce when considering if we should use soul food. that causes issues early in the run when we cannot afford to restore MP and repeatedly go into battle where we run out of MP and kill the enemy in melee, thus failing to get the 50MP from exploding curse of weaksauce.
* buffing init should be done regardless of your HP. and be done before buffing DA
* fix the buffs: ghostly shell, astral shell, reptilian fortitude, springy fusilli, wellberg's dim bulb
**which all had not properly set a min MP value below which we do not want to drop when casting them (as **that would leave us too few MP to actually fight and win combat). this value has been set to 30 mp
* get the durability buffs even if your maxhp is over 100 if you do not have …
=> soul food fix && some buff maintainance

RELEASE/scripts/autoscend/paths/community_service.ash
Only use familiars for hopeful drops in NEP whilst freeturns are available
It hasn't
=> Stop adventuring in NEP until you run out of turns

RELEASE/scripts/autoscend/auto_restore.ash
fix restore code incorrectly storing some float values as int.
for most restorers this is not an issue. but for some it is (for example laugh it off costs 1 MP and heals 1 to 2 HP. so its value is 1.5)
ash. and also ran it in QT
=> fix restore code incorrectly storing float values as int

BUILD/settings/any.dat, BUILD/settings_extra/any.dat, RELEASE/data/autoscend_settings.txt, RELEASE/data/autoscend_settings_extra.txt, RELEASE/scripts/autoscend/auto_restore.ash
instead of always ignoring a failure to restore MP or HP, it should now handle it based on settings (which were added to GUI). Either aborting or continuing as desired by the user. By default we will now abort on failure to restore.
tested in QT softcore
=> restore abort or continue on failure based on setting

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/quests/level_13.ash
Simplify stay in run logic after beating the sorceress, as I was just in a Sneaky Pete run and autoscend automatically broke the prism.
Also precache a bunch of item prices with mall_prices() when a day starts to drastically reduce mall searches when restoring or considering consumables in a softcore run. 
Not yet but this is a pretty simple change.
=> Fix stay in run logic for avatar paths

RELEASE/scripts/autoscend/auto_restore.ash
as title. Should result in not removing Cannelloni Cocoon/Disco Nap/Tongue of the Walrus in Rank 6 optimization any more.
~Hasn't yet (in progress).~ Looks fine in Casual. Should probably run a Standard or QT too just to verify it's fine in-run.
=> don't consider excess HP from healing skills as "wasted".

RELEASE/scripts/autoscend.ash
Add a visit_url to the fireworks shop because apparently implementing a shop as a clan VIP item which has no business being a clan VIP item since there's literally no group interaction is hard or something.
Also update min mafia version to last change which affected the firework shop.
I added this manually to my aftercore "breakfast" script which fixed the issue. Haven't tested it in an actual run and also don't care.
=> Workaround for yet more spaghetti code in KoL.

RELEASE/relay/relay_autoscend.ash, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/combat/auto_combat_default_stage2.ash, RELEASE/scripts/autoscend/combat/auto_combat_default_stage3.ash, RELEASE/scripts/autoscend/combat/auto_combat_default_stage4.ash, RELEASE/scripts/autoscend/combat/auto_combat_default_stage5.ash, RELEASE/scripts/autoscend/combat/auto_combat_header.ash, RELEASE/scripts/autoscend/combat/auto_combat_util.ash, RELEASE/scripts/autoscend/paths/avatar_of_sneaky_pete.ash
- Move multi-round stun handling from step5 to step3 of combat
- Improve Avatar of Sneaky Pete combat
- Improve Avatar of Boris combat
- Always use majorAttack on Groar
- Fix not upgrading Sneaky Pete motorcycle if all skills have been learned
- Peel out can be a banish (unused by autoscend as we don't upgrade the motorcycle that way)
- Peel out is also a free run, use it to run away from monsters we would have banished but can't (we should probably use free runs to burn delay)
- Track free runs and show them on the relay page (currently just peel out)
Two sneaky pete softcore runs.
=> Combat improvements, various Avatar of Sneaky Pete changes

RELEASE/scripts/autoscend/quests/level_11.ash
do hiddenTavernUnlock before looking at the availability of the tavern to force noncombat
try to respect user setting auto_consumeMinAdvPerFill for cursed punch while there is apartment delay, that's when autoscend didn't try cursed punch on its own before because it looked for the tavern before unlocking it
respect user setting auto_limitConsume for cursed punch
count amount of inebriety needed for Thrice-Cursed instead of 3
verify that Cursed Punch can be drunk before doing hiddenTavernUnlock for the apartment
verify that elevatorAction is not already going to happen before using forced noncombat
todo: in_tcrs check quality and size of cursed punch instead of skipping? if that is possible
QT run
=> hidden apartment cursed punch & stench jelly fix

RELEASE/scripts/autoscend/quests/level_any.ash
lockpicks still get pulled if all extra keys get destroyed.
autoscend doesn't wait for keys to start daily dungeon, so this could end up wasting a meat paste or two instead of saving the pull but only when you get bones manually in a no cubeling path.
also avoid warnings that it fails to buy Platinum Yendorian Express Card if you don't have one in storage because you shouldn't try to autobuy that anyway?
only loaded in QT
=> avoid warnings that it fails to buy Platinum Yendorian Express Card

BUILD/settings/pre.dat, BUILD/settings_extra/pre.dat, RELEASE/data/autoscend_settings.txt, RELEASE/data/autoscend_settings_extra.txt, RELEASE/relay/relay_autoscend.ash, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_settings.ash
* added setting auto_doGalaktik_initialize (PRE type setting) which determines the state of auto_doGalaktik (POST type setting) when we initialize an ascension.
this allows you to set whether it should or should not do galaktik as a matter of course. By default it is set to false. Accounts lacking in IOTMs which struggle with meat might want to set it to true in the GUI.
**Note: POST type settings are used only for the current ascension and will be reset when you start a new ascension
**Note: PRE type settings are used only for the purpose of configuring POST type settings on initialization
* renamed auto_alwaysGetSteelOrgan to auto_getSteelOrgan_initialize and clarified its description. this is a pre type setting which gets copied to auto_getSteelOrgan on ascension initialization.
* GUI …
=> auto_doGalaktik_initialize & renamed auto_alwaysGetSteelOrgan & GUI will configure setting defaults first

RELEASE/scripts/autoscend/auto_familiar.ash
check configuration of mini-adventurer for isAttackFamiliar
tested in mafia CLI in QT
=> isAttackFamiliar accuracy improved for [Mini-Adventurer] & [Reagnimated Gnome]

BUILD/monsters/sniff.dat, RELEASE/data/autoscend_monsters.txt
Issue raised in Discord by @HippoKingKoL
- fix SGEEA removing On the Trail for Camel Toe/Skinflute unnecessarily
- same fix for War Hippies in KoE
- clean up some old redundant crap from cc_ascend days.
Hasn't but the changes are a copy of the Bob Racecar/Racecar Bob entries which works as expected.
=> Olfaction/SGEEA fix(es)

RELEASE/scripts/autoscend/quests/level_03.ash
Sloon reported in Discord script aborts when tavern cellar layout is invalid. Looked at code and there is an automatic retry to fix stale data. However there's a bug where the property value isn't refreshed.
Error reported:
gCLI. Forced invalid layout and then confirmed existing code does properly refresh the layout. Just had to add another get_property to refresh the tavern variable.
=> Fix Tavern Cellar Refresh

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/combat/auto_combat.ash, RELEASE/scripts/autoscend/combat/auto_combat_default_stage5.ash
hotfix sauceror MP crash (and subsequent meat crash as it has to keep on buying galaktik consumables to fuel its crashing MP) caused by a function that was trying to get more MP from the curse of weaksauce explosion. We were trying to let mortar deal the killing blow so we get extra MP... to facilitate that we were delaying with salsaball, but accidentally killing the enemy with salsaball and only getting back 2MP. Thus losing lots of MP per combat instead of gaining MP. With the sauceror profligate spending of MP outside of combat it combined into poverty.
Now it will prefer to delay with seal tooth and will check that salsaball does not kill the monster before casting it. Exact calculation is still in the works, but this will estimate things with making sure enemy HP is higher than 15 …
=> hotfix sauceror MP crash due to mortar delay

RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/quests/level_10.ash, RELEASE/scripts/autoscend/quests/level_11.ash
Currently, the L11 shen snake handler attempts to delegate quest zones to the appropriate quest handler, notably Smut Orc Camp and Top Floor of the Castle in the sky. Unfortunately, the first check these handlers perform is whether a soft lock is in place on these zones because we may potentially find a snake there later- which will always be the case if we are in this situation- leading to the delegation failing and us autoadventuring in the snake zone instead, leading to inefficiencies and aborts.
This PR fixes the above issue by releasing the shen soft lock on zones where we are actively looking for the snake, instead of only releasing the lock once the snake for that zone has been found.
Tested in failing case and appears to be functioning in regular ascension. Not yet tested under …
=> Release lock on snake zones once we are actively looking for that zone's snake.

RELEASE/scripts/autoscend/auto_post_adv.ash
those are too expensive and provide a very minor improvement to XP gains. Only maintain them if you have lots of excess meat to burn
sauceror normal QT
=> [Carol of the Thrills] & [Aloysius\' Antiphon of Aptitude] should only be used if rich

RELEASE/scripts/autoscend/auto_consume.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/paths/kolhs.ash
redoing #840
chew spleen items that provide adventures if we do not have something better to chew.
relevant to QT because those old familiars can appear there and can drop those chewables. and they are not standard restricted in QT
normal QT runs with 0 iotms. one chewed 3 Powdered Gold, another account chewed 1 aqua de vida.
that is all they chewed at all, most of their spleen was still empty.
2 more runs did not have anything to chew
=> allow chewing spleen for adventures from familiars

RELEASE/scripts/autoscend/auto_consume.ash, RELEASE/scripts/autoscend/auto_familiar.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2018.ash, RELEASE/scripts/autoscend/quests/level_07.ash
I saw an outdated condition that tries to use a spleen item if Powdered Gold is restricted. Now both that item and Powdered Gold are restricted together except in G lover. so autoscend produces the item but never uses it
I think it was trying to use it only in standard when there were no other uses for spleen. it makes more sense to use the same conditions to produce and use that item
not tested
=> update outdated conditions for nightmare fuel

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/combat/auto_combat.ash, RELEASE/scripts/autoscend/combat/auto_combat_disguises_delimit.ash, RELEASE/scripts/autoscend/combat/auto_combat_header.ash, RELEASE/scripts/autoscend/paths/disguises_delimit.ash
Change all Majora references to Disguises (for disguises delimit).  Made all references "disguises" for consistency
Removed all of the references to "majora" since people did not like them.
I am in a disguises delimit path with no issues.
=> Remove Majora References

RELEASE/scripts/autoscend.ash
If we are currently in the Way of the Surprising Fist challenge path, items should not be autosold as all the acquired meat will be donated to charity. If the player wants to donate to charity, they can do that manually.
Added my section of code with a print() function to confirm that we exited the autosell crap function automatically. Reaffirmed by watching as it acquired a Gathered Meat-Clip and then printed my statement, leaving the meat clip in the inventory. Print statement removed for this PR, but the functionality remains.
=> do not autosell in way of the surprising fist

RELEASE/scripts/autoscend/iotms/mr2017.ash
* for asdon marting feeding when [all-purpose flower] is invalid
* refactored and cleaned up the code for asdon martin consumption of loaf of soda bread. stopping a bunch ofm potential errors
bug reported by bastard0 (#1553305) avayarun#9713 on discord. they are testing this for me
see post below
=> [asdon martin] feeding refactor and fix inf loop when feeding [all-purpose flower] in glover

RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/combat/auto_combat.ash, RELEASE/scripts/autoscend/combat/auto_combat_ed.ash
* expanded pre_adv footer info with class, path, mus, mox, mys, current equipment, turtle blessing, pasta thrall, seal clubber fury, actuallyed servant,  jarlsberg companion.
* added combat info about enemy when initializing combat
ash calls
normal quantum terrarium run
normal ed run
=> provide info on combat initialize and expand pre_adv footer info

RELEASE/scripts/autoscend/iotms/mr2015.ash
as subject. Schedule for NCs after the first one needs verified and added but this will at least fix the issue with wasting advs in the zone on day 2+.
Hasn't.
=> fix for spamming the DMT on day 2+ searching for a NC that won't come for 45 more adventures.

RELEASE/scripts/autoscend/auto_util.ash
check song duration of equipped accordion too instead of only inventory accordions
tested that song duration is still 10 after antique accordion is equipped
=> check song duration of equipped accordion

BUILD/settings/any.dat, RELEASE/data/autoscend_settings.txt, RELEASE/scripts/autoscend/auto_restore.ash, RELEASE/scripts/autoscend/auto_settings.ash
restore code generates exceptional amounts of debug info. limit this via auto_log_level_restore setting that is responsible for extra debug info. Allowing you to use debug level logging without having to deal with the data dumps of restore code
ash calls
QT normal run
=> restore code disable extra debugging

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/paths/wildfire.ash
Built out the wildfire.ash file and added a spot to import it in autoscend and define it in header.
It didn't break anything for me.
=> .ash file and header/autoscend.ash imports

RELEASE/scripts/autoscend/auto_choice_adv.ash
fix ca 879.
choice 4 and 5 were flipped in our handling
Testing ASH scripts is tricky and generally involves you doing multiple runs with a change to see how it performs. If you did any particular tests, or have particular tests you would like to do but cant (e.g. need to test with an expensive item you dont have access to) please mention that here. Relevant Mafia session logs may also be helpful.
=> fix ca 879

RELEASE/scripts/autoscend/auto_choice_adv.ash, RELEASE/scripts/autoscend/auto_util.ash
* do not bother checking mall price of engorged sausages and you if you encounter it. It is rare so we might as well just grab it. Plus the check is not meaningful since we can not actually go to the mall to check at the time. And the historical price will not be meaningful there since it never gets updated for that specific item.
* workaround for mall_price() while in noncombat adv:
initially this PR was fixing stack overflow issue where it hit the server ~700 times in an infinitely nested set of calls before hitting stack overflow.
mafia r20840 fixed this upstream by returning -1 (unless the data was updated today in which case it shows todays cached price).
Still using the same workaround, only now working around the -1 by giving us a more meaningful value in that it will return …
=> auto_mall_price() should return historical_price() if invoked in a choice adventure

BUILD/familiars/item.dat, RELEASE/data/autoscend_familiars.txt
Reported in discord that choctopus wasn't being used when gelatinous cubeling was. We already had choctopus in familiars/regen, but missing in familiars/item. 
None. Don't have fam to test with
=> Added choctopus to fairywhelps in item fams

RELEASE/scripts/autoscend/quests/level_13.ash
Psalm of Pointiness should be removed too when trying to kill wall of bones without boning knife
and Feeling Nervous. that one is not used now but I add it in #875
=> uneffect Psalm of Pointiness for wall of bones

RELEASE/scripts/autoscend/iotms/mr2014.ash
handleBjornify seems like it should return true not false if the requested familiar is already in it
the way handleBjornify is used in autoscend it also looks like it should try 
>if(!autoEquip($slot[back], $item[buddy bjorn])) 
instead of returning false if(equipped_item($slot[back]) != $item[buddy bjorn])
but I don't have buddy bjorn to test
=> handleBjornify if bjorn is requested familiar return true

RELEASE/scripts/autoscend/auto_consume.ash
workaround for https://kolmafia.us/threads/inventory-desync-when-using-create-to-use-the-nash-crosby-still.26323/
as of r20865 distilling using create() command inventory desync which in turn causes errors when trying to use the still.
fixed via `cli_execute("refresh inv");`
during bedtime `void bedtime_still()` was doing
buy 1 soda water
distill it to tonic water
attempt to distill it again to tonic water without buying a replacement soda water and fail.
with this code this no longer happened.
=> hotfix inventory desync when using `boolean distill(item target)`

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_consume.ash
fixed upstream in mafia r20870
https://kolmafia.us/threads/inventory-desync-when-using-create-to-use-the-nash-crosby-still.26323/
ash commands
=> Revert "hotfix inventory desync when using `boolean distill(item target)`"

BUILD/monsters/yellowray.dat, RELEASE/data/autoscend_monsters.txt, RELEASE/scripts/autoscend/quests/level_12.ash
Reported in Discord that manual use of wishes for frat boy spy was needed. My understanding is this is a high value wish so let's do it. 
Purposefully not supporting route of fighting for hippies. Would need to update yellow ray target list. See no reason to improve slower route.
Validates. Don't have genie to test
=> Added wishing for Orcish Frat Boy Spy

RELEASE/scripts/autoscend/auto_consume.ash
Nightcap determination considers only desirability, picking the most desirable drink. Ties are broken by taking the drink that came first in the list. This can result in more expensive drinks being used as nightcaps, when there are equally desirable drinks that are cheaper.
This was discovered when Autoscend started recommending `corpse on the beach` as a nightcap instead of `space wine`. Both items give the same adventures and have the same desirability. However, `corpse on the beach` comes first in the list, so it was picked, despite it costing 18k while space wine costs only 5k. (Before the last holiday, it was excluded since it cost more than 20k)
Modify the algorithm to break ties in desirability by using the mall price.
I ran the modified logic and it recommended `space wine` as a …
=> Break nightcap ties with mall price

RELEASE/scripts/autoscend/quests/level_13.ash
count wall of skin damage instead of sources to fix some errors
L13_towerNSTower thought it needed 2 less damage sources with each Shell blocking skills but these skills don't do 2 damage every round
it counted 13 sources to do 50 damage in 4 rounds but passive sources don't work on the last round
count that reactive sources don't work without getting hit
and added familiar equipment sources. and some better than nothing familiars.
run in QT
todo: didn't fix that it doesn't verify hit chance or attack skills to force hit chance or MP or improve the combat code for any of that. is Belch the Rainbow only 5 damage and not 6?
didn't make it try to pull or edit what it pulls, only 1 familiar equipment without knowing if it needs to.
didn't try to use buffs that make familiar act more often or …
=> wall of skin damage accounting fixes

BUILD/familiars/item.dat, RELEASE/data/autoscend_familiars.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_bedtime.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/paths/heavy_rains.ash
Removes Reagnimated Gnome from Heavy Rains as the benefit of the familiar equipment is negated by necessity for the miniature life preserver in the path.  I also made some minor code cleanup on heavy rains items for consistency and visibility.
Modified this myself on my own version of autoscend and I have run Heavy Rains.  It hasn't used the gnome once in a new run.
=> Remove Reagnimated Gnome from Heavy Rains

RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/quests/level_12.ash
* auto_bestWarPlan() fixed
it was was only planning to do the currently done sidequests + 1 undone sidequest with the best returns. After the best sidequest was done the next one was added to the plan. This meant that it was not a plan at all but merely returning a value of "what is the nest best sidequest todo". only without considering that the sidequest in question might not be unlocked yet. Which meant it was just wasting adventures by not doing a currently unlocked sidequest until it became the best value. The cause of this error is weirdness with how records are handled. see below
* void copy_warplan(WarPlan target, WarPlan source) created and used
record A = B; does not copy the contents of record B into record A, it instead copies memory address references from B into A. thus …
=> hotfix auto_bestWarPlan()

RELEASE/scripts/autoscend.ash
As subject. More important now that Dance Police is stocking more ascension relevant stuff like key lime pies and possible nightcaps like emergency margaritas/vintage smart drinks.
Works fine from what I can see. I ran with `auto_dontConsumeKeyLimePies` disabled in a Normal run & it skipped purchasing from Dance Police during consumption.
=> forbid Dance Police store

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_acquire.ash, RELEASE/scripts/autoscend/auto_restore.ash, RELEASE/scripts/autoscend/autoscend_header.ash
* boolean canPull(item it) fixed. it did not account for mallprice returning 0 or -1
* make the instructions on how to bypass aborting due to MP restore fail more visible (and in line with other similar cases) by making the text blue
* make auto_newbieOverride last for 5 adv instead of 1
* boolean canPull(item it) modified into  boolean canPull(item it, boolean update)
* allows canPull to use historical instead of current pricing
tested in wildfire
=> boolean canPull(item it) fixed & misc

BUILD/settings/any.dat, RELEASE/data/autoscend_settings.txt, RELEASE/scripts/autoscend/auto_bedtime.ash, RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/auto_settings.ash, RELEASE/scripts/autoscend/autoscend_header.ash
bedtime improvements
* add settings for various bedtime pull related stuff.
* instead of printing a suggestion of items to pull. make sure they are really needed and if so pull them automatically during bedtime
* automatically pull in bedtime equipment that improves your rollover adv and pvp gains.
* does not pull weapon, off-hand, or accessories yet due to those require more complex code to handle conflicts. This is currently being worked on in a followup PR
* fill remaining pulls with clovers
* printout the estimated number of pulls needed to finish the entire ascension after we perform automatic pulls instead of before. That function also printsout other info about what remains todo this ascension beyond just pulls
tested many times during standard and wildfire.
=> Bedtime pulling

RELEASE/scripts/autoscend/auto_acquire.ash
auto_mall_price has an issue if mall_price returns -1 for a tradeable item. this is usually caused by an IO error during mall search.
It results in an abort. in some situations (where we look at the price even for an item we already have) then autoscend will continue to abort the entire day and nothing you can do can make it run.
this PR will prevent the abort by using historical price instead, which is close enough in terms of value.
if this is the first time your mafia install tries to look up that item then historical price will return 0 even if it is available in the mall, which results in the item not being bought. potentially wasting some adventures. Although it is very much an edge case. As it requires a new mafia instance or your first time doing a new path and a path specific …
=> int auto_mall_price(item it) fix

RELEASE/scripts/autoscend/paths/wildfire.ash
fix an inf loop in wildfire when pumping water in certain situations (has to do with your fullness level).
one of the == should have been an <=
while I was at it I also slightly streamlined the code to make it clearer and less prone to mistakes, and added a safety catch
wildfire
=> hotfix wildfire pumping inf loop

RELEASE/scripts/autoscend/paths/heavy_rains.ash
Fixes a ChoiceAdventure Misnumber for Thunder Thighs.
=> Thunder is not Rain

RELEASE/scripts/autoscend/combat/auto_combat_default_stage2.ash, RELEASE/scripts/autoscend/combat/auto_combat_ed.ash
Reported in discord that extinguisher skill is attempted to be used, even if not equipped. Happened when user had a weapon in the override setting. Added check that extinguisher is equipped before using the zone specific skills. Polar vortex already check by confirming the skill could be used, which indirectly checks that extinguisher is equipped.
Validates
=> confirm extinguisher is equipped before using skill

RELEASE/scripts/autoscend/auto_acquire.ash, RELEASE/scripts/autoscend/auto_bedtime.ash
* don't pull familiar equip at bedtime if you are in a path that does not allow familiar
* buddy bjorn and snow suit were pulled on turn 0. unless an outdated list said we are in a path that does not allow familiar. replaced that list with the function `pathHasFamiliar()`. this will both fix the issue of pulling those items in newer paths that forbid familiar (such as dark gyffte) and also help in the future as more such paths are added
fixes #954
it does not break standard.
need to actually go into dark gyfte to test it
=> path restriction on pulls for familiar equip

RELEASE/scripts/autoscend/paths/heavy_rains.ash
L13 Quest has incorrect reference
Script validates
=> Fix L13 Heavy Rains

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_acquire.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/combat/auto_combat_default_stage3.ash, RELEASE/scripts/autoscend/quests/level_01.ash, RELEASE/scripts/autoscend/quests/level_11.ash
Cleans up some WOTSF items: still autoselling pork gems, pulling offhand items, and general code consistency.
A few WOTSF runs
=> WOTSF clean-up

RELEASE/scripts/autoscend.ash
For paths that don't have perms available (Robot) but the item autopulls
=> Use spinal-fluid-covered emotion chip to get skill

BUILD/monsters/replace.dat, RELEASE/data/autoscend_monsters.txt, RELEASE/scripts/autoscend/auto_util.ash
For alternate boss bat factoids, like the other paths are already checking.
Needed to add pathid because `You, Robot` has a comma in it.
=> Don't replace bats in robot or wildfire

RELEASE/scripts/autoscend/auto_familiar.ash
Discord reported abort due to spleen familiar handling dividing by zero. Issue was golden monkey was in bjorn. haveSpleenFamiliar() returned non-zero, but couldn't change to it. So line 515 (before this change) in auto_familiar attempted to divide by zero and aborted
Validates
=> Fix divide by zero in Spleen familiar handling

RELEASE/scripts/autoscend/auto_bedtime.ash
Fixes #965 by adding a `have_skill($skill[Super-Advanced Meatsmithing])` in the `craft Chrome Sword` step of `auto_bedtime.ash`
Fortunately, this happens consistently if:
1. It is day one of the run
2. Account has free crafts at the time
3. Account does not have Chrome Sword
4. Account has enough ores
5. Account does **NOT** have `Super-Advanced Meatsmithing`
Prior to this change:
Bedtime will terminate with an exception, and will not proceed with the rest of bedtime.
After this change:
If `have_skill($skill[Super-Advanced Meatsmithing])`, (i.e. 1-4 conditions above are all true), then it should still proceed with creating the chrome sword. However, it should no longer terminate unexpectedly if Super-Advanced Meatsmithing is unavailable.
=> check for super-advanced meatsmithing skill for day 1 bedtime chrome sword

RELEASE/scripts/autoscend/auto_choice_adv.ash
Adds back in choice 700 handling that was broken by mini-adventurer addition
Validates
=> Fix Choice 700 Handling (KOLHS)

BUILD/monsters/banish.dat, BUILD/monsters/sniff.dat, BUILD/monsters/yellowray.dat, RELEASE/data/autoscend_monsters.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/iotms/mr2013.ash, RELEASE/scripts/autoscend/iotms/mr2015.ash, RELEASE/scripts/autoscend/iotms/mr2017.ash, RELEASE/scripts/autoscend/quests/optional.ash
if I understanding things correctly kol changed something which made my_class() break for ed the undying. which was fixed in r25863 but now gives this warning. So I fixed this in autoscend and also updated the since command to ensure we do not use mafia older than this fix, as older versions of mafia won't work with ed anymore.
validates.
=> fix warning that we should change "Ed" to "Ed the Undying"

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/paths/license_to_adventure.ash, RELEASE/scripts/autoscend/quests/level_12.ash
* use provider instead of hardcoded list when preparing +combat for lobsterfrogman in sonofa beach
* this fixes an error where we fail to adventure there because we try to use equip() to equip an accessory into slot 1 when that accessory is a "single" type acc and already equipped in slot 3
* some cleanup on related code. better handling of failure
* some cleanup on the combat directives
hardcore standard. i was running into this problem which is solved by this code.
=> sonofa beach cleanup

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/paths/auto_path_util.ash
* if path drop was detected we reinitialize settings. do not ask the user if they want a 100% familiar run during reinitialize. Instead just keep the setting from the first initialize we did that ascension.
* this could have broken 100% familiar run if the user was doing a softcore standard. finished ronin. and was AFK while it popped up the question (for 15 seconds) on if they want to set current familiar to be 100% familiar run
* cleanup code on how reinitialize is done
hardcore standard. dropped standard
=> safer reinitialize of setting on path drop. protect 100% familiar setting

RELEASE/scripts/autoscend/auto_bedtime.ash, RELEASE/scripts/autoscend/auto_buff.ash, RELEASE/scripts/autoscend/auto_post_adv.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2015.ash, RELEASE/scripts/autoscend/paths/actually_ed_the_undying.ash, RELEASE/scripts/autoscend/paths/community_service.ash, RELEASE/scripts/autoscend/paths/heavy_rains.ash, RELEASE/scripts/autoscend/paths/kingdom_of_exploathing.ash, RELEASE/scripts/autoscend/quests/level_04.ash, RELEASE/scripts/autoscend/quests/level_05.ash, RELEASE/scripts/autoscend/quests/level_07.ash, RELEASE/scripts/autoscend/quests/level_09.ash, RELEASE/scripts/autoscend/quests/level_10.ash, RELEASE/scripts/autoscend/quests/level_11.ash, RELEASE/scripts/autoscend/quests/level_12.ash, RELEASE/scripts/autoscend/quests/level_13.ash
* boolean buffMaintain(effect buff) created
* used the above new function via find `, 0, 1, 1)` and replace `)` then going over the results and making sure no problems were introduced.
validates
=> boolean buffMaintain(effect buff)

RELEASE/scripts/autoscend/auto_buff.ash, RELEASE/scripts/autoscend/auto_post_adv.ash, RELEASE/scripts/autoscend/autoscend_header.ash
remove the use of to_effect() on the string and instead send $effect[] in the first place. This allows for automatic error detection and correction
ash calls
=> facecheck string -> effect

RELEASE/scripts/autoscend/auto_acquire.ash, RELEASE/scripts/autoscend/auto_buff.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_providers.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/paths/community_service.ash, RELEASE/scripts/autoscend/paths/heavy_rains.ash, RELEASE/scripts/autoscend/paths/kingdom_of_exploathing.ash, RELEASE/scripts/autoscend/quests/level_03.ash, RELEASE/scripts/autoscend/quests/level_09.ash, RELEASE/scripts/autoscend/quests/level_13.ash
* velour buffs: scariersauce, Dirge of Dreadfulness (Remastered), Snarl of Three Timberwolves
* use the velour skills when needed
* uneffect the velour skills when needed
* boolean[skill] ATSongList() -> boolean[effect] ATSongList()
* this was needed to allow us to uneffect an accordion song when two different songs key off of the same skill. such as dirge of dreadfulness and its remastered version.
fixes #992
ash calls. see below
=> velour buffs

RELEASE/scripts/autoscend/auto_settings.ash, RELEASE/scripts/autoscend/autoscend_header.ash
some code cleanup on auto_setting and added some related tools.
* void cleanup_property(string target);
* necessary for rename_property to work property. maybe should use it on all properties?
* void auto_rename_property(string oldprop, string newprop);
* I was sure we had a whole bunch of these. but when I was done writing this and went to apply it I only found a single case.
* void boolFix(string p);
* cleaner and easier for a human to read
tested via ash commands
also validation
=> settings upgrade cleanup

RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/quests/optional.ash
during nemesis quest the tomb of the unknown YOURCLASS only appears once when adventure in the unquiet garves.
we assumed that it has not been found yet and adventured in the unquiet garves for it. however if it was already exposed or if we found it but failed to complete it for some reason (ex: not having the correct item on hand) then it will continually waste adventures in the unquiet garves looking for the tomb even though it will not appear there anymore.
this PR solves this by checking to see if the tomb has been discovered already and if it has been going there directly.
ash calls on both accounts that had the tomb discovered and had not.
also had an account stuck at wasting adventures on the unquiet garves which this code fixed and made it go to the tomb properly and get the LEW
=> fix wasting adv when tomb already found during nemesis optional quest

RELEASE/scripts/autoscend/paths/license_to_adventure.ash
* in this old path we have code for consuming the old [astral energy drink] for adventures.
the code was not doing anything since astral energy drinks have been removed from the game.
in 2022 a different item with the same name was added to kol and mafia automatically assumes you are referencing the newer item. deleted that bit of code for using it as it inapplicable (their usage method is completely different and we do not want to consume the new astral energy drink at that spot).
* gets rid of 6 lines of mafia nag messages
see #995
validation
=> removed [astral energy drink] from license to adventure

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_acquire.ash, RELEASE/scripts/autoscend/auto_bedtime.ash, RELEASE/scripts/autoscend/paths/avatar_of_boris.ash, RELEASE/scripts/autoscend/paths/avatar_of_jarlsberg.ash, RELEASE/scripts/autoscend/paths/avatar_of_sneaky_pete.ash, RELEASE/scripts/autoscend/paths/nuclear_autumn.ash
Attempt to buy 11-leaf clovers from hermit instead of ten-leaf. Didn't touch logic as to when we buy. Likely should since clovers are much more valuable now and want to grab all 3 at beginning of every day.
In support of #995 
cli commands
```
> ash import<autoscend.ash> acquireHermitItem($item[11-Leaf Clover])
Changing "ed" to "Ed the Undying" would get rid of this message. (zlib.ash, line 503, char 29 to char 31)
[INFO] Hermit acquistion of: 11-leaf clover
Purchasing chewing gum on a string (1 @ 50)...
You spent 50 Meat
You acquire an item: chewing gum on a string
Purchases complete.
Using 1 chewing gum on a string...
You acquire an item: worthless knick-knack
Finished using 1 chewing gum on a string.
Visiting the Hermit...
You acquire an item: 11-leaf clover
Hermit successfully looted! …
```
=> acquire 11-leaf clovers from hermit

RELEASE/scripts/autoscend/combat/auto_combat_default_stage2.ash
disable using fire extinguisher against screambat as a temporary workaround for the issue where combat fails against screambats if you have fire extinguisher
validates
=> hotfix: temporary workaround for #1011

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_bedtime.ash, RELEASE/scripts/autoscend/auto_consume.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/combat/auto_combat_default_stage4.ash, RELEASE/scripts/autoscend/iotms/mr2021.ash, RELEASE/scripts/autoscend/paths/path_of_the_plumber.ash
* automatically consume in plumber once we reach level 13 and no longer care about the XP
* only warn about manual consumption during bedtime instead of every loop. and be clearer with it as well. Also always display the instruction of "eat then run me again" regardless of log settings.
* started adding some measure of consumption for XP to plumber
standard plumber run
=> plumber consume

RELEASE/scripts/autoscend/iotms/mr2022.ash
auto_bowlingBallCombatString is used both to determine if a skill/item will be use speculatively and then if it will be used, actually uses them. Speculation was incorrectly marking the skill/item as used, so couldn't be cast when we wanted it to be
Relates to #997 
Validates and ran a day. Confirmed skills used as expected
=> HotFix - Don't Mark CBB Skills/Item as used if only speculating using them

RELEASE/scripts/autoscend.ash
Reported in Discord that adv limit abort was triggered for Daily Dungeon when auto_forceFatLootToken was true. In hardcore runs on accounts that don't have the cube, it is expected to reach the adv limit in this situation.
Removed adv limit abort in Daily Dungeon if auto_forceFatLootToken is true
Validates
=> Remove adv limit warning in daily dungeon if auto_forceFatLootToken is true

RELEASE/scripts/autoscend/combat/auto_combat_quest.ash
based on Combat #1019 
don't flyer gremlins if it will get you killed
stun if you need to let weaksauce delevel the gremlin longer before you can survive its attacks
update auto_JunkyardCombatHandler with the better flyering found in regular combat handler
=> gremlin and flyering fixes

RELEASE/scripts/autoscend/paths/auto_path_util.ash
- seal clubber
buy Club Foot for getStunner()
usefulness of Wolverine at level 4 depends on fury skills, buy it at lower meat if it will enable banish or stun, higher meat otherwise
- sauceror
buying Itchy Curse Finger is useless to autoscend without Curse of Weaksauce, it never uses the other curses
buying Saucemaven is useless when there is no stomach space for any of the saucy foods
- accordion thief
removed  Five Finger Discount
~~add conditions for buying Five Finger Discount  to be either < level 11 or have planned 10000 of expenses in meatReserve. I think better not to buy the skill at all, it won't break even under 50000 meat spent. autoscend barely spends 1/3 that in discountable stores in a normal path? unless all meat always gets spent on MP restores but the high meat …
=> guild skills of seal clubber, sauceror, accordion thief

RELEASE/scripts/autoscend/quests/level_any.ash
if you found the tires first and have 0/4 meat engine parts and farming the parts in softcore it must be smarter to pull the meat engine
even above 0/4 in paths where Gnollish Gearhead can fail to drop toolbox but don't want to calculate the odds.
autoscend doesn't try to isolate gearheads but added an appearance_rates exception tested in cli
=> when Farming for a Bitchin' Meatcar check if you should pull the meat engine

RELEASE/scripts/autoscend/quests/level_12.ash
boolean L12_themtharHills() make sure zone is available before we try to clover it
related to #995
was stuck failing at this spot until I switched to fix code
=> hotfix stuck at trying to clover castle top floor when unavailable

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash
debug mode was not working since we were checking
for interrupt in multiple spots. which meant we were setting interrupt and then discharging it before any adventuring could be done.
fixed it by limited when it actually sets the interrupt
tested in ed. path does not matter though
=> fixed debug mode

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_acquire.ash, RELEASE/scripts/autoscend/auto_buff.ash, RELEASE/scripts/autoscend/auto_consume.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/combat/auto_combat_util.ash
auto_consume.ash
avoid unnecessary mall_price searches by auto_spleenFamiliarAdvItemsPossessed
auto_buff.ash
autoscend.ash
don't acquireTotem to cast a skill you don't have
combat/auto_combat_util.ash
don't pick middle finger ring banish when muscle too low for can_equip($item[Mafia middle finger ring])
auto_util.ash
skip shrugAT when anticipated song is not known, skips many INFO messages like "I think we're good to go to apply Carlweather's Cantata of Confrontation" when you don't have the skill
assumes it's not asking for a song from another player out of ronin, I don't find autoscend doing that and the same is already assumed for the 6 avatar classes skipped by shrugAT
=> Skip some unnecessary operations

RELEASE/scripts/autoscend/quests/level_12.ash
Check if we have Sinuses for Miles before using a clover to grab an inhaler.  Fixes an issue Lacey Jones noted in ASS
Validates
=> Update L12 Nuns

RELEASE/scripts/autoscend/quests/level_10.ash
after questL10Garbage is over Flavor of a Raver should choose Yeah, You're for Me, Punk Rock Giant then Copper Feel to unlock hole or skip
instead it took the drum 'n' bass 'n' drum 'n' bass record in run
=> fix Flavor of a Raver choice when trying to open hole

RELEASE/scripts/autoscend/auto_equipment.ash
Add similar conditions to Kramco to forbid Cursed Magnifying Glass assuming void monsters interrupt Map the Monsters like the goblins
also extended to forbid equipping it when it leads to non free fights in softcore. and addBonusToMaximize to charge it otherwise
not tested with the item, validates only
=> condition use of Cursed Magnifying Glass

BUILD/familiars/gremlins.dat, RELEASE/data/autoscend_familiars.txt
Gelatinous Cubeling is better than Barrrnacle for gremlins
it delevels more often? either its base chance is higher or it's going to be heavier because it gets used for at least 12 fights and the Barrrnacle	doesn't. plus it's a fairy.
=> Gelatinous Cubeling is better than Barrrnacle for gremlins

BUILD/familiars/stat.dat, RELEASE/data/autoscend_familiars.txt, RELEASE/scripts/autoscend/iotms/mr2020.ash
Temporary Fix to stop spending infinite meat buying commerce ghost items . Will clear the commerce ghost item preference prior to trying to buy the item
=> Never attempt to buy commerce ghost items whilst broken

RELEASE/scripts/autoscend/combat/auto_combat_default_stage4.ash
#1053 red rocket hotfix workaround. simply disable the check for fullness > 3 on next item to be consumed.
will reenable it once a better fix is finalized.
validates. but I need to wait until dayroll to properly test it.
=> hotfix lots of errors when looking at red rocket

RELEASE/scripts/autoscend/iotms/mr2014.ash
remove the semirare checker checking for any counter		 if(get_counters("", 0, 6) != "")
don't pull grimstone mask unless running short on scrips.
rod explores faster than compass, but pulling the mask for rod ends up worse on average than pulling a scrip for compass, because of the 5 advs spent taking silver coins instead of getting pages (and stats and flyering) from fights in the desert
softcore run
have not calculated if the mask is still useful in hardcore versus Melodramedary + killing jar + drum machine + stone rose. There is still a per-ascension preference that can be toggled off if someone wants to skip the mask in hardcore
in softcore autoscend pulls drum machine and killing jar. drum machine = 30% exploration, killing jar = 15%, can of black paint = 15%.
40% exploration left, …
=> reconsider pulling grimstone mask for exploration

RELEASE/scripts/autoscend/auto_post_adv.ash
keep 5 soulsauce for soul bubble if not missing much MP
at high MP soulsauce can get wasted on soul food leaving a sauceror with no ability to stun in combat
sauceror run
=> keep soulsauce for soul bubble

RELEASE/scripts/autoscend/auto_pre_adv.ash
use removeML settings when going to the junkyard without very high moxie
fix the "Last minute MCD alterations if Limit set" that was ignoring removeML and capping up to ML limit anyway
sauceror run
=> gremlins junkyard ML pre_adv fix

RELEASE/scripts/autoscend/auto_familiar.ash
Red-Nosed Snapper handling always stops any choice even with no snapper
zones like Fantasy ship and Copperhead never chose a familiar
in run
=> fix no familiar choice due to Red-Nosed Snapper handling

RELEASE/scripts/autoscend/auto_choice_adv.ash
choice was not supported if already got boning knife, skip choice is different
confirmed choice 2 no longer exists
=> fix Home on the Free Range repeat choice

RELEASE/scripts/autoscend/auto_bedtime.ash, RELEASE/scripts/autoscend/auto_equipment.ash
- pull potato alarm clock at bedtime
- addBonusToMaximize for can of mixed everything and carnivorous potted plant
if user decided to pull them under their own responsibility only, not pulled by the script. because plant = 25 ML no requirements and autoscend can't be reasonable yet with ML, and mixed everything can drop things like firemilk for auto_consume
- pull the rollover improvements that are of same quality as potato alarm clock earlier in the bedtime pulls
at low level day 1 bedtime, try to pull the >=5 rollover improvements over level 11 items for more benefit early
in slow runs they get pulled at the end of day 2 anyway while the level 11 items can be pulled with the same benefit even on day 2,3 or later.
- don't call bedtime VIP clan without VIP key
in run
=> pull potato alarm clock at bedtime and others

RELEASE/scripts/autoscend/auto_buff.ash
Emo chip skills were only being checked for < 3 casts that day before being tracked. There are many other checks, such as already have the buff, that could later cause the buff not to be cast. 
Added a check to confirm the buff will actually be cast prior to tracking them as being cast
Fixes #972 
Ran HC standard AT. Only tracked emotion skills when actually cast
=> Fix Emotion Chip Skill Tracking

RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_zone.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/combat/auto_combat_default_stage3.ash
don't get combat rate modifiers for Lucky! adventures
also no item bonus or cold damage at The Smut Orc Logging Camp after bridge built (Shen)
in run
=> don't get combat rate modifiers for Lucky! adventures

RELEASE/scripts/autoscend/quests/level_10.ash
Amulet of Extreme Plot Significance is the only equipment needed. Titanium Assault Umbrella should not get pulled
run
=> remove Titanium Assault Umbrella pull

RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/iotms/mr2021.ash
Multiple Discord reports of getting beaten up by tentacles. The logs I've see are all backed up tentacles. Learned that backed up monsters have +ML applied twice. This change reduces +ML when going to backup next fight.
Partial fix for #1057 . This changes makes backed up tentacle fights easier. Full fix would instead improve our combat handling.
Validates. In run testing in progress
=> Reduce ML when backing up an enemy

RELEASE/scripts/autoscend/auto_equipment.ash
avoid cursed magnifying glass, kramco, or carnivorous potted plant interfering with back up or map the monsters
no cursed magnifying glass so only validated. I am told void monsters are bad for backup, makes sense if they can be copied
=> prevent equipment interference with backing up

RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_zone.ash
examples like goatlet (L8) blasting soda (L13)
also increase item bonus target in goatlet if want goat's milk on the way
in run
=> use food drop / booze drop bonus

RELEASE/scripts/autoscend/quests/level_12.ash
skip sidequests if battlefield is empty. if script is restarted elsewhere or user finished the war
in run
=> skip sidequests if battlefield is empty

RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/quests/level_10.ash, RELEASE/scripts/autoscend/quests/level_13.ash
don't pull star chart when about to adventure in hole in the sky for stars or lines anyway
also pull and buy missing stars and lines out of ronin. are the existing price checks enough?
then, no need to unlock hole after breaking ronin if the key components could be bought
broke ronin
=> don't pull star chart when about to adventure in hole

RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/quests/level_11.ash
red badge / Space Trip Safety Headphones  -10ml in the maximizer gets set just for having them equipped, so once red badge gets equipped it keeps getting equipped into other zones that don't need -ML until 3 accessories can beat -10*25 score. no references to these items elsewhere.
you don't always have a red badge to wear, an example I found where this would sometimes get pre_adv to remove ML is L11_shenCopperhead maximizing with -10ml, with a red badge available Ur-kel\'s Aria of Annoyance would be removed by pre_adv next adventure for The Copperhead Club, but not without a red badge so this still wouldn't have worked well
Testing ASH scripts is tricky and generally involves you doing multiple runs with a change to see how it performs. If you did any particular tests, or have particular …
=> don't equip red badge only because of equipped red badge

RELEASE/scripts/autoscend/auto_familiar.ash, RELEASE/scripts/autoscend/auto_zone.ash, RELEASE/scripts/autoscend/quests/level_12.ash, RELEASE/scripts/autoscend/quests/level_13.ash
don't strip delevel familiars for gremlins
meat familiar not useful for Groar
item familiar not useful for Ron Copperhead
item bonus not needed to get Ultrahydrated
in run
=> don't strip delevel familiars for gremlins

RELEASE/scripts/autoscend/combat/auto_combat_default_stage3.ash, RELEASE/scripts/autoscend/quests/level_09.ash
fix lumberCount() and fastenerCount() wrong type
condition Logging hatchet and Loadstone
use Mating Call to balance bridge parts
use cold bonus or if negative ML try to default to saucestorm. override chance of non cold damage like spirit snap.
plus don't use Saucegeyser if it's going to be hot
in run
=> Smut bridge

RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/combat/auto_combat_default_stage4.ash, RELEASE/scripts/autoscend/combat/auto_combat_quest.ash, RELEASE/scripts/autoscend/paths/auto_path_util.ash
count beehive item damage multipliers
don't stun for flyering if already staggers
buy Deft Hands skill if needed
in run. other item damage multiplier sources not tested
=> Flyer update

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_acquire.ash, RELEASE/scripts/autoscend/paths/casual.ash
some changes that can save hundreds of mall searches
- should not need Bulk caching mall prices for consumables again after ascending on the same day
- explicitly request historical_price of consumables that were already cached
if item type is food or booze for them price already gets cached on autoscend day start so that mafia will give historical_price when asked for mall_price, but if mafia session has to be restarted then mafia will have lost its cache and will do mall searches looking for every consume item considered. so ask explicitly for historical instead.
can't do the same for hprestore,mprestore, autoscend caches them but hprestore and mprestore types corresponding with mall_prices search categories are not available, can't use item subrecords .maxhp and .maxmp because they …
=> use cache prices and remove some unnecessary operations

RELEASE/scripts/autoscend/auto_buff.ash
BuffMaintain when speculating would assume mall purchases would work. Which is fine, however we shouldn't even attempt to buy when in hardcore or if it is a quest item.
This fixes speculation thinking it can get buffs when it can not. Also fixes attempting to buy things and failing when not ran speculatively. 
Discovered when #1073 bought the ML hat when I couldn't max out -com or +com. 
Ash calls while in run
=> Hot Fix - BuffMaintain Speculation Fix

RELEASE/scripts/autoscend/combat/auto_combat_default_stage5.ash
Currently in HC TT run. Noticed I was attacking a lot for little damage, then using major attack once. If that didn't kill the monster I then had to manually kill it. This change helps by avoiding doing low damage attacks and instead using saucestorm.
2 days of HC TT
=> Saucestorm instead of low damage attacks

RELEASE/scripts/autoscend.ash
Removes Ed from ability to use emotion chip.  During run:
"Using 1 spinal-fluid-covered emotion chip...
You can't learn that skill."
Validates
=> Ed can't use emotion chip

BUILD/familiars/item.dat, RELEASE/data/autoscend_familiars.txt
Very basic Grey Goose support. Only added it to item familiars. Exact location in item fam hierarchy can be decided later when support for skills are added. Mafia does not yet support the goose combat skills.
Script switched to Grey Goose when needing an item type fam in standard PM
=> Added Grey Goose to item familiars

RELEASE/scripts/autoscend/combat/auto_combat_default_stage2.ash, RELEASE/scripts/autoscend/combat/auto_combat_ed.ash
Certain monsters we don't want to use the Saber YR since Use the Force doesn't end combat "properly".
The Knight (Snake) is only YR'd in Ed & I think this is a mafia bug with Ed which breaks NC handling. Regardless if you have the Saber you don't need the Knight's sword & shield for ML.
The topiary monsters are Spit on by the Melodramedary in paths which can use familiars. YR'ing them with the Saber will not give 4x drops since the Saber YR forgets everything that happened in combat thus wasting the use of Spit.
I think these changes were overlooked during refactoring the combat code.
Validates. Theophrastus has been running the Ed change manually however.
=> don't use Saber YR in combat when we shouldn't

RELEASE/scripts/autoscend/auto_bedtime.ash, RELEASE/scripts/autoscend/paths/actually_ed_the_undying.ash
There is an issue in KoL itself where Ed servants can not be swapped if certain conditions happen. Per Discord this failure state happens when a level 7 or greater Scribe is in use during RO. This PR always changes our active servant to the Priest. Priest is unlocked prior to Scribe so this is a safe operation.
Note - even changing to a level 7 or greater Scribe during the day will make KoL's UI break when trying to switch familiars. In this state ash commands to swap servants still work. However issues gets worse when RO happens as ash commands don't work anymore.
Didn't get bug after RO
=> workaround Ed servant bug

RELEASE/scripts/autoscend/paths/quantum_terrarium.ash
the quantum_terrarium.ash file is visiting qterrarium.php every time it is loaded, which seems to be every pre_adv, every post_adv, every choice, sometimes just on the main loop
- it records the terrarium in a string but none of the related functions are used anywhere
- if it's also supposed to be a terrarium visit to update familiars it would not be the right way to do that due to the high amount of requests and running even outside of path
this pr moves it into the only function that would refer to its data if these functions are ever used
in non quantum terrarium run and with debug trace on
have not tested if quantum terrarium path ever loses track of its familiar without these visits
=> qterrarium.php fix

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_bedtime.ash, RELEASE/scripts/autoscend/auto_familiar.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/iotms/mr2017.ash, RELEASE/scripts/autoscend/paths/bees_hate_you.ash, RELEASE/scripts/autoscend/quests/level_09.ash
Removes some calls that won't work in BHY due to exclusion of B letters.  Can't use genie bottle, no need for Bloody Hand to make volleyball, can't use/pull tiny barrel familiar.
Also has various code cleanup for areas I reviewed for BHY.
Did a BHY run
=> BHY Code Cleanup

RELEASE/scripts/autoscend.ash
AWOL can't tap spinal fluid either. Adding that to the ever increasing list of paths it doesn't work on. Also changing that list to
!(a || b || c) instead of !a && !b && !c to make the path check  self contained and easier to read.
Run in Awol, confirm it doesn't get stuck doing nothing before turn 0. Did not test in Boris, ZS or Ed
=> AWOL support: Do not try to use Spinal fluid

RELEASE/scripts/autoscend/paths/auto_path_util.ash
If Torso Awareness isn't available, the script will buy it in a Gnome sign if it has the spare meat, and a good shirt. At the moment, it only considers the Garbage Tote to be worth it. This slightly expands the list of shirts that are considered worthwhile (including Astral, Shoe Ad, Tunac and Fresh Coat of Paint).
Couple of Ed ascensions.
=> More shirts that make Torso worth it

RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/clan.ash
Previously used ash function `faxbot()` requires in game chat to be open to function. This is not desirable. No longer required. Updates heavily based on what garbo does to fax in embezzlers. 
CLI in aftercore. Made sure chat was closed and that `faxbot()` failed:
```
> ash faxbot($monster[ghost])
Configuring faxable monsters.
Configuring Easyfax (2504737)
Configuring CheeseFax (3038166)
Faxable monster lists fetched.
Visiting Fax Machine in clan VIP lounge
Asking Easyfax to send a fax of ghost: ghost
No response from Easyfax after 60 seconds.
Visiting Fax Machine in clan VIP lounge
Asking CheeseFax to send a fax of ghost: ghost
No response from CheeseFax after 60 seconds.
```
Worked with these updates (false param means don't fight it):
```
> ash import<autoscend.ash> …
```
=> Fax works when chat window is closed

RELEASE/scripts/autoscend/auto_settings.ash
auto_edDelayTimer comment said "replaced with auto_delayTimer that works in all paths" but it was being renamed the other way around so instead it always cleared auto_delayTimer
run
=> fix auto_delayTimer

RELEASE/scripts/autoscend/auto_consume.ash, RELEASE/scripts/autoscend/iotms/clan.ash, RELEASE/scripts/autoscend/paths/community_service.ash
make sure to have used steel margarita before overdrinking
canDrinkSpeakeasyDrink is only used from autoDrink which is the same general function used for overdrinking, so canDrinkSpeakeasyDrink should allow overdrinking, inebriety checks would be done when selecting the drink in the first place. no speakeasy drinks are used yet except in community service with inebriety checks so this change makes no difference right now
community_service.ash: removed starting with the size 6 drink now that it has changed
validated only, the situations are in theory or were not encountered
=> liver of steel bedtime and drinking

RELEASE/scripts/autoscend/auto_familiar.ash
autoscend probably did not use item familiar there because it would clover for sonars which is no longer possible
run
=> use item familiar in Guano Junction for sonars

RELEASE/scripts/autoscend/auto_util.ash
added appearance_rates check
queue argument must be true, example:
pygmy witch lawyer only appears in The Hidden Park if relocatePygmyLawyer == my_ascensions()
pygmy witch lawyer is always in monsters list of $location[The Hidden Park]
appearance_rates($location[The Hidden Park]) without queue argument shows 20.0 pygmy witch lawyer
=> don't prepare to banish impossible monsters

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_acquire.ash, RELEASE/scripts/autoscend/auto_bedtime.ash, RELEASE/scripts/autoscend/auto_post_adv.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_providers.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2015.ash, RELEASE/scripts/autoscend/iotms/mr2017.ash, RELEASE/scripts/autoscend/iotms/mr2018.ash, RELEASE/scripts/autoscend/quests/level_03.ash, RELEASE/scripts/autoscend/quests/level_07.ash, RELEASE/scripts/autoscend/quests/level_09.ash, RELEASE/scripts/autoscend/quests/level_11.ash, RELEASE/scripts/autoscend/quests/level_12.ash, RELEASE/scripts/autoscend/quests/level_13.ash, RELEASE/scripts/autoscend/quests/optional.ash
Various clean-up items for G-Lover.  Adds in auto_is_valid($effect) for ability to check effects that can't be used in G-Lover and removes those effects from functioning.
Several G-Lover runs
=> Various G-Lover Changes

RELEASE/scripts/autoscend/iotms/mr2015.ash, RELEASE/scripts/autoscend/quests/level_08.ash
Ninja snowmen have a separate tick of environmental damage at the start of their turn, which expected_damage() does not account for. This causes the script to waste 50 adventures and abort, if you are not able to survive but the script thinks you can. The environmental damage is likely around 15%, but I set it to 20% to have a 5% buffer.
Chateau painting snowmen did not check survival. Added survival check.
=> Account for Ninja Snowmen Assassin Environmental Damage

RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/combat/auto_combat_default_stage2.ash
fix careAboutDrops() false return
Writing Desk is a valid target for Stomping Boots
check careAboutDrops, it's unfinished but better than not checking
validates only
=> Care about drops

RELEASE/scripts/autoscend.ash
bypass beaten up abort if it's the quest beaten up before Dr. Awkward
shouldn't autosell the only Chaos Butterfly, autoscend even sniffs the giant to get it
run
=> dr awkward did not beat you

RELEASE/scripts/autoscend/auto_providers.ash
previous PR seemed to work but not in some cases because modifying the goal in the final int [element] provideResistances  function doesn't directly modify the result returned when the provider fails and in the other boolean provideResistances functions that call it,
must modify its results instead of the goal
issue details #1156
in run
=> re do compensate current equipment when calling provideResistances with doEquips = false

RELEASE/scripts/autoscend/auto_acquire.ash
Swapping the hardcoded 30k price limit on purchases for a player's `autoBuyPriceLimit`. 
Not yet.
=> remove hardcoded price

RELEASE/scripts/autoscend/iotms/mr2022.ash
Utilizing the `_juneCleaverSkips` property that wasn't available on initial implementation.
No
=> implement skips

RELEASE/scripts/autoscend/quests/level_09.ash
if clue use failed somehow autoscend would still think it had a clue pending and adventured 50 times, so only set the property that a clue was used if it was successful and try to re use a clue if the last encounter was one of the zone monsters instead of the clue
run
=> aboo clue failure

RELEASE/scripts/autoscend.ash
A minor issue was reported where, when people were already getting beaten up too much, the June Cleaver choice adventure Poetic Justice was triggering an abort for being beaten up too much.
-
=> Minor June Cleaver Fix

BUILD/familiars/stat.dat, RELEASE/data/autoscend_familiars.txt
fix [ghost of crimbo commerce] which was uncommented incorrectly in https://github.com/Loathing-Associates-Scripting-Society/autoscend/commit/8d02212403f277760390ea009b9dce360c16f1d3
undeleted notes were left over after uncommenting which are being parsed as if they are part of the familiar name. resulting in an error in parsing the familiar name.
tested in post ronin
=> hotfix [ghost of crimbo commerce] uncommenting error

RELEASE/dependencies.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_zone.ash
remove dependency on can_adv as it has disappeared from SourceForge
use newly added location_accessible() function in mafia instead
Hasn't tbh. Validates though.
=> remove dependency on can_adv

.gitignore, RELEASE/scripts/autoscend/auto_bedtime.ash
Log when doBedtime() exits early due to having spare adventures, more to consume, or unexpectedly.
Add .vs* to .gitignore to allow coding in VS Code without adding all the VS autogen files.
**Prep:** In Autoscend.ash, comment out lines 1913-1929 (after "Actually doing stuff" to consumeStuff()) to focus only on running bedtime.
Do not consume anything to max before beginning testing.
Test will likely cover a full day's worth of adventuring, including overdrinking.
1. In kolmafia, run autoscend with more than 4 adventures. 
Should see "Still adventurous! Stopping bedtime."
2. Spend adventures, then rerun autoscend.
Should see "Still hungry! Stopping bedtime."
3. Eat to fullness, spend adventures, then rerun autoscend.
Should see "Still sober! Stopping bedtime."
4. Comment out inebriety …
=> Bedtime Halt Check Logging

RELEASE/scripts/autoscend/combat/auto_combat_default_stage3.ash
Include logic to use the NA Skill Throat Refrigerant against Smut Orcs for Blech House when in NA
-
=> Add Throat Refrigerant to Smut Orc skill logic

RELEASE/dependencies.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_canadv.ash, RELEASE/scripts/autoscend/auto_zone.ash
Re-adds a copy of canadv.ash as auto_canadv.ash as mafia's location_accessible() function needs (a lot of) work before we can use it reliably as a replacement for can_adv().
Hasn't. Validates.
=> reinstate can_adv as location_accessible is "unreliable"

RELEASE/scripts/autoscend/quests/level_11.ash
when failing to adventure in oasis for any reason autoscend would set mafia's desertExploration value to 0, this leads to keep adventuring in the desert after it is done, for as many ~50 adventures it is allowed to
instead use the same exploration check done when failing to enter the pyramid and abort if wrong exploration was not the issue
tested matcher in cli
=> don't erase desertExploration on oasis failure

RELEASE/scripts/autoscend/auto_consume.ash
change from <= to <  to match auto_acquire
fixes consume failure if all wanted consumables were exactly at the limit price that can not be acquired
=> fix consume failure at exact price limit

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2022.ash
mafia does not have tracking for familiar sweat yet, this just makes sure it gets collected
also add 2 location exceptions in sweatpantsPreAdventure
run
=> put tiny stillsuit on terrarium familiar when not worn

RELEASE/scripts/autoscend/quests/level_11.ash
ultrahydrated was required before giving gnasir items, usually meant 1/5 chance to waste an adventure in the Oasis before finishing exploration with wormride (when last desert page acquired as Ultrahydrated expires)
now moved up to give gnasir items before looking for Ultrahydrated
run
in theory this might also change the order autoscend does things in one rare softcore case, if no wormriding and <= 15 exploration is left and a killing jar wasn't already pulled by bedtime, L11 could now pull a killing jar before it decides to adventure for a stone rose. I think no wormriding only happens in G-lover and this would not be a bad change anyway and it would probably be better for L11 not to require no wormriding to pull a killing jar but did not change that in this PR
=> don't get ultrahydrated just for gnasir

RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/paths/path_of_the_plumber.ash
use same statgains boosting as in previous cases
plumber force equip option added because plumber is not allowed to adventure without tool, and arbitrary equipment changes made after maximize in pre adv could unequip it
script run but not triggered plumber change it's fixing an edge case that doesn't happen in ronin (need 3 statgains accessories to lose tool)
=> increase shore vacation statgains 

RELEASE/scripts/autoscend/auto_familiar.ash
when + combat rate is wanted, this is the only familiar that gives + combat rate
skipping + combat rate in these locations in some cases was put in another PR #1147
run
=> use Jumpsuited Hound Dog at Sonofa Beach, Lair of the Ninja Snowmen

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_canadv.ash, RELEASE/scripts/autoscend/auto_zone.ash, RELEASE/scripts/autoscend/paths/wildfire.ash, RELEASE/scripts/autoscend/quests/level_12.ash
mafia has changed these location names and removed Post-War Junkyard
validate
=> Frat House In Disguise, Hippy Camp In Disguise, Post-War Junkyard removed

BUILD/monsters/sniff.dat, RELEASE/data/autoscend_monsters.txt, RELEASE/scripts/autoscend/auto_consume.ash
don't skip valid key lime pies for non valid pies, for g lover
filthy poultices not g valid so g-lovers doing hippy war should olfact nurses for gauze garters for shadow,
change to sniff naughty version after normal would be better with some sniffs but hits the usual limitations of sniff data system so just mirrored Exploathing conditions
added topiary animals sniff and improved conditions for other sniffs
run
=> G lover pie and sniff nurses

RELEASE/scripts/autoscend/auto_familiar.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_zone.ash, RELEASE/scripts/autoscend/quests/level_03.ash, RELEASE/scripts/autoscend/quests/level_11.ash
don't need item drop for forced encounters and most lucky adventures
don't need +combat for shen Lair of the Ninja Snowmen after peak
don't need +combat in The Haunted Library all the non combat are free to skip
don't need item drop to start the war
[The Typical Tavern Cellar] location was not used, autoAdvBypass used Noob Cave for this quest because The Typical Tavern Cellar is not a real location in the game but it is a virtual location in mafia that autoscend tries to check and that's how it knows where it is to handle things like monster level but removed what it tried to do in that location that was incorrect:
item familiar not needed for Typical Tavern Cellar
combat frequency modifier is already decided in the quest file instead of the zone file
in tavern quest only give value to …
=> remove unnecessary zone preparation

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/quests/level_07.ash, RELEASE/scripts/autoscend/quests/level_08.ash
use evilness reduction bonus in L7 conditions
fix slay the dead incompatible with Iron Palm Technique or user forced weapon
don't switch right away from L7 to L8 quest to not waste current olfactions or banishes in paths that put L8 over L7
in run
=> L8 to L7 override

RELEASE/scripts/autoscend/iotms/mr2017.ash, RELEASE/scripts/autoscend/iotms/mr2022.ash
Both issues reported in the discord channel.
- Cosmic Bowling Ball wasn't checking it is in inventory when attempting to throw it at a Pygmy Bowler & thus causing hangs in combat. Check we have one in inventory before trying to throw it at anyone (or like, use it at all).
- Mafia recently changed how it detects ownership of certain older IotMs which meant it now always sets the horseryAvailable property regardless of whether that is actually true in game due to path restricions. We will now check if it's not path restricted.
validates
=> check horsery is legal and bowling ball is available

RELEASE/scripts/autoscend/auto_bedtime.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/quests/level_12.ash
Calculate the universe can only be cast 3 times now
Untested, trivial change to cap at 3 if skillLevel144 is greater.
=> Limit of 3 calculate the universe

RELEASE/scripts/autoscend/auto_acquire.ash, RELEASE/scripts/autoscend/auto_canadv.ash, RELEASE/scripts/autoscend/auto_familiar.ash, RELEASE/scripts/autoscend/auto_post_adv.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_zone.ash, RELEASE/scripts/autoscend/iotms/mr2019.ash, RELEASE/scripts/autoscend/iotms/mr2021.ash, RELEASE/scripts/autoscend/iotms/mr2022.ash, RELEASE/scripts/autoscend/paths/you_robot.ash, RELEASE/scripts/autoscend/quests/level_11.ash
Convert a bunch of get_property strings to ints when comparisons are made. Workaround for recent mafia bug. There may be more strings that need to be coerced this but should be most of them I hope.
Minimal local testing.
=> Add a bunch of missing get_property().to_int()

RELEASE/scripts/autoscend/auto_familiar.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/paths/zombie_slayer.ash
Adds a function to check if a given familiar is actually useable in Zombie Slayer
It hasn't
=> add zombieSlayer_usable function

RELEASE/scripts/autoscend/iotms/mr2021.ash
should avoid getting more free kill charges when about to do nuns because the fights would be capped to 1000 meat
in run
=> don't get free kill charges when about to do nuns

RELEASE/scripts/autoscend/auto_bedtime.ash
Bedtime logic assumes you will be doing Frat side of war. Have added logic to prevent it suggesting you need to get the frat outfit when you are doing the hippy side (and logic to suggest getting it if you dont have it yet)
=> suggest only correct war outfit

BUILD/monsters/sniff.dat, BUILD/monsters/yellowray.dat, RELEASE/data/autoscend_monsters.txt, RELEASE/scripts/autoscend/auto_consume.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/auto_zone.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/quests/optional.ash
pulling alternatives for LX_joinPirateCrew. partially addresses #472
consider pull The Big Book Of Pirate Insults ahead of starting beerpong quest and keep trying to get outfit and insults together, saves fights and pulls for missing pieces
added to consume blacklist hot wing, wet stew, gravy boat
update zone goals for pirate outfit, hot wings
sniff last missing F'c'le pirate if its drop not capped
use the added itemdropcapped check to avoid some unnecessary sniffs and yellow ray
run
=> Pirates quest improvements

RELEASE/scripts/autoscend/auto_acquire.ash, RELEASE/scripts/autoscend/auto_consume.ash, RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/quests/level_11.ash, RELEASE/scripts/autoscend/quests/level_12.ash
allow wearing non 100% kramco when adventuring in delay zone anyway
add backup camera to canBurnDelay to keep delay zones for backups
use friars booze buff for bottle of Chateau de Vinegar
do not delay filthworms if capped item
add conditions to pull Fake Washboard
limit meat spent on green beer in Surprising Fist
refresh inventory before checking muffin fail
run, keep delay zones for backups was not checked with backups left but it's same code as other delay burns
=> allow wearing non 100% kramco in delay zone and other

RELEASE/scripts/autoscend/quests/level_11.ash
Hi, this is my first PR. Am starting small, but please provide any feedback :)
I was getting stuck whenever I got to Palindome Stage 5 because it would throw `Whoops! You're not actually in a choice adventure` I think this is because it is trying to reacquire 2 Love Me Vol 2 when it should be continuing passed it, so I added a check for the internalQuestProgress 
I ran it this ascension and didnt get stuck
=> add check for Palindome Stage 4 Status

RELEASE/scripts/autoscend/auto_acquire.ash, RELEASE/scripts/autoscend/auto_buff.ash
I was getting a "not in choice" rejection early game.
Removing visit_url("choice.php?pwd&whichchoice=835&option=2", true);
which is https://kol.coldfront.net/thekolwiki/index.php/Barely_Tales resolved it. I dont see why this would be part of acquire radio
In run
=> Remove Barely Tales choice from Detuned Radio Acquire

RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/paths/casual.ash, RELEASE/scripts/autoscend/paths/you_robot.ash, RELEASE/scripts/autoscend/quests/level_08.ash, RELEASE/scripts/autoscend/quests/level_09.ash, RELEASE/scripts/autoscend/quests/level_11.ash, RELEASE/scripts/autoscend/quests/level_12.ash, RELEASE/scripts/autoscend/quests/level_13.ash
restart clover usage when interrupted by June cleaver adventures, instead of aborting
in run
=> restart clover usage when interrupted by June cleaver

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/iotms/mr2021.ash, RELEASE/scripts/autoscend/paths/live_ascend_repeat.ash
Minor changes to account for combat frequency not working in LAR
No need for shoe gum or VIP hats that affect combat frequency
Validates
=> LAR Changes

RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/combat/auto_combat_util.ash, RELEASE/scripts/autoscend/iotms/mr2022.ash
User in discord reported that Avatar of Boris was trying to use parka. This is bad because Boris can't wear shirts.
Culprit was `auto_handleParka()`. Added check for torso there plus a couple other spots.
Validates
=> Parka check for torso

RELEASE/scripts/autoscend/iotms/mr2022.ash
recover stillsuit before trying to equip it, I don't know if it's the most efficient way to do it but seems needed to properly run with the last stillsuit changes after a familiar uses different equipment
not tested
=> stillsuit recovery hotfix

RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2022.ash, RELEASE/scripts/autoscend/quests/level_09.ash
Fixes #1219 by breaking out logic to prep for smut orc logging camp into it's own function. Then calling this new function in pre-adv. This way regardless of why we are adving in the logging camp (normally or via shen snakes), we always prep. Added check to not prep if bridge progress is complete.
Also adjusted autumnaton going to twin peaks even if user has camel. 
In normal standard seal clubber run
=> Move prep for smut orcs to pre adv

RELEASE/scripts/autoscend/iotms/mr2022.ash
Autumnaton can not be used in g-lover or pokefam
validates
=> Autumnaton path restrictions

RELEASE/scripts/autoscend/combat/auto_combat_quest.ash
In dino you can just use the magnet right away on gremlins
Yes
=> Use magnet for dinos

BUILD/monsters/replace.dat, RELEASE/data/autoscend_monsters.txt
Replacing beefy bodyguard bats in dino will cause a fight with the normal boss bat, bad for factoirds.
Sure
=> don't replace boss bat in dino

RELEASE/scripts/autoscend/auto_consume.ash
stillsuit doesn't need to be equipped to drink, also avoids having to add the extra steps to recover from another terrarium familiar
run
=> stillsuit doesn't need to be equipped to drink

RELEASE/scripts/autoscend/auto_equipment.ash
Adds missing commas to defaultMaximizeStatement
Running autoscend with mainstat > 122
=> Adds missing commas to defaultMaximizeStatement

BUILD/familiars/drop.dat, RELEASE/data/autoscend_familiars.txt, RELEASE/scripts/autoscend/auto_consume.ash
Add cookbookbat to drop familiars so that we generate ingredients, first prioritizing enough to be able to make a single tier 2 food and then generating excess ingredients so we can make multiple or make higher tier foods.
Prevent autoscend from ever trying to eat the 1x/ascension legendary Cookbookbat foods too, as 1) we don't have logic in place to stop trying to eat them after the 1st one 2) the player may wish to save them for aftercore or other purposes.
I've only done a single Standard day with this added (so not extensive testing, but also not a very complex change). During that day I generated significantly more turns – in my previous runs, it was using a lot of smiling rat and macaroni duck, and nearly all of those turns used Cookbookbat instead. The lost stat familiar turns are …
=> Add basic cookbookbat support

RELEASE/scripts/autoscend/iotms/mr2019.ash
Autoscend optionall uses the hewn moon rune spoon to tune the moon. Before doing that, it checks it has everything it wants from the sign you're leaving. This adds two new conditions:
1) If you have a cookbookbat, it'll buy a bugbear outfit before moving signs, so it can still buy dough.
2) If you are in LKS, it'll make sure you have a frilly skirt for the pirate unlock.
Two runs moving from knoll sign to canadia sign.
=> add dough for cookbookbat and frilly skirt for LKS to knoll sign

RELEASE/scripts/autoscend/auto_restore.ash
if pants increase max resource and auto discount pants to buy restore items will lower current resource so will buy restore item and auto discount pants to buy restore items will lower current resource so will buy restore item and auto discount pants to buy restore items will lower current resource so will buy restore item and auto discount pants to buy restore items will lower current resource so will buy restore item and auto discount pants to buy restore items will lower current resource so will buy restore item and auto discount pants to buy restore items will lower current resource so will buy restore item and auto discount pants to buy restore items will lower current resource so will buy restore item and auto discount pants to buy restore items will lower current resource so will …
=> prevent infinite loop by discount pants when buying from NPC store

BUILD/monsters/sniff.dat, BUILD/settings_extra/post.dat, RELEASE/data/autoscend_monsters.txt, RELEASE/data/autoscend_settings_extra.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_bedtime.ash, RELEASE/scripts/autoscend/auto_familiar.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/auto_zone.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/combat/auto_combat_default_stage1.ash, RELEASE/scripts/autoscend/iotms/mr2012.ash, RELEASE/scripts/autoscend/iotms/mr2013.ash, RELEASE/scripts/autoscend/iotms/mr2020.ash, RELEASE/scripts/autoscend/iotms/mr2022.ash, RELEASE/scripts/autoscend/paths/actually_ed_the_undying.ash, RELEASE/scripts/autoscend/paths/heavy_rains.ash, RELEASE/scripts/autoscend/paths/license_to_adventure.ash, RELEASE/scripts/autoscend/quests/level_13.ash
8-Bit realm got an overhaul. White pixels no longer needed to obtain the pixel key. Now we must adv in the 4 zones within the 8-bit realm to build points and buy the pixel key at 10k points.
This PR removes everything I could find with the old pixel key quest and replaces it with the new.
This won't result in optimal turns but I do respect which zone has double points so shouldn't be terrible. In particular providers for meat and item would be helpful. 
None yet. Only know it validates atm.
=> 8-Bit Realm Changes

RELEASE/scripts/autoscend/quests/level_13.ash
Currently mafia (r27115) doesn't reset the 8bit prefs on ascension. This change ensures the asc is equipped, which refreshes the prefs, prior to using them
In run
=> Ensure 8bit prefs are refreshed prior to using them

RELEASE/scripts/autoscend/quests/optional.ash
During Low Key Summer, we need to do the pirates unlock and join the crew. This isn't possible when the Island war is in Progress. This could previously cause a halt in the script.
Several HC LKS runs.
=> don't try to join the pirate crew when the war is in progress

RELEASE/scripts/autoscend/combat/auto_combat_util.ash
Adds divine champagne popper as a banisher
Several LKS runs. They're mostly used in the pyramid chambers once other stuff has run out. They're properly tracked on the relay status page as well.
=> add divine champagne popppers as a banish

RELEASE/scripts/autoscend/quests/level_12.ash
level 11 quest shouldn't get blocked now, but this is better in case of future changes to level 11
=> don't delay filthworms if level 11 quest blocked

RELEASE/scripts/autoscend/iotms/mr2021.ash
Automated purchase of the 1/day fireworks hats from the underground fireworks shop has been known to simply fail under unknown conditions for some time.  It is not clear if this is a mafia issue or a KoL issue, see https://kolmafia.us/threads/sometimes-unable-to-buy-limited-items-from-underground-fireworks-shop.27277/
This changes auto_buyFireworksHat() in mr2021.ash to, if retrieve_item() fails to acquire the specified hat, use visit_url() calls to get the hat instead.
Code primarily attributed to Zdrvst (#3286685) from their personal scripting; I only put it in this file and added support for the other two hats.
Prior to making these changes to my local copy, autoscend would consistently fail out when attempting to buy a fireworks hat at the start of the day/run, for a total of about 20 …
=> use visit_url to buy fireworks hats if retrieve_item fails

RELEASE/dependencies.txt, RELEASE/scripts/autoscend/combat/auto_combat.ash, RELEASE/scripts/autoscend/iotms/mr2016.ash, RELEASE/scripts/autoscend/iotms/mr2018.ash, RELEASE/scripts/autoscend/paths/pocket_familiars.ash
Some dependencies can be installed through git or SVN. For those which can be, check whether they have been installed through either git or SVN.
I can confirm the interior of the `if` returns the appropriate result for git scripts, though I haven't run it in-run.
=> fix: also check for git installed deps

RELEASE/scripts/autoscend/quests/level_any.ash
Need to actually have a workshed in order for the existing shed check vs desired shed check to be useful
Added code and it used my model train set after having not used it
=> Workshedfix

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/iotms/mr2021.ash
This reverts commit 742c0e5ecee4ff387ffd03869160fe0b3b9098a0.
Should be no longer required as it looks like the mafia issue has been fixed. Also updated min mafia version.
Ran day 1 & started day 2 in Normal Standard SC run. Seems to work fine but it wasn't always reproducible and I don't recall if my test account hit the issue in the first place.
=> Revert "use visit_url to buy fireworks hats if retrieve_item fails (#1245)"

RELEASE/scripts/autoscend/quests/level_any.ash
Some paths can't use worksheds so force setWorkshed to return false
There wasn't any
=> Don't use worksheds in some paths

BUILD/familiars/drop.dat, RELEASE/data/autoscend_familiars.txt
When I initially added Cookbookbat support, I made it conservative in terms of generating ingredients so that CBB wouldn't monopolize our familiar turns. However, in HC standard this means it generates a few ingredients and then falls back to a starfish-type familiar, which isn't very worthwhile.
After discussing a bit in Discord, we thought it'd be better to just add a final fallback if all other drop familiar conditions are met to keep generating ingredients.
TBH I haven't tested it yet, and don't plan to be in-run for a bit, but it's a simple change and I'm not concerned. The biggest reason to test would be to understand if there are loadouts/paths where this holds onto CBB too much.
=> Add fallback for generating Cookbookbat ingredients

RELEASE/dependencies.txt, RELEASE/scripts/autoscend/iotms/mr2019.ash
Follow-up to #1242.
Comb-Beach cannot be installed using git and so will stop being installable at the end of 2023.
I ran the function manually. From looking at the code, `CombBeach free` and `combo {advCount}` (and also plain `combo`, but that one might fail if you have no combs left) should do the same thing.
=> refactor: use combo over Comb-Beach

RELEASE/scripts/autoscend/quests/level_any.ash
Issue reported in discord. Per Malibu, Pete gets a still but also whatever workshed you install. So no special treatment needed here
Validates
=> Let Pete use a Workshed

RELEASE/scripts/autoscend/auto_util.ash
Reported in Discord, thanks Hippo. 
Validates
=> Fix missing escape character for parka NC detection

RELEASE/scripts/autoscend/auto_util.ash
Tracking of forced NCs needs the exact NC name, separated by commas. Commas inside NC names have to be escaped. This one wasn't.
Doesn't prevent it running.
=> Add escaped comma to forced NC name

BUILD/familiars/item.dat, BUILD/familiars/stat.dat, RELEASE/data/autoscend_familiars.txt
Added Hobo in Sheep's Clothing under #Fairyballs in item.dat and stat.dat. Hobo drops have not been factored in yet.
I had a Grouper as the item drop familiar consistently. In this fork it successfully switched it over to Hobo for default item drop familiar.
=> Added basic usage of Hobo in Sheep's Clothing

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/iotms/mr2022.ash
Use the new `equipped_amount(item, true)` function to check all familiars for equipped items. This means the custom loop is unnecessary. On the downside, it will now check familiars for all items; on the upside it will now find items equipped on the hand / left-hand man / hatrack / scarecrow.
Also use `retrieve_item` instead of manually going over familiars to get the stillsuit. `retrieve_item` should steal the item from any user's familiar if equipped.
Ran with it, it unequipped the stillsuit from the pet rock and stuck it on the Grinning Turtle. 
Also it drank the distillate later.
=> fix: retrieve stillsuit from unusable familiars

RELEASE/scripts/autoscend/auto_consume.ash
Some items in the game generate consumables so we use them before deciding diet. This now adds two more the (nearly useless) booze bindle from Oliver's place, and the actually-probably-a-useful-nightcap Boozehounds anonymous gold token from drunk pygmies.
2 HC runs.
=> Use boozehounds anonymous token

RELEASE/dependencies.txt
dependency.txt is missing the release branch for combo
git installed
=> Update combo dependency to match other scripts (missing release branch)

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/iotms/mr2023.ash
Reported in Discord. Gravel is being used on Eldritch Tentacles. However
```
> ash $monster[Eldritch Tentacle].attributes.to_lower_case().contains_text("free")
> ash $monster[Witchess Knight].attributes.to_lower_case().contains_text("free")
Returned: true
```
I have a [mafia PR](https://github.com/kolmafia/kolmafia/pull/1590) in to change that so Eldritch Tentacles are correctly marked as `FREE`. Once that's merged I'll add the version update to this PR too.
Validates. My test account doesn't have 2023 IotMs yet and the conditions to trigger this would need a lot of synthetic setup (need to have `nextAdventure` set to The Haunted Bathroom, The Haunted Gallery or The Haunted Bedroom before fighting a tentacle).
=> don't use gravel on inherently free monsters

RELEASE/scripts/autoscend/auto_pre_adv.ash
In Actually Ed, Fist of the Mummy is sufficient to damage ghosts, so when checking to see if the player can damage ghosts, check if the player has that instead of checking for Storm of the Scarab.
Has not been tested, shouldn't need testing.
=> Fist of the Mummy can damage ghosts

RELEASE/scripts/autoscend/combat/auto_combat_default_stage2.ash
Add shadow bricks to the possible instakill options.
Ran with shadow bricks. It used them in the war. It funkslung them until it only had one left, but I think that's fine, as the first one kills and then the second is unused.
=> feat: use shadow bricks to freekill if available

RELEASE/scripts/autoscend/quests/level_11.ash
Basically, Spookyraven cannot be done the traditional way so we need to ensure that the script doesn't try to get the wine bomb in Hardcore and that it gets the ingredients. Checked manually earlier today
Please include a summary of the change. Pull requests should always be against the [main branch](https://github.com/Loathing-Associates-Scripting-Society/autoscend/tree/main).
Testing ASH scripts is tricky and generally involves you doing multiple runs with a change to see how it performs. If you did any particular tests, or have particular tests you would like to do but cant (e.g. need to …
=> Zombie Slayer Update For Spookyraven

RELEASE/scripts/autoscend/quests/level_any.ash
Added text mentioned by Malibu Stacey; tested manually
Please include a summary of the change. Pull requests should always be against the [main branch](https://github.com/Loathing-Associates-Scripting-Society/autoscend/tree/main).
Testing ASH scripts is tricky and generally involves you doing multiple runs with a change to see how it performs. If you did any particular tests, or have particular tests you would like to do but cant (e.g. need to test with an expensive item you dont have access to) please mention that here. Relevant Mafia session logs may also be helpful.
=> Zombie Slayer must go Junkyard route for island

RELEASE/scripts/autoscend/iotms/mr2022.ash
There is a check for if the player can drink before choosing the June Cleaver option that gives Dad's Brandy, but there isn't a check for if the player can specifically drink Dad's Brandy. This changes the check to be more specific, because several paths can drink but can't drink the brandy. 
A similar change could be made for guilty sprouts, but it's a less trivial change because the current behavior is to take guilty sprouts even if the player is too low-level to currently eat them.
Minimally tested in-run as Jarlsberg.
=> Check if we can drink Dad's Brandy specifically before choosing it

RELEASE/scripts/autoscend/auto_pre_adv.ash
Fixes 
level_11.ash shrugs Ur-Kel then pre_adv applies it again, increasing ML and wasting MP every turn
in run
=> don't re apply ML buff in copperhead pre_adv

RELEASE/scripts/autoscend/auto_pre_adv.ash
If the next location to adventure in has monsters that could be added to the locket, equip it automatically
in progress
=> equip the combat lover's locket if monsters are missing from the next zone

RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/combat/auto_combat_default_stage5.ash
Handling of physically immune monsters can be improved per discussion in Discord.
Added more Avatar skills to prep for ghosts command. I'm not familiar with many of these paths, so please comment if I should have picked different skills or simply add a couple more.
Removed abort for seal clubbers if can't find spell to do damage to ghosts. Added check that simply attacking will deal damage to ghosts towards end of combat stage 5. In theory this check isn't needed if prep for ghosts in preadv worked properly.
Did a few standard seal clubber runs. This is just to confirm I didn't make anything worse. Didn't actually test on a previously failing class
=> Improve Ghost Combat for Avatar Classes and Simply Attacking

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_bedtime.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2017.ash, RELEASE/scripts/autoscend/iotms/mr2023.ash, RELEASE/scripts/autoscend/paths/avatar_of_west_of_loathing.ash, RELEASE/scripts/autoscend/quests/level_11.ash, RELEASE/scripts/autoscend/quests/level_12.ash, RELEASE/scripts/autoscend/quests/level_13.ash
This adds helper functions for the cursed paw, with wish tracking and one initial use (sleaze damage for the zeppelin). More can be added later.
At the moment, I left the use protected behind the auto_useWishes preference being true. I'm not sure if that's appropriate, and I'm more than happy to change it before merging.
3 HC Standard runs worked fine.
However, the zeppelin code also interacts with the Genie Bottle code, and I don't have a Genie bottle. Can someone else test this please?
=> Initial cursed paw support

RELEASE/scripts/autoscend/iotms/mr2023.ash
Mafia halts scripts when a monkey_paw() call returns false, so we have to avoid that. Explicitly check user hasn't maxed out their wishes before trying.
gCLI:
```
> ash import <autoscend> ; auto_makeMonkeyPawWish($effect[Frosty]);
[INFO] Out of monkey paw wishes for Frosty
> ash import <autoscend> ; auto_makeMonkeyPawWish("frosty");
[INFO] Out of monkey paw wishes, skipping frosty
> ash import <autoscend> ; auto_makeMonkeyPawWish($item[rusty hedge trimmers]);
[INFO] Out of monkey paw wishes, skipping rusty hedge trimmers
```
=> add explicit checking for all monkey paw wishes used

RELEASE/data/autoscend_settings.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_bedtime.ash, RELEASE/scripts/autoscend/auto_consume.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/autoscend_record.ash
This PR is to add emergency bedtime handling when rollover is fast approaching.  The time setting auto_stopMinutesToRollover (default 5) determines when autoscend will stop its normal run, consume as much as it can (without wasting too much adv to the rollover limit), and do bedtime.  This is to prevent autoscend terminating without proper bedtime processing due to rollover.  This feature can also be used just to stop the day's run early; for example, if you have somewhere to be 2 hours before rollover, set auto_stopMinutesToRollover to 125 or so.
Before testing, I put an abort() statement in doBedtime() just after the if block that tests (! almostRollover()).  This prevents bedtime from being done so I could resume my run for another test.
In the GUI, I set auto_stopMinutesToRollover to …
=> Emergency bedtime when rollover's fast approaching

RELEASE/scripts/autoscend/iotms/mr2023.ash
User in discord reported Ed is broken due to issue with resting. Issue is trying to restore cinch when there is nowhere to rest.
Ascended as Ed, got error, changes in PR fix error.
=> can't rest if we don't have spot to rest

BUILD/settings/any.dat, BUILD/task_order/Legacy Of Loathing.dat, BUILD/task_order/default.dat, RELEASE/data/autoscend_task_order.txt, RELEASE/scripts/autoscend/auto_adventure.ash, RELEASE/scripts/autoscend/auto_choice_adv.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/clan.ash, RELEASE/scripts/autoscend/iotms/mr2016.ash, RELEASE/scripts/autoscend/iotms/mr2021.ash, RELEASE/scripts/autoscend/paths/heavy_rains.ash, RELEASE/scripts/autoscend/quests/level_08.ash
* Remove special monster handling in heavy_rains.ash, this is unnecessary now
* Add a few extra summons in heavy rains to match old special summoning behavior, imo this could be extended to do even more summons there's a ton of rain man summons available
* Check if a monster can be summoned by first checking manual, then checking the rain man page text if no factoids are available
* Handle escaping from Rain Man if the summon fails
* Don't back up if nextLocation is Noob Cave or None, as these are used to denote monsters fought without a location (all summons for example). This was causing my rain man summoned monster to allow backing up, and of course that worked and I lost the summon.
* don't manually verify time-spinner minutes if speculating
* equip the combat lover's locket if …
=> refactor rain man to be called from summonMonster

RELEASE/scripts/autoscend/paths/casual.ash
Issue reported in Discord. Upon breaking ronin, script attempted to buy and use several fams. This should prevent that
User in Discord which had this issue manually made these updates, restarted Mafia, and it started working
=> Don't mall buy and use fams in Legacy of Loathing

RELEASE/scripts/autoscend/paths/legacy_of_loathing.ash
Previously, in Legacy of Loathing, the script would reportedly buy replicas that were already owned once the player had enough progression to loop past 2004 replicas. This adds a proper check for if the player owns a replica, or the familiar from a replica, before buying that replica again.
Untested, I don't have an account with enough progression.
=> Legacy of Loathing progression fix

BUILD/monsters/replace.dat, RELEASE/data/autoscend_monsters.txt
Prevents the path boss bat from being fought. Also fixed a comma instead of a semicolon.
Yes
=> Don't replace bats in legacy of loathing

RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/autoscend_header.ash
Mafia now has `modifier` as a type. Can not be a variable name
Validates
=> Hot Fix - Modifier now a type, can't bee variable name

RELEASE/scripts/autoscend/iotms/mr2015.ash
Issue reported in discord of autoscend looping and not doing anything. Cause was we think we have chateau but actually don't.
Not sure why we had a visit_url to see if chateau was in the mountains. Removed as the chateau is in the mountians in LoL, even if you haven't bought it yet. Cause of loop. 
validates
=> Fix Chateau in LoL

RELEASE/scripts/autoscend/iotms/mr2018.ash
fix wrong item id for replica tote in legacy of loathing
yeah
=> fix tote in lol

RELEASE/scripts/autoscend/iotms/clan.ash
Reported in Discord.
G-Lover can't use the photocopy to fight the faxed monster so don't bother trying to use the fax in the first place.
Validates. I ain't getting into a G-Lover run just to try this.
=> G-Lover can't use faxes so don't try to acquire

RELEASE/scripts/autoscend/paths/legacy_of_loathing.ash
After adding support to buy the LoL Patriotic Eagle in #1318 , this adds logic to skip the Patriot Eagle if in a 100% Familiar Run (continuing the logic/idea from #1313) .
Tested in the start of a new run today. Found and fixed a bug where the is100FamRun() wasn't checked first (not having it first led to the 'else' condition from line 50 not being met, halting the script). Works fine now.
- [ x ] My code follows the style guidelines of this project.
- [ x ] I have performed a self-review of my own code.
- [ x ] I have commented my code, particularly in hard-to-understand areas.
- [ x ] I have based my pull request against the [main branch](https://github.com/Loathing-Associates-Scripting-Society/autoscend/tree/main) or have a good reason not to.
=> Lo l 100% fam

RELEASE/dependencies.txt, RELEASE/scripts/autoscend/combat/auto_combat.ash, RELEASE/scripts/autoscend/paths/pocket_familiars.ash
Due to https://github.com/kolmafia/kolmafia/pull/1815, Helix-Fossil no longer works. Point at my fork instead until the PR is merged.
It hasn't.
=> fix: use forked version of Ezandora's script broken due to modifiers change

RELEASE/scripts/autoscend/paths/legacy_of_loathing.ash
Updating logic for Patriotic Eagle boolean based on feedback in Discord. Also removing the first 'else' when starting to look at legacy IoTMs
This updates the Legacy of Loathing boolean for purchasing a Patriotic Eagle hatchling
Fixes (Cleans up code to make a discord reported halt easier to diagnose)
Not tested, but thought through with HippoKing in Discord chat. Updated file passes Mafia validate command/routine.
- [ x ] My code follows the style guidelines of this project.
- [ x ] I have performed a self-review of my own code.
- [ x ] I have commented my code, particularly in hard-to-understand areas.
- [ x ] I have based my pull request against the [main branch](https://github.com/Loathing-Associates-Scripting-Society/autoscend/tree/main) or have a good reason not to.
=> Updating Patriotic Eagle boolean

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_buff.ash, RELEASE/scripts/autoscend/auto_post_adv.ash, RELEASE/scripts/autoscend/auto_providers.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2023.ash, RELEASE/scripts/autoscend/quests/level_any.ash
Uses the 2002 Mr. Store
Buys:
Meat Bulter for RO Adv
Detect Secret Doors as it is a good skill
Black Monolith for stats
Crimbo cookies for HC LoL runs... should we expend this to more options?
Idol Microphone for buffs
Doing a normal standard run and it is working well. Buys butler, monolith, and mic. Saw it use the mic properly as well for modern zombie init
=> 2002 support

RELEASE/scripts/autoscend/iotms/mr2017.ash
makeGeniePocket() now uses the replica genie bottle if that's what the user has, not just the genie bottle
I changed the line in my Mafia's scripts/autoscend/iotms/mr2017.ash that I changed here, and ran autoscend (again).  I observed that my LoL bedtime was able to complete, when it wasn't before.
- [ x] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ x] I have based my pull request against the [main branch](https://github.com/Loathing-Associates-Scripting-Society/autoscend/tree/main) or have a good reason not to.
=> Allow makeGeniePocket() to use replica bottle

RELEASE/scripts/autoscend/quests/level_12.ash
Fixes an issue where softcore legacy of loathing runs fail to acquire the pre-war hippy/frat outfits and from there the war hippy/frat outfits and thus do not start the war.
Without these changes autoscend is perpetually stuck in a loop of powerlevelling when it finishes doing everything other than the war or quitting when it reaches level 13. With these changes it starts the war. I've only tested it on 1 run so far.
=> Softcore Legacy of Loathing L12 fix

RELEASE/scripts/autoscend/combat/auto_combat_default_stage4.ash, RELEASE/scripts/autoscend/iotms/mr2017.ash, RELEASE/scripts/autoscend/iotms/mr2023.ash
Couple fixes for red rocket usage
1 Remove check for billiards. This relied on always consuming booze before food. This is no longer true.
2 Added fullness check. Only need to use red rocket if we can still eat today. Save some meat
Misc Fixes
1 Gather 2002 store credits
2 Can't wish for fantasy bandit, ninja snowman assassin, modern zmobie
Also using this PR to try out making a branch in the main repo rather my fork
=> Fixes for Red Rocket, 2002 Store, and Wishing

RELEASE/scripts/autoscend/auto_pre_adv.ash
Small graphical fix. pre adventure was reporting +- when the bonus was negative. ex:
`[INFO] mus: 83 + -55. mys: 138 + -113. mox: 92 + -56`
fixed to only add a + if it is a positive value that need sit.
tested with negative values.
`[INFO] mus: 83-55. mys: 138-113. mox: 92-56`
tested with positive mods
`[INFO] mus: 1430+287. mys: 1947+1850. mox: 1430+644`
=> auto_pre_adv.ash reports negative stat modifiers for stats as +-

RELEASE/scripts/autoscend/paths/small.ash
* get beehive. wall is too difficult without it
* get boning knife. wall is too difficult without it
* ignore flyer in hardcore. being small means you very often die when using it. and in hardcore access to workarounds is restricted. Ideally this would be replaced with a more detailed check & fix in the future.
* do not get [steel margarita]. can only consume size 1 drinks
fixes #1350
validates
=> extra settings for [A Shrunken Adventurer Am I]

RELEASE/scripts/autoscend/quests/level_12.ash
autoscend wouldn't start the battlefield since flyering in HC was disabled in the small.ash but the war plan didn't check to see if this preference was set.  I'm checking the preference directly instead of the path as I suspect this is also broken if someone were to manually set the preference or in paths where it's set but the path isn't subsequently checked in the war plan.
This was tested in a Hardcore A Shrunken Adventurer am I! run.
=> Don't consider the arena if auto_ignoreFlyer is set.

RELEASE/scripts/autoscend/auto_post_adv.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/quests/level_08.ash
* generic infinite loop catcher. warns if no adv was spent for 10 adv in a row. aborts once it reaches 30 in a row.
* boolean L8_trapperGroar() fixes
* cleanup the code for checking for groar issues.
* added potential catching of insufficient cold res causing inf loop
* abort and inform player to finish it and report the issue.
* added option to ignore it for rest of day and go do other stuff
I got my main stuck in inf loop at groar fight because kol bug where a recently added +3 cold res buff does not actually provide any cold res.
I tested it there and it correctly caught the infinite loop. Both reporting it and aborting once it reached 30 loops without spending an adv.
with the groar fixes added in. it aborted sooner and reported the issue specific to that problem.
the setting it …
=> generic infinite loop detection & better L8_trapperGroar() problem detection and handling

RELEASE/scripts/autoscend/auto_bedtime.ash
I'm a seal clubber. Noticed Drunkula's Cape was pulled for RO advs. Problem is only sauce gets that bonus
Works
=> Don't pull RO gear our class doesn't get a bonus for

RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/combat/auto_combat_default_stage5.ash
Should fix #1342.
Adds pungent mung and beanstorm from AoWoL to valid spells for fighting ghosts.
Requires enemy physical resistance to be under 80 to use fan hammer.
Untested, please test.
=> AoWoL Ghost Fighting support

RELEASE/scripts/autoscend/iotms/mr2023.ash
Noticed my free rests weren't being used in small. Turns out we're always stuck on a big rock to rest in/on (how does that work anyway?). The only time free rests are used otherwise is by the restore code (when we have used some cinch).
Personally I think the clause itself should be removed completely as it will block using rests to charge Cincho before hitting level 9 and the extra 40 HP & MP from having the Frobozz House isn't going to be that important but I'll have to test that separately in a Standard run.
Current run without this change has used:
In progress. My test account just finished day 1 of a Normal Small run so I'll let it run day 2 after rollover & then jump back into another run to test it properly.
=> Add exception for Small path when checking if we can use free rests when restoring cinch.

RELEASE/scripts/autoscend/auto_consume.ash
HC small was first path to allow eating legendary pizzas. This should have been added then
Old behavior:
```
ash import<autoscend.ash> auto_autoConsumeOneSimulation("eat").name
Updating inventory...
Preference _concoctionDatabaseRefreshes changed from 14 to 15
Returned: Pizza of Legend
```
New behavior:
```
ash import<autoscend.ash> auto_autoConsumeOneSimulation("eat").name
Updating inventory...
Preference _concoctionDatabaseRefreshes changed from 15 to 16
Returned: Calzone of Legend
```
=> Eat each legendary pizza once per life

RELEASE/data/autoscend_familiars.txt, RELEASE/scripts/autoscend/auto_acquire.ash, RELEASE/scripts/autoscend/auto_adventure.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/paths/you_robot.ash, RELEASE/scripts/autoscend/quests/level_08.ash, RELEASE/scripts/autoscend/quests/level_09.ash, RELEASE/scripts/autoscend/quests/level_11.ash, RELEASE/scripts/autoscend/quests/level_12.ash, RELEASE/scripts/autoscend/quests/level_13.ash
Had most of this kicking around for a while and been meaning to put it up for review so it's been pretty well tested but I will give it one more run since I cleaned up the code a bit for this PR.
This will now cause us to hold on to an 11-leaf clover in hardcore in paths which we are required to get the Wand of Nagamar.
It will only do this from day 2 onwards so day 1 clovers can all be used. If anyone manages to get the script to do 1 day Unrestricted runs, more power to them but it's not the remit of this script.
We don't need to do this in Normal runs because we already pull the components of the wand we don't already have (which I guess it could be all of them but that is still just 2 pulls and we would pull a clover if we are still able to before attempting to pull the components …
=> Refactor clover handling and save clovers in hardcore for wand

RELEASE/scripts/autoscend/combat/auto_combat.ash
Basically, sometimes you'll abort during a war boss fight that you can probably handle because we assume combat is 30 rounds, when these specific fights can go to 50.
I'll run it through small tomorrow.
=> Longer war boss fights

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_consume.ash, RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/auto_familiar.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2023.ash
Reported in discord that LoL doesn't have a mosquito. This fixes that by instead of hardcoding a familiar we expect to have, instead search for an actually available familiar
Did a normal standard run without issue
=> Don't assume we have a mosquito when searching for a default familiar

RELEASE/scripts/autoscend/combat/auto_combat_default_stage2.ash, RELEASE/scripts/autoscend/combat/auto_combat_ed.ash, RELEASE/scripts/autoscend/combat/auto_combat_util.ash
Currently double-use waffles. Trying to update code so that it doesn't do that.
Running through normal Standard Sauceror for as quick a run as possible.
=> Don't double-use waffles

RELEASE/scripts/autoscend/iotms/mr2022.ash
Trainset gives lots of xp. Don't need to double mainstat until level 13. This changes makes it so we double lumber mill at level 11 instead of 13. With the hopes of getting more CMC consults D1 since we will finish building the bridge sooner
D1 of normal standard run went well. Still only got 1 consult in, homebodyl. However I got unlucky with bridge part drops. Had a 30/47 split. Change worked as intended - when I hit 11, train set was confgured to double lumber mill instead of mainstat. Still got to level 14 end of D1, so leveling isn't an issue on a shiny account
=> Coal lumber mill at lvl 11 instead of 13

BUILD/monsters/sniff.dat, BUILD/task_order/Avatar of Jarlsberg.dat, BUILD/task_order/Legacy of Loathing.dat, BUILD/task_order/Quantum Terrarium.dat, BUILD/task_order/Zombie Slayer.dat, BUILD/task_order/default.dat, RELEASE/data/autoscend_monsters.txt, RELEASE/data/autoscend_task_order.txt, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/auto_zone.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/quests/level_13.ash
Use the 8-bit realm zones as delay zones.
Ran lots of Standard & Small with the initial draft of these changes. Backups of Fantasy Wanderers are always placed in an 8-bit zone. Haven't seen any other uses of them as there is so much delay in the game and I worked on the task order to open as many as possible a long time ago.
=> use 8-bit realm zones for wanderers

RELEASE/scripts/autoscend/iotms/mr2021.ash
Pull breathitins. We have extra spleen in standard, let's use it. For out of standard, put conditional to not pull if we have spleen fam or can interact. Figure we have better choices then?
Going to do a small normal run. D1 went well. Pulled at start and used right away, no charges wasted on other free outdoor fights
D2 went well too.
=> pull breath

BUILD/familiars/item.dat, BUILD/familiars/meat.dat, BUILD/familiars/stat.dat, RELEASE/data/autoscend_familiars.txt
Previously was incorrectly requiring 2 candles to prioritize Jill's extra 50% bonus's. Actually just need 1
CLI. Have 1 LED candle in inventory. `autorun` is my alias to easily import and run autoscend commands
Before
```
> autorun lookupFamiliarDatafile("meat")
[DEBUG] lookupFamiliarDatafile is checking for type [meat]
Returned: Hobo Monkey
```
After
```
> autorun lookupFamiliarDatafile("meat")
[DEBUG] lookupFamiliarDatafile is checking for type [meat]
Returned: Jill-of-All-Trades
```
=> Only need 1 led candle for jill

RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2021.ash
Summon and backup green ops soldiers. They progress L12 war regardless of where killed plus have a chance to drop smoke bombs for free runs. Smoke bombs are already supported
Normal small run. D1 it used locket to summon grops and then backed up until out of charges, as expected. 3 backups in this case. In days past it would have been 4. Some variability is expected.
=> summon and backup grops into delay

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2022.ash
Fixing a minor issue with delay burning using the CMG. I checked my log from my current run to see how it was handling using the 8bit zones to burn delay & noticed it failed to fight a void monster 3 times in a row in Vanya's Castle. Once the bonus zone changed to Megalo-City it equipped the CMG correctly & fought the void monster.
This change forces the CMG to be equipped in the off-hand slot when burning delay fighting a free void monster rather than relying on the maximizers weighting.
I also added a small change to when the CMG is equipped to charge it as we can pre-charge it for the next day when we still have delay to burn.
Hasn't yet. My test account is in Small but has finished day 1. I'll have it run day 2 after rollover then start a new day 1 to verify it's all as expected.
=> make sure CMG is equipped when burning delay and pre-charge it for subsequent days.

RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_restore.ash, RELEASE/scripts/autoscend/quests/level_09.ash, RELEASE/scripts/autoscend/quests/level_11.ash
This commit makes autoscend more aggressive about spending meat on combat MP. Specifically, it changes the meat_reserve param for many locations of pre-adventure MP logic to 0, allowing autoscend to spend all available meat to ensure there is MP before adventuring. "Pre-adventure" MP in this context means MP acquired after buffing and immediately before adventuring, mainly, combat MP.
- Removes hardcoded 1k meat reserve for acquireMP in auto_pre_adv
- Removes meat_reserve check when restoring MP to use skills to restore HP in auto_restore
- Updates early acquireMP in level_09 when checking for orc overkill to match pre_adv
- Removes meat_reserve check when restoring MP to kill specters in level_11
Fixes loathers/autoscend#842
Impacts loathers/autoscend#743: more spending on combat MP …
=> Uncap PreAdv MP Restore Spending

RELEASE/scripts/autoscend/quests/level_11.ash
Standard HC run ran out of stuff to do. Stuck at 10 desert left to explore and didn't find any monsters with ultrahydrated. This lets us continue if we finish everything else
Ran out of stuff to do in HC. Made this change, autoscend continued run
=> early exit for ultra-hydrated bofa wait

RELEASE/scripts/autoscend/auto_familiar.ash, RELEASE/scripts/autoscend/iotms/mr2021.ash
Noticed LED Candle wasn't being equipped, was using the tiny gold medal instead. This should fix that.
Also tweaked some of the CMC item choices to try to get more Breathitins. 
- Homebodyl is a waste of a choice and 2 spleen if you have the CBB and are in a knoll sign. My logs show it only ever being used for cooking because its charges are used first before the CBB (and I have 7 charges left when I ascend so we only use 4 anyway).
- Don't take the ice crown in Normal Small. I actually think this isn't much use generally as the only time I've seen it worn is for Aboo Peak & it's not actually needed there it's just the maximizer using it because it's available.
- Don't take food or booze in Small path. This might need better conditions in hardcore but for now lets not waste a use.
Run …
=> equip LED Candle and some CMC tweaks

BUILD/settings/any.dat, BUILD/settings_extra/any.dat, BUILD/settings_extra/post.dat, BUILD/task_order/A Shrunken Adventurer am I.dat, BUILD/task_order/Avatar of Jarlsberg.dat, BUILD/task_order/Legacy of Loathing.dat, BUILD/task_order/Quantum Terrarium.dat, BUILD/task_order/Zombie Slayer.dat, BUILD/task_order/default.dat, RELEASE/data/autoscend_properties.txt, RELEASE/data/autoscend_settings.txt, RELEASE/data/autoscend_settings_extra.txt, RELEASE/data/autoscend_task_order.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_settings.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/paths/avatar_of_boris.ash, RELEASE/scripts/autoscend/paths/grey_goo.ash, RELEASE/scripts/autoscend/paths/you_robot.ash, RELEASE/scripts/autoscend/quests/optional.ash
Removed some more preferences and their associated functions
- auto_doArtistQuest - unnecessary in-run.
- auto_noSleepingDog - unused since consumption was rewritten 3-4 years ago.
- auto_cookie - unused since the semirare & clover revamp, possibly even before that.
- auto_doArmory - unnecessary in-run.
- auto_doMeatsmith - unnecessary in-run.
Removed some unused Grey Goo functions that did nothing.
Changed a couple of maps I wrote for LKS to be static since I was in the file anyway.
Updated the minimum mafia version to r27660 as it has fixes for the maximizer when using the JoAT familiar.
Ran a few Normal Small runs on a couple of accounts. No issues.
=> Remove some more unnecessary prefs and related functions

RELEASE/scripts/autoscend/quests/level_09.ash
Inspired by Stacey's SDQ PR, Smut Orc Keepsake Boxes haven't been accounted for in fastener or lumber count. This fixes that, without needing to use them, which was only done in L9_chasmBuild, which is currently towards the end of the task orders.
Bought a keepsake box in aftercore and called fastenerCount and lumberCount from the cli.
=> Account for Smut Orc Keepsake Boxes in Bridge Part Counts

RELEASE/scripts/autoscend/auto_pre_adv.ash
Dismissing vampieroghi thrall when going to hidden apartment building. We never bind the vamp thrall, but it is possible to manually do it and we should handle that.
Issue reported in discord
Validates
=> unbind vampieroghi at hidden apartment building

BUILD/task_order/A Shrunken Adventurer am I.dat, BUILD/task_order/Avatar of Jarlsberg.dat, BUILD/task_order/Legacy of Loathing.dat, BUILD/task_order/Quantum Terrarium.dat, BUILD/task_order/Zombie Slayer.dat, BUILD/task_order/default.dat, RELEASE/data/autoscend_task_order.txt, RELEASE/scripts/autoscend/auto_routing.ash, RELEASE/scripts/autoscend/autoscend_header.ash
Reported in Discord. Some people are being blocked with just the Pyramid to finish as I didn't add the softblock handling for underground adventures to the other task orders files. I was already working on this which fixes the issue.
validates. I'll jump into Normal Standard just to double check it all works fine.
=> copy small task order to default

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/clan.ash
Should fix the issues with cheesefax being offline, as reported in Discord.
I ran `ash import <autoscend> ; zataraClanmate()` and confirmed it returned false.
=> fix: check if a player is online before trying consults

RELEASE/scripts/autoscend/combat/auto_combat_default_stage1.ash
Reported in discord. User in HC Oxycore. Was backing up NSA into end of day free fights. Got to critically low turns (<2) while doing end of day free fights and aborted. Doesn't expect adv's to be used while free fighting. 
This should fix backing up from a free to a not free fight when low on advs.
Validates
=> Don't backup away from a free fight at end of day

RELEASE/scripts/autoscend/auto_consume.ash
Reported in discord. Not respecting `auto_limitConsume` in Small. Added more than is strictly necessary but it won't hurt to check it in more of the consumption functions.
validates. I'd need to wait until after rollover to test it & I also don't see the point of `auto_limitConsume` because I'm not worried about a robot not playing optimally enough for me that I want to repeatedly intervene.
=> add more checks of auto_limitConsume

RELEASE/scripts/autoscend/auto_pre_adv.ash
Adds new function, low_mp_handler, that calculates and acquires target MP numbers when the max is below 32.
This function includes readable and configurable properties, MIN_USEFUL_MP and TARGET_MP. These properties are currently designed to ensure we can cast the maximum number of Saucestorms in each fight.
Adds low_mp_handler to both the main logic and the 'Can we kill ghosts?' logic.
Updates the 'Can we kill ghosts?' logic to unreservedly use our meat when restoring MP for ghost killing, matching other recent changes.
Partially addresses https://github.com/loathers/autoscend/issues/743 - just needs a <6 MP case, possibly aborting.
Tested on a non-shiny hardcore run to ensure performing as expected. MP targets accurately selected and adjusted as max MP grows. Tested for several days on …
=> Add MP Handling < 32

BUILD/task_order/default.dat, RELEASE/data/autoscend_task_order.txt
When I updated the default task order in #1390 I "accidentally" removed LM_edTheUndying, LX_bugbearInvasion and LX_lowkeySummer from it. This restores them.
These should go in their own task order files since at least 2 of the 3 I wrote as custom routing for those paths before the task order functionality was created by Rinn but that's tech debt for a future contributor I guess.
validates. I'm not running all 3 of those paths to check it.
=> re-add Ed, bugbear & LKS functions to default task order

RELEASE/scripts/autoscend/auto_choice_adv.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/iotms/mr2022.ash, RELEASE/scripts/autoscend/quests/level_any.ash
Make KoE Great Again
Recent IOTM and 8-Bit Realm changes were preventing autoscend from doing anything in KoE path.  This cleans those up (and now lets it run!), fixes a NC choice in Haunted Library, and adds some descriptors in auto_choice_adv for ease of review.
Two KoE runs, one softcore and one hardcore
=> KOE and auto_choice_adv Cleanup

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_sim.ash, RELEASE/scripts/autoscend/autoscend_header.ash
Let autoscend accept an optional `sim` parameter to print if you have required, suggested, and marginal things
Things and descriptions taken from prior similar effort, which was a separate script. This PR incorporates it as part of autoscend.
https://github.com/JamesDowney/kol-json-suggestions
Formatting of display generally taken from Kas's scripts
Bat recipes and combat locket monsters are only shown if you own the respective iotm
Tested on my main which has everyone. And on my testing alt which doesn't have much
Main:
Alt:
=> Create sim function

RELEASE/scripts/autoscend/iotms/mr2022.ash
You can't eat guilty sprouts in Dark Gyffe or Avatar of Jarlsberg, so autoscend should avoid getting them in those paths.
=> Vampyres can't eat guilty sprouts

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/combat/auto_combat_default_stage2.ash, RELEASE/scripts/autoscend/combat/auto_combat_ed.ash, RELEASE/scripts/autoscend/combat/auto_combat_util.ash
Quick fix adding Everything Looks Green to any instance of standard free runs
Running it on D2 and D1 of standard HC runs. Only had one instance of ELG over both of those so will force it to have it on a normal run, but there's no real reason why it shouldn't work fine.
=> ELG added for standard free runs

RELEASE/scripts/autoscend.ash
Autoscend doesn't support Community Service, but the check for whether a player is in a Community Service run happens a lot later than desirable if you happen to be tired and ascend into the wrong path or run the wrong ascension script without realizing until it's too late to reverse the damage.
I ran autoscend in CS and it aborted before doing things it probably shouldn't do if it is just about to abort.
It's the same exact check as before, just moved closer to startup so that if someone runs autoscend in CS they don't get clubbed for it.
- [x ] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ x] I have based my pull request against the [main …
=> Abort earlier if run in Community Service

RELEASE/scripts/autoscend/auto_restore.ash, RELEASE/scripts/autoscend/iotms/mr2017.ash, RELEASE/scripts/autoscend/iotms/mr2019.ash, RELEASE/scripts/autoscend/quests/level_any.ash
Avoid a warning due to the mismatched name after the change. Requires at least r27735 but the script already requires r27772.
Did a run (in Standard, but Mafia parsed the items okay).
=> fix: Asdon Martin keyfob name change

RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/iotms/clan.ash
A follow-up to #1380. Use OnlyFax instead of CheeseFax. The cycle continues!
I haven't, but the numbers look right.
=> feat: replace CheeseFax with OnlyFax for Zatara consults

RELEASE/scripts/autoscend/auto_providers.ash
Lyle can give Peppermint Rush, which might be useful for the modern zombies / 8-bit if we happen to not have enough turns from previous Surprisingly Sweet Slashes.
Did a run; it was used in Vanya's Castle.
=> feat: get Peppermint Rush from Lyle before init tests

RELEASE/scripts/autoscend/quests/level_any.ash
When deciding where to go with drones out, don't go to Twin Peak if we already have enough hedge trimmers (e.g. if autumnaton was sent out and returned).
Hasn't yet. Hit the bug last run, will see if I hit it again.
=> fix: don't go to Twin Peak with drones if enough trimmers

RELEASE/scripts/autoscend/combat/auto_combat_default_stage2.ash, RELEASE/scripts/autoscend/combat/auto_combat_util.ash
Only try to Monkey Slap if no wishes have been used today.
Also contains a couple of other fixes around banishes / runaways:
* `auto_combat_util.ash` was slinging GSBs with `, nothing` but `auto_combat_default_stage2.ash` was matching on `, none`
* The latter file was also always matching on `, none`, but the player might not have Ambidextrous Funkslinging.
Did a run, all went smoothly.
=> fix: can only Monkey Slap if no wishes have been used

RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/quests/level_13.ash
If we have a spooky test at the NS tower, we may fail to cast dirge due to already having max songs (from the init / stat tests).
Shrug once before remastered dirge / dirge to avoid this. 
If I hit spooky at the tower I'll see if it fixes the problem. Might take a while ;)
=> fix: don't fail to cast dirge at NS tower

RELEASE/scripts/autoscend/auto_equipment.ash
As title
Hasn't. I have never encountered this issue myself but hopefully this helps us provide some info to the mafia devs. Validates.
=> add debugging & workaround for maximizer empty hands issue

RELEASE/scripts/autoscend/auto_equipment.ash
Just removing the abort & adding a maximize call to workaround the bug. Kept a warning message so people can search logs if required in future for mafia devs.
Hasn't. Again, I'm unable to reproduce this myself. Validates.
=> Maximizer no weapons bug: remove the abort, add another maximizer call to workaround the bug.

RELEASE/scripts/autoscend/auto_bedtime.ash
Return `false` for stooper use in smol to fix bedtime. Stooper is not increasing liver in smol, so it should not be used.
Fixes #1423
I applied the fix and bedtime is working now.
=> Disallow using stooper in smol because of organ restrictions

RELEASE/dependencies.txt, RELEASE/scripts/autoscend/combat/auto_combat.ash, RELEASE/scripts/autoscend/iotms/mr2016.ash, RELEASE/scripts/autoscend/iotms/mr2018.ash, RELEASE/scripts/autoscend/paths/pocket_familiars.ash
Ezandora's scripts now support git downloads, and have moved from the `Release` branch to the `master` branch.
=> feat: move Ezan's scripts back to her; relocate to default branch

RELEASE/scripts/autoscend/quests/level_11.ash
Reported in discord:
> Has this ever happened to you?: You need to grow the beanstalk, but you don't have an enchanted bean, so you try to get one fron the Beanbat Chamber, but the Chamber isn't open, and Autoscend gets stuck instead of trying to open the Chamber?  I've had it a few times lately.  Next time it happens I'll give it a proper investigation
Relevent snippet of log:
> [INFO] Planting enchanted bean to open the beanstalk and start L10 quest.
> [INFO] In the bat hole!
> [INFO] Requested monkey paw wish without paw available, skipping sonar-in-a-biscuit
> [INFO] No enchanted bean. Getting one from The Beanbat Chamber.
> [WARNING] Can't get to The Beanbat Chamber right now.
> [INFO] Planting enchanted bean to open the beanstalk and start L10 quest.
> [INFO] In the bat hole!
> …
=> Don't delay for batsnake if out of stuff to do

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_buff.ash, RELEASE/scripts/autoscend/auto_providers.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/combat/auto_combat_util.ash, RELEASE/scripts/autoscend/iotms/mr2024.ash, RELEASE/scripts/autoscend/quests/level_10.ash
Spring Shoe support. Equips Spring Shoes before planting the beanstalk, Spring Kicks and Springs Away as appropriate, added Crunchy Steps and Ultra-Soft Steps to providers
Did D1 of a Normal Standard Sauceror run and all things that I added were performed and worked as expected
=> Spring Shoes

RELEASE/scripts/autoscend/combat/auto_combat_util.ash, RELEASE/scripts/autoscend/paths/avatar_of_shadows_over_loathing.ash
AoSoL's Punt is 28021, which autoscend supports. WereProfessor added a Punt skill number 7510 (support was added in Mafia r27841), so now mafia throws multiple skill match warnings.
Adding [7510]Punt (duplicating the [28021]Punt use, more or less) to auto_combat_util.ash would make sense if autoscend is expected to eventually handle WereProfessor, but that's more than just a trivial warning-removal fix.
Before patch, importing `autoscend.ash` gives
```
Multiple matches for "Punt"; using "[28021]Punt". (auto_combat_util.ash, line 641, char 28 to char 32) Clarify by using one of:
$skill[[7510]Punt]
$skill[[28021]Punt]
Multiple matches for "Punt"; using "[28021]Punt". (auto_combat_util.ash, line 641, char 64 to char 68) Clarify by using one of:
$skill[[7510]Punt]
$skill[[28021]Punt]
Multiple …
```
=> Disambiguate AoSoL's Punt skill

RELEASE/scripts/autoscend/paths/auto_path_util.ash
Make autoscend buy `Bind Vermincelli` and `Bind Spice Ghost` because they are also considered as pasta thralls. Especially the vermincelli can be useful for some extra MP gain.
Can not test it, i already own the skills.
=> Buy thrall skills that are used by autoscend

RELEASE/scripts/autoscend/auto_restore.ash, RELEASE/scripts/autoscend/iotms/mr2023.ash
As described in the issue, `timesRested` can be unreliable when checking if resting actually took place.
When `doFreeRest()` returns `false`, we check if cinch has been increased. If yes, resting worked, if no, we really abort.
Fixes #1420
Several smol runs. Works smoothly
=> Check if we actually recovered cinch when doFreeRest() returns false

RELEASE/scripts/autoscend/iotms/mr2018.ash
On April 1st, noncombat text gets randomly garbled with "salad". This results in 
`You grab your boombox and select the soundtrack for your life, which you can do 11 more times today.` turning into variants like `Salad grab your boombox and select the salad for your life, which salad can do 11 salad times today.`
autoscend can't determine song count which isn't very problematic since it selects a song anyway, but this error
```
> [WARNING] Could not find how many songs we have left...
```
could be avoided by making the matcher more flexible.
Before:
```
use 1 SongBoom&trade; BoomBox
Preference lastEncounter changed from Enter the Boxing Daycare to Choose a Soundtrack
Encounter: Choose a Soundtrack
Preference boomBoxSong changed from Total Eclipse of Your Meat to 
Preference boomBoxSong …
```
=> Refactor regex for boombox song count to handle April 1st word salad

RELEASE/dependencies.txt
Excavator has moved to a release branch; don't try to install the old one.
=> fix: excavator is now on a branch

RELEASE/dependencies.txt
Excavator is on loathers now, use that path instead of the git url redirect
n/a
=> update excavator to loathers

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/quests/level_07.ash
Checking for 999 evilness in addition to <= 0 to determine if Bonerdagon is ready to be fought.
Currently autoscend doesn't kill the Bonerdagon.
It checks totalEvilness to be less than or equal to 0 before trying to adventure in the Haert of the Cyrpt.
This changes the evilness check to include 999 - which should only be reached if all 4 sub-zones are cleared and the Haert is open.
I've run this with only checking 999, as well as the current suggested change which includes a check for 999 evilness, but also keeps the original <= 0 check.
I've monitored the prefs while autoscend is running, and as soon as all 4 sub-bosses are killed, the evilness seems to go straight to 999. 
Before change:
```
[DEBUG] Attempting to execute task 48 L7_crypt
Using 1 Evilometer...
Finished using 1 …
```
=> Change Bonerdagon evilness check to include 999

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_choice_adv.ash, RELEASE/scripts/autoscend/auto_post_adv.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/combat/auto_combat_default_stage2.ash, RELEASE/scripts/autoscend/combat/auto_combat_default_stage3.ash, RELEASE/scripts/autoscend/combat/auto_combat_default_stage5.ash, RELEASE/scripts/autoscend/iotms/mr2024.ash
Implements Everfull Dart Holster. This force equips the Holster if Everything Looks Red is not active to ensure we can Bullseye when it is ready. It will only try to Bullseye if the % chance is >= 50%. Will auto-upgrade perks as the choice adventure comes up at the end of combat. In stage 5 of combat we will use as many darts as possible to increase perks faster
Many, many Standard Normal runs across all classes
=> Everfull Darts Holster

BUILD/task_order/default.dat, RELEASE/data/autoscend_task_order.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/auto_providers.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/combat/auto_combat_default_stage1.ash, RELEASE/scripts/autoscend/combat/auto_combat_kingdom_of_exploathing.ash, RELEASE/scripts/autoscend/iotms/mr2024.ash, RELEASE/scripts/autoscend/paths/kingdom_of_exploathing.ash, RELEASE/scripts/autoscend/quests/level_11.ash, RELEASE/scripts/autoscend/quests/level_13.ash
This includes April's IOTM, the Apriling Band. It does four things with it.
- Summons the April Tuba and April Sax
- Generates lucky adventures using the April sax.
- Forces noncombats using the April Tuba.
- Uses the +combat and -combat intrinsic functions.
Additionally, this PR adds a priority to using the Spring Shoes, because they generate + and - combat potions, and also MP.
It adds a monkey paw wish usage to grab the Drum Machine if necessary.
Finally, this contains various changes/fixes to Kingdom of Exploathing, which was a bit broken. 
Standard HC ascension for the Apriling Band and Spring Shoes stuff. Half a KoE HC ascension for the changes there. This will be fully tested before merging.
=> Apriling band implementation, and smoe updates to Kingdom of Exploathing.

RELEASE/scripts/autoscend/auto_choice_adv.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/quests/level_09.ash, RELEASE/scripts/autoscend/quests/level_any.ash
Multiple Twin Peak NC issues report in discord. This PR does the following:
1. Flesh out NC 606 in the choice adv script
2. Create function to prepare for Twin Peak NC. Has speculative option
3. Call function to prepare in pre_adv
~~todo: look at goose drones code to make sure it is correct for this update~~ done
No issues with 1 standard run
=> Put Twin Peak into Choice Handler

BUILD/monsters/freerun.dat, RELEASE/data/autoscend_monsters.txt, RELEASE/dependencies.txt, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/combat/auto_combat_default_stage2.ash
At the moment we only use our free runaways against monsters we want to banish, but can't.
This PR adds a separate list of monsters that we don't want to banish, but do want to use free runaways on.
They were selected as having no useful drops, and being in delay zones.
One day of unrestricted HC. It ran away twice against things it wouldn't have otherwise done. I was expecting more, there's still more testing necessary. Bander/boots runaways still barely used.
Update: after another day of HC (completion of d2, new ascension d1), with expanded monsters it now uses tonnes more runaways. I'm happy for it to be merged now. I do intend to update the banish logic so we can free-run after using Spring Kick, but that can easily go in another PR.
=> add additional monsters for free runs

RELEASE/scripts/autoscend/iotms/mr2023.ash
Updates CCSC logic to not break certain quests and paths
Fixes #1409, fixes #1432 
Untested, will test after Halloween on 4/30
=> CCSC War and WOTSF Fix

RELEASE/scripts/autoscend/auto_util.ash
Disco Nap is tagged as a passive skill in mafia because it has a passive component that adds a free rest, but auto_is_valid should still return false for it in G-Lover since it's also a noncombat recovery skill and can't be cast.
Fixes the G-Lover infinite recovery loop issue https://github.com/loathers/autoscend/issues/1419)
I waited until I was triggering the infinite loop to implement it to make sure it fixed it.
=> Fix infinite recovery looping in G-Lover

RELEASE/scripts/autoscend.ash
Adding Jarlsberg and Sneaky Pete to Emotion Chip Prevention
Comments out that request
Running it right now, ya dig
=> Avatar Paths Can't Use Emotion Chip

RELEASE/scripts/autoscend/iotms/mr2017.ash
Grammatical fix, lines 822 and 912 (can not -> cannot). Does not address any open issues; just something that always bugs me when I see it flow through on the CLI. 
-SadOatcakes :)
I did not test this as it shouldn't change anything about how the script runs; it's a superficial edit to a CLI message.
- [ x] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] I have based my pull request against the [main …
=> Update mr2017.ash (grammar only, no real code change)

RELEASE/scripts/autoscend/auto_choice_adv.ash
Currently we don't force candy cane sword being equipped if we don't have the war outfit. However there is nothing stopping maximizer. 
This change will prevent the choice adv script from starting the war until we have a war outfit.
Validates
=> Only use candycane sword to skip war start if we have war outfit

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_restore.ash
Reported in discord a few times. Fixed issue and fixed one spot for VS code formatting
`keep getting "failed to rest to charge cincho" message, then autoscend aborts. `
Ran in CLI. Pref changes as expected and burns mp as expected. Confirmed when this pref is false, burn command does not work as well.
=> Burn MP Properly For Free Resting

BUILD/monsters/freerun.dat, RELEASE/data/autoscend_monsters.txt, RELEASE/data/autoscend_task_order.txt
Updates the free run condition for the Ornate Nightstand to only happen after we get the Disposable Instant Camera and Lord Spookyraven's Spectacles
Untested
=> Update freerun to only do ornate nightstand after conditions

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_bedtime.ash
Fixes #1444
Decided to keep it simple and just don't fight seals when drunk. Otherwise would have to either update pre adv to allow this or to do maximizer/etc in the seal clubbing functions. Both of which can be done, but is it worth it. I'm thinking no
Hasn't
=> no drunk seal bashing

RELEASE/dependencies.txt, RELEASE/scripts/autoscend/auto_choice_adv.ash, RELEASE/scripts/autoscend/auto_consume.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2024.ash
Add apron kit to foods we consider eating. Will pull if none on hand.
Core of this implementation is C2T's script to actually consume the kit:
https://github.com/C2Talon/c2t_apron
Use any ingredients we have on hand that aren't still needed for quests or potentially harmful. Does not pull or otherwise acquire ingredients, only considers whats already on hand.
Ascended alt into a normal standard run. This account does not have the IOTY, so expect it to pull the kit
Ran consume command
Confirmed apron kit was pulled and consumed
ignore the mat.group lines, from debugging/understanding c2t's script
=> Black and White Apron Support

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_restore.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2019.ash, RELEASE/scripts/autoscend/iotms/mr2023.ash
1. (Primary) Removes abort in mr2023.ash when failing to restore cinch. Instead log that we will try again later and continue
2. (Secondary) Created auto_burnMP() to more reliably burn MP. Didn't know that burn only extends existing buffs. Function adds a default skill for the burn command to cast if there are no active buffs to extend
Validates
=> Burn MP Better

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/combat/auto_combat_util.ash, RELEASE/scripts/autoscend/iotms/mr2024.ash
This summons items from the Mayam calendar. It prioritises the stinkbomb and yamtility belt items, then yams, item drops, cheese, wood etc.
It adds the use of the Such Great Heights adventure for +adventures if you have the spare stone wool. I added it because it recharges the calendar, but it will do it even if you don't have a calendar.
Mayam stinkbomb is implemented as a banish, but isn't always used because of the much higher priority of Spring Kick. This may need to be changed.
Couple of days of HC unrestricted runs.
=> Add support for Mayam calendar

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_util.ash
User in discord reported:
Could not find a known, usable skill of yours uniquely matching "29 Sauce Contemplation"
[ERROR] Error running auto_pre_adv.ash, setting auto_interrupt=true
Asked user to set lastChanceBurn to be blank and resolved issue. Must be mafia doesn't check if we have the default skill before trying to cast it
code validates. Pref change was tested by user manually and it solved their issue
=> reset default mana burn skill

RELEASE/scripts/autoscend/combat/auto_combat_wereprofessor.ash
Bug found by Rinn on Discord. Would exit early out of trying Advanced Research if an enemy id matched an existing substring. This should now look at each individual id already researched
Untested after most recent commit
=> WereProf Advanced Research Fix

RELEASE/scripts/autoscend/auto_pre_adv.ash
Remove call to Minerva's Zen as source has changed
As listed
Fixes #1463
Not needed, commenting out inapplicable script
=> TCRS Minor Update

BUILD/settings/any.dat, RELEASE/data/autoscend_settings.txt, RELEASE/scripts/autoscend/iotms/mr2022.ash
When designer sweatpants are full of sweat, add a fallback to make sweat-ade during the run, so that the player can optionally consume those at the end of the day when they have spleen capacity left. This only happens when:
- Sweat collected is at >95% AND
- liver is fully cleaned (or nothing drunk yet) AND
- Not in sensitive zones for sleaze/drunkenness AND
- autoscend is configured to break the hippy stone at the start of the run (auto_pvpEnable) AND
- there is enough spleen capacity remaining today for an additional sweat-ade
Completed a 2-day HC 11TIHU run with this, ending up with 3 sweat-ades on day 1, and 1 on day 2 (after the day 1 consumables were used)
=> Collect sweat-ade as fallback for designer sweatpants when PVPing

RELEASE/scripts/autoscend/auto_buff.ash
Reported in discord. Log analysis showed user didn't have enough elemental damage according to ghost check in pre adv to go to a shadow rift. This happened when we were trying to get the shadows water buff though... so there is no combat.
This change should make it so pre adv is not called, meaning no check for sufficient elemental damage.
CLI. Was able to get shadow waters buff while in aftercore with `buffMaintain($effect[shadow waters])`
=> don't do pre adv when getting shadow waters buff

RELEASE/scripts/autoscend/iotms/mr2023.ash
Fixes an abort when using the Jill-of-all-trades for the Yossarian quest.
Reported in Discord.
Hasn't. It's a single line change to a switch statement. I'm willing to take the chance.
=> Add "gremlins" to JoAT LED candle types

RELEASE/scripts/autoscend/auto_familiar.ash
Reported in discord.
If you own the Reagnimated Gnome (or I guess, are in Quantum Familiars) & get to day 6 the script would abort because you would have all of the Gnome's equips.
Do we even use anything other than the kgnee? Who knows? Not me that's for sure but at least we won't abort on day 6 any more.
Hasn't. I honestly don't have the time to waste getting a test account with the Gnome into day 6 of an Unrestricted run just to test this and neither should you.
=> Only visit the Cake-Shaped Arena with the Reagnimated Gnome if we don't have all the equipment yet.

RELEASE/scripts/autoscend/quests/level_11.ash
there was a missing else in L11 and I added it. no logged issue on this i think, replying to an issue reported on discord
have not tested sorry doggs
=> fix missing else in L11 quest

RELEASE/scripts/autoscend/quests/optional.ash
No campground access in You, Robot so this prevents repeated attempts to use housing items
Adds a check for being in You, Robot for houseUpgrade()
Validates
=> No You, Robot Campground

RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/combat/auto_combat_default_stage5.ash, RELEASE/scripts/autoscend/combat/auto_combat_util.ash, RELEASE/scripts/autoscend/iotms/mr2024.ash
- yellow and green are handled as standard  
yellow rays and free runs respectively
- blue is handled as a stunner when available
- red is used at stage 5 whenever available (after
Evert darts, didn't see any reason to save it)
- Not sure how to deal with purple
Ran it a couple days on my account, it uses the candles as needed.
=> Added handling of red blue green and yellow candle

RELEASE/scripts/autoscend/combat/auto_combat_quest.ash
After a recent KoL update, the tool gremlins allow using the magnet against any non-crit hit, which is helpfully made clear by a comment in the HTML.
A run completed the gremlin quest successfully.
=> feat: tool gremlins allow magnet on any non-crit hit

RELEASE/scripts/autoscend/paths/kingdom_of_exploathing.ash
Autoscend was previously counting your effective amount of rare meat isotopes by dividing your meat total by 1,000, without accounting for NPC shop discounts. Now it will.
Sidenote: the method that calculates the discount checks for having Travoltan trousers, but as far as I can tell nothing equips them? Does mafia automatically equip them and designer sweatpants when possible?
=> Rare Meat Isotope count now accounts for discount

RELEASE/scripts/autoscend.ash
Autoscend was getting stuck trying to cast ode to booze as a seal clubber, but it didn't have an accordion. Not sure why, it hadn't previously gotten stuck. Autoscend will now buy an antique accordion if you have enough meat or isotopes. 
Untested.
=> Buy antique accordion from Cosmic Ray in KoE

RELEASE/scripts/autoscend/combat/auto_combat.ash, RELEASE/scripts/autoscend/combat/auto_combat_default_stage3.ash, RELEASE/scripts/autoscend/combat/auto_combat_disguises_delimit.ash, RELEASE/scripts/autoscend/combat/auto_combat_fall_of_the_dinosaurs.ash
Fall of the Dinosaurs / Disguises Delimit struggles with doing the Shadow Rifts. Add some more options for this.
Implode Universe is an auto kill. It fails on some special monsters, which is the reason I mark it as used. I don't know if any exist that can be eaten by dinos and have over 80% physical resistance, but some may be added in the future.
Silent Treatment removes physical resistance from shadow trees and elemental resistance from ghostasaurus. This enables killing straightforwardly.
Also try using Implode Universe when past round 25 instead of aborting. I've hit this with a spikolodon hermetic seal; there are probably other cases.
Ran Fall of the Dinosaurs a bunch.
=> use Implode Universe / Silent Treatment against difficult enemies

RELEASE/scripts/autoscend/auto_util.ash
Discord user had error where they were adventuring in 8-bit realm forever. Turns out we were trying to place a sausage goblin there to burn delay. Kramco isn't valid anymore in trendy
Validates
=> Support Trendy

BUILD/monsters/replace.dat, RELEASE/data/autoscend_monsters.txt
Don't replace the Boss Bat in wereprof under the assumption the user is looking for Manuel factoids.
Also fix not replacing the Boss Bat in AOSOL.
Hasn't yet.
=> feat: don't replace the boss bat in wereprof, fix aosol spelling

BUILD/settings_extra/any.dat, RELEASE/data/autoscend_settings_extra.txt, RELEASE/scripts/autoscend/auto_equipment.ash
Supports
https://kolmafia.us/threads/maximizer-didnt-equip-a-weapon.29577/page-4#post-175257
Adds prop to let user abort when getting maximizer bug. Prop by default doesn't exist, meaning false. 
Can set prop to true via extra settings in the relay browser or `ash set_property("auto_debug_maximizer", true);`
Validates
=> User prop to abort when no weapon equipped

RELEASE/scripts/autoscend/quests/level_10.ash
It was possible to get stuck in a loop of NCs in the Castle in Kingdom of Exploathing. This fixes it by choosing to fight a goth giant instead of Copper Feel if you're in KoE and don't have the airship to immediately complete the quest.
=> KoE: Prevent getting stuck in NC loop in castle

RELEASE/scripts/autoscend/combat/auto_combat_default_stage5.ash, RELEASE/scripts/autoscend/combat/auto_combat_header.ash, RELEASE/scripts/autoscend/combat/auto_combat_util.ash
Protonic ghosts do damage based on max HP. If we are an muscle class with high max HP and low elemental resistance, the previous calculation lead to unexpected death.
Ran with it, successfully skipped and killed ghosts as expected.
Might be a bit cautious but I think it's better than dying.
=> feat: better calcs for whether we can survive shoot ghost

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/auto_post_adv.ash
Some paths still take a bit of time to get meat together, especially those that have no trainset and need to buy torso.
This adds using the spring shoes and secret door detection high autosell items as a meat source.
Some paths still take a bit of time to get meat together, especially those that have no trainset and need to buy torso.
This adds using the spring shoes and secret door detection high autosell items as a meat source.
Additionally, if we're broke (meat<reserve) then prefer the spring shoes until we're not any more.
Invoked altered functions with gCLI.
=> More meat autoselling, esp spring shoes and secret door drops

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/paths/wereprofessor.ash
WereProfessor only buys skills if
* it's the beginning of the ascension
* organs are full and it has very few adventures left
* it is about to transform into a wolf
It calculates the latter using "wereProfessorTransformTurns", which is only updated when you view the charpane. Autoscend almost never views the charpane, so this preference is almost never updated, so autoscend generally doesn't buy skills during the run. This can really hinder daycount if it doesn't buy stomach / liver.
Also fix a separate issue where it only bought skills if it had 1 more RP than required.
Running WereProf.
=> fix: wereprof skill buying

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2023.ash, RELEASE/scripts/autoscend/quests/level_any.ash
Autoscend should not buy and try to read the Manual of Secret Door Detection if it's going to fail.
It also shouldn't buy the meat butler if there's no campground.
Ran WereProfessor.
=> fix: improve 2002 purchases for avatar paths

RELEASE/scripts/autoscend/auto_buff.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_providers.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/quests/level_04.ash, RELEASE/scripts/autoscend/quests/level_12.ash, RELEASE/scripts/autoscend/quests/level_13.ash
Standing on Alium's Add Item Provider #1331 Shoulders, but for Meat. Values are either to achieve specific targets (wall of meat in 1 turn, Fungal Plains max points) or estimates I'm not particularly beholden to.
Tested in a separate local branch merged with the ag-improvements branch in a HC Avant Guard run. At The Fungus Plains, saw it try to provide 450% meat drop as expected per PR
=> Add Meat Provider

BUILD/monsters/freerun.dat, RELEASE/data/autoscend_monsters.txt, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/auto_zone.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/combat/auto_combat_ed.ash, RELEASE/scripts/autoscend/combat/auto_combat_util.ash, RELEASE/scripts/autoscend/iotms/mr2022.ash, RELEASE/scripts/autoscend/paths/actually_ed_the_undying.ash, RELEASE/scripts/autoscend/quests/level_13.ash
This PR contains several updates. Most of these directly relate to the Actually Ed path, mostly copy/pasting updates that were made to the main combat scripts into the Ed combat script.
Full list of Ed changes:
- Reorder purchase of organs so Liver is before Stomach now we no longer need semirares, but still need to play pool.
- Move spookyraven down the task order list if we've already hit level 11 (and so no longer get the extra pool skill from having the Staff of Ed)
- Add drop forces/pickpockets (eg Polar Vortex)
- Use pickpockets/forces on Warehouse guards
- Add shadow brick use
- Use lash of the cobra to get shadow bricks
- Add darts use
- Add spikolodon use
- Add free run use
- Use Speakeasy free fights while farming ka
Changes that affect other paths:
- Expands the list of …
=> Ed modernisation, free run expansion and other small fixes

RELEASE/scripts/autoscend/auto_bedtime.ash
Not sure what the thoughts are toward the bedtime "resources are still available!" messages in this file; most are for stuff from back in 2015. But in that context, I've been running non-Standard runs and seeing reminders for Deck and Chateau use, I was considering the daily resources that are available that might be worth reminding users are available for manual intervention. 
A lot of these resources, even though they seem a bit wasted are also a bit trickier and maybe-not-advisable to tell a user to make use of (Carto mapping, making decisions about a random monster to reminisce about/fax, forcing NCs, clover uses), but I feel like August Scepter casts are a pretty fair one to remind users of?
Addition was made to auto_bedtime.ash to tell the user the amount of August Scepter casts …
=> Bedtime reminder for unused August Scepter casts 

BUILD/monsters/sniff.dat, BUILD/restoration/skill.dat, RELEASE/data/autoscend_monsters.txt, RELEASE/data/autoscend_restoration.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_acquire.ash, RELEASE/scripts/autoscend/auto_choice_adv.ash, RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_restore.ash, RELEASE/scripts/autoscend/auto_zone.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/combat/auto_combat_default_stage2.ash, RELEASE/scripts/autoscend/combat/auto_combat_default_stage3.ash, RELEASE/scripts/autoscend/combat/auto_combat_util.ash, RELEASE/scripts/autoscend/iotms/mr2014.ash, RELEASE/scripts/autoscend/iotms/mr2021.ash, RELEASE/scripts/autoscend/iotms/mr2024.ash, RELEASE/scripts/autoscend/paths/license_to_adventure.ash, RELEASE/scripts/autoscend/paths/low_key_summer.ash, RELEASE/scripts/autoscend/paths/you_robot.ash, RELEASE/scripts/autoscend/quests/level_04.ash, RELEASE/scripts/autoscend/quests/level_09.ash
1. Bonus to maximizer if have free fights left
2. Equip bat wings at airship
3. Leap the smut bridge
4. Add rest upside down as a restore option
5. Swoop pickpocket
6. Bonus - only sniff dairy goat if we need cheese still
Standard run
Test status:
=> More Bat Wings Support

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/combat/auto_combat_quest.ash, RELEASE/scripts/autoscend/quests/level_12.ash
After the gremlins change, they no longer need to be stasised, so change the code accordingly. Don't buff HP or value -ml too heavily because we only need to survive one hit (unless it's a crit).
Also never stun tool gremlins to try to finish the fight ASAP. It's possible we should only not stun if we have an attacking familiar or passive damage, but given we are minimizing ML the additional flyer bonus is not going to be significant.
Did some runs. Autoscend gets the jump on the gremlins, flyers, then magnets them. Player took 3 damage from flyering, so I'm not concerned about survivability.
At lower skill levels it should either fail to get the jump and magnet immediately, or flyer if survivable then magnet. I'm happy with this.
=> feat: never stun tool gremlins, and don't stasis them either

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2024.ash
Gets bridge parts and levels via mouthwash
Future PR can support banish and pickpocket combat items
Not yet
=> Support Sept-Ember Censer

RELEASE/scripts/autoscend/auto_consume.ash
Blacklisting bag of QWOP to prevent it from being consumed as it being consumed can cause combat issues/aborts due to abilities like Thrust-Smacks also being fumbling with the buff given by the food.
(No issue filed, just posted in ASS #autoscend channel)
Not formally tested yes?
=> Update auto_consume.ash to blacklist "bag of QWOP"

RELEASE/scripts/autoscend/combat/auto_combat.ash
Without this change, after completing an ascension there can be portscan counters left over. I assume this happens when an agent is encountered in a "special" way and this is the right fix, but it might not be.
Many runs.
=> fix: clear portscan counter when encountering agent

RELEASE/scripts/autoscend/auto_buff.ash
Issues seen while testing #1331.
`buffMaintain` should return true if it tried to do something (looking at the useSkill / useItem behaviour). The CLI commands / visit_urls were not doing this, so do so.
Also shouldn't get the Grim Brother buff if speculating.
Can't test the Grim Brother change because I don't have one. Did some more item provider runs.
=> fix: buffMaintain should return true if it tried to do something

RELEASE/scripts/autoscend/auto_providers.ash
Add a couple more item sources I have available at the end of a run.
Autumn leaf also gives +combat but I had spares. Loathing Idol also gives init and +combat, but I had /lots/ of spares.
Did a run.
=> feat: add a couple more item sources

RELEASE/scripts/autoscend/auto_adventure.ash
There was a change to the HTML that we use to detect whether we are in combat or not when we call autoAdvBypass. This fixes that
Multiple standard normal runs. Also anecdotal evidence from Loathers Discord.
=> Detect combat in autoAdvBypass

RELEASE/relay/relay_autoscend.ash
I wanted to know where we were spending turns in execution, so I stuck a table on the relay browser page.
Note that this is *all* turns, not just turns run by autoscend.
One character in HC, done one day. Couple of characters in aftercore.
=> Add list of locations where turns have been spent to the bottom of the relay browser page

RELEASE/scripts/autoscend/auto_util.ash
When the Roman Candelabra was added, the yellow ray was only half implemented. I guess this got missed because it was always overruled by the Parka for any shiny player.
Now Candelabra is the only yellow in standard, it needs fixing. This does that.
1 day 1 of a HC Standard run. Please help test.
=> finish implementing the yellow ray from Roman Candelabra

RELEASE/scripts/autoscend/auto_buff.ash, RELEASE/scripts/autoscend/auto_providers.ash
There is a new + and - combat skill each from Crimbo 2024. This adds using them.
2 runs on shiny player, 1 run on non-shiny. Shiny player doesn't use them due to +-25 combat keep easily being reached, non-shiny player does.
=> add 2024 crimbo combat modifiers

RELEASE/scripts/autoscend/iotms/mr2023.ash
Autoscend uses circadian rhythms against a 151 Infantryman summoned at the start of the run, but is probably only intended to do that when on the battlefield.
Ran fine.
=> fix: don't circade a 151 summon

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/combat/auto_combat_default_stage2.ash, RELEASE/scripts/autoscend/quests/level_11.ash
Aborting due to not having enough pulls to make wet stunt nut stew. Same as issue below
Fixes #1487 
Got this error in a normal QT run. Issue caused abort every time. Made this change, script moved along and running.
=> Delay palindrome if out of pulls

RELEASE/scripts/autoscend/auto_restore.ash
Mafia refuses to equip the bat wings to cast rest upside down if doing so would reduce your maximum HP / MP leading to a loop. However, autoscend seems to only try the best restore. This leads to a situation where autoscend won't restore HP at all, leading you to your death. 
Going to do some runs with it.
=> fix: do cast using bat wings if Mafia won't

RELEASE/scripts/autoscend.ash
Fix "This is version: 0" on logs.
Ran it once.
=> fix: show reasonable version for git installs

RELEASE/scripts/autoscend/quests/level_any.ash
Add missing line from update to level 08 quest adding the NC force - make sure we go back to slope once we've said we're forcing going to to the slope.
Couple of standard SC runs on a shiny character.
=> make sure we route to extreme slope when we've tried to force an NC

RELEASE/scripts/autoscend/auto_equipment.ash
The function was missing baywatch.
Use Mafia's "Nonstackable Watch" modifier instead of a list of items for determining watches.
One run, worked as expected.
=> fix: use Mafia's knowledge of watches

RELEASE/scripts/autoscend/iotms/mr2024.ash
Follow-up to #1532.
As suggested, spend spare ingredients on consumables. Also get spiced rum in addition to tamale; they are awesome at least.
Over 2 days, I think this will provide:
* with spring shoes: dinghy, goldschlepper, tamale; goldschlepper, rum, tamale
* without spring shoes: dinghy, anchor bomb, rum, tamale; anchor bomb, rum, tamale
Did some runs (okay, d1 on one account and d2 on another).
=> feat: get rum and tamales with spare Takerspace ingredients

RELEASE/scripts/autoscend/auto_post_adv.ash, RELEASE/scripts/autoscend/combat/auto_combat_default_stage3.ash
Fixes a few things with logging
- Only logs the combat for chained combats that end with an NC (like dart perks)
- Only logs once an Avalanche has actually been triggered in combat
- Log the location of the NC as well as the forcer, NC, and turn for clarity in our tracker
- Don't tearaway pants if you want an NC forcer, unless the monster is a plant (tearaway pants could kill the monster before casting the NC forcer)
One NC for avalanche because I had used up the other 2 charges figuring this out. Other items have been tested during the run.
=> NC Forcer/Logging Fixes

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/iotms/mr2024.ash
Use up to 3 mouthwashes to level, prioritised over bridge parts when < level 13.
Never level past 15 with mouthwash to prevent wastage.
Get septimus charms with remaining embers.
Use left/off hander's buff from scepter with sufficient cold res in off-hand.
Use mayam walled in for cold res.
1 HC run with character with both available IOTMs.
Note that this can be tested as part of the branch hk_mixed_branch which contains all the changes from several branches I'm independently PRing.
https://github.com/loathers/autoscend/tree/hk_mixed_branch
=> Mouthwash changes

RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2024.ash
Photobooth implementation did not previously check if we'd used our max number of effects before trying to cast those effects. This can cause a halt, and for some reason didn't in my previous testing. This may currently be a showstopper. This PR fixes it.
Interpreter, invocation just starting running.
=> add check on number of times clan photobooth request made

RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/combat/auto_combat_default_stage3.ash, RELEASE/scripts/autoscend/combat/auto_combat_header.ash, RELEASE/scripts/autoscend/combat/auto_combat_util.ash, RELEASE/scripts/autoscend/iotms/mr2023.ash, RELEASE/scripts/autoscend/quests/level_12.ash
We can force drops using the Flash Liquidizer Ultra Dousing Accessory from the 2002 Mr Store catalog. This is a pickpocket that only takes one item but can be used repeatedly. The main place is it useful is Filthworms. This adds the code to support using it, and implements it only for the filthworms, making it grab them early-on in the ascension.
Just one HC standard run through the orchard so far.
=> Implement using FLUDA douses for filthworms

RELEASE/relay/relay_autoscend.ash, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/iotms/mr2024.ash, RELEASE/scripts/autoscend/quests/level_11.ash
- We've needed tracking of lucky adventures for a while, so this adds that.
- Lucky is now abundant, summons rare. So this switchess the priorities for how to get Baa'baa'bu'ran to clovering first.
- The tracker has got busy recently. We have some long entries, and some multiples (douse, for example, spams).
- We can now specify the delimiter per tracker, so short entries can still be commas while long ones might be newlines.
- We can now stack multiple identical entries in the tracker. What was before (shadow slab:Perpetrate Mild Evil:0),(shadow slab:Perpetrate Mild Evil:0),(shadow slab:Perpetrate Mild Evil:0) now shows as (shadow slab:Perpetrate Mild Evil:0 x3).
- Bold daycount.
D1 standard HC, shiny character, forced some lucky adventures (by manually calling …
=> Lucky tracker, tracker changes, try to clover baa'baa before summon

RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/combat/auto_combat_util.ash, RELEASE/scripts/autoscend/iotms/mr2025.ash
In standard right now, we have 2 IOTM sniffs once you're out of olfaction: Monkey Point and McHugeLarge Slash.
This didn't work. This makes them work.
D2 of standard HC run on shiny character.
=> fix McHugeLarge slash and Monkey paw sniffs

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/iotms/mr2023.ash
Late nerf day made tentacles above 11 non-free. This can waste turns if we habitat them. So I turned off habitating them if they're going to be non-free.
One day on a HC Standard character with BoFa. Needs more testing, specifically checking if we're pushing it too far or maybe the limit can be increased by one.
=> don't habitat tentacles if they'll be non-free

RELEASE/scripts/autoscend/auto_list.ash, RELEASE/scripts/autoscend/autoscend_header.ash
This adds some useful sorting functions that take unsorted Mafia maps of items and effects, and returns them as lists sorted by a numeric modifier.
These functions are used in several upcoming PRs, I thought it was easier to get them in separately rather than having multiple re-merges.
Many runs.
=> Add functions to sort raw Mafia variable container types by numeric modifiers

RELEASE/scripts/autoscend/iotms/mr2019.ash
You can't beach comb with no adventures left, so don't try.
Ran it when I hit the bug.
=> fix: don't try to comb with no adventures

BUILD/task_order/default.dat, RELEASE/data/autoscend_task_order.txt, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/quests/level_12.ash
The war needs an NC to be started, but 3 NCs are available. Fortunately, there are two IOTMs that mean a forced NC will always give you the ability to start the war. If you have either, now force an NC to start the war.
Additionally, we now have a way to instantly unlock the island (pirate dinghy). Once we have and can wear the war outfit, and are level 12, unlock the island and use a force to start the war in one turn so we can start flyering immediately. This has been added to only the default task_order so far.
(also, for some reason the task order build has put default in a different place than it was in the repo, I just let it move it - if other people are getting inconsistent ordering we should fix it, should be one line in assemble.sh to sort eg alphabetically).
Example of the NC …
=> Force NC to start war if have Cane/Cartogrpahy. Do it ASAP if we have all requirements.

BUILD/monsters/sniff.dat, RELEASE/data/autoscend_monsters.txt, RELEASE/scripts/autoscend/auto_consume.ash, RELEASE/scripts/autoscend/auto_restore.ash, RELEASE/scripts/autoscend/auto_routing.ash, RELEASE/scripts/autoscend/auto_util.ash
* Only use mini kiwi aioli if food is large enough since it is flat adv/full
* No longer summon/sniff GrOps
* Don't route for CMC in paths with no campground/workshed
* Only use advanced HP restore options if cocoon isn't an option
Several HC runs across shiny standard/ed, nonshiny standard and softcore LoL.
=> Set of minor changes

RELEASE/relay/relay_autoscend.ash
Splitting on "," meant that every item after the first had a starting space, which meant that the first entry wouldn't get stacked with those after it. This was most obvious on genie wishes / magical sausages.
Checked in browser.
=> fix: include first item in preferences in stacking

RELEASE/scripts/autoscend/auto_bedtime.ash, RELEASE/scripts/autoscend/quests/level_11.ash
Hopefully fix the issue with not getting wet stew in hardcore.
Also redo the logic a bit: don't force us to have +300 item to do Whitey's: it is normally worth doing. Additionally, +food drops count, and a shiny character will have rollercoaster / bat wings that aren't counted in the 300.
Also try to monkeypaw items at the end of day 1 with the guild and beach unlocked, that happens e.g. with a tearaway pants moxie class.
Not yet.
=> fix: get wet stew in hardcore

RELEASE/scripts/autoscend/auto_providers.ash, RELEASE/scripts/autoscend/quests/level_12.ash
A lot of wishes were added for meat in Avant Guard to allow the nuns to be completed in 6 turns. This wound up being total overkill in standard (I had all 8 daily standard wishes deployed on nuns once).
This PR leaves all the AG wishes in place, but only wishes for +200% meat effects if not in AG.
Lots of HC runs in/out of standard with shiny and non-shiny characters.
=> Less meat wishes

BUILD/assemble.sh, BUILD/monsters/freerun.dat, RELEASE/data/autoscend_monsters.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/paths/low_key_summer.ash, RELEASE/scripts/autoscend/quests/level_05.ash
A lot of extra tasks and efficiencies have been added since LKS was optimised in autoscend. This updates the script to handle a few of them.
* Copy/pastes the early tasks from the default task order.
* Adds free runs for LKS only zones.
* Only wait for keys before the nuns (2x 50% meat keys) if they're needed (there's tonnes of alternatives now: backup camera, yamtility belt, feather boa).
* Don't wait for delay zones to complete Knob Outskirts in LKS (broke LKS for muscle classes)
* Only get the +exp keys early if we need the XP
Additionally, there are two more general changes:
* Changes assemble.sh to sort filenames case insensitive. This was how most of the repo was set up, but sometimes caused issues when people sorted filename-sensitive making the order different in the RELEASE data …
=> Low Key Summer Modernisation

BUILD/monsters/yellowray.dat, RELEASE/data/autoscend_monsters.txt, RELEASE/scripts/autoscend/combat/auto_combat_default_stage2.ash
We now use the FLUDA douse pickpocket on the Filthworms. At the moment this works fine in standard except log entries, but in unrestricted where we have eg, Feel Envy or other forced drops it will use these before trying to douse. So with an envy, you use both the envy and the douse to get the same item.
This adds a condition to the YR so it tries dousing first, and only YR/Envies if it gets to round limit for dousing.
3 shiny HC runs, inc 2 unrestricted.
=> If using Douse on monster, do not YR (or especially cast envy) before

RELEASE/scripts/autoscend/auto_familiar.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2023.ash
If we didn't need to force the Patriotic Eagle, we would return $familiar[none]. This returns whatever was previously picked instead.
Untested, but should work
=> Pass famChoice through if we don't need to force the eagle

RELEASE/scripts/autoscend/auto_familiar.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/iotms/mr2023.ash, RELEASE/scripts/autoscend/iotms/mr2025.ash
Don't summon a tiny gold medal if we have astral pet sweater, stillsuit or cupid bow (or are in small, following existing code).
Cupid bow code extracted from #1577. 
Not yet.
=> feat: extract having good fam equipment from tiny gold medal summon code

RELEASE/scripts/autoscend/auto_consume.ash
Previously, auto_consume would consume once the user got to less than 10 adv (other than chewing spleen). This changes that to be either 10 or 1+how much the user wants to reserve at the end of the day, whichever is greater.
Set auto_advToReserve to my current adventure count and it triggered the consume code. Unsetting it it runs like normal.
=> Make auto_consume respect auto_advToReserve

RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/combat/auto_combat_util.ash, RELEASE/scripts/autoscend/paths/quantum_terrarium.ash, RELEASE/scripts/autoscend/quests/level_11.ash
This should fix some of the reported issues with Eagle being used inappropriately in Avant Guard and Quantum Terrarium.
Also, in QT:
* Forces reassembled blackbird or reconstituted crow when going to the black forest
* If they are the randomly chosen fam, go to the black forest if still needed
* Forces melodramadery or LHM when adventuring in the desert
* If the melodramadery is randomly, go to the desert if still needed
Almost a full QT run. The melodramadery and blackbird changes weren't tested as they were caught mid-run
=> Disallow Patriotic Screech in some paths. Some QT optimizations

RELEASE/scripts/autoscend/iotms/mr2018.ash
In Avant Guard, we need the bodyguard, so we can't fight bandits with no familiar.
Worked to get past that point.
=> fix: do not try to adventure with no familiar in AG

RELEASE/scripts/autoscend/quests/level_11.ash
Fix Palindome for hardcore avatars. Previously, running autoscend again after it aborted worked, so I think this is the right move.
It might be questionable whether certain avatar paths can get +100% item drop, and so whether they should brute force the palindome.
Couple of AoSoL runs, WereProf, Dark Gyffte
=> fix: in hardcore, when an avatar class, return after reading

RELEASE/scripts/autoscend/combat/auto_combat_default_stage5.ash, RELEASE/scripts/autoscend/quests/level_10.ash, RELEASE/scripts/autoscend/quests/level_11.ash
Extract the non-eagle changes from #1592.
Various changes from a WotSF run.
Don't try to do the airship while Healers are phylum banished.
Don't avoid adventuring in the Castle Basement with an umbrella you can't equip.
Don't require enough meat to buy the forged identification documents when you won't need to buy them.
Fight Wu Tang a bit better.
Fist run.
=> fix: various wotsf issues, delay airship with banished dudes

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/paths/bugbear_invasion.ash, RELEASE/scripts/autoscend/quests/level_10.ash, RELEASE/scripts/autoscend/quests/level_11.ash, RELEASE/scripts/autoscend/quests/level_any.ash
Enter the `screechCombat` eagle block if banish location is unset.
Set which phylum we're trying to unbanish so we can confirm it didn't run out.
Fist run.
=> feat: improve eagle banish clearing

RELEASE/scripts/autoscend/combat/auto_combat_util.ash
Can't use Patriotic Screech in G-Lover due to lack of G's
It Hasn't
=> There's no G in USA

BUILD/settings/any.dat, BUILD/settings/post.dat, RELEASE/data/autoscend_settings.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/paths/bugbear_invasion.ash, RELEASE/scripts/autoscend/paths/wereprofessor.ash
Banishing phyla is high variance and can mess up the routing. Let the user turn it off. 
Bugbear, werewolf.
=> feat: add a pref to banish phyla

RELEASE/scripts/autoscend/quests/level_12.ash
If we don't have the scepter, we can't try nuns at all.
On day 1, we definitely won't have enough waffles, so again don't try.
Avant Guard, day 1, stopped at the nuns.
=> fix: don't even try nuns on day 1 AG

RELEASE/scripts/autoscend/combat/auto_combat_util.ash
Boris can't equip off-hand weapons, so can't equip the candelabra. Check this. 
Boris run.
=> fix: don't try the roman candle YR in boris

RELEASE/scripts/autoscend/quests/level_08.ash
Ensure Plumber is wearing work boots when trying to use the McDuffel equipment to get the NonCombat(s) - Plumber autostops you from going into a zone if you dont have a way to actually fight due to not wearing one of the plumber equips.
It Hasn't
=> Allow Plumber to use McDuffel to climb the Peak

BUILD/monsters/banish.dat, RELEASE/data/autoscend_monsters.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_bedtime.ash, RELEASE/scripts/autoscend/auto_choice_adv.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_providers.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/autoscend_header.ash, RELEASE/scripts/autoscend/combat/auto_combat_util.ash, RELEASE/scripts/autoscend/iotms/mr2023.ash, RELEASE/scripts/autoscend/iotms/mr2025.ash, RELEASE/scripts/autoscend/quests/level_10.ash
Using the Peace Turkey as a -combat modifier has been sitting in the provider for ages but didn't actually work. This fixes that.
Additionally:
* Always craft split pea soup before combat, whether we're using it as a banish or not.
* If it leaves us with at least one split pea soup, allow it to be used as a banish
* Stop candy-caning the airship as much (before it expected it could get an amulet for the cane sword, it can't)
* Since we no longer phylum banish it, irritating series of random encounters is just a regular banish now
* Consume pre-workout powder if we need it to banish.
* At bedtime, fill up our spleen if possible with CMC drops, condo drops and then energised spores from SIT.
1.5 zooto runs. The completed one was my fastest auto run by 10 turns, and I have a …
=> Use Peace Turkey for NCs, pea soup as free runaway, more condo spleen

RELEASE/scripts/autoscend/combat/auto_combat_header.ash, RELEASE/scripts/autoscend/combat/auto_combat_util.ash
We use "Douse Your Foe" to get shadow bricks from shadow slabs. We only use it so many times, then move to other skills. When you have lots of other sources of combat actions, this can cause us to hit our round limit and require the player to kill manually.
This PR makes the max number of douses lower if you are going to use other pickpockets afterwards.
Couple of zooto SC runs, sepos in Discord also tested one day.
=> More conditions to prevent halting while dousing shadow bricks

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/combat/auto_combat_default_stage3.ash
We use douse foe to get shadow bricks from slabs, but previously had no way to tell if it had worked so just kept dousing until we were short on turns for other combat actions.
Ryo added a new Mafia variable to tell us that it's succeeded, so let's use that now.
One day's shadow rifting, worked perfectly.
=> Use new mafia variable to check for douse foe success

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_acquire.ash
Adds ifs to each user_confirm so that they actually do things in turbo
Tested each user_confirm (except the one in auto_acquire) with yes's and no's and it branched as expected
=> Actually use user_confirms in Turbo

RELEASE/scripts/autoscend/auto_zone.ash, RELEASE/scripts/autoscend/quests/level_13.ash
- 8-bit Realm is no longer available if we need red pixel potions
- Don't buff until items are acquired
- halt if healing before shadow fails
🙃
=> Shadow fixes

RELEASE/scripts/autoscend/quests/level_12.ash
Having no familiar aborts the adventuring from the "no familiar" check.
This can occur if we have no meat familiars, which can be true in Zombie Slayer.
Zombie Slayer runs.
=> fix: don't equip no familiar at nuns

RELEASE/scripts/autoscend/iotms/mr2023.ash
If the pre-adventure script visited a URL, the visiting of the choice would fail as the campground leaves wasn't the most immediately visited page.
This should fix that. 
Not yet, will try tomorrow.
=> fix: do the leaf fight more consistently

RELEASE/scripts/autoscend/auto_acquire.ash, RELEASE/scripts/autoscend/auto_consume.ash
- When running turbo, don't pull legendary pizzas if they cannot be eaten
- When running turbo, don't pull an early dieting pill unless a legendary pizza was pulled
- Allow Jarlsberg and Zombie Slayer to use dieting pills by lowering min adv per full requirements. The other classes that have food limitations have options that are at least the hard coded 8.5. Maybe this should set via a property?
- Fix fullness left check to be greater than or equal to 2 * fullness
tbd: I'll test it after rollover
=> Turbo dieting pill fix

RELEASE/scripts/autoscend/paths/wildfire.ash
This can happen if we started as knoll and then used the spoon to switch signs, or if we bought the bus pass or used some other way to unlock the desert. 
Wildfire run.
=> fix: don't hose the garage if the desert is open

RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/auto_util.ash, RELEASE/scripts/autoscend/iotms/mr2019.ash, RELEASE/scripts/autoscend/iotms/mr2023.ash, RELEASE/scripts/autoscend/paths/heavy_rains.ash, RELEASE/scripts/autoscend/paths/zootomist.ash
Issue brought up on Discord about BHY not respecting no Bs when trying to maximize mp when eating sausage from sausage goblin. This hopefully fixes it.
Also removes most calls directly to maximizer so that we utilize our custom functions more.
Standard maximizer call in BHY adds 1 beeosity now and it functions as expected (1 item has 1 "b" in its name). Removing the beeosity clause from the statement adds a second item with a "b" in its name
=> Add beeosity and get rid of most maximize statements

RELEASE/scripts/autoscend/iotms/mr2020.ash
With #1636, after mapping the monsters autoscend aborts. Seems unlikely to be desired.
Run.
=> fix: don't interrupt after mapping

RELEASE/scripts/autoscend/auto_pre_adv.ash
In Legacy of Loathing (and perhaps elsewhere), you can end up at the wall of bones with no non-combat damaging familiars. Allow adventuring in this case. 
LoL run.
=> fix: allow fighting the wall of bones with no familiar

RELEASE/scripts/autoscend/paths/zootomist.ash
Added Homemade Robot to the familiar blacklist for the Zooto path. Resolves #1644 .
Made change locally, ran script to continue Zooto run.
- [ X] My code follows the style guidelines of this project.
- [ X] I have performed a self-review of my own code.
- [ X] I have commented my code, particularly in hard-to-understand areas.
- [ X] I have based my pull request against the [main branch](https://github.com/loathers/autoscend/tree/main) or have a good reason not to.
- [ X] I have updated the GitHub wiki [path](https://github.com/loathers/autoscend/wiki/Path-Support) or [IOTM](https://github.com/loathers/autoscend/wiki/IOTM-Support) support pages, as appropriate.
=> Avoid homemade robot in Zooto

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/iotms/mr2022.ash, RELEASE/scripts/autoscend/iotms/mr2024.ash
Can't access the Noob Cave or Sept-Ember Censer shop, can't buy the toy accordion.
With bat wings you can end up at the tower without having adventured in any bat zones (autoscend bat wings for sonars and then lockets a screambat), so allow Harem as an alternative.
Exploathing runs.
=> feat: various updates in Kingdom of Exploathing

RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/auto_equipment.ash, RELEASE/scripts/autoscend/auto_familiar.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_zone.ash, RELEASE/scripts/autoscend/combat/auto_combat_ed.ash, RELEASE/scripts/autoscend/combat/auto_combat_zombie_slayer.ash, RELEASE/scripts/autoscend/iotms/mr2013.ash, RELEASE/scripts/autoscend/iotms/mr2023.ash, RELEASE/scripts/autoscend/paths/actually_ed_the_undying.ash, RELEASE/scripts/autoscend/quests/level_03.ash, RELEASE/scripts/autoscend/quests/level_12.ash
There's a bunch of warnings now because Mafia changed zone names. Doesn't do anything dangerous but spams the gCLI. This gets rid of those warnings.
I've run a bunch of runs with this (and a whole bunch of other stuff). Don't think it broke anything.
=> update zone names given mafia update, removes warnings

RELEASE/scripts/autoscend/auto_familiar.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_restore.ash, RELEASE/scripts/autoscend/auto_zone.ash, RELEASE/scripts/autoscend/iotms/mr2022.ash, RELEASE/scripts/autoscend/paths/casual.ash, RELEASE/scripts/autoscend/quests/level_08.ash
Use our combat_appearance_rates to exclude potential monsters from consideration in a couple of functions. Also a couple of Path of the Plumber changes to make it run significantly smoother
Checked output of apprates[mob] <= 0 and matched expected mobs to not show up in the Spooky Forest (Baiowolf & The Headless Horseman).
HC Path of the Plumber through D1:L15. (1st ever run of it so catching a few things low shiny folk might experience with it too)
=> Check auto_combat_appearance_rates in the zone to see if we actually can do anything

RELEASE/scripts/autoscend/auto_util.ash
More paths where you shouldn't get the Manual of Secret Door Detection because you can't read books.
Pokefam.
=> fix: more paths that make you illiterate

RELEASE/scripts/autoscend/auto_choice_adv.ash
After using the jar of oil in G Lover, do the other choices instead of running away.
G Lover run.
=> fix: don't skip the twin peaks NC after using the oil jar

RELEASE/scripts/autoscend/auto_post_adv.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_restore.ash
Disco nap was trying to be cast even though we didn't have the mp for it. This should fix that.
Make sure the April Shower Thoughts Shield is equipped when casting the 1mp class skills in post_adv so that we get more buffs.
Move CCSC handler to below statgain increasers so that it doesn't get overwritten in unrestricted runs.
Multiple runs seeing:
Equips the ASTS for 1mp class skills
Saw CCSC not be overwritten by Fourth of May Cosplay Sword at Hidden Bowling Alley after I moved the CCSC handler.
Have not seen disco nap be used, but it is consistently being removed from consideration because I don't have a negative effect when it is being considered and because that will remove a negative effect, we are keeping it available until it is needed, which I have never seen it be. So, it is …
=> Don't try to use disco nap if we don't have the MP. Equip April Shield for more buffs

RELEASE/scripts/autoscend/auto_post_adv.ash, RELEASE/scripts/autoscend/auto_pre_adv.ash, RELEASE/scripts/autoscend/auto_util.ash
After adding the save/load equip functions, I noticed that there was a lot of additional time being spent equipping and then unequipping my Baywatch during the post adventure buffing sequence, basically with each buff's skill being cast. This PR reduces maximizes for -mana cost before buffing in pre-adventure, post-adventure, and during mana burning (which kind of defeats the purpose of burning mana, but it was another slowdown I saw). Also, will not try to cast Spirit Boon if not a Turtle Tamer, another slowdown
Multiple turns observing how equipment is saved with various auto_log_info statements I added during my testing (removed from final commit).
=> Reduce Equipment Swapping While Buffing

BUILD/settings/post.dat, RELEASE/data/autoscend_settings.txt, RELEASE/scripts/autoscend.ash, RELEASE/scripts/autoscend/paths/pocket_familiars.ash, RELEASE/scripts/autoscend/quests/level_06.ash, RELEASE/scripts/autoscend/quests/level_10.ash, RELEASE/scripts/autoscend/quests/level_11.ash
Delay completing zones without NC forcers where NC forcers would be useful.
Pokefam
=> feat: add a configurable property for estimated day count
